feat: 모임 내 닉네임 중복 검증
woowacourse-teams/2024-ody pull request #119
Opened 2024-07-24 12:50 UTC by mzeong

# 🚩 연관 이슈 
close #81

<br>

# 📝 작업 내용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-24 17:55 UTC, coli-geonwoo approved these changes
제리 고생 많았어 👍

2024-07-24 19:07 UTC, eun-byeol requested changes
테스트 코드까지 꼼꼼하게 챙겨주셨네요! 간단한 코멘트 남겼으니 확인 부탁드려요🙌

2024-07-24 19:07 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        } catch (DataIntegrityViolationException exception) {
[질문]
DB에서 에러를 발생시키지 않고 중복 검사를 할 수도 있었을텐데, 이렇게 구현한 이유가 궁금해요🤔
DB를 한 번에 조회하기 위함이었을까요?

2024-07-24 19:07 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        } catch (DataIntegrityViolationException exception) {
[제안]
이미 참여한 회원인지 검증하는 로직도 있어야 할 것 같아요.
`memberId - meetingId`에도 unique 조건이 걸릴 것 같은데, DB에서 에러가 발생하는 예외로는 두 경우를 구분하기 어렵지 않을까요?
아래처럼 코드를 작성할 수 있을 것 같아요.
```java
    @Transactional
    public Mate save(MateSaveRequest mateSaveRequest, Meeting meeting, Member member) {
        if (mateRepository.existsByMeetingIdAndNicknameNickname(meeting.getId(), mateSaveRequest.nickname())) {
            throw new OdyException("모임 내 같은 닉네임이 존재합니다.");
        }

        if (mateRepository.existsByMeetingIdAndMemberId(meeting.getId(), member.getId())) {
            throw new OdyException("모임에 이미 참여한 회원입니다.");
        }
        return mateRepository.save(mateSaveRequest.toMate(meeting, member));
    }
```

2024-07-25 00:22 UTC, hyeon0208 approved these changes

2024-07-25 00:23 UTC, eun-byeol approved these changes

2024-07-25 00:23 UTC, merged