feat: 특정 회원이 참여한 모임 목록 조회 API 구현
woowacourse-teams/2024-ody pull request #129
Opened 2024-07-24 17:51 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #117 

<br>

# 📝 작업 내용
- [x] 특정 회원이 참여한 모임 목록을 반환한다

### 참고사항
- 테스트 간섭이 생기는 두 테스트를 우선 Disabled 처리 후 PR 요청합니다.
    - NotificationRepositoryTest :  findAllMeetingLogsById()
    - MeetingControllerTest: findMine

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-24 19:16 UTC, eun-byeol commented on backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
> +                .statusCode(200);
[제안]
메서드 체이닝은 한 줄에 하나로 컨벤션을 정하긴 했지만,
`given().log().all()` 이런 부분은 한 줄에 표시해줘도 괜찮을 것 같아요! 제리&카키도 한 줄로 작성하더라고요.
RestAssured는 따로 컨벤션으로 정하면 좋을 것 같습니다!

2024-07-24 19:19 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +                .toList();
[제안]
체이닝으로 한 번에 작성하는건 어떨까요?
```suggestion
        List<MeetingSaveResponse> saveResponses = meetingService.findAllMeetingsByMember(member)
                .stream()
                .map(this::makeSaveResponse)
                .toList();
```

2024-07-24 19:20 UTC, eun-byeol requested changes
늦은 시간까지 고생 많았어요! 간단한 리뷰 남겼으니 확인부탁드립니다~🙌

2024-07-25 01:19 UTC, hyeon0208 approved these changes

2024-07-25 01:21 UTC, eun-byeol approved these changes

2024-07-25 01:22 UTC, mzeong approved these changes

2024-07-25 01:40 UTC, merged