feat: 알림 생성 시점이 전송 시점보다 늦은 경우 예외 처리
woowacourse-teams/2024-ody pull request #166
Opened 2024-07-26 01:18 UTC by eun-byeol

# 🚩 연관 이슈 
close #156

<br>

# 📝 작업 내용
- [x] 알림 생성 시점이 전송 시점보다 늦은 경우 바로 알림 전송

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-27 12:39 UTC, hyeon0208 approved these changes
고생했어요 조조 ~ 👍🏻
코드 꼼꼼하게 잘 작성하셨네요 👍🏻
간단한 리뷰 남기고 나중에 머지시에 고려해야할 부분 메모 해놓고 갑니다

[메모]
- develop 코드에 머지 시 sendAt이 나노초로 저장되기 때문에 notificationServiceTest에서 즉시 전송되는 알림을 조회 할 때 today도 withNano(0)으로 나노 초 제거 후 filter 조건에서 notification.getSendAt().isEqualTo(today) 로 비교하면 좋을 듯
- develop 코드에 머지 시 입장 알림 타입과 출발 알림 타입의 구분을 위해 notificationServiceTest에서 즉시 전송되는 알림을 조회 할 때 filter 조건에 출발 알림 타입 필터링 구문도 필요 할듯

2024-07-27 12:39 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    @SpyBean
[질문]
@Autowired여도 테스트가 잘 동작하지 않나요 ??
테스트 코드상에서 @SpyBean이 적용될 이유는 없는것 같아 질문드립니다  😄

2024-07-27 12:39 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +        notificationService.saveAndSendDepartureReminder(meeting, mate, member.getDeviceToken());
assertThat 구문에 when절에 대한 코드를 넣기 보다는 바깥으로 추출되서 사용되는게 개인적으로는 더 깔끔하지 않나 생각이 드는데 조조는 어떠신가요 ?
```suggestion
               Optional<Notification> departureNotification = allMeetingLogs.stream()
                .filter(notification -> notification.getSendAt().getDayOfMonth() == today.getDayOfMonth())
                .findFirst();

        assertThat(departureNotification).isPresent();
```

2024-07-27 12:39 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +                        .findFirst()
[제안]
지금이야 테스트시에 조회되는게 고작 1개라 의미없겠지만
순서가 상관없다면 findAny()로 조건에 맞는 요소를 더 빨리 찾는게 좋을 것 같아요 😄

2024-07-28 07:18 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    @SpyBean
[반영 완료]
오! 예리한 리뷰 감사합니다 👍👏👏👏

2024-07-28 15:05 UTC, coli-geonwoo requested changes

2024-07-28 15:05 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +                        .findFirst()
**[의견]**

지금 맥락도 충분히 납득되고 테스트 코드도 잘 읽혔어요! 한가지 우려되는 건 하나의 테스트에서 notificationService의 다른 메소드와 의존성이 생길 수도 있을 것 같아요. 단례로 이 테스트의 실패 원자성이 보장되지 않아 실패 원인이 findAllMeetingLogs인지 savandsenddepartureReminder인지 헷갈리는 경우가 생길 수 있다는 생각이에요!

repository단에서 notification을 직접 조회하는 방법에 대한 조조의 생각이 궁금합니다 🤔

2024-07-29 16:03 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +        if (sendAt.getValue().isBefore(LocalDateTime.now())) {
[반영 완료]

오오 예리한 리뷰 감사합니다👏

2024-07-29 16:07 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +        notificationService.saveAndSendDepartureReminder(meeting, mate, member.getDeviceToken());
[반영 완료]
동의합니다~🙋‍♀️

2024-07-29 16:20 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +                        .findFirst()
[반영 완료]
👍

[질문]
**병렬처리가 아닌 경우에도, findAny와 findFirst가 성능에 차이가 있나요?**

- findAny : 가장 먼저 탐색 되는 요소 리턴
- findFirst : 조건에 일치하는 요소들 중에 순서가 가장 앞에 있는 요소 리턴
- [출처](https://has3ong.github.io/programming/java-streamintro3/)

findFirst도 순차적으로 탐색하다가, 요소를 찾으면 바로 반환해서 똑같지 않을까? 하는 의문이 들었어요!🤔

2024-07-29 16:50 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +                        .findFirst()
[반영 완료]
동의합니다~!🙋‍♀️

2024-07-30 01:31 UTC, mzeong approved these changes

2024-07-30 04:03 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +                        .findFirst()
이전에 리뷰 받았던 부분이 있어서 다시 확인했었는데
findAny()와 findFirst()에 대한 차이에 대해 물어봤을 뿐 성능에 대한 질문이 아니였었네요
햇갈렸던 것 같아요 😂
결론은 데이터를 찾는 방법이 다를 뿐 멀티 스레드가 아닌 상황에서는 성능 차이가 없다입니다 😀

2024-07-30 04:03 UTC, hyeon0208 approved these changes

2024-07-30 17:20 UTC, coli-geonwoo approved these changes

2024-07-30 17:20 UTC, merged