test: RouteClient Mock 테스트
woowacourse-teams/2024-ody pull request #177
Opened 2024-07-28 07:11 UTC by eun-byeol

# 🚩 연관 이슈 
close #114

<br>

# 📝 작업 내용
- [x] RouteClientMockTest 추가
- [x] RouteServiceTest에서 검증하고 있는 부분을 RouteClientMockTest로 이전
- [x] Test 전용 RouteClient Stub 객체 생성 후 FCM test와 연결

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
‼️`BaseControllerTest`, `BaseServiceTest`를 상속받는 테스트 클래스는 `FakeRouteClient`가 Bean으로 설정됩니다‼️
```
FakeRouteClient 로직
1. if 출발지 == 도착지 -> 0(분)
2. else -> 16(분)
```

**[결론] RouteService.calculateDepartureTime() 로직**
```
1. if 출발지 == 도착지 -> 약속시간 10분 전 시간
2. else -> 약속시간 26분 전 시간
```

2024-07-28 09:15 UTC, hyeon0208 requested changes
테스트 작성하시느라 고생 많으셨습니다 ~ 😄
몇 가지 궁금한점들이 있어 질문 남겨보아요
MockServerTest로 외부 API를 테스트해보진 않아서
예외 응답을 json으로 하나씩 만드는 등의 테스트 세팅을 하는 과정들이 좀 까다롭게 느껴졌는데
직접 작성하시면서 클라이언트 객체를 MockBean으로 모킹한 것과 어떤 차이가 있었는지 듣고 싶습니다 ~! 👍🏻

2024-07-28 09:15 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +        assertThat(routeTime.getMinutes()).isEqualTo(15);
[질문]
FakeClient의 calculateRouteTime()은 16분을 반환할텐데 왜 15가 되나요 ??

2024-07-28 09:15 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +@Import(RouteConfig.class)
[질문]
테스트를 위해 FakeRouteClient 클래스를 만든 것으로 보이는데
현재 오디세이 테스트 상에서 FakeClient가 사용되지 않고 실제로 사용하는 구현체와 설정을 쓰는 이유가 있나요 ??

2024-07-29 12:28 UTC, mzeong commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +        assertThat(routeTime.getMinutes()).isEqualTo(15);
저도 궁금해서 코드 확인해보니 MockRestServiceServer로 RestTemplate이 successResponse.json을 응답하게 하고 있는데, 
해당 응답 내 totalTime이 15네요

totalTime 관련해서는 OdsayResponseDeserializer의 findMinutes 메서드 확인하면 ODsay 응답으로부터 소요시간을 어떻게 얻어오는지 확인할 수 있어요

2024-07-29 12:45 UTC, mzeong commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +@Import(RouteConfig.class)
저도 궁금합니다 테스트하고자 하는 바가 달랐던 건가요?

2024-07-29 17:02 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/BaseServiceTest.java
> +@ActiveProfiles("test")
[반영 완료]
Fake 객체를 사용하는 RouteServiceTest를 지우면서 불필요한 설정이 남아있었네요👍

2024-07-29 18:01 UTC, eun-byeol commented
> 예외 응답을 json으로 하나씩 만드는 등의 테스트 세팅을 하는 과정들이 좀 까다롭게 느껴졌는데

맞아요. 그러나 불가피했다고 생각해요.
오디세이의 응답 형태가 통일되어 있지 않고, 성공/실패 HTTP 응답 코드 모두 200으로 반환되고 있었어요.
**다양한 응답 상황**에 대해, 제대로 로직이 수행되는 지 확인해야 했어요.

가장 중요하게 테스트한 부분이에요.
1. `successResponse.json`: 오디세이 응답 중에서 `소요시간(totalTime)`을 잘 바인딩해서 찾아오는가?
2. `errorXXResponse.json`: 오디세이 응답 형태에 따라, 성공/실패를 잘 분기 처리 하는가?

+) 더 좋은 테스트 방법이 있다면, 공유해 주세요~

---

> 클라이언트 객체를 MockBean으로 모킹한 것과 어떤 차이가 있었는지� 듣고 싶습니다 ~! 👍🏻

`OdsayRouteClient 내 RestClient를 모킹한 것`과 `오디세이 Server를 모킹한 것`의 차이를 물어보신 게 맞을까요?🤔

RestClient를 모킹한다면, 요청이 실제 올바르게 갔는지 확인할 수 없을 것 같아요.
server를 모킹하면 `mockServer.verify()`통해 설정된 모든 예상 요청이 실제로 수행되었는지 확인할 수 있습니다.

제가 잘못 이해한 부분이 있다면 다시 말씀해주세요~

2024-07-30 04:09 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +@Import(RouteConfig.class)
위 질문과 더불어 생긴 궁금증이였는데
질문을 합쳐보자면 테스트를 위해 `FakeRouteClient`를 만들었는데 `FakeRouteClient`를 사용하지 않고 있어요
하지만 "오디세이의 응답 이후의 비즈니스 로직을 테스트"를 하기 위해 `FakeRouteClient`가 아닌 개발 환경에서 사용되는
`OdsayRouteClient` 과 설정 `RouteConfig`를 사용하는 부분이 이해가 되지 않아요
"비즈니스 로직을 담고 있지 않은 Fake 객체로 검증하지 않았다"라고 하셨는데  그렇다면 `FakeRouteClient`는 왜 필요했는가가 더더욱 궁금해요 🤔

2024-07-30 05:45 UTC, hyeon0208 approved these changes

2024-07-30 14:56 UTC, merged

2024-07-30 15:06 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
> +@Import(RouteConfig.class)
`OdsayRouteClientTest`와 별개로,
`FakeRouteClient`를 둔 이유는`모든 테스트 시에 실제 오디세이 api를 호출하지 않도록` 모킹하기 위함 입니다.
`BaseControllerTest`에 MockBean으로 `RouteClient`를 정의해 놓을 수 있겠지만,
`BaseServiceTest`에서도 `RouteClient`가 사용될 경우 중복코드가 발생할 수 있어 클래스로 분리했습니다.

제가 잘못 이해했거나, 궁금증이 해소되지 않았다면 다시 한 번 말씀해주세요😃