refactor: DTO 변환을 담당하는 계층을 컨트롤러에서만 담당하도록 수정
woowacourse-teams/2024-ody pull request #180
Opened 2024-07-28 07:51 UTC by hyeon0208

# 🚩 연관 이슈 
close #176

<br>

# 📝 작업 내용
- DTO 변환을 담당하는 계층을 컨트롤러에서만 담당하도록 수정
- MateService.save(), NotificationService.save() 호출 시 인자로 넘기는 mate 객체에 meeting, member가 이미 초기화되어 있어 불필요하게 넘기는 파라미터 제거
- Mate에서 String 타입의 닉네임을 getter로 가져올 때 getNickname().getNickname()이 디미터 법칙을 위반 및 가독성을 저해한다고 생각해  Mate에서 getter 시 Nickname 타입을 반환하는 것이 아닌 String 타입을 반환하도록 수정

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
약속 방 개설자가  방을 생성하고 참여하는 흐름을 /meetings POST 요청에 다 합치지 않고
/meetings POST, /mates POST 분리되게 요청을 하도록 수정하면 /meetings POST 요청을 매핑하는 컨트롤러 코드가 훨씬 더 깔끔해질 것 같아요
이 부분은 안드로이드 측과 얘기해보면 좋을것 같은데 어떻게 생각하시나요 ?

2024-07-28 15:38 UTC, coli-geonwoo requested changes
카키!! 고생많았어!!!!! 몇가지 의견 남겼으니 카키 마음에 드는 리뷰만 취사선택하길! 👍 

약속 방 개설자가 방을 생성하고 참여하는 흐름을 /meetings POST 요청에 다 합치지 않고
�/meetings POST, /mates POST 분리되게 요청을 하도록 수정하면 /meetings POST 요청을 매핑하는 컨트롤러 코드가 훨씬 더 깔끔해질 것 같아요
이 부분은 안드로이드 측과 얘기해보면 좋을것 같은데 어떻게 생각하시나요 ?

내 의견 : 안드측에서만 동의하면 더 Restful한 API라 생각합니다!

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        notificationService.saveEntryAndDepartureNotification(mate);
[제안]

메서드가 역할 2개를 담당하는 느낌이 들어서 메서드를 분리하는 건 어떨까요? 카키의 의견이 궁금합니다!

```suggestion
        notificationService.saveEntry(mate);
        notificationService.saveDepartureTime(mate);
```

혹은 파라미터를 통해 재사용성을 높여도 괜찮다고 생각합니다!
```suggestion
        notificationService.save(mate, ENTRY);
        notificationSErvice.save(mate, DEPARTURE);
```

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(MeetingSaveResponse.of(meeting, mates));
[질문]

지적보단 정말 순수한 궁금증인데 2줄에서 1줄로 정렬한 이유가 궁금합니다 😄

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/domain/Mate.java
> +    public String getNickname() {
디미터 법칙 👍

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        if (mateRepository.existsByMeetingIdAndNicknameNickname(
[제안]
NicknameNickname으로 메서드 네이밍을 한 이유가 궁금합니다! 확실하진 않지만 Embeddable이면 Nickname만으로 조회가 가능하지 않을까 싶어서 궁금해졌어요🤔 

```suggestion
        if (mateRepository.existsByMeetingIdAndNickname(
```

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        if (mateRepository.existsByMeetingIdAndMemberId(mate.getMeeting().getId(), mate.getMember().getId())) {
[제안]

id보다 meeting이나 member로만 조회하는 건 어떨까요? HQL내에서 자동으로 id(식별자)로 탐색을 해서 성능상 손실은 없습니다.
```suggestion
        if (mateRepository.existsByMeetingAndMember(mate.getMeeting(). mate.getMember())) {
```

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
> +                .map(mate -> new MateResponse(mate.getNickname()))
훠얼씬 깔끔해진 코드!!! 👍

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +    public void saveEntryAndDepartureNotification(Mate mate) {
[의견 - 선택]

파라미터를 mate 하나로 줄여 사용성이 좋아진 점이 눈에 띄는 것 같아요!
다만 현재 mate안에 meeting/ member를 touch해 lazy loading 특성상 쿼리가 2번 더 나가야 할 것 같아요.

성능 문제는 추후 고려해야 할 문제라 생각하지만 만약 외부에서 받아올 수 있는 이미 초기화된 객체가 있으면 파라미터를 열어주는게 성능에는 좋을 수도 있을 것 같다는 생각입니다!!

2024-07-28 15:38 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Meeting meeting = meetingService.save(Fixture.ODY_MEETING1);
👍

2024-07-29 11:52 UTC, eun-byeol requested changes
역시 코드가 깔끔하네요👍

DTO 변환을 컨트롤러에 두는 방식을 시도해 본 것은 좋았지만,
하나의 트랜잭션 단위로 처리해야 할 부분들이 묶이지 않는다는 단점이 있었어요.

제리와 코드를 합치는 과정에서 service component와 module로 계층화해서 해소해보는 것을 제안드려요.
- controller
  - component service(DTO 반환, module service 의존)
  - module service(domain 반환, repository 의존)
 
코드 합치는 과정이 선행돼야 할 것 같아, RC로 남겨둘게요!

2024-07-29 11:52 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        if (mateRepository.existsByMeetingIdAndNicknameNickname(
디미터 법칙을 지키기 위해 getNickname()를 따로 정의했기 때문인 것 같아요.

2024-07-29 11:52 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> -    public void saveAndSendDepartureReminder(Meeting meeting, Mate mate, DeviceToken deviceToken) {
[제안]

void를 반환하기보다는, 생성된 리소스를 반환하는 건 어떤가요?
지금 controller에서는 반환값을 사용하지 않지만, void를 반환하도록 하면 service 테스트 시도 더 쉬워질 것 같아요.

2024-07-29 11:52 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
>                  .doesNotThrowAnyException();
[제안]

예외가 발생하지 않았다는 것만으로, 리소스가 생성되었음을 보장할 수 있을까요?🤔
save가 void를 반환하는 것이 아니라, 생성된 리소스를 반환하고 검증하면 더 좋을 것 같습니다!

2024-07-29 11:59 UTC, eun-byeol commented
> **약속 방 개설자가 방을 생성하고 참여하는 흐름을 /meetings POST 요청에 다 합치지 않고
�/meetings POST, /mates POST 분리되게 요청을 하도록 수정하면 /meetings POST 요청을 매핑하는 컨트롤러 코드가 훨씬 더 깔끔해질 것 같아요
이 부분은 안드로이드 측과 얘기해보면 좋을것 같은데 어떻게 생각하시나요 ?**

콜리 답변에 동의해요.

그러나, 이어져 있는 두 작업을 실패했을 때, 처리를 안드로이드가 해줘야 해요.
ex) `방 개설 api 성공` 후 -> `방 참여 api가 실패`하게 된다면? 안드로이드에서 `방 참여 api를 재요청`을 보내거나, `방 삭제 api를 호출`해야 해요.
실패 시 로직을 백에서 처리해야 할지, 안드로이드에서 처리해야 할지 고려해야 할 것 같습니다!

2024-07-29 12:50 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        notificationService.saveEntryAndDepartureNotification(mate);
하나의 트랜젹선으로 묶여야 하는 과정이네요! 조조 의견에 동의합니다.

2024-07-29 13:22 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        notificationService.saveEntryAndDepartureNotification(mate);
하나의 트랜잭션으로 묶으면서 메서드를 재사용할 수 있게 하고 싶은데 
그렇게 되면 토픽 구독이 필요 없는 입장알림도 구독을 하게 되는 문제가 있게 되더라구요 
아니면 하나의 메서드에서 알림 타입별로 분기 처리를 통해 로직을 수행하면 일부 공통 로직은 제거가 되지만
오히려 가독성이 저해가 되는 느낌을 받았어요 🥲

2024-07-29 13:25 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(MeetingSaveResponse.of(meeting, mates));
기존에는 `"한 줄에 한 점만 찍는다"`라고 컨벤션을 정했어서 한 줄에는 모두 한 점만 찍게 두었는데
저번에 무조건 한 줄에 한 점만을 찍었을 때 애매해지는 코드가 많이 나와 
이야기 했을 때 `"한 줄에 한 점만 찍는다"`라는 것은  점의 개수가 중요한 것이 아닌 디미터 법칙을 위반하는 경우에 해당되기 때문에
디미터 법칙을 위반한 경우에만 개행을 하자라고 이야기가 나왔던 걸로 기억을 해
해당 코드는 디미터 법칙을 위반하는 경우가 아니라 한줄로 개행하게 되었어요 😀
만약 저 라인이 120줄이 넘었다면 개행이 됬을 꺼 같아요 🤔

2024-07-29 13:34 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        if (mateRepository.existsByMeetingIdAndNicknameNickname(
`existsByMeetingIdAndNickname` 네이밍 쿼리를 사용했을 때
임베디드 클래스인 Nickname에 접근하는데 String으로 넘긴 nickname과 Nickname 객체와 타입이 일치하지 않아서 
`InvalidDataAccessApiUsageException` 예외가 발생해요
그래서 String으로 넘긴 nickname과 타입이 일치하는 Nickname객체의 내부 필드 값을 네이밍 쿼리로 작성해야 하더라구요 👍🏻

2024-07-29 13:42 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        if (mateRepository.existsByMeetingIdAndMemberId(mate.getMeeting().getId(), mate.getMember().getId())) {
처음 알게됬는데 JPQL을 보니 객체를 파라미터로 줬을 때 자동으로 id 식별자로 탐색하는 거 같네요 👍🏻
하지만 Repository DB 저장소의 특성에 맞게 데이터에 접근하는 방식을 좀 더 명확히 표현해주는게 어떨까요 ??

2024-07-29 14:10 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +    public void saveEntryAndDepartureNotification(Mate mate) {
지금은 `mateSaveRequest.toMate(meeting, member);`로 값이 다 채워져있는 Mate를 넘기기 때문에 추가 쿼리가 발생하지 않고 있어요
그리고 `mateService.save(mate);`로 저장된 후 반환된 Mate를 넘긴다하더라도 현재 OSIV가 켜져있기 때문에 컨트롤러에도 영속성 컨텍스트가 존재하고 영속성 컨텍스트에 이미 Mate를 save()할 때 정보가 담겨져 있기 때문에 추가 쿼리가 발생하지 않아요
콜리가 말씀한 부분도 고려가 필요한데 이 부분은 
영속성 컨텍스트에  Mate와 연관관계가 있는 데이터가 저장되어 있지 않을 때 Mate를 조회하고 이 Mate안에 있는 연관관계 필드에 접근할 시 고려가 필요할 것 같아요 👍🏻

2024-07-29 14:12 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/domain/Mate.java
> +        return nickname.getNickname();
트레이드 오프 영역이겠지만
해당 코드를 작성할 때 추가적인 옵션 설정을 피하고 싶어서 위 처럼 네이밍하긴 했습니다
이 임베디드 타입의 객체의 필드 이름에 대한 부분도 나중에 컨벤션으로 짚고 넘어가면 좋을 것 같네요 👍🏻

2024-07-29 14:19 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> -    public void saveAndSendDepartureReminder(Meeting meeting, Mate mate, DeviceToken deviceToken) {
생성된 리소스를 반환해준다면 반환값을 사용하지 않더라도 service에서 테스트시에 편해질 것 같네요 😄
해당 메서드 내부에선 서로 다른 두 타입의 Notification을 저장하고 있기 때문에 List<Notification>으로 줘봤습니다 👍🏻

2024-07-29 14:25 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
>                  .doesNotThrowAnyException();
위 처럼 예외가 발생하지 않았다는 것을 테스트한 이유는
저장 테스트 였다면 리소스가 잘 생성되었음을 테스트 했겠지만 
닉네임 중복 시 예외가 발생함을 테스트하면서 닉네임 중복이 되지 않으면 발생 안한다를 테스트하고 싶었어요
이 관점에 대해서는 어떻게 생각하실까요 ?😄

2024-07-29 18:06 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        notificationService.saveEntryAndDepartureNotification(mate);
카키 의견에 동의합니다
내부 로직이 완전히 다르니, 하나로 묶기보단 분리하는 게 좋은 것 같아요!

2024-07-29 18:14 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
>                  .doesNotThrowAnyException();
납득완

+) 저장 테스트를 하지 않는 이유가 있나요?🤔

2024-07-29 18:16 UTC, eun-byeol approved these changes

2024-07-30 04:01 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
>                  .doesNotThrowAnyException();
예외가 발생하는지에 대한 테스트와 더불어 예외가 발생하지 않음을 테스트해
jpaRepository내부에 구현되어있는 save()가 잘 되었는지에 대한 테스트는 하지 않아도 된다고 판단했어요 😀

2024-08-02 06:17 UTC, closed without merging