refactor: 서비스가 DTO 반환하도록 수정
woowacourse-teams/2024-ody pull request #181
Opened 2024-07-28 11:04 UTC by mzeong

# 🚩 연관 이슈 
close #175

<br>

# 📝 작업 내용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-28 15:53 UTC, coli-geonwoo requested changes
제리 고생 많았어!!! 몇 가지 생각 남겨놓았으니 마음에 드는 것만 반영하길...!

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        MeetingSaveResponse meetingSaveResponse = meetingService.findAndSendNotifications(mateSaveRequest, member);
[제안]

찾고 noti를 보낸다는 구현이 method 명에 드러나 있는 것 같아서 다음과 같은 네이밍은 어떤가요?
```suggestion
        MeetingSaveResponse meetingSaveResponse = meetingService.sendNotifications(mateSaveRequest, member);
```

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +    public MeetingSaveResponse saveAndSendNotifications(
[제안]

saveAndSendNotifications도 구현이 모두 반영된 네이밍이라 생각되어 다음과 같은 네이밍 제안합니다!
```suggestion
    public MeetingSaveResponse entry(
```

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +        MeetingSaveResponse meetingSaveResponse = meetingService.saveAndSendNotifications(meetingSaveRequest, member);
개인 취향이지만 깔끔해진 controller...👍

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +        meetingService.validateInviteCode(inviteCode);
Typo 범인 저인 것 같은데 감사합니다 🙇

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +    public MeetingSaveResponse saveAndSendNotifications(MeetingSaveRequest meetingSaveRequest, Member member) {
[제안]

개인적으로 controller 단에서 service를 호출할 때는 saveAndSendNotification이라는 과정을 알 필요가 없다고 생각했어요! save로 구현은 은닉하면 어떤가요? notification은 save 과정에서 캡슐화되어도 괜찮은 서비스 로직이라 생각해서요!

2024-07-28 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
>      public void updateStatusToDone() {
[제안 - 선택]
```suggestion
    public Notification send() {
                     return new Notification(this.mate, this.type, this.sendAt, DONE);
    }
    
```

약간 setter랑 비슷한 느낌이 들어서 그런데 상태 변화를 불변객체로 표현하도록 로직을 수정하면 어떨까 하는 생각이 들었어요. 많은 리소스가 들 수도 있을 것 같아 제안으로만 남겨둡니다.

2024-07-29 13:36 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +        return new MeetingSaveResponses(meetingSaveResponses);
[반영] [3aca3cf](https://github.com/woowacourse-teams/2024-ody/pull/181/commits/3aca3cf5324d99dbb662d15b1da3302302935db9)

2024-07-29 14:31 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +    public MeetingSaveResponse saveAndSendNotifications(MeetingSaveRequest meetingSaveRequest, Member member) {
개인적으로는 컨트롤러 쪽에서 해당 메서드를 호출할 때 어떤 로직이 실행되는지 알아야 한다 생각해요
save()로만 되어 있는데 내부 구현이 복잡해지면 코드를 처음 보는 3자 입장에서는 당황스러울 수도 있다고 생각합니다 🤔

2024-07-29 14:38 UTC, hyeon0208 approved these changes
Service단에서 Dto 변경을 담당하게 코드를 수정하면서 많은 수정이 있었네요 
깔끔하게 변경해주신것 같아요 고생했습니다 제리 👍🏻
추후에 DTO 변환 담당 위치를 컨트롤러로 할 것인지 서비스로 할 것인지 정하면
각자 리팩토링하면서 수정이 필요했던 부분 공유하면 좋을 것 같네요 😄
참고로 제 코드에는 반영하지 않았는데 
`FcmSendRequest`에 NotificationId를 넘기지 않고 Notification 객체 자체를 넘기게 되면
`FcmSender`내부에서 조회 쿼리를 사용할 필요가 없어지겠더라구요
나중에 반영할 코드 선택한 뒤 같이 반영해보시죠 👍🏻

2024-07-29 18:18 UTC, eun-byeol approved these changes

2024-08-01 00:23 UTC, mzeong commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +
한 메서드에서 저장과 알림 전송이라는 두 가지 일을 수행하고 있어 의도적으로 개행을 넣었으나
메서드 길이가 짧아 개행이 가독성에 크게 영향을 주진 않네요

2024-08-01 00:45 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
>      public void updateStatusToDone() {
불변을 위해 새로운 객체를 생성하게 되면 
해당 객체를 테이블에 저장하는 작업과 이전 객체를 테이블에서 삭제하는 작업이 추가로 이루어져야 해서
코드가 복잡해진다고 판단해 현재 코드를 유지했습니다!

2024-08-02 06:32 UTC, coli-geonwoo approved these changes
고생 많으셨습니다!!

2024-08-02 06:32 UTC, merged

2024-08-02 06:33 UTC, mzeong commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        MeetingSaveResponse meetingSaveResponse = meetingService.findAndSendNotifications(mateSaveRequest, member);
여러 코멘트를 통해 구현을 감추는 메서드명을 제안해줬는데 
메서드의 의미를 잘 전달해 협업 시 오해가 없도록 하기 위해 기존 메서드명을 유지했습니다!