refactor: application에서 repository, datastore, retrofit service 인스턴스 관리
woowacourse-teams/2024-ody pull request #183
Opened 2024-07-29 10:48 UTC by aprilgom

# 🚩 연관 이슈 
close #168

<br>

# 📝 작업 내용
[ ] repository, datastore, retrofit service 싱글턴 오브젝트들 application으로 이동

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-29 11:05 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
> +    val addressSearchViewModelFactory = AddressSearchViewModelFactory(kakaoGeoLocationRepository)
인터페이스 주입 하는 것으로 바꿔주세요! 현재는 구현체가 들어가네요! 타입 써주시면 좋을것 같아요

2024-07-29 11:05 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
> +    private val dataStore: OdyDatastore,
이것도 Repostiroy여야 할것 같아요

2024-07-29 11:07 UTC, haeum808 commented
컨테이너로 나누는거 찬성입니다!

2024-07-29 11:49 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
> +    val addressSearchViewModelFactory = AddressSearchViewModelFactory(kakaoGeoLocationRepository)
바꿔주었습니다잉

2024-07-29 11:49 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
> +    private val dataStore: OdyDatastore,
Repo를 주입해주고 application에 인스턴스를 만들어 주었습니다

2024-07-29 11:52 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
> +    private val dataStore: OdyDatastore,
해놓고 보니까 #169 번 이슈네요. #169 번 닫아야 할 듯

2024-07-29 11:53 UTC, haeum808 approved these changes
고생하셨습니다

2024-07-30 12:11 UTC, kimhm0728 requested changes
차람! 코드 리뷰가 늦어서 미안합니다... 2차 스프린트 끝나고 약간 헤이해졌네요. ㅠㅠ 앞으로는 24시간 룰 꼭 지킬게요! 고생하셨습니다! 👍

2024-07-30 12:11 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
> +        AddressSearchViewModelFactory(kakaoGeoLocationRepository)
`ViewModelFactory`도 `Application`으로 이동하신 이유가 있으실까요? `ViewModel`은 화면과 1:1 대응되기 때문에 인스턴스가 하나만 생성되는 것이 명확하다고 생각해요. 그래서 저는 `Activity`에서 바로 `ViewModelFactory`의 생성자 호출을 해줘도 될 것 같습니다.

Application에서 선언해준 객체들은 애플리케이션 생명주기 전반에서 살아있기 때문에 신중하게 결정해야 한다고 생각해요! 🙂

2024-07-30 12:11 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/data/remote/thirdparty/fcm/service/FCMService.kt
> -            (application as OdyApplication).odyDatastore.setToken(token)
이 부분이 삭제되면서, `fcmRepository.postFCMToken()` 해주는 부분도 빠진 것 같은데 제가 못 찾는 걸까요????

2024-07-31 12:52 UTC, kimhm0728 approved these changes
리뷰 반영된 것 확인했습니다 👍 고생하셨어요~!!!

2024-07-31 13:03 UTC, merged