refactor: RouteClient 응답 분기를 객체로 캡슐화
woowacourse-teams/2024-ody pull request #188
Opened 2024-07-30 17:30 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #179

<br>

# 📝 작업 내용
- RouteClientMapper를 통한 OdsayResponse 응답 분기
 - code == 500 > OdyServerErrorException
 - code == -98(출, 도착지가 700m 이내일 때 에러 코드) > 0분 반환
 - code exists > OdsayBadRequest 반환
 - code와 minutes 모두 없음 > OdsayServerErrorException
 - minutes exists > minutes 반환 

### 참고사항
- 조조 코드 merge 이전에 commit을 몇개 날려놓아서 충돌이 생길 것 같아요
- merge 시 충돌은 꼼꼼하게 확인후 해결하겠습니다.
<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
- OdsayResponseMapper가 가독성 있게 잘 들어오는지 궁금합니다.

2024-07-31 01:20 UTC, mzeong approved these changes
이전보다 odsay 응답 매핑 과정이 잘 이해가 돼요 👍👍

2024-07-31 01:29 UTC, eun-byeol requested changes
역할 분리를 잘 해주셨네요👏 몇 가지 리뷰가 있어서 RC 하겠습니다!

[제안]
`mapMinutes` 테스트도 챙겨주세요~!

2024-07-31 01:29 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +    }
[질문]

롬복으로 처리하면 잘 동작하지 않나요?
`@NoArgsConstructor(access = AccessLevel.PRIVATE)`를 사용하지 않은 이유가 궁금해요

2024-07-31 01:29 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +    public static long mapMinutes(OdsayResponse response) {
[질문]

static 메서드로 작성한 이유가 궁금해요🤔

2024-07-31 14:51 UTC, coli-geonwoo commented
> [제안] `mapMinutes` 테스트도 챙겨주세요~!
- 테스트 작성하다 700m 이내일 때도 오류를 반환한다는 로직 에러 하나 발견했어요! 조조의 꼼꼼함 덕분에 빠르게 캐치할 수 있었던 것 같아요 👍

2024-07-31 16:32 UTC, hyeon0208 approved these changes
고생하셨습니다 콜리 ~ 
역할분리가 잘 이뤄진거 같고 `OdsayResponseMapper`가 가독성있게 잘 읽혀져요 👍🏻
테스트도 꼼꼼히 작성하셨네요 👍🏻
이만 approve 드립니다 ~!

2024-07-31 16:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +    public static long mapMinutes(OdsayResponse response) {
콜리가 말씀하신 것 처럼 Mapper가 상태를 관리하지 않고 항상 정적인 작업만을 처리한다는 점에서 static하게 메서드를 사용하도록 한 부분 좋은 것 같아요 👍🏻

2024-07-31 16:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +    private static final String CLOSE_LOCATION_CODE = "-98"; //출발지-도착지가 700m 이내일 때
주석이 없다면 이해하기 어려울 수도 있는 부분인 것 같네요
적절한 주석사용 👍🏻

2024-07-31 16:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +                .orElse(EMPTY_MESSAGE)
```suggestion
                response.message()
                     .orElse(EMPTY_MESSAGE)
```
점 "."이 개행된 후 들여쓰기가 빠졌어요 🫣

2024-07-31 16:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/OdsayResponse.java
>          OptionalLong minutes
개인적으로 Optional<Long>, OptionalLong으로 하지 않은 이유가 궁금해서 찾아봤는데 
Optional<Long>은 방식/언박싱으로 인한 큰 오버헤드가 있는 것으로 보아
래퍼 타입인 Long 아닌 기본형인 long을 사용할 때는 콜리가 작성한 것처럼 OptionalLong을 사용하는 것이 적절한 것 같네요
👍🏻👍🏻👍🏻

2024-08-01 14:36 UTC, eun-byeol approved these changes
꼼꼼하게 테스트 작성해주셨네요👍 고생하셨습니다!

2024-08-01 15:24 UTC, merged