refactor: 2차 스프린트 리팩터링
woowacourse-teams/2024-ody pull request #196
Opened 2024-08-01 09:49 UTC by aprilgom

# 🚩 연관 이슈 
close #195

<br>

# 📝 작업 내용
- [x] FCMService와 NotificationHelper 분리

<br>

# 🏞️ 스크린샷 (선택)

<img width="417" alt="localproperties" src="https://github.com/user-attachments/assets/f3438264-cdc4-446d-87b2-4749aab1224d">

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-01 13:08 UTC, haeum808 approved these changes
고생하셨습니다.

2024-08-01 13:35 UTC, kimhm0728 requested changes
아까 권한 설정하는 부분 early retrun 하기로 얘기하지 않았나요?? `vm -> viewModel` 네이밍도 수정 부탁드려요.

오늘 아침 슬랙에 제가 리팩터링하면 좋을 것 같은 사항들 정리해서 보냈는데, 대부분 반영이 안 된 것 같습니다. 물론 참고하라고 올린 거였지만, 네이밍 컨벤션 조차도 수정되어 있지 않으니 '아예 읽지 않았나?'라는 생각도 듭니다.. 만약 차람이 반영하지 않는 걸 원하신다면, 그에 대한 이유를 말씀해 주셔야 서로 소통이 원활할 것 같아요.

제가 정리해둔 부분 이외에도 2차 스프린트 때 구현된 코드들 전체적으로 꼼꼼히 봐주시면 정말 좋을 것 같습니다~!

(쿠션어 넣는 걸 잘 못해서 말투가 딱딱합니다. 아주 기분 좋은 상태입니다. 🙂)

2024-08-01 13:50 UTC, aprilgom commented
헉..진짜 미안합니다 FCM쪽 분리에 집중해서 깜박했네요.. 제가 따로 물어봐서 피드백받았는데 수정을 안한건 소통을 거부한다거나 그런 의도는 아니었어요..

2024-08-01 14:31 UTC, kimhm0728 commented
괜찮습니다. 저도 잘 까먹습니다.. 

추가 리팩터링 후에 다시 리뷰요청 부탁드려요. 오늘까지는 시간이 촉박할 수도 있을 것 같아서, 충돌이 나지 않는 선에서 천천히 진행해주셔도 됩니다!

2024-08-02 01:45 UTC, kimhm0728 approved these changes
추가된 커밋들 확인했습니다. 리뷰 반영 잘 해주셔서 감사해요! 고생하셨습니다!

2024-08-02 01:45 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/model/NotificationUiModelMapper.kt
> +fun List<NotificationLog>.toNotificationUiModels(): List<NotificationLogUiModel> = this.map { it.toNotificationUiModel() }
👍

2024-08-02 04:56 UTC, merged