Feature/190
woowacourse-teams/2024-ody pull request #218
Opened 2024-08-01 13:05 UTC by haeum808

# 🚩 연관 이슈 
close #190 

<br>

# 📝 작업 내용
- [x] JoinCompleteActivty에서 하던 모임 방 개설 모임 방 참여를 MeetingCreationViewModel에서 수행
- [x] onShare(), onClick()
- [x] 모임 방 개설, 모임 방 참여 request, reponse 도메인 모델 생성 및 고체
- [x] navigateAction으로 변경

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-01 15:55 UTC, kimhm0728 requested changes
고생하셨습니다. 커밋 엄청 많네요.. 리뷰 잘 반영해주셔서 감사해요!

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/complete/MeetingCompletionActivity.kt
> +            delay(FINISH_DELAY_MILLIS)
지금껏 하드코딩 되어있었다는 사실도 인지하고 있지 못했네요 ㅋㅋ 👍

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    fun makeMeeting() {
클래스명도 MeetingCreationViewModel 이니 이 부분도 createMeeting()으로 통일하는 건 어떤가요? `makeMeetingResponse` 프로퍼티도 동일한 의견입니다!

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +                    meetingDate.value.toString(),
`meetingName`과 `meetingDate`도 null인지 체크하면 어떨까요? 프로퍼티 선언 시 `MutableLiveData()`에 초기값을 주입해 주지 않아서, null인 경우도 발생할 수 있을 것 같습니다.

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +                    destinationLongitude.slice(0..8),
소수점 자르는 부분을 `meetingCreationInfo` 또는 그에 대응되는 data model에서 해주면 어떨까요? 소수점 6자리까지만 가능하다는 로직은 우리 오디 서버 api에만 해당하는 로직이기 때문에, 그에 맞는 data 계층 model에서 해주면 좋을 것 같아요.

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteActivity.kt
화면 간 여러 데이터를 주고받는 로직이 사라지게 되었네요 👍

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
> +        runCatching { service.postMates(meetingJoinInfo.toJoinRequest()).toMeeting() }
```suggestion
    override suspend fun postMates(meetingJoinInfo: MeetingJoinInfo): Result<Meeting> {
        return runCatching { service.postMates(meetingJoinInfo.toJoinRequest()).toMeeting() }
        }
```
오 한줄로 된 함수인데 다음줄에 작성해도 린트 안 걸리나요? ㅋㅋㅋ 신기.... 
개인적으로 위와 같은 방식이 더 좋긴 합니다. 너무 길어지면 return으로 명시해주는 편인데, 그냥 제 취향이라 반영하지 않으셔도 됩니다.

2024-08-01 15:55 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +) : ViewModel(), MeetingCreationListener, MeetingJoinListener {
예전에 Click Listener들을 어디서 implement 할지에 대해 얘기가 나왔었어요. 그때가 프로젝트 초반이었어서, 구현이 조금 진행된 후에 다시 얘기해보기로 했던 것 같은데요. 혹시 다들 어떤 의견이신가요? 

저는 액티비티에서 implement하는 게 좋습니다. 뷰모델의 함수를 호출하더라도 액티비티를 한번 거쳐서 구현되는 걸 선호합니다. 뷰모델에서 뷰 관련 클릭 리스너들을 implement하는게 어색하게 느껴지기도 하고요. (대부분의 리스너 이름도 뷰에 의존도가 높기 때문. 예를 들어 onClickXXXButton) 

차람과 해음의 의견이 궁금합니다! @aprilgom @haeum808

2024-08-01 16:45 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/complete/MeetingCompletionActivity.kt
> +            delay(FINISH_DELAY_MILLIS)
크크 드디어 바꿨네요

2024-08-01 16:45 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteActivity.kt
훨씬 간단해졌습니다!

2024-08-02 01:16 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    fun makeMeeting() {
변경하겠습니다!

2024-08-02 01:18 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +                    meetingDate.value.toString(),
오케이 변경하겠습니다.

2024-08-02 01:26 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +                    destinationLongitude.slice(0..8),
그렇네요! 감사합니다!

2024-08-02 01:36 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
> +        runCatching { service.postMates(meetingJoinInfo.toJoinRequest()).toMeeting() }
더 좋은것 같네요 변경하겠습니다.

2024-08-02 01:55 UTC, aprilgom reviewed
수고하셨습니다!

2024-08-02 01:55 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/JoinRepository.kt
> +    suspend fun postMates(meetingJoinInfo: MeetingJoinInfo): Result<Meeting>
data 레이어와 domain 레이어의 분리 좋습니다

2024-08-02 01:55 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    private val _joinNavigateAction: MutableSingleLiveData<MeetingJoinNavigateAction> =
join activity와 meeting creation activity가 같은 viewModel을 공유하고 있어 이런 코드가 나왔네요.
(보통 두 액티비티가 하나의 뷰 모델을 공유하나요?? 이건 그냥 질문)
일단 joinNavigateAction이라는 네이밍을 넣었으니 _navigateAction을 _meetingCreationNavigateAction으로 바꾸는 게 어떨까요?
아니면 아예 원 액티비티에 뷰모델을 하나 두고, 프래그먼트로 분리해준 뒤 두 navigate action을 하나로 합치는 건 어떤가요?

2024-08-02 01:55 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    override fun onClickMJoinMeeting() {
오타인 것 같아요.

2024-08-02 01:55 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/listener/MeetingCreationListener.kt
> +    fun onClickMJoinMeeting()
여기네요

2024-08-02 02:00 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/domain/model/MeetingCreationInfo.kt
> +data class MeetingCreationInfo(
맞습니다 ㅜㅜ

2024-08-02 02:00 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/JoinRepository.kt
> +    suspend fun postMates(meetingJoinInfo: MeetingJoinInfo): Result<Meeting>
감사합니다!

2024-08-02 02:01 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    override fun onClickMJoinMeeting() {
변경하겠습니다!

2024-08-02 02:01 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/listener/MeetingCreationListener.kt
> +    fun onClickMJoinMeeting()
감사합니다!

2024-08-02 02:06 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    private val _joinNavigateAction: MutableSingleLiveData<MeetingJoinNavigateAction> =
두 액티비티가 하나의 뷰 모델을 공유하는 건 안좋은 방식이라고 생각합니다.
api 특성상 이렇게 할 수 밖에 없었는데 이제 추가로 api가 생겨서 나눌 수 있을 것 같습니다.

2024-08-02 02:13 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +) : ViewModel(), MeetingCreationListener, MeetingJoinListener {
뷰모델에 로직을 두고 뷰는 뷰모델의 라이브 데이터를 변화를 구독해 동작하는 것이 mvvm의 핵심이라 생각해서, 보통 리스너를 뷰모델에 두었습니다. 이 과정에서 보일러 플레이트가 늘어나는 건 단점인 것 같습니다.
+ 사실 저도 ClickListener로 작성해서 좀 반성하는 부분이긴 한데.. 리스너의 메서드 이름을 특정 동작(클릭 등)에 의존되게 짓기 보단, 어떤 동작을 하려고 하는지를 중점으로 이름을 짓는 쪽이 좋았을 것 같아요. ShareListener처럼요.

2024-08-02 04:49 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
> +    private val _joinNavigateAction: MutableSingleLiveData<MeetingJoinNavigateAction> =
좋아요~

2024-08-02 04:52 UTC, aprilgom approved these changes

2024-08-02 05:00 UTC, kimhm0728 approved these changes

2024-08-02 05:01 UTC, merged