refactor: BaseActivity, BaseFragment
woowacourse-teams/2024-ody pull request #220
Opened 2024-08-01 15:19 UTC by haeum808

# 🚩 연관 이슈 
close #197 

<br>

# 📝 작업 내용
- [x] application
- [x] binding
- [x] snackbar

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
- 아직 BindingActivity, BindingFragment가 적용이 안되어 있습니다. 코드리뷰 받고 추후에 변경하겠습니다.

2024-08-01 16:11 UTC, aprilgom reviewed
수고하셨습니다~

2024-08-01 16:11 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +abstract class BindingActivity<T : ViewDataBinding>(
BaseActivity 대신 BindingActivity라는 이름을 채택하신 이유가 있나용

2024-08-01 16:16 UTC, kimhm0728 requested changes
리뷰 달아두었습니당. 

`BindingActivity`에는 `showSnackBar`, `showToast`가 없고 `BindingFragment`에는 `showToast`가 없는데, 필요한 경우에 추가하려고 일부러 제외하신 건가요??

그리고 Base 뷰들 생성하자고 얘기가 나온 이유가, application에 DI가 추가되면서 모든 뷰에 application을 프로퍼티로 선언하는 보일러 플레이트가 생긴다는 이유였던 것 같은데요. (맞죠..??) `BindingActivity`, `BindingFragment`에 application도 같이 넣어주면 좋을 것 같습니다.

2024-08-01 16:16 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +    protected lateinit var binding: T
```suggestion
    protected val  binding: T by lazy { DataBindingUtil.setContentView(this, layoutRes) }
```
이 부분 by lazy로 초기화해주면 안 되나요?? 궁금..

2024-08-01 16:16 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +abstract class BindingActivity<T : ViewDataBinding>(
혹시 BaseActivity, BaseFragment 라는 네이밍은 어떠신가요? BindingActivity은 뭔가 익숙치 않은데.. 저만 그런 걸 수도 있음. 

데이터 바인딩/뷰 바인딩을 쓰는 Activity와 그렇지 않은 Activity와 구분하기 위한 네이밍인가요?

2024-08-01 16:16 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        snackBar?.dismiss()
show 전에 dismiss해주는 거 꼼꼼하네요 👍

2024-08-01 16:16 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        message: String,
`@StringRes messageId: Int`는 어떠신가요?

2024-08-01 16:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +abstract class BindingActivity<T : ViewDataBinding>(
넵 구분하기 위한 네이밍인데 어떤가요?

2024-08-01 16:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        snackBar?.dismiss()
감사합니다!

2024-08-01 16:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        message: String,
변경하겠습니다!

2024-08-01 16:39 UTC, haeum808 commented
실수가 많았네요, BindingActvity에 showSnackBar 메서드를 넣어주었습니다. 그리고 BindingFragment에 application을 넣었습니다.

2024-08-01 16:40 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +    private var snackBar: Snackbar? = null
추가하겠습니다!

2024-08-01 16:41 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
> +    protected lateinit var binding: T
이 방법이 더 깔끔하네요 변경하겠습니다.

2024-08-02 01:40 UTC, kimhm0728 requested changes
리뷰 반영된 것 확인했습니다. 기존 Activity, Fragment에 적용한 후에 다시 리뷰 요청 부탁드려요~

2024-08-02 04:58 UTC, aprilgom approved these changes
제 리뷰는 모두 반영하셨네요!
수고하셨습니다!

2024-08-02 04:59 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        _binding = null
꼼꼼한 null처리 좋습니다!

2024-08-02 06:23 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
> +        _binding = null
우하하

2024-08-02 06:25 UTC, haeum808 commented
BindingActivity에서 by lazy로 하니 에러 나와서 다시 바꿨습니다.

2024-08-02 06:30 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
>          initializeDataBinding()
`initializeDataBinding()` 이 반복이 되는 것 같은데, BindingActivity에 추상함수로 포함시키는 것도 괜찮은 것 같아요~

2024-08-02 06:36 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
>          initializeDataBinding()
추가하겠습니다!

2024-08-02 07:07 UTC, kimhm0728 approved these changes
고생하셨습니다~!

2024-08-02 08:10 UTC, merged