docs: 약속 참여자 상태 목록 조회 API 문서화
woowacourse-teams/2024-ody pull request #243
Opened 2024-08-02 11:00 UTC by hyeon0208

# 🚩 연관 이슈 
close #234 

<br>

# 📝 작업 내용
약속 참여자 상태 목록 조회 API 문서화

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-02 12:42 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/domain/EtaStatus.java
> +    MISSING,
[제안]
정렬해주면 어떨까요? 왜냐면.. 기부니 좋으니까요😄
```suggestion
    ARRIVAL_SOON,
    ARRIVED,
    LATE_WARNING,
    LATE,
    MISSING,
```

2024-08-02 12:46 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +        String currentLongitude
[필수]

위도, 경도 example이 반대네요~
예시 반대로 바꿔주시면 좋을 것 같아요!
위도 - 39.123345
경도 - 126.234524

2024-08-02 12:47 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +        String currentLongitude
[필수]

위도, 경도 example이 반대네요~
아래처럼 반대로 바꿔주시면 좋을 것 같아요!
```suggestion
        @Schema(description = "현재 위도", example = "39.123345")
        @Nullable
        String currentLatitude,

        @Schema(description = "현재 경도", example = "126.234524")
        @Nullable
        String currentLongitude
```

2024-08-02 12:50 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +public record MateStatusRequest(
[제안]
`MateEtaRequest` 로 바꾸는건 어떤가요?

```suggestion
public record MateEtaRequest(
```

2024-08-02 12:55 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/dto/response/MateStatusResponse.java
> +        @Schema(description = "도착지까지 남은 소요시간",  example = "32")
[제안]

'분' 단위도 명시해주면 어떨까요?

```suggestion
        @Schema(description = "도착지까지 남은 소요시간(분)",  example = "32")
```

2024-08-02 12:59 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +        return ResponseEntity.ok(mateStatuses);
[제안]

API 명세서 작성할 때 놓친 부분인데, `201`을 반환하는 건 어떤가요?
`PATCH`도 리소스 생성 메서드이니까요~!

```suggestion
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(mateStatuses);
```

2024-08-02 13:01 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
> +                            description = "클라이언트 입력 또는 약속 시간 30분 이전 조회 시도 시",
[제안]

```suggestion
                            description = "클라이언트 입력 오류 또는 약속 시간 30분 이전 조회 시도 시",
```

2024-08-02 13:12 UTC, eun-byeol requested changes
빠르게 문서화 작업 해주셨네요!👍
몇 가지 제안한 리뷰 확인해주시고, RC로 남겨둘게요!

@hyeon0208 @coli-geonwoo

2024-08-02 15:09 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +        String currentLongitude
<img width="362" alt="image" src="https://github.com/user-attachments/assets/f510d5ec-fd1a-44e5-8e66-8bc716659973">
API 문서에 작성되어 있는 Request 바디 그대로 작성했습니다 !

2024-08-02 15:13 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +public record MateStatusRequest(
처음에는 api 응답에 있는 데이터명 그대로 따라가다가 `MateStatusRequest`로 네이밍 하다
참여자별 상태를 갖는 Enum은 `EtaStatus`로 네이밍하게 되었는데
개인적으로는 Eta가 현재 응답 DTO에 대한 이름을 잘 명시된 것 같아서 
Dto명도 `MateEtaRequest`로 네이밍하고 api uri도 수정되면

2024-08-02 15:14 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/dto/response/MateStatusResponse.java
> +        @Schema(description = "도착지까지 남은 소요시간",  example = "32")
소요시간이라 되어있으면 헷갈릴 여지가 있을 것 같네요 해당 부분 반영했습니다 👍🏻

2024-08-02 15:20 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +        return ResponseEntity.ok(mateStatuses);
`PUT` 이 자원이 저장하지 않을 경우 리소스를 생성하고
`PATCH`는 리소스의 일부만을 변경하기 때문에 201 응답보다는 
현재 응답 데이터도 있는 상황에선 200 응답이 적절하다고 생각합니다 🤔

2024-08-02 15:21 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
> +                            description = "클라이언트 입력 또는 약속 시간 30분 이전 조회 시도 시",
반영완료 👍🏻

2024-08-02 15:22 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +                new MateStatusResponse("카키공주", EtaStatus.MISSING, -1L)
콜리의 폭주를 막지 못했습니다 ☠️☠️☠️

2024-08-02 15:22 UTC, hyeon0208 commented
@eun-byeol 
리뷰 반영했으니 시간되시면 확인해주세요 😄

2024-08-02 15:31 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +        String currentLongitude
API docs가 잘못 되어있네요..!
docs는 제가 수정해놓겠습니다!
코드는 수정해주셔야 할 것 같아요~

2024-08-02 15:42 UTC, eun-byeol commented
빠르다 빨라,,,🚀
approve 할게요!

[필수]
- [위경도 반대 예시 재수정 요청드려요~ Docs가 잘못 되어 있었어요](https://github.com/woowacourse-teams/2024-ody/pull/243#discussion_r1701802972)

[합의 필요]
- `Eta`를 클래스 명에 사용할 지 여부는, 실제 API 구현하실 때 고려해주시면 좋을 것 같아요.

2024-08-02 15:43 UTC, eun-byeol approved these changes

2024-08-03 01:36 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +        String currentLongitude
[수정완료]

2024-08-03 14:09 UTC, mzeong commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +public record MateStatusRequest(
dto 이름으로 `MateEtaRequest`를 사용하는 거 좋아요
uri는 `/v1/meetings/{meetingId}/mates/etas` 사용하는 것 어떤가요?

2024-08-03 14:13 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +        return ResponseEntity.ok(mateStatuses);
카키의 말처럼 PATCH는 기존 리소스를 수정하는 것이기 때문에 생성을 의미하는 201보다는 200이 적절할 것 같아요
꼼꼼하게 살펴보고 코드리뷰를 남겨주는 조조 좋아요 👍

2024-08-03 14:25 UTC, mzeong approved these changes

2024-08-03 14:25 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
> +                            description = "클라이언트 입력 오류 또는 약속 시간 30분 이전 조회 시도 시",
[제안] '약속 시간 30분 이전'이라는 표현이 의도가 잘 전달될 것 같은가요? 노션에다가 제가 쓴 문장인데 작성 당시에 살짝 어색했어서 수정을 제안해봅니다..

```suggestion
                            description = "클라이언트 입력 오류 또는 약속 시간 30분 전보다 이른 시간에 조회 시도 시",
```

2024-08-03 14:40 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/dto/request/MateStatusRequest.java
> +public record MateStatusRequest(
`/v1/meetings/{meetingId}/mates/etas` 맘에 드네요 ! 👍🏻

DTO명과 URI를 변경하는데 다들 동의하는 것 같아 DTO 명 `MateEtaxxx`로 변경과 더불어 반영했습니다 😄

2024-08-03 14:44 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
> +                            description = "클라이언트 입력 오류 또는 약속 시간 30분 이전 조회 시도 시",
"이전"도 좋다고 생각하는데 제리가 제안한 대로 변경해주면 좀 더 직관적으로 와닿을 꺼 같아요 !
반영완료 👍🏻

2024-08-03 15:24 UTC, mzeong reviewed
[e8a5115](https://github.com/woowacourse-teams/2024-ody/pull/243/commits/e8a51150b478081beaa0264241858b8a7d399d1c) 커밋을 한 이유가 있나요? conflict 해결이 잘 안 되고 있나요?

2024-08-03 15:47 UTC, hyeon0208 commented
@mzeong 
PR에서 Resolve conlicts이 비활성화되서
Git Desktop으로 하다가 위 커밋이 찍혔는데 해결이 안되서
`Use the command line` 대로 충돌난 파일 해결해도 왜 conlicts 변함이 없을까요 ?? 🤯🤯🤯

2024-08-03 17:48 UTC, merged