feat: 약속 참여 V1 API 구현
woowacourse-teams/2024-ody pull request #247
Opened 2024-08-03 04:36 UTC by hyeon0208

# 🚩 연관 이슈 
close #223 

<br>

# 📝 작업 내용
- 개설과 참여가 분리된 /v1/mates API 구현

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
- 기존 설계에서는 개설자가 참여까지 바로 이어져 `meetingService`가 `mateService`를 가지고 로직이 수행되어 "약속 참여"에 대한 API를 개선하는 과정에서 `meetingService`의 일부 변경이 있었어요
- 일부 코드들은 #231 PR에서 남긴 리뷰 요청 사항에 대해 얘기 나눠본 후에 같이 수정해줘야할 것 같아요

2024-08-03 19:58 UTC, coli-geonwoo commented
@hyeon0208  오늘 중으로 리뷰 완료할 예정입니다!

2024-08-04 00:57 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
>                              description = "모임 참여 성공",
[필수]

이전 PR에서 놓친 부분인데, `모임` -> `약속`으로 일괄 변경해주시면 좋을 것 같아요~!

2024-08-04 01:27 UTC, eun-byeol requested changes
@hyeon0208 
코드는 빠르게 잘 작성해주셨는데,
테스트 실패하는 부분 해결해주셔야 할 것 같아요!
meetingService 관련 빈 순환참조 에러 때문에 application context에 등록되지 않는 것 같아요.

우선 RC로 남겨두겠습니다!

2024-08-04 01:27 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/mapper/OdsayResponseMapper.java
> +                        .orElse(EMPTY_MESSAGE)
to. 모든 크루
가끔 설정해 둔 포맷팅이 풀려있는 경우가 있어서, 잘 적용 되어 있는 지 모두 한 번씩 확인해보면 좋을 것 같아요!
포맷팅 적용이 자동이 아니라서, 아마도 단축키 눌러야 될거예요~ 커밋 전 한 번씩 체크 부탁드려요~!

[우테코 스타일 포맷팅 참고](https://velog.io/@pgmjun/IntelliJ-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC%EC%9D%84-%EC%84%A4%EC%A0%95%ED%95%B4%EB%B3%B4%EC%9E%90-feat.%EC%9A%B0%ED%85%8C%EC%BD%94)

2024-08-04 14:03 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
>                              description = "모임 참여 성공",
새로 변경된 API 문서에는 전부 "약속"으로 작성되어 있었네요
이전에 작성한 문서들은 "모임"이라는 단어로 문서를 작성해 기존에 있던 DTO들은 전부 "모임"이란 단어를 사용하고 있어요
노션의 문서에 맞춰 일단 수정하긴 했습니다만
저번에 내부적으로는 기존에 작성된 코드들 변경 때문에 "모임"이란 단어 그대로 쓰기로 한것으로 기억을 해서
더 늘어나기전에 이번에 확실히 정하고 전체 변경하면 좋을 꺼 같네요 🤔

2024-08-04 15:25 UTC, eun-byeol requested changes
@hyeon0208 
재개장하시느라 고생 많으셨습니다~

제 PC에서는 `MateServiceTest` 테스트 케이스가 실패하던데, 정확한 이유는 파악하지 못 했습니다..!
카키도 테케 다시 한 번 확인해주시면 감사드리겠습니다~
다른 분들도 똑같이 테스트 케이스가 실패하나요?

우선 RC로 남겨둘게요!

2024-08-04 15:25 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +                        meetingService.findById(meetingSaveResponseV1.id()),
[질문]

저만 테스트가 실패할까요..?🥲 두 테스트 모두 `DateTimeException`이 터져요.

![image](https://github.com/user-attachments/assets/2ad9703c-d7d6-45ce-b81c-47dae0ec7863)
<details>
  <summary>에러 로그</summary>
<pre><code>
Invalid value for NanoOfSecond (valid values 0 - 999999999): -226000000
java.time.DateTimeException: Invalid value for NanoOfSecond (valid values 0 - 999999999): -226000000
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:319)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:718)
	at java.base/java.time.LocalTime.with(LocalTime.java:859)
	at org.hibernate.type.descriptor.java.LocalTimeJavaType.wrap(LocalTimeJavaType.java:143)
	at org.hibernate.type.descriptor.java.LocalTimeJavaType.wrap(LocalTimeJavaType.java:39)
	at org.hibernate.type.descriptor.jdbc.TimeJdbcType$2.doExtract(TimeJdbcType.java:111)
	at org.hibernate.type.descriptor.jdbc.BasicExtractor.extract(BasicExtractor.java:44)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.getCurrentRowValue(JdbcValuesResultSetImpl.java:379)
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.getJdbcValue(RowProcessingStateStandardImpl.java:120)
	at org.hibernate.sql.results.graph.basic.BasicResultAssembler.extractRawValue(BasicResultAssembler.java:52)
	at org.hibernate.sql.results.graph.basic.BasicResultAssembler.assemble(BasicResultAssembler.java:59)
	at org.hibernate.sql.results.graph.DomainResultAssembler.assemble(DomainResultAssembler.java:35)
	at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.extractConcreteTypeStateValues(AbstractEntityInitializer.java:1037)
	at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeEntityInstance(AbstractEntityInitializer.java:794)
	at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeEntity(AbstractEntityInitializer.java:769)
	at org.hibernate.sql.results.graph.entity.AbstractEntityInitializer.initializeInstance(AbstractEntityInitializer.java:761)
	at org.hibernate.sql.results.internal.InitializersList.initializeInstance(InitializersList.java:73)
	at org.hibernate.sql.results.internal.StandardRowReader.coordinateInitializers(StandardRowReader.java:113)
	at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:87)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:190)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:211)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:83)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:76)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:65)
	at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:145)
	at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:117)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.load(SingleIdEntityLoaderStandardImpl.java:75)
	at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:3726)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3715)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:604)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromCacheOrDatasource(DefaultLoadEventListener.java:590)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:560)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:544)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:207)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadWithRegularProxy(DefaultLoadEventListener.java:290)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:242)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:111)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:68)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:138)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1225)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1213)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:209)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:160)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:149)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:112)
	at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:149)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2429)
	at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2400)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:319)
	at jdk.proxy3/jdk.proxy3.$Proxy195.find(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.findById(SimpleJpaRepository.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocati [...]

2024-08-04 23:33 UTC, mzeong commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +                        meetingService.findById(meetingSaveResponseV1.id()),
저도 확인해봤는데 제 로컬에서는 테스트가 모두 통과해요

2024-08-05 03:08 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +                        meetingService.findById(meetingSaveResponseV1.id()),
저도 테스트가 통과하는데 조조 쪽에서 터지는 이유를 모르겠네요 😥

2024-08-05 03:12 UTC, hyeon0208 commented
@eun-byeol 
@mzeong 
@coli-geonwoo 
모든 API 요청에 대한 응답으로 시간 형식이 초까지 포함된 형식으로 넘어온다고 하여 
응답 DTO의 LocalTime이 "시간 : 분" 만 응답되도록 수정했습니다

2024-08-05 10:07 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +                        meetingService.findById(meetingSaveResponseV1.id()),
다시 실행시켜보니 다 성공하네요!😄

2024-08-05 10:07 UTC, eun-byeol approved these changes

2024-08-05 11:06 UTC, mzeong approved these changes

2024-08-05 12:54 UTC, merged