docs: 약속 개설 API 문서화
woowacourse-teams/2024-ody pull request #249
Opened 2024-08-03 09:47 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #230 

<br>

# 📝 작업 내용
- [ ] #230 

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-03 13:12 UTC, hyeon0208 approved these changes
깔끔하게 분리된 개설 문서작업을 완료해주셨네요 ~ 👍🏻
approve 목걸이 드리고 갑니다 😄

2024-08-03 15:11 UTC, mzeong approved these changes

2024-08-03 15:11 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveV1Request.java
> +public record MeetingSaveV1Request(
[제안] `MeetingSaveRequestV1`, `MeetingSaveResponseV1`으로 네이밍하는 건 어떤가요? 버전이 맨 뒤에 붙는 게 쬐끔 더 눈에 잘 들어오는 것 같아요

추가로, 한 메서드 내에 다른 버전의 dto가 쓰일 일이 없을 것 같은데 변수 이름은 버전을 제외하고 `meetingSaveRequest`로만 쓰는 것 어떤가요?

2024-08-03 15:11 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +    public ResponseEntity<MeetingSaveV1Response> saveV1(
[제안] 시그니처가 달라 동일하게 `save`라고 네이밍해도 될 것 같아요

2024-08-03 15:11 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveV1Request.java
> +
[제안] 추가로 개행이 들어갔네요

```suggestion
```

2024-08-03 19:46 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
**[반영 완료]**

deprecated 옵션이 있는 줄 몰랐네요!  작성해주면 더 좋을 것 같아요! 좋은 제안 감사합니다 🙇

2024-08-03 19:49 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveV1Request.java
> +public record MeetingSaveV1Request(
**[반영 완료]**

저도 그 편이 더 좋을 것 같아요. 동의합니다.

2024-08-03 19:52 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveV1Request.java
> +
**[반영 완료]**

2024-08-04 01:34 UTC, eun-byeol requested changes
@coli-geonwoo
리뷰 남긴 부분은 #250 에서 반영해주셔도 좋을 것 같아요

approve 하겠습니다!
충돌난 부분이 있어 merge하지 않았습니다.

2024-08-04 01:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequestV1.java
> +        @Schema(description = "모임 이름", example = "우테코 16조")
[필수]

Request, Response 모두 
`모임` -> `약속`으로 일괄 변경해주셔야 할 것 같아요!

2024-08-04 02:16 UTC, eun-byeol approved these changes

2024-08-04 09:26 UTC, merged