design: 유저 현황 화면 디자인
woowacourse-teams/2024-ody pull request #252
Opened 2024-08-03 18:42 UTC by kimhm0728

# 🚩 연관 이슈 
close #209

<br>

# 📝 작업 내용
- [x] 유저 현황 화면 디자인

<br>

# 🏞️ 스크린샷 (선택)
<img width="452" alt="스크린샷 2024-08-04 오전 3 10 29" src="https://github.com/user-attachments/assets/d5eea5fc-3b0f-4223-8454-c44930d8e21a">
<br>
아직 기능 연결은 하나도 해놓지 않은 상태라서, 안스 캡쳐본만 일단 올립니다.

<br>

# 🗣️ 리뷰 요구사항 (선택)
### 리뷰 참고사항
- 로그 화면에 쓰이는 툴바를 해당 화면에서 재사용했습니다. 지금보니 로그창 툴바에 뒤로가기 버튼이 없길래(원래 피그마에도 없었고 현재는 추가된 상태) 추가하고 리스너 연결도 같이 했습니다~! 

- `activity_meeting_room.xml`에서 뷰들 제약조건 걸어줄 때 layout xmlns으로 사용되어있길래, 다른 뷰들과 통일성을 위해 app으로 변경했습니다.

### 질문
- 현재는 유저 현황 화면을 `dashboard`라고 표현을 했는데, 백엔드와 동일하게 `etas`로 네이밍하는 것도 좋을 것 같아요. 다들 어떤게 좋으신가요?

```
presentationroom
   └─ room
      ├─ log
      └─ dashboard
```
- 패키지를 위처럼 두면 좋을 것 같아요. 그런데 지금 로그 화면이 모두 `MeetingRoom`으로 네이밍 되어있어서 패키지를 바꾸기가 좀 애매하네요.. 홈 화면에서 약속 하나를 눌렀을 때 이동할 수 있는 화면들이 여러개이고, 그 안에서 화면의 순서도 변경될 여지가 있기 때문에 특정한 하나의 화면을 MeetingRoom이라고 하면 안 될 것 같아요. 다들 어떠신가요?

2024-08-04 03:20 UTC, aprilgom requested changes

2024-08-04 03:20 UTC, aprilgom commented on android/app/src/main/res/layout/item_dashboard.xml
> +        <TextView
<img width="491" alt="스크린샷 2024-08-04 12 00 32" src="https://github.com/user-attachments/assets/8f9779aa-4415-4249-83f7-af19275e3f29">


<img width="493" alt="스크린샷 2024-08-04 11 48 30" src="https://github.com/user-attachments/assets/1dc0d7c8-cac3-455a-84e5-35901086297c">

닉네임의 길이에 따라 뱃지와 예상 도착시간의 위치가 달라지는데, 피그마로 봤을 때 뱃지끼리 같은 줄에 정렬되어 있어야 할 것 같아요!

2024-08-04 03:20 UTC, aprilgom commented on android/app/src/main/res/values/strings.xml
> +    <string name="location_permission_self">위치 권한을 켜서 오디인지 공유해 보세요.</string>
안내 메시지라면 name 뒷편에 _guide를 붙이는건 어떨까요? (제안입니다)

2024-08-04 03:20 UTC, aprilgom commented on android/app/src/main/res/layout/item_dashboard.xml
> +            app:layout_constraintStart_toEndOf="@id/tv_nickname_dashboard"
`app:layout_constraintStart_toStartOf="parent"`
거기에 start 마진을 주면 일단 되긴 하는데..
다른 폰에서 어떻게 보일지 모르겠네요. 뱃지와 남은 시간이 오른쪽에 붙어있어야 할 것 같은데..
<img width="491" alt="스크린샷 2024-08-04 12 15 58" src="https://github.com/user-attachments/assets/54e37f86-d8d6-416d-965b-16137761a235">
<img width="491" alt="스크린샷 2024-08-04 12 15 21" src="https://github.com/user-attachments/assets/a86128fb-3f52-4105-9cef-fa6a812c5b51">

2024-08-04 04:18 UTC, aprilgom reviewed
그리고 현황 화면 패키지와 로그 화면 패키지를 room 아래 두는건 괜찮은 것 같습니다.
etadashboard는 어떤가요?

2024-08-04 08:14 UTC, haeum808 reviewed
고생하셨습니다!

2024-08-04 08:14 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
>          binding.rvNotificationLog.layoutManager = LinearLayoutManager(this)
동적으로 변경해야 할때만 Activity에서 layoutManager 설정하는건 어떤가요?

2024-08-04 08:14 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
>          binding.rvNotificationLog.layoutManager = LinearLayoutManager(this)
adapter도 xml에서 설정해주는건 어떤가요?

2024-08-04 11:07 UTC, kimhm0728 commented on android/app/src/main/res/values/strings.xml
> +    <string name="location_permission_self">위치 권한을 켜서 오디인지 공유해 보세요.</string>
변경했습니다! 다른 string resource들과 통일성을 위해서라도 guide를 붙이는 것이 좋겠네요 👍

2024-08-04 11:21 UTC, kimhm0728 commented on android/app/src/main/res/layout/item_dashboard.xml
> +        <TextView
<img width="522" alt="스크린샷 2024-08-04 오후 8 17 58" src="https://github.com/user-attachments/assets/e4bb1812-a8a1-4c28-873c-6e95127dfe2f">

요런 부분은 고려하지 못했네요 ㄷㄷ 감사해요! 
차람이 아래 코멘트에 남겨주신 것처럼 뱃지 제약조건을 변경해서, 뱃지를 화면 가장 중앙에 배치했습니다. 
그리고 뱃지의 왼쪽에 있는 닉네임과 오른쪽에 있는 textView를 0dp로 설정해서 남아있는 모든 공간을 차지하게 했습니다. [c183a4c](https://github.com/woowacourse-teams/2024-ody/pull/252/commits/c183a4c8972867b14e4490b1e0a61e642b8a3d2c)

2024-08-04 11:23 UTC, kimhm0728 commented
@haeum808 @aprilgom 
해음! PR 본문에 있는 질문 확인 부탁드려요! 해음도 동의한다면 제가 MeetingRoom 네이밍, 패키지 구조까지 변경해보겠습니다~!
그리고 차람이 말한 `etadashboard` 좋은 것 같아요. 그러면 `EtaDashBoardActivity.kt`, `activity_eta_dashboard.xml`가 되겠군요...!!!

2024-08-04 11:24 UTC, haeum808 commented
저는 대쉬보드로 사용하는거에 동의합니다!

2024-08-04 11:26 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
>          binding.rvNotificationLog.layoutManager = LinearLayoutManager(this)
아앗 이부분 제가 개발한 부분이 아니긴 한데 ㅋㅋㅋㅋㅋㅋ 저도 동의합니다. 간단한 거니까 제가 바꾸겠습니다~! [a1ec3ad](https://github.com/woowacourse-teams/2024-ody/pull/252/commits/a1ec3ad26174234bc3396f6953884e222f872d3b)

2024-08-04 11:28 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
>          binding.rvNotificationLog.layoutManager = LinearLayoutManager(this)
```kotlin
binding.rvNotificationLog.adapter = adapter
```
이 부분 말하는 거 맞을까요?? 어차피 바인딩 객체에 어댑터를 전달할 거라면, 현재 코드와 다른 부분이 없어보여서요!!!

2024-08-04 11:28 UTC, aprilgom approved these changes
수고하셨습니다!

2024-08-04 11:36 UTC, haeum808 approved these changes
고생하셨습니다!

2024-08-04 11:38 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
>          binding.rvNotificationLog.layoutManager = LinearLayoutManager(this)
맞습니다. 생각해보니 비슷하겠네요! 원래 방식이 좋습니다!

2024-08-04 14:31 UTC, haeum808 commented
etaDashboard와 log가 같은 room 패키지에 있을 필요는 없을거 같긴하네요. 따로 나누는건  어떤가요? @kimhm0728 @aprilgom

2024-08-05 05:47 UTC, aprilgom commented
log와 etaDashboard가 왜 붙어있다 여겼을까? 잠깐 생각해봤는데,
그 둘은 약속의 멤버목록을 가지는 모임방같은 존재들이네요.
어느정도 자연스러운 것 같습니다.

2024-08-05 05:52 UTC, aprilgom approved these changes

2024-08-05 05:52 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/eta/EtaDashboardActivity.kt
> +package com.woowacourse.ody.presentation.room.eta
패키지 명에는 코멘트가 안 달려서 여기에 적습니다. 패키지 명도 변경하는 건 어떨까요?
`eta` -> `etadashboard`

2024-08-05 06:41 UTC, merged