refactor: 약속 단건 조회 API 구현
woowacourse-teams/2024-ody pull request #256
Opened 2024-08-05 00:10 UTC by eun-byeol

# 🚩 연관 이슈 
close #224

<br>

# 📝 작업 내용
#245 리뷰 반영했습니다.
- @ArraySchema
- @ErrorCode404
- LocalDate, LocalTime JsonFormat 적용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-05 10:59 UTC, hyeon0208 approved these changes
꼼꼼하게 테스트까지 작성해주셨네요 👍🏻
approve 드리고 갑니다 😄

2024-08-05 10:59 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +    @DisplayName("회원이 참여하고 있는 특정 약속의 참여자 리스트를 조회한다.")
예외 상황까지 꼼꼼한 테스트 👍🏻

2024-08-05 10:59 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
> +    @ErrorCode404(description = "존재하지 않는 약속이거나 해당 약속 참여자가 아닌 경우")
👍🏻

2024-08-05 10:59 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm", timezone = "Asia/Seoul")
[질문]
pattern으로 시간 분만 응답으로 나가게 되었는데
타입을 String으로 변환한 이유가 있나요 ??

2024-08-05 15:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +    public List<Mate> findAllByMemberAndMeetingId(Member member, Long meetingId) {
반영했습니다~👍

2024-08-05 15:38 UTC, coli-geonwoo requested changes
조조! 구현하느라 고생 많으셨어요! 몇가지 리뷰 사안 적었어요!

테스트 코드 상에서 반영이 꼭 필요한 부분 생겨 우선 RC로 남겨놓습니다.

2024-08-05 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "Asia/Seoul")
[제안-선택]

커스텀 직렬화 도구를 통해 LocalDate와 LocalTime 형식을 지정할 수 있어요. json으로 반환할 때 우리가 반환로직을 지정해줄 수 있습니다. 매번 LocalDate나 LocalTime마다 jsonformat을 붙이기 보다 하나의 클래스 선언으로 모든 LocalTime과 LocalDate의 형식을 지정해줄 수 있습니다.

ex) yyyy-MM-dd로 형식 맞추는 클래스
다만 조금 시간이 걸리는 리팩터링 사안이라 반영은 조조 의사에 맡길게요!!

```java
@JsonComponent
public class CustomLocalDateSerializer extends JsonSerializer<LocalDate> {
    private static final DateTimeFormatter TIME_FORMATTER = new DateTimeFormatterBuilder()
            .appendPattern("yyyy-MM-dd")
            .toFormatter()
            .withZone(ZoneId.of("Asia/Seoul"));

    @Override
    public void serialize(
            LocalDate localDate,
            JsonGenerator jsonGenerator,
            SerializerProvider serializerProvider
    ) {
        try {
            jsonGenerator.writeString(TIME_FORMATTER.format(localDate));
        } catch (IOException exception) {
            throw new RuntimeException("날짜 변환 과정에서 문제가 발생했습니다.");
        }
    }
}

```

```java
@JsonComponent
public class CustomLocalTimeSerializer extends JsonSerializer<LocalTime> {
    private static final DateTimeFormatter TIME_FORMATTER = new DateTimeFormatterBuilder()
            .appendPattern("HH:mm")
            .toFormatter()
            .withZone(ZoneId.of("Asia/Seoul"));

    @Override
    public void serialize(
            LocalTime time,
            JsonGenerator jsonGenerator,
            SerializerProvider serializerProvider
    ) {
        try {
            jsonGenerator.writeString(TIME_FORMATTER.format(time));
        } catch (IOException exception) {
            throw new RuntimeException("시간 변환 과정에서 문제가 발생했습니다.");
        }
    }
}
```

2024-08-05 15:38 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
> +        @ArraySchema(schema = @Schema(implementation = MateResponse.class))
👍

2024-08-05 15:38 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +        Long mate1Id = mateRepository.save(Fixture.MATE1).getId();
**[제안- 필수]**

오늘 카키와 발견한 문제인데 Fixture.Mate들은 쓰면 안될 것 같아요. 연관관계가 설정된 엔티티인데 static 객체라서 전체 테스트를 돌릴 때 id가 계속 변하게 되더라고요.

테스트 스트림이 병렬이라 어쩔 땐 mate id가 일치해서 통과하는데 다른 코드가 먼저 돌아가 autoincrement되어 테스트가 깨져요.

Mate는 새로운 객체를 만들어서 사용해야 안전할 것 같습니다. 관련 내용은 내일 더 이야기나눠보아요.

```suggestion
       Mate mate = new Mate(.......) //mate는 fixtue 쓰지 말것!!
        Long mate1Id = mateRepository.save(mate).getId();
```

2024-08-05 15:38 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
> +                () -> assertThat(mateNicknames).containsOnly(
[제안]

순서까지 검증해주는 containsExactlyOnly를 쓰면 더 정확할 것 같아요

2024-08-05 16:09 UTC, eun-byeol commented on backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
> +                () -> assertThat(mateNicknames).containsOnly(
데이터를 정렬해서 주는 것이 아니라서,
오히려 순서를 보장해서 테스트하는 것이 맞지 않다고 생각했어요!

2024-08-06 06:13 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd", timezone = "Asia/Seoul")
커스텀 직렬화 도구 사용하는 것은 새롭게 이슈 파서 적용하는 게 좋을 것 같아요.
이미 @JsonFormat 적용되어 있는 코드가 많아서, 한 번에 수정하면 좋을 것 같습니다~

2024-08-06 11:00 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +        Long mate1Id = mateRepository.save(Fixture.MATE1).getId();
반영 완료했습니다~👍

2024-08-06 11:04 UTC, eun-byeol commented
**변경 사항**
1. meetingId primitive type으로 변경
2. JsonFormat 불필요한 옵션 제거
3. Fixture.MATE 제거

**리뷰 반영한 코드는 [여기](https://github.com/woowacourse-teams/2024-ody/pull/256/files/f5fb8dc28ce0d63f57f6cee2f8f24943fe061c97..ec00da9847bb4a8293ba7a503d5f63651580f6a8)에서 확인 가능합니다.**

2024-08-06 11:12 UTC, mzeong approved these changes

2024-08-06 11:19 UTC, coli-geonwoo approved these changes

2024-08-06 11:20 UTC, coli-geonwoo commented
직접 커밋 변경 범위도 설정해주고 친절한 조조.... 👍 

리뷰 사안 최대한 많이 수용해줘서 감사합니다!! approve 합니다!

2024-08-06 11:29 UTC, merged