feat: 단일 약속 api 연결
woowacourse-teams/2024-ody pull request #281
Opened 2024-08-06 18:17 UTC by aprilgom

# 🚩 연관 이슈 
close #237

<br>

# 📝 작업 내용
- [x] 단일 약속 api 연결
- [x] 날짜에 따른 오디 버튼 활성화/비활성화
<br>

# 🏞️ 스크린샷 (선택)

https://github.com/user-attachments/assets/68a56c09-69f6-4649-ba4a-92f802ca007f

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-06 22:27 UTC, haeum808 approved these changes
고생하셨습니다

2024-08-06 22:27 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
> +    private val meetingId: Long = savedStateHandle[PUT_EXTRA_MEETING_ID] ?: -1L
이 savedStataeHandle meetingId의 역할이 뭔지 궁긍합니다!

2024-08-06 23:07 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
> +    private val meetingId: Long = savedStateHandle[PUT_EXTRA_MEETING_ID] ?: -1L
home activity에서 선택한 meeting의 Id입니다.

2024-08-07 01:35 UTC, kimhm0728 requested changes
고생하셨어요! 👍

2024-08-07 01:35 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModelMapper.kt
> +        isEnabled = datetime.isAfter(LocalDateTime.now()) && datetime.isBefore(LocalDateTime.now().plusDays(1)),
현황 화면으로 이동할 수 있는 버튼은 모임 시간 30분 전부터 활성화됩니다. 수정 부탁드려요!

2024-08-07 01:35 UTC, kimhm0728 commented on android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
> +    xmlns:tools="http://schemas.android.com/tools">
tools 안 쓰이는 것 같은데 삭제 부탁드립니다!

2024-08-07 01:35 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
> +    ): T {
오 새로운 지식 알아갑니다~!

2024-08-07 01:47 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/home/model/MeetingCatalogUiModelMapper.kt
> +        isEnabled = datetime.isAfter(LocalDateTime.now()) && datetime.isBefore(LocalDateTime.now().plusDays(1)),
수정했습니다

2024-08-07 01:47 UTC, aprilgom commented on android/app/src/main/res/layout/layout_navigate_to_meeting_room.xml
> +    xmlns:tools="http://schemas.android.com/tools">
넵넵

2024-08-07 01:47 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
> +    ): T {
아주 좋아 너무 좋아~

2024-08-07 01:48 UTC, kimhm0728 approved these changes
굿입니다!!

2024-08-07 01:50 UTC, merged