refactor: 약속 리스트 관련 수정 사항
woowacourse-teams/2024-ody pull request #312
Opened 2024-08-07 22:12 UTC by aprilgom

# 🚩 연관 이슈 
close #307

<br>

# 📝 작업 내용

- [x] 약속 리스트 아이템 디자인 올바르게 수정
- [x] 약속 리스트 아이템 navigation
- [x] 비활성화된 오디 버튼 클릭 시 메시지 변경
- [x] 접었다 폈다 할 때 깜빡힘 현상 수정

<br>

# 🏞️ 스크린샷 (선택)

https://github.com/user-attachments/assets/be4109fe-c039-418f-818f-32adef8cffd9

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-07 22:47 UTC, haeum808 approved these changes
고생하셨습니다!

2024-08-07 22:47 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        binding.rvMeetingList.itemAnimator = null
xml에서 해주는건 어떤가요?

2024-08-07 22:47 UTC, haeum808 commented on android/app/src/main/res/layout/item_meeting_catalog.xml
> +                tools:visibility="gone"
이 부분 지워도 괜찮을까요?

2024-08-07 22:56 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        binding.rvMeetingList.itemAnimator = null
app:itemAnimator="null"을 rv_meetinglist에 넣으면 되나요?

2024-08-07 22:58 UTC, aprilgom commented on android/app/src/main/res/layout/item_meeting_catalog.xml
> +                tools:visibility="gone"
지워주었습니다.

2024-08-08 00:58 UTC, kimhm0728 requested changes
고생하셨습니다 👍

2024-08-08 00:58 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsNavigateAction.kt
> +    data class NavigateToMeetingRoom(val meetingId: Long) : MeetingsNavigateAction
MeetingRoom 아니고 NotificationLog 화면인 것 같아요!

2024-08-08 00:58 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
> +        viewModelScope.launch {
반환값이 Job인 이유가 있을까요? 이 반환값을 활용하고 있는 곳이 없는 것 같아서요. 
```suggestion
    override fun navigateToEta(meetingId: Long) {
        viewModelScope.launch {
```
이렇게 변경하면 되지 않을까요??

2024-08-08 00:58 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        binding.rvMeetingList.itemAnimator = null
xml로 이동했다면 이 부분은 제거해주세요!

2024-08-08 00:58 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsBindingAdapter.kt
> +            meetingDay >= today.plusDays(2) && meetingDay <= today.plusDays(7) -> {
`meetingDay >= today.plusDay(2)` 조건이 다시 추가된 이유가 뭔가요? (진짜 궁금)

2024-08-08 01:01 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsBindingAdapter.kt
> +            meetingDay >= today.plusDays(2) && meetingDay <= today.plusDays(7) -> {
아 이거 하루 지났을 때 -1일이라 표시되는 문자가 있어서..

2024-08-08 01:01 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        binding.rvMeetingList.itemAnimator = null
넵

2024-08-08 01:02 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsNavigateAction.kt
> +    data class NavigateToMeetingRoom(val meetingId: Long) : MeetingsNavigateAction
바꿔주었습니다

2024-08-08 01:33 UTC, closed without merging