refactor: 시간 비교 로직에서 초/나노초 단위 trim
woowacourse-teams/2024-ody pull request #346
Opened 2024-08-10 06:38 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #343

<br>

# 📝 작업 내용
- [x] #343 

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
- 현재 develop 기준으로 trim 처리하긴 했는데 빠르게 merge한 이후, 카키와 진행 중인 Status mapping 로직 리팩터링 하면서 한번 더 반영하겠습니다. (리팩터링 브랜치를 먼저 파서 #343 리팩터링 내용을 반영하지 못한 상황)

- [관련 커밋내용만 보기](9ec78c2b555b7746aa99ef3c016aae2dd06f33b2)

2024-08-10 07:09 UTC, eun-byeol approved these changes
테스트까지 꼼꼼하게 작성해주셨네요.
고생하셨어요 콜리!

몇 가지 질문을 남겼으니 확인해주세요🤔
approve 할게요!

2024-08-10 07:09 UTC, eun-byeol commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +    public static LocalDateTime now() {
[제안]

now() 보다 저 자세한 네이밍이면 좋을 것 같아요. nowWithTrim, trimNow 같이 trim 작업이 내부에 수행됨을 알려주는 게 좋지 않을까요?
지금으로서는 메서드 시그니처를 봤을 때 LocalDateTime.now()과 어떤 차이가 있는지 모를 것 같아요.

2024-08-10 07:09 UTC, eun-byeol commented on backend/src/test/java/com/ody/util/TimeUtilTest.java
> +                () -> assertThat(actualTime.compareTo(expectedTime)).isZero()
[질문]

여기만 compareTo를 사용한 이유가 있나요?

2024-08-10 07:11 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +                .withNano(ROUND_DIGITS);
아니요. 개행이나 컨벤션에 아직 제가 예민하지 못하네요 😅  반영해두겠습니다!

2024-08-10 07:12 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/util/TimeUtilTest.java
> +                () -> assertThat(actualTime.compareTo(expectedTime)).isZero()
LocalTime에는 isEqual 메서드가 없어 compareTo로 비교 테스트를 수행하였습니다.

2024-08-10 07:12 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +    public static LocalDateTime now() {
조조 의견에 동의해요! nowWithTrim 좋은 메서드 명이네요 👍

2024-08-10 10:32 UTC, hyeon0208 requested changes
빠르게 적용해주셨네요 ~ 👍🏻
간단한 리뷰만 남기고 갑니다 😄

2024-08-10 10:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +                .withNano(ROUND_DIGITS);
[제안]
변수의 값이 달라져 첫 줄부터 개행하신거 같은데
지금 대로면 time 변수와 체이닝 메서드가 관련이 없어 보이는 것 같아요
```suggestion
        return time.withSecond(ROUND_DIGITS)
                .withNano(ROUND_DIGITS);
```
개인적으로는 첫 줄 부터 개행하긴 보단 이런식으로 작성하는 것이 time에 어떠한 행위를 적용했는지 직관적으로 보일 것 같아요

2024-08-10 10:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +public class TimeUtil {
[제안[
TimeUtill이 LocalDateTime과 LocalTime을 가공하고 
시간만 가공해줄 것 같은데 날짜가 포함된 LocalDateTime을 반환해주는게 어색하게 느껴졌어요

클래스명을 DateTimeUtil로 네이밍 해주는 것은 어떻게 생각하실까요 ??

2024-08-10 10:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +    public static LocalDateTime trim(LocalDateTime time) {
[제안]
뭘 다듬는 다는지 의미 전달이 좀 더 명확하도록 
`trimSecondsAndNanos()`는 어떠신강쇼 ?

2024-08-11 10:21 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +                .withNano(ROUND_DIGITS);
[답변]
아, 첫줄을 개행했다는 질문이 그 이야기였군요. 합리적인 리뷰네요! 반영해놓겠습니다. 👍

2024-08-11 10:23 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +    public static LocalDateTime trim(LocalDateTime time) {
일반 객체 메서드에서는 구현 내용이 드러나는 걸 좋아하지 않는데, 카키 말대로 유틸 클래스는 기능적 차원의 메소드를 가져다 쓰는 것이니 명확한 메서드가 좋겠네요. 반영하겠습니다

2024-08-11 10:26 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +public class TimeUtil {
TimeUtil에서 Time은 특정 LocalTime을 칭하기 보다 시간과 관련된 유틸성 기능을 모아놓은 다는 추상적 의미가 더 큰 것 같아요. Collections.sort를 List.sort로 만들지 않은 것 처럼 `시간 관련 유틸 클래스`로서 TimeUtil이 저는 괜찮은 클래스 명이라 생각해요.

다른 분들은 어떤 메서드명이 더 자연스럽다 생각하시나요?

2024-08-11 15:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +public class TimeUtil {
둘 다 이해가 가요.
카키는 Date + Time 두 단어의 조합으로 본 것 같고, 콜리는 DateTime 하나의 단어로 해석해서 지엽적이다라고 본 것 같아요.

저는 timeUtil이 더 적합한 것 같아요. 둘 다 time 하위에 있는 클래스라서요.
`import java.time.LocalDateTime;`
`import java.time.LocalTime;`

2024-08-12 02:44 UTC, mzeong commented on backend/src/main/java/com/ody/util/TimeUtil.java
> +public class TimeUtil {
해당 유틸 클래스가 시간과 관련한 가공 기능만 제공하고 있어 TimeUtil로 네이밍할 것 같아요

만약 ‘년/월/일 하위로 제거’와 같은 날짜를 대상으로 하는 기능도 함께 제공한다면 일시 관련 유틸이라는 의미를 드러내기 위해 네이밍으로 DateTime을 고려할 것 같아요

2024-08-12 02:44 UTC, mzeong approved these changes

2024-08-12 05:16 UTC, hyeon0208 approved these changes

2024-08-12 05:17 UTC, merged