refactor: 권한 체크, 권한 요청 분리
woowacourse-teams/2024-ody pull request #347
Opened 2024-08-10 07:43 UTC by haeum808

# 🚩 연관 이슈 
close #342 

<br>

# 📝 작업 내용
- [x] 알림 권한
- [x] 위치 권한

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-10 08:03 UTC, aprilgom requested changes

2024-08-10 08:03 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +            if (grantResults.isNotEmpty() &&
`if (grandResults ~` 조건문이 반복되고 있는데, 함수로 분리해보는 건 어떨까요

2024-08-10 08:12 UTC, aprilgom requested changes

2024-08-10 08:12 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +            if (grantResults.isNotEmpty() &&
`grantResults.isNotEmpty()`가 반복되고 있는데요,
처음부터 grantResults가 empty라면 리턴해버리는게 깔끔할 것 같습니다.

2024-08-10 08:22 UTC, aprilgom reviewed
수고하셨습니다잉

2024-08-10 08:22 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                grantResults[0] == PackageManager.PERMISSION_GRANTED
이부분 `!=`로 바꾸면 함수 분리도 생각해볼 수 있을 것 같습니다.
`if (grantResults[0] != PackageManager.PERMISSION_GRANTED)`
함수 분리를 했는데도 뭔가 지저분할 것 같다 싶으면 분리 안하셔도 좋습니다

2024-08-10 08:31 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
> +        fun getIntent(context: Context): Intent = Intent(context, MeetingsActivity::class.java)
헉 그렇네요!

2024-08-10 09:11 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        if (requestCode == PermissionHelper.NOTIFICATION_REQUEST_CODE) {
변경하겠습니다!

2024-08-10 09:12 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +            if (grantResults.isNotEmpty() &&
좋습니다!

2024-08-10 09:17 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                grantResults[0] == PackageManager.PERMISSION_GRANTED
함수화 하겠습니다!

2024-08-10 09:19 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        if (permissionHelper.hasNotificationPermission() &&
이부분은 액티비티에 있는게 좋은 것 같습니다. 객체에서 받아서 조합해서 쓰는 느낌으로

2024-08-10 10:15 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        if (permissionHelper.hasNotificationPermission() &&
그렇군요..

2024-08-10 10:15 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        permissionHelper.requestNotificationPermission(this)
여기선 NotificationPermission만 요청하고 있는 것 같은데요,
나머지를 다른 곳에서 요청하고 있어서 그런가요? (그냥 질문)

2024-08-10 10:15 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
> +    fun coarseAndFineLocationPermission(activity: Activity) {
여기 request가 빠진 것 같아요

2024-08-10 10:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
> +    fun coarseAndFineLocationPermission(activity: Activity) {
추가하겠습니다!

2024-08-10 10:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        permissionHelper.requestNotificationPermission(this)
맞습니다!!

2024-08-10 10:35 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +        permissionHelper.requestNotificationPermission(this)
그런데 다른 곳에서 해줘도 될거 같아요!

2024-08-10 10:54 UTC, aprilgom approved these changes
수고하셧습니다잉
회장님 남은 주말 잘 보내세요

2024-08-10 11:32 UTC, haeum808 commented
감사합니다 사장님

2024-08-10 11:42 UTC, aprilgom commented
> 감사합니다 사장님

342-a 브랜치에 코드 작성해봤는데, 
한번 보시고 괜찮으면 가져가시면 감사할 것 같습니다잉

2024-08-10 15:52 UTC, kimhm0728 requested changes
고생하셨습니다. 부지런하네요 해음 ☀️

2024-08-10 15:52 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +    override fun onRequestPermissionsResult(
이건 다른 이슈에서 먼저 작성된 부분이긴 하지만, BindingActivity에서도 이 함수를 override한 이유가 있을까요? `super.onRequestPermissionsResult()`만 호출해주고 있는 것 같아서요!

2024-08-10 15:52 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.Q)
`@RequiresApi`는 IDE 상에서 오류만 막아주는 역할이고, 실제로 Q 버전 이하의 디바이스에서 이 함수를 호출했을 때는 오류가 발생하는 것으로 알고 있는데요. (아닐 수도 있음..)
`@RequiresApi` 대신 if 문으로 분기처리를 하면 어떨까요? 
예시)
```kotlin
        if (Build.VERSION_CODES.Q > Build.VERSION.SDK_INT) {
            return
        }
```
`@RequiresApi` 사용하고 있는 모든 부분에 해당하는 리뷰입니다! 
+ 항상 호출되어야 할 `onCreate()` 전체에 `@RequiresApi` 어노테이션을 달아두는 것도 어색하게 느껴져서요!

2024-08-10 15:52 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
> +    }
`PermissionHelper` 내에 반복되는 이 부분도 함수로 분리하는 건 어떨까요? 그러면 `Manifest.permission.ACCESS_COARSE_LOCATION`와 같은 상수들만 인자로 받으면 될 것 같아요.

권한이 많아지면 `PermissionHelper` 내의 함수들도 많아질 것 같은데, `Manifest.permission.ACCESS_COARSE_LOCATION`와 같은 상수 자체를 액티비티에서 받아와도 되겠네요.
예시)
```kotlin
// PermissionHelper
    fun hasPermission(permissionCode: String): Boolean {
        return ContextCompat.checkSelfPermission(
            context,
            permissionCode,
        ) == PackageManager.PERMISSION_GRANTED
    }
    
// Activity
permissionHelper.hasPermission(Manifest.permission.ACCESS_COARSE_LOCATION)
```
액티비티에서 위 `hasPermission()`과 같은 함수를 호출할지, 그대로 `PermissionHelper`에 둘지는 해음의 스타일대로 반영해주세요~

2024-08-13 01:25 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +    override fun onRequestPermissionsResult(
삭제하겠습니다!

2024-08-13 01:28 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.Q)
변경하겠습니다!

2024-08-13 02:03 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/common/PermissionHelper.kt
> +    }
fun hasBackgroundLocationPermission(): Boolean {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            ContextCompat.checkSelfPermission(
                context,
                Manifest.permission.ACCESS_BACKGROUND_LOCATION,
            ) == PackageManager.PERMISSION_GRANTED
        } else {
            true
        }
    }

위 코드 같이 버전 확인이 필요하면 한 메서드에서 너무 많은 분기 처리가 일어날 것 같아서 현상유지 쪽으로 가겠습니다!

2024-08-13 05:03 UTC, kimhm0728 approved these changes
고생하셨습니다~! 👍

2024-08-13 05:12 UTC, merged