design: 로그인 화면 디자인
woowacourse-teams/2024-ody pull request #388
Opened 2024-08-14 06:34 UTC by aprilgom

# 🚩 연관 이슈 
close #378

<br>

# 📝 작업 내용
- [x] 로그인 화면 디자인

<br>

# 🏞️ 스크린샷 (선택)

![무제](https://github.com/user-attachments/assets/05e12432-2c09-4122-8b88-ddafde9ca977)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-14 06:48 UTC, haeum808 approved these changes
mdpi(1.0)랑 hdpi(1.5)랑 사이즈 크기가 반대네요. 차람 제것도 다 바꿔줄 수 있나요?
현재는 hdpi 이미지들이 mdpi 보다 작네요

달력이랑 손뼉 사진은 삭제해주세요!

2024-08-14 06:57 UTC, aprilgom commented
> mdpi(1.0)랑 hdpi(1.5)랑 사이즈 크기가 반대네요. 차람 제것도 다 바꿔줄 수 있나요? 현재는 hdpi 이미지들이 mdpi 보다 작네요
> 
> 달력이랑 손뼉 사진은 삭제해주세요!

수정해주었습니다잉

2024-08-14 07:58 UTC, haeum808 approved these changes

2024-08-14 11:46 UTC, kimhm0728 requested changes
고생하셨습니다!

2024-08-14 11:46 UTC, kimhm0728 commented on android/app/src/main/res/layout/activity_login.xml
> +        android:layout_height="wrap_content"
지금 `layout_marginHorizontal` 적용이 안 되고 있어요. 제약 조건 start, end를 parent로 설정했으니 `layout_width`을 `wrap_content`이 아닌 0dp로 해야 ImageView가 화면의 width에 꽉 찰 것 같습니다.

imageView의 `scaleType` 속성을 통해 이미지가 깨지지 않도록 하거나, `layout_constraintDimensionRatio`로 이미지 비율을 유지하는 건 어떨까요?
아래 코드는 참고만 해주세요~

```xml
    <ImageView
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginHorizontal="20dp"
        android:layout_marginBottom="24dp"
        android:src="@drawable/img_kakao_login"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="477:72"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />
```

2024-08-14 11:46 UTC, kimhm0728 commented on android/app/src/main/res/layout/activity_login.xml
> +        />
그리고 pr 올리기 전 xml 정렬 단축키 부탁합니다!

2024-08-14 11:46 UTC, kimhm0728 commented on android/app/src/main/res/layout/activity_login.xml
> +    android:id="@+id/main"
이 부분 쓰이지 않고 있는데 삭제하는 건 어떨까요?

2024-08-14 12:37 UTC, aprilgom commented on android/app/src/main/res/layout/activity_login.xml
> +        android:layout_height="wrap_content"
png는 일부러 잡아 늘리면 이미지가 깨지지 않을까? 생각했는데 이런 방법이 있었네요. 감사합니다!

2024-08-14 12:38 UTC, aprilgom commented on android/app/src/main/res/layout/activity_login.xml
> +        />
넵

2024-08-14 12:38 UTC, aprilgom commented on android/app/src/main/res/layout/activity_login.xml
> +    android:id="@+id/main"
알겠습니다잉

2024-08-15 03:49 UTC, kimhm0728 approved these changes
리뷰 반영 확인했습니다 굿굿 👍

2024-08-15 03:51 UTC, merged