test: InviteCodeViewModel 테스트
woowacourse-teams/2024-ody pull request #392
Opened 2024-08-14 08:37 UTC by aprilgom

# 🚩 연관 이슈 
close #391 

<br>

# 📝 작업 내용
- [x] SingleLiveData를 위한 getOrAwaitValue 구현
- [x] SingleLiveData<Unit>이 한 번 Handle되었는지 알기 위한 getIfHandled 구현
- [x] checkInviteCode() 메서드의 테스트 구현

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-14 08:45 UTC, haeum808 approved these changes
고생하셨습니다!

2024-08-14 08:45 UTC, haeum808 commented on android/app/src/test/java/com/woowacourse/ody/fake/FakeAnalyticsHelper.kt
> +    ) {}
= Unit 어떤가요?

2024-08-14 10:59 UTC, aprilgom commented on android/app/src/test/java/com/woowacourse/ody/fake/FakeAnalyticsHelper.kt
> +    ) {}
좋습니다잉

2024-08-14 11:58 UTC, kimhm0728 requested changes
고생하셨습니다~!

2024-08-14 11:58 UTC, kimhm0728 commented on android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
> +        ).isInstanceOf(InviteCodeNavigateAction.CodeNavigateToJoin::class.java)
given when then 사이에 한줄 띄우는 건 어떤가요?? 다른 코드와 통일성을 위해..

2024-08-14 11:58 UTC, kimhm0728 commented on android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
> +        InviteCodeViewModel(
`InviteCodeViewModel`에 대한 테스트임이 명확하니, `viewModel`이라고 네이밍해주는 건 어떤가요? Activity에서도 뷰모델 풀네임을 쓰기보다, `viewModel`이라고 작성하는 것 처럼요!

2024-08-14 11:58 UTC, kimhm0728 commented on android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
> +            inviteCodeViewModel.invalidInviteCodeEvent.getIfHandled(),
이미 소비되었는지 확인하기보다, 에러 이벤트가 발생했는지 여부만을 테스트하는 건 어떨까요? 어차피 이전에 `invalidInviteCodeEvent`가 발생하지 않았음은 명확하니까요. (+ 비슷한 맥락으로 다른 테스트와의 독립성을 제거하기 위해 `setUp()`에서 viewModel을 매번 초기화해주는 것을 선호하긴 합니다.)

이건 개인적 의견이니 반영하지 않으셔도 됩니다!

2024-08-14 11:58 UTC, kimhm0728 commented on android/app/build.gradle.kts
> +    }
이건 어떤 속성인가요? 궁금..

2024-08-14 12:46 UTC, aprilgom commented on android/app/build.gradle.kts
> +    }
이 친구는 안드로이드에 의존적인 메서드가 유닛 테스트 안에서 실행되서 일어나는 에러때문에 넣어놓은 코드인데요,
정확히는 `AnalyticsHelper`의 확장함수 `logNetworkEvent()` 내의 `bundleOf()` 메서드가 유닛 테스트 안에서 실행되어 
![err](https://github.com/user-attachments/assets/fd761c42-2043-4596-9818-8caa9f825c9d)
이런 버그를 내기에, 에러에 첨부된 링크를 따라 처리했습니다.
[링크]( https://developer.android.com/r/studio-ui/build/not-mocked )

2024-08-14 13:03 UTC, aprilgom commented on android/app/build.gradle.kts
> +    }
안드로이드에 의존적인 메서드가 유닛 테스트 안에서 실행되서 일어나는 에러인 것 같습니다. 문서에서는 `Context.getString()`을 예시로 들고 있네요. Mock을 통해 해결하는 것을 권장하고 있지만, 저희는 Mock을 쓰지 않기로 했기에 `unitTests.isReturn~`으로 해결했습니다.

2024-08-14 13:09 UTC, aprilgom commented on android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
> +        ).isInstanceOf(InviteCodeNavigateAction.CodeNavigateToJoin::class.java)
좋아요!

2024-08-14 13:22 UTC, aprilgom commented on android/app/src/test/java/com/woowacourse/ody/viewmodel/InviteCodeViewModelTest.kt
> +            inviteCodeViewModel.invalidInviteCodeEvent.getIfHandled(),
Event의 content를 설정할 때 hasBeenHandled가 변경되지 않나요? Handled 여부를 확인하면 이벤트가 발생 되었는지 알 수 있는것이라 생각했습니다.

2024-08-15 03:47 UTC, kimhm0728 commented on android/app/build.gradle.kts
> +    }
헉 그렇군요..
저도 뷰모델 테스트할 때 차람이랑 비슷한 방식으로 했었는데, 오류는 발생하지 않았거든요.. 일단 저 방식으로 해결된다니 다행입니다! 저도 저 속성에 대해 더 찾아봐야겠어요 알려줘서 감사합니다 👍

2024-08-15 03:48 UTC, kimhm0728 approved these changes
리뷰 반영된 것 확인했어요 감사합니다 👍👍

2024-08-15 04:54 UTC, merged