refactor: splash 라이브러리 사용으로 변경
woowacourse-teams/2024-ody pull request #406
Opened 2024-08-16 07:30 UTC by haeum808

# 🚩 연관 이슈 
close #386 

<br>

# 📝 작업 내용
- [x] splash 라이브러리 사용

<br>

# 🏞️ 스크린샷 (선택)
[Screen_recording_20240816_162919.webm](https://github.com/user-attachments/assets/007977f3-eabd-4d84-9b18-f62bbd3ec6d3)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-16 07:48 UTC, kimhm0728 requested changes
고생하셨습니다.
해음이 첨부해주신 영상에는 오디 로고가 조금 잘리는 것 같아요. scaleX, scaleY를 수정하면 해결될까요?
\+ 기존 스플래쉬와 동일하게 애니메이션을 없애면 어떨까요??!!!

2024-08-16 07:48 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                    }
이 부분 함수로 빼면 어떨까요??

2024-08-16 08:44 UTC, aprilgom approved these changes
수고하셨습니다

2024-08-16 08:44 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +            ObjectAnimator.ofPropertyValuesHolder(splashScreenView.iconView, scaleX, scaleY).run {
애니메이션 킹받으니까 빼는걸로 -_-

2024-08-17 04:09 UTC, haeum808 commented
Screen_recording_20240817_130938.webm

2024-08-17 05:11 UTC, aprilgom approved these changes
킹받는 애니메이션 제거 좋습니다

2024-08-17 05:49 UTC, kimhm0728 approved these changes
굿굿 좋아요

2024-08-17 06:23 UTC, merged