feat: 콕찌르기 기능
woowacourse-teams/2024-ody pull request #420
Opened 2024-08-19 11:07 UTC by haeum808

# 🚩 연관 이슈 
close #385 

<br>

# 📝 작업 내용
- [x] 지각 위기, 지각일 때 콕찌르기 기능 
- [x] 스낵바로 알려주기
- [x] fcm 콕찌르기 메시지 추가

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-19 15:42 UTC, kimhm0728 requested changes
빠르게 구현해주셨네요. 고생하셨습니다!
해음 시간날 때 `fetchNudge()` 쪽 뷰모델 테스트에 추가해도 아주 좋을 것 같습니다!
아직 서버와 테스트는 안 해봤으니 approve는 추후에 하겠습니다.

2024-08-19 15:42 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
> +            mateEtaUiModel.isUserSelf.not() &&
이걸 보고 갑자기 궁금한 점이 생겼는데 지금은 자기자신이 `지각 위기` 또는 `지각`일 때도 띠용띠용 애니메이션이 보이나요?? 만약 버튼 애니메이션에서 자기 자신인지에 대한 분기처리가 없다면 추후에 추가해도 좋을 것 같아요!

2024-08-19 15:42 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
> +
이 프로퍼티명만 봤을 때는 String이 닉네임을 뜻하는지 잘 와닿지 않는 것 같아요. 닉네임이란 걸 프로퍼티명에 드러내면 어떨까요??

2024-08-20 01:44 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
> +            mateEtaUiModel.isUserSelf.not() &&
애니메이션 있는게 이쁜거 같아서 유지하겠습니다!

2024-08-20 04:10 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
> +
nudgeSuccessMate로 변경하겠습니다!

2024-08-20 04:38 UTC, kimhm0728 approved these changes

2024-08-20 04:59 UTC, aprilgom requested changes
수고하셨습니다해음

2024-08-20 04:59 UTC, aprilgom commented on android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
> +    suspend fun getNudge(
fetchNudge로 바꿔주세요

2024-08-20 08:45 UTC, aprilgom approved these changes
굿

2024-08-20 08:45 UTC, merged