feat: 약속 리스트에서 뒤로가기 2번 하면 나갈 수 있는 기능 구현
woowacourse-teams/2024-ody pull request #472
Opened 2024-08-23 04:54 UTC by haeum808

# 🚩 연관 이슈 
close #471 

<br>

# 📝 작업 내용
- [x] 뒤로가기 버튼 두번 눌렀을 때 알림 토스트

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-08-23 04:57 UTC, kimhm0728 requested changes
👍👍👍

2024-08-23 04:57 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                }
`lastBackPressedTime`를 Activity 클래스의 프로퍼티로 분리하고, 이 부분도 함수로 분리하면 어떨까요? 
프로퍼티에 로직까지 있는 것보다 함수에 로직이 있는게 더 가독성이 좋은 것 같아요.

2024-08-23 04:57 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                }
문자열도 strings 분리 부탁드려요.

2024-08-23 04:57 UTC, kimhm0728 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
> +                }
2000도 상수로 분리합시다!

2024-08-24 06:16 UTC, aprilgom approved these changes
좋네요

2024-08-26 06:07 UTC, kimhm0728 approved these changes
좋습니다!! 👍

2024-08-26 06:07 UTC, merged