design: 설정화면 디자인
woowacourse-teams/2024-ody pull request #492
Opened 2024-09-06 12:12 UTC by haeum808

# 🚩 연관 이슈 
close #481 

<br>

# 📝 작업 내용
- [x] 개인정보 처리방침 디자인
- [x] 서비스 이용 약관 디자인
- [x] 로그아웃 디자인
- [x] 회원탈퇴 디자인

<br>

# 🏞️ 스크린샷 (선택)
![Screenshot_20240906_211225](https://github.com/user-attachments/assets/ecf7dc40-3da1-4ccd-b090-53b6c37ffc84)

<br>

# 🗣️ 리뷰 요구사항 (선택)
SeetingActivity에 

<img width="339" alt="image" src="https://github.com/user-attachments/assets/f9326693-e3cd-4e64-acd7-038942d1dc2e">

위에서 각 로직 구현해주시면 됩니다.

2024-09-06 16:03 UTC, kimhm0728 requested changes
해음 빠르게 구현해주셨네요 👍👍
네이밍 관련 코멘트 몇개 달아두었습니다. 제가 예시로 남겨둔 네이밍들은 정말 예시일 뿐이니 해음의 스타일대로 변경해주세요~!!

2024-09-06 16:03 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> +                dividerInsetEnd = dpToPx(26)
다만 `26`을 companion object에 빼면 어떨까요~???? `dimens.xml`에 빼도 좋겠지만, resources에서 가져오는 것이 귀찮으니......

2024-09-09 03:11 UTC, haeum808 commented on android/app/src/main/res/layout/item_setting.xml
> +        android:layout_height="wrap_content"
그러개요 둘다 적용이 되는군요. 그래도 더 적합한 match_parent로 변경했습니다.

2024-09-09 04:12 UTC, aprilgom approved these changes

2024-09-09 04:12 UTC, aprilgom commented on android/gradle/libs.versions.toml
>  [versions]
버전들 전체적으로 업데이트해준건가요

2024-09-09 04:13 UTC, kimhm0728 approved these changes
리뷰 반영된 것 확인했습니다! 고생하셨어용 해음

2024-09-09 04:18 UTC, haeum808 commented on android/gradle/libs.versions.toml
>  [versions]
맞습니다!

2024-09-09 04:18 UTC, merged