feat: 로그아웃 기능 구현
woowacourse-teams/2024-ody pull request #499
Opened 2024-09-09 19:04 UTC by aprilgom

# 🚩 연관 이슈 
close #498 

<br>

# 📝 작업 내용
- [x] 로그아웃 처리
    - [x] 카카오 인증 서버에 로그아웃 요청
    - [x] 오디 서버에 로그아웃 요청
    - [x] 클라이언트 저장소에서 acccess token과 refresh token 삭제
- [x] 로그아웃 처리 후 로그인 화면으로 이동
- [x] 스낵바 메시지로 로그아웃 안내

<br>

# 🏞️ 스크린샷 (선택)

https://github.com/user-attachments/assets/d2f36226-77ab-43f7-9de3-c0c63530ba04

<br>

# 🗣️ 리뷰 요구사항 (선택)
로그아웃 요청이 성공하던 실패하던 저장된 access token과 refresh token을 모두 접근할 수 없도록 삭제하는 방식으로 구현했습니다. 
(카카오도 동일하게 로그아웃에 실패하더라도 토큰을 삭제하는 방식으로 구현되어있네요. [카카오 로그아웃](https://developers.kakao.com/docs/latest/ko/kakaologin/android#logout))

지금은 로그아웃 요청이 실패했을 때 토큰을 지워버리니 로그아웃 재요청을 하지 못하고 서버에 만료 기간이 남은 refresh token이 그대로 남아버리는데요, [logout만을 위한 token을 발급하는 방법](https://medium.com/android-news/solving-offline-logout-problem-f3b50da49e7e)이 있는 것 같습니다. access token을 지우지 않고 계속 재시도하는 방법이 있으나, 앞선 링크에 "저장된 토큰을 누군가 탈취할 수도 있다" 소개되어 있네요. 좋은 예시는 아니나 토큰을 남기는게 별로 좋지 않다는건 동의하고 있습니다.

이대로도 동작에는 문제가 없고, refresh token도 만료 기간이 지나면 쓸 수 없게되니 지금은 그냥 둬도 괜찮지 않을까? 하는 생각입니다. 다른 할 일들도 있고.. 이후에 토큰을 저장할 때 암호화해서 저장하는 것도 생각해 볼 일인 것 같아요.(지금 말고)

2024-09-10 01:16 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +
kakaoLogoutResuest.isFailure이면 얼리 리턴하고 그 이후에 logoutService.postLogout()을 실행하면 어떤가요?

2024-09-10 02:26 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/core/service/LogoutService.kt
> +interface LogoutService {
로그인과 로그아웃이 다른 interceptor를 써서 같은 서비스에 넣기는 힘들 것 같습니다..

2024-09-10 02:27 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +
카카오 로그인이 실패했습니다! 라고 예외처리를 하는 방향이 되겠네요.

2024-09-10 02:28 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> +        private val NAVIGATED_REASON = "NAVIGATED_REASON"
좋습니다

2024-09-10 02:28 UTC, aprilgom commented on android/app/src/main/res/values/strings.xml
> +    <string name="withdrawal_success">회원 탈퇴 되었습니다.</string>
깜빡했어요

2024-09-10 03:46 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +
카카오에 로그아웃 요청이 제대로 되지 않는 경우를 아래와 같은 방법으로 테스트해봤는데요,
카카오 로그인 -> 오프라인 상태에서 카카오 로그아웃 -> 카카오 로그인
클라이언트에 있는 토큰이 삭제되면 로그아웃으로 판단하고 새로 로그인하는 것 같습니다.

2024-09-10 12:24 UTC, kimhm0728 requested changes
리뷰가 늦었네요 계속 깜빡함.. .죄송해요 😢 고생하셨어요 차람~!!!

2024-09-10 12:24 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> +        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
👍

2024-09-10 12:24 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +            _loginNavigateEvent.setValue(LoginNavigatedReason.LOGOUT)
안드에서 로컬 액세스 토큰 삭제하는 작업과 백에서 리프레쉬 토큰을 삭제하는 작업의 원자성 보장은 어떻게 하기로 했나요?
서버에서 400, 500을 던져줬을 때의 예외 상황은 고려하지 않기로 했나요??
아까 점심쯤에도 계속 고민중이던 것 같은데, 차람이 내린 결론이 궁금합니다~!

2024-09-10 12:24 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
> +class SplashActivity : AppCompatActivity() {
원래는 `LoginActivity`에서 splash도 띄우는 걸로 구현이 되어있었는데, `LoginActivity`와 `SplashActivity`를 분리한 이유가 궁금해요!

2024-09-10 12:24 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
> +class SplashActivity : AppCompatActivity() {
아 로그아웃 후에 LoginActivity를 startActivity할 때 스플래쉬까지 같이 떠서 그런 건가요?

2024-09-10 12:24 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
> +        super.onCreate(savedInstanceState)
`navigateToLogin()`는 `super.onCreate(savedInstanceState)` 이후에 호출해도 되지 않을까요? 스플래쉬 관련 작업은 `super.onCreate(savedInstanceState)` 이후에 호출하면 터지는 걸로 알고 있는데, 다른 작업들은 super 이후에 호출하는 게 일반적인 방식인 것 같아서요~!

2024-09-10 22:56 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/core/service/LogoutService.kt
> +interface LogoutService {
좋습니다!

2024-09-10 23:07 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
> +        }
스낵바를 SettingActivity에서 띄우고 LoginActivity로 이동했을 때 스낵바가 나타나지 않더라구요..
이유를 알아보니, 스낵바는 토스트와 다르게 특정 액티비티에 종속되어 있는 것 같습니다.

2024-09-10 23:13 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +            _loginNavigateEvent.setValue(LoginNavigatedReason.LOGOUT)
카카오 서버에 로그아웃 요청이 실패한 경우 카카오 로그인을 재시도 -> 로그인이 정상적으로 진행됨
카카오 로그아웃 처리를 하지 않고 카카오 로그인을 재시도해본 결과 -> 로그인이 정상적으로 진행됨 (??)
아마 로그아웃의 역할은 서버에 등록된 토큰을 사용하지 못하도록 처리하는 것이 전부인 것 같은데, 카카오쪽 인증 토큰을 활용하지 않는 입장으로서는 아예 로그아웃 요청을 안보내도 상관이 없다는 생각이 들어요.

2024-09-10 23:14 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
> +class SplashActivity : AppCompatActivity() {
맞아요!

2024-09-10 23:14 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
> +        super.onCreate(savedInstanceState)
넵 좋습니다!

2024-09-10 23:45 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +            _loginNavigateEvent.setValue(LoginNavigatedReason.LOGOUT)
그래서, 로그아웃 요청을 보내되, 실패해도 큰 상관은 없다! (너무 얼렁뚱땅인가요?)

2024-09-11 01:00 UTC, kimhm0728 approved these changes
고생하셨어요 차람~!!!!

2024-09-11 01:03 UTC, merged