refactor: 민감한 설정을 jasypt를 활용해 암호화 적용
woowacourse-teams/2024-ody pull request #511
Opened 2024-09-10 17:04 UTC by hyeon0208

# 🚩 연관 이슈 
close #510 

<br>

# 📝 작업 내용
- 민감한 설정을 jasypt 라이브러리를 활용해 암호화 적용
- dev, prod CD 파이프라인에서 이미지 빌드시 jasypt 비밀번호 환경변수 전달해 빌드되도록 수정
  - jasypt로 암호화한 값들을 복호화하기 위해서는 비밀번호가 필요한데 외부에 노출을 막기 위해 git action secret 변수에 저장해둬 ARG 키워드로 이미지 빌드시 패스워드가 적용되어 복호화되도록 했습니다.
- 서브모듈자체를 사용안하려 했는데 fcm-admin-sdk.json 의 경우에는 yml로 작성되있지 않아 암호화가 안되더라구요. 어차피 해당 파일은 서브모듈에 있는 yml 파일들 처럼 수정될 여지가 없어 보여 그대로 사용하면 될 것 같아요

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-09-10 17:30 UTC, coli-geonwoo approved these changes
하루에 PR 3개..... 고생 많았습니다 카키!

2024-09-10 17:30 UTC, coli-geonwoo commented on backend/src/main/resources/application-prod.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
이게 무슨 의미이지? 하고 생각했는데 암호화된 문자열이었네요 😂

2024-09-10 17:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +public class JasyptConfig {
각 설정에 대한 오디톡해주면 좋을 것 같아요 🦻

2024-09-10 17:30 UTC, coli-geonwoo commented on backend/src/main/resources/application-prod.yml
> +    url: ENC(b2OC3sqkv3yOFNN3PLvGEXfS9PNhJa1KZBJO7m2UFkKaVDLrQfHW4lcAiXDKGdGQGOiTJP0fdbgRLmVOOpkRTQQBFdLk9Kc56xoqAv7zM37vAuAhiO1SXggzqFbE3nBVEiZ8LlXWbASOehuAoByOAg==)
- 문법 : ENC(암호화된 값)

괄호 안에 있는 값들이 build 시에는 복호화되어 사용하게 되는 거군요!

2024-09-10 17:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
다른 설정은 이해했는데 

- setSaltGeneratorClassName
- setIvGeneratorClassName

이 두가지는 이해하기가 힘들어서 무엇인지 궁금해요. 레퍼런스들에도 어떤 분은 적용하고 어떤 분은 적용하시지 않았기도 해서요 🤔

2024-09-10 17:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setPoolSize("1");
jasypt에서는 기본값으로 2를 추천한다고 하는데, 공식 문서 찾아보니 코어 수에 알맞게 설정하는 걸 추천하고 있었어요 1보다 조금 더 늘려도 괜찮을 것 같아요
![image](https://github.com/user-attachments/assets/6e0c13f0-68bd-44ac-9822-31b5b4893592)



ref) http://www.jasypt.org/general-usage.html

2024-09-11 01:46 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
jasypt 공식문서에서 옵션별로 상세한 설명이 없어요 현재 적용된 설정 코드도 제공해준 기본 설정을 적용했습니다.
크게 건드릴 설정이 없는 것 같기도 했구요.

setSaltGeneratorClassName를 등록하는 것은 Salt 방식을 사용한다 정도로 이해했고
setIvGeneratorClassName를 등록하는 것은 초기화 벡터를 적용한다 정도로 이해했습니다.

2024-09-11 01:56 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setPoolSize("1");
일반적으로 서버 코어수랑 동일하게 설정한다는 것 같네요 !
<img width="736" alt="image" src="https://github.com/user-attachments/assets/105c00a9-4406-4580-a4f2-880adff3ad18">
저희 서버 스펙에 맞게 설정하면 2가 적당한 것 같네요 👍

2024-09-11 02:34 UTC, eun-byeol requested changes
고생하셨어요 카키! 설명을 잘 해주셨지만, 새로운 기술이니 간단하게 오디톡 해주세요~!~!🙇‍♀️

> 해당 방법이 서브모듈 충돌을 피할 수 있어서 너무 좋은데, 몇가지 단점도 있을것같아요. 원래 방식으로 돌아가자는 말은 아닙니다!
- yml에서 암호화된 값을 다른 팀원이 알아볼 수 없어요.
- 시크릿 키를 노션과 같은 다른 페이지에서 따로 관리해야 해요.
서브모듈이 위 두 관점에서 장점이 있었다고 생각해요. 이에 대해서는 어떻게 생각하시나요?

> 서브모듈자체를 사용안하려 했는데 fcm-admin-sdk.json 의 경우에는 yml로 작성되있지 않아 암호화가 안되더라구요. 어차피 해당 파일은 서브모듈에 있는 yml 파일들 처럼 수정될 여지가 없어 보여 그대로 사용하면 될 것 같아요

fcm-admin-sdk.json 또한 문자열로 취급해서 yml에서 key-value로 설정해두면 가능할 수도 있을것같아요. 단, 코드 변경이 좀 생길 수 있어서 언급만 하겠습니다~ 백로그에 남겨둬도 좋겠네요!

2024-09-11 02:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +@Profile({"local", "dev", "prod"})
[필수]
소소+1ㅎㅎ
```suggestion
@Profile({"local", "dev", "prod"})
@Configuration
```

2024-09-11 02:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setPoolSize("2");
[질문]
스레드풀을 2개로 설정한 이유가 있을까요? 궁금합니다🤔

2024-09-11 02:34 UTC, eun-byeol commented on backend/src/main/resources/application-dev.yml
> +    password: ENC(VRtr3RjM+XnPvRdLjrPMHyTSzDlEjR7o)
[질문]
여기 임의값들은 출처가 어디인가요? 빌드 후 복사한 값들일까요? 도와줘요 오디톡~😮

2024-09-11 05:30 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +@Profile({"local", "dev", "prod"})
반영 완~

2024-09-11 05:32 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/JasyptConfig.java
> +        config.setPoolSize("2");
[콜리와 코맨트 대화 내용](https://github.com/woowacourse-teams/2024-ody/pull/511#discussion_r1752383714)
위에서 얘기한데로 저희 EC2 서버 코어가 2개라서 jasypt에서 추천해주는 코어 수 설정으로 해줬습니다 !

2024-09-11 05:42 UTC, hyeon0208 commented
> yml에서 암호화된 값을 다른 팀원이 알아볼 수 없어요.
시크릿 키를 노션과 같은 다른 페이지에서 따로 관리해야 해요.
서브모듈이 위 두 관점에서 장점이 있었다고 생각해요. 이에 대해서는 어떻게 생각하시나요?

암호화된 값을 다른 팀원들이 알아볼 수 없다는 점이 불편하긴 합니다. 
하지만 서브모듈을 사용했을 때 서브모듈의 순서에 의존하는 부분들이 많이 불편했고 서브모듈에 변경이 생긴 PR이 머지 된 후
develop pull 받는 과정에서 submodule update를 항상 인식하고 적용해야한다는  점이 불편했어요
그리고 submodule update를 해주지 않아 의도한 설정이 아닌 문제도 여러번 있었구요

시크릿 키를 노션과 같은 다른 페이지에서 관리에서 관리하고 있는데 공개된 노션이 아니라서 크게 문제 되지 않을 것 같아요
문제가 된다면 지금 모든 암호들이 있으면 안되기도 하구요
프로젝트 패키지 하나로 관리하면서 암호화된 값을 노션에서 형상관리로 표현해주면 jasypt를 이용한 암호화가 더 편한 것 같아요 !

> fcm-admin-sdk.json 또한 문자열로 취급해서 yml에서 key-value로 설정해두면 가능할 수도 있을것같아요. 단, 코드 변경이 좀 생길 수 있어서 언급만 하겠습니다~ 백로그에 남겨둬도 좋겠네요!

조조가 제안한대로 적용했어요 👍 
단 fcm-admin-sdk.json 값들이 모든 프로필에 공통적으로 사용되어 application-common yml에 정의하려 했는데 못 읽고
application.yml 에서만 해당 설정을 읽을 수 있네요 
이 부분은 추후에 원인을 파악하고 좋은 방법으로 수정해봐야할 것 같아요

2024-09-11 12:27 UTC, eun-byeol approved these changes
고생하셨습니다~!👍 암호화-복호화 방법 꼭 알려주세요~!

2024-09-12 01:02 UTC, mzeong approved these changes
로컬에서 실행시킬 때 따로 해줘야 하는 설정이 있나요? 실행이 실패해요

2024-09-12 05:19 UTC, merged