feat: 회원 삭제 API
woowacourse-teams/2024-ody pull request #512
Opened 2024-09-10 19:35 UTC by mzeong

# 🚩 연관 이슈 
close #497

<br>

# 📝 작업 내용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-09-11 02:32 UTC, coli-geonwoo requested changes
역시 제리답게 깔끔한 코드를 작성하셨네요!

Approve 남기면 제가 다시 PR를 확인하지 않는 것 같아 제리가 남긴 답변을 확인하고 의견 나누고자 RC남깁니다.

안드쪽과도 합의할 내용이 많은 PR이었는데 고생많으셨습니다!

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public boolean isStatusDismissed() {
[의견]

enum type은 public static이니 의미만을 담고 메서드로 한번더 물어보지 않아도 된다고 생각해요! 위의 updateStatusToDone에도 이미 Notification이 NotificationStatus를 알고 있다고 생각했구요!

다음과 같은 구조는 어떤가요?

```suggestion
    public boolean isStatusDismissed() {
            return status == NotificationStatus.DISMISSED
    }
```

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
> +    @Modifying(clearAutomatically = true)
[의견]

저는 개인적으로 JPA 벌크성 쿼리를 좋아하는 편은 아니라 애플리케이션 단에서 처리하는 의견에 대해 제리를 설득해보려 합니다. 

- 1. status를 바꾸는 로직은 아마 DISMISSED로 바꾸기 위함이라 생각되는데 mateid를 기반으로 조회한 notification을 update하는 연산은 오디의 특정 서비스 로직과 결합도가 높다고 생각해요. 따라서 이 메서드도 좋지만 재사용성이 크지는 않을 것 같다는 의견이에요.

- 2. Modifying은 카키가 작성했던 벌크성 쿼리용으로 주로 사용되는 것으로 알고 있어요. 위의 상황은 일관적으로 적용되어야 하는 로직보다 삭제라는 이벤트가 발생했을 때 서비스 단에서 처리해주어야 하는 로직이라는 의견입니다.

[제안]

따라서 repository에서는 mateID와 status만으로 조회하고 애플리케이션 단에서 updateStatusDissmissed()로 관리하는 건 어떨까요? 기존에 updateStatusToDone() 메서드와 일관성도 생길 것 같다는 생각입니다.

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/common/FixtureGenerator.java
> +public class FixtureGenerator {
앞으로 테스트할 때 제리 덕분에 많이 편하겠네요

잘 쓰겠습니다 👍

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
> +    @DisplayName("회원 삭제 API 멱등성 검증")
[의견 - 선택]

사소한 부분이긴 한데 멱등성이라는 키워드를 기반으로 무엇을 테스트하려는 것인지가 직관적으로 드러나지 않는 것 같다는 생각이 들었어요

다음과 같은 문장은 어떤가요?
`이미 삭제한 회원에 대한 삭제 요청에도 204를 반환한다`

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/member/service/MemberServiceTest.java
> +                () -> assertThat(etaRepository.findById(eta.getId())),
```suggestion
                () -> assertThat(etaRepository.findById(eta.getId())),
```

이 라인은 혹시 어떤 걸 테스트 하는 것인가요?

2024-09-11 02:32 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public static Notification createMemberDeletion(Mate mate) {
[의견 공유]

제리한테 반영을 바라기보다 의견을 듣고 싶어 적는 코멘트인데요. 현재 Notification이 각 Status 별 생성 로직을 모두 알고 있는게 부자연스러워서요. status가 추가될 때마다 notfication 정팩메가 하나씩 추가되는 게 notification이 status를 크게 의식하고 있는 느낌이에요.

나중에라도 notification 생성 로직만을 담당하는 creator 혹은 mapper를 만드는 것에 대해 어떻게 생각하시나요?

2024-09-11 05:56 UTC, eun-byeol requested changes
많은 file change가 생겼네요. 고생했어요 제리~!~!🐹
질문을 몇 개 남겨서, RC 요청드릴게요!

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +@SQLRestriction("deleted_at is NULL")
[질문]
deleted_at = null을 포함하고싶은 경우엔, JPQL을 사용해야 하나요? 그 외 방법도 있는지 궁금합니다!🤔

저는 엔티티에 쿼리 조건을 걸어두는것을 선호하진 않아요.
repo레이어에서 쿼리를 만들때 엔티티에 변경사항을 잘 모른다면, 의도치 않게 where 절이 계속 추가되고 오류 포인트가 될 가능성이 높기 있기 때문이에요.
그러나, 지금 우리팀 상황에는 적절하다고도 생각해요. `삭제도 함께 조회하는 경우` vs `삭제되지 않은것만 조회하는 경우` 중 후자를 더 많이 사용하니까요.
**Q. 제리가 SQLRestriction을 선택한 이유는 무엇이었나요?**

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +    private LocalDateTime deletedAt;
[질문]
soft delete를 boolean이 아니라 DateTime으로 둔 이유는 무엇인가요?🤔
저는 과거에 boolean으로 true/false(NotNull)로 표현했었어요.

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +                .ifPresent(mateRepository::delete);
[질문]
`deleteById(mateId)`로 하면 안 되나요?🤔

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/main/java/com/ody/member/domain/Member.java
>                  columnNames = {"deviceToken"}
[제안]

제리가 작업한 부분은 아니지만, 통일성을 위해 단일 Unique키는 필드 옆에 조건을 걸어주는건 어떤가요?
[카키 PR에서 제약조건 언급한 부분](https://github.com/woowacourse-teams/2024-ody/pull/507#discussion_r1752354933)

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
> +        assertThat(actual.getDeletedAt()).isNotNull();
꼼꼼🐹👍

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
> +        );
[질문]
여기는 직접 생성해준 이유가 있나요?

2024-09-11 05:56 UTC, eun-byeol commented on backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
> +@Import({FixtureGenerator.class})
[제안]
하나인 경우 `{}`생략가능합니다!
```suggestion
@Import(FixtureGenerator.class)
```

2024-09-11 18:09 UTC, hyeon0208 approved these changes
Fixture 맛있게 개선해주셨네요 👍 
여러 부분 변경되었을텐데 고생많았어요 제리 💯 
간단한 질문들만 남기고가서 approve 드려요 🥇

2024-09-11 18:09 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public boolean isStatusDismissed() {
콜리말도 동의하지만 Enum에서 boolean 메서드를 정의해서 재사용하는 경우도 많은 것 같아서 지금도 좋은 것 같아요 !

2024-09-11 18:09 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/DatabaseCleaner.java
> +        entityManager.createNativeQuery("DELETE FROM Notification")
[질문]
SQLDelete() 어노테이션은 네이티브 쿼리에만 적용되나요 ?

2024-09-11 18:09 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/FixtureGenerator.java
> +public class FixtureGenerator {
아 ㅋㅋ 맛있다 ~ 👍🏻

2024-09-11 18:09 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
> +@Import(JpaAuditingConfig.class)
```suggestion
@Import({JpaAuditingConfig.class, FixtureGenerator.class})
```

2024-09-12 02:00 UTC, mzeong commented on backend/src/main/java/com/ody/mate/repository/MateRepository.java
> +    List<Mate> findAllByMemberId(long memberId);
그럴려면 (1)accessToken에서 memberId 추출 → (2)memberId로 Member 조회 → (3)findAllByMember 과정이 필요한데 
삭제된 회원에 대한 회원 삭제 요청 시 (2) 과정을 지저분할 것 같아요

2024-09-12 02:11 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public boolean isStatusDismissed() {
[반영] Enum에서 boolean 메서드를 정의해서 사용하는 경우가 있어서 위와 같이 코드를 작성했는데 사실 제가 좋아하는 방식은 아니라 콜리의 리뷰를 반영했습니다 😁 [cbff59f](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/cbff59fd4493041d6def017cf82686e4f944bbcd)

2024-09-12 02:17 UTC, mzeong commented on backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
> +    @DisplayName("회원 삭제 API 멱등성 검증")
[반영] [618cb0e](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/618cb0e09d838016ad5faf4963a439ad303f5877)

2024-09-12 02:26 UTC, mzeong commented on backend/src/test/java/com/ody/member/service/MemberServiceTest.java
> +                () -> assertThat(etaRepository.findById(eta.getId())),
[반영] 요즘 눈이 침침하네요 [3d36048](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/3d36048bd366e95401862b927f622de431386397)

2024-09-12 03:30 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public static Notification createMemberDeletion(Mate mate) {
이번에 작업하면서 필요성을 느꼈어요 이슈 생성해두었습니다 https://github.com/woowacourse-teams/2024-ody/issues/522

2024-09-12 03:39 UTC, mzeong commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +
[반영] [5bf8995](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/5bf8995ab810b4f1cd0b0791849aebc6933905f1)

2024-09-12 03:40 UTC, mzeong commented on backend/src/main/java/com/ody/eta/service/EtaService.java
> +                .ifPresent(etaRepository::delete);
네 맞아요! `@SQLDelete`로 삭제 명령을 재정의한 거예요

2024-09-12 03:55 UTC, mzeong commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +    private LocalDateTime deletedAt;
저도 삭제 필드의 타입을 무엇으로 해야 할지 고민했는데 
boolean은 삭제 여부만 확인할 수 있지만, datetime은 삭제 여부+시점까지 알 수 있어 정보를 더 담을 수 있는 타입으로 결정했습니다. 
운영 디비에서 datetime → boolean 으로의 변경은 가능하지만 반대는 불가능한 점도 고려했습니다.

2024-09-12 03:58 UTC, mzeong commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +    private LocalDateTime deletedAt;
모든 엔티티가 createdAt, updatedAt, deletedAt을 가지고 있는 것에 동의합니다~ 
그때 그때 필요한 엔티티에 적용해도 좋겠지만 한 번에 적용해두면 나중에 동시 작업할 때 편할 거 같네요 👍

2024-09-12 04:15 UTC, mzeong commented on backend/src/test/java/com/ody/common/DatabaseCleaner.java
> +        entityManager.createNativeQuery("DELETE FROM Notification")
createQuery는 엔티티 클래스를 대상으로 쿼리를 수행해서 createQuery에만 `@SQLDelete`가 적용돼요!!
데이터베이스 클렌징 작업 때는 hard delete가 하고 싶은 거라 createNativeQuery로 바꿔주었습니다

2024-09-12 04:28 UTC, mzeong commented on backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
> +@Import(JpaAuditingConfig.class)
[반영] [1af7ae1](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/1af7ae1acafb63f24a3eee0017b02984fd77fd84)

2024-09-12 04:28 UTC, mzeong commented on backend/src/test/java/com/ody/member/controller/MemberControllerTest.java
> +@Import({FixtureGenerator.class})
[1af7ae1](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/1af7ae1acafb63f24a3eee0017b02984fd77fd84)

2024-09-12 05:26 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/repository/MateRepository.java
> +    List<Mate> findAllByMemberId(long memberId);
아! 이해했습니다. 답변 감사합니다.

2024-09-12 05:27 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public static Notification createMemberDeletion(Mate mate) {
오... 의견만 듣고자 적은 코멘트인테 바로 이슈 생성까지! 의견에 공감해준 것 같아 기쁘네요 😄 

시간 남으면 관련 이슈 작업해보겠습니다 💪

2024-09-12 05:29 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +    private LocalDateTime deletedAt;
관련 stack overflow 토론글이 있어 공유합니다

https://stackoverflow.com/questions/68323/what-is-the-best-way-to-implement-soft-deletion

2024-09-12 05:30 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
> +        assertThat(actual.getDeletedAt()).isNotNull();
entitymanger native query 테스트 처음 봐요  👍

2024-09-12 05:31 UTC, coli-geonwoo approved these changes
제리! 리뷰 반영 긍정적으로 검토해주셔서 감사합니다 🙇 

정책적으로 안드측과 합의할 일도 많고 테스트짜기도 복잡한 부분이 많았을 텐데 정말 고생 많으셨어요 👏 

제가 드리고 싶은 말은 다 드린 것 같아 approve 합니다

2024-09-12 06:30 UTC, mzeong commented on backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
> +    @Modifying(clearAutomatically = true)
[반영] 변경해야 할 알림이 많을 경우를 고려해 벌크 쿼리를 작성했는데 서비스 특성상 알림이 많을 것 같지 않네요! [adb4f5c](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/adb4f5c6103f828869770cd0e5b926a3f4048f69)

2024-09-12 06:35 UTC, mzeong commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +                .ifPresent(mateRepository::delete);
[반영] deleteById를 사용하는 게 더 좋을 것 같아요! [e25bd05](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/e25bd05f10633b17092a57499634c61e8b59a5d9)

2024-09-12 06:43 UTC, mzeong commented on backend/src/main/java/com/ody/member/domain/Member.java
>                  columnNames = {"deviceToken"}
[반영] 확인해보니 이미 DeviceToken 내에서 필드에 unique 제약조건을 걸어두어서 Member 내 제약조건만 제거하여 피드백 반영했습니다 [f979e02](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/f979e02129537088c4b4b7991cf845870d1c8067)

2024-09-12 06:48 UTC, mzeong commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +@SQLRestriction("deleted_at is NULL")
baledung에서는 `@FilterDef`, `@Filter`를 사용하라고 제시해줘서 ([How to Get the Deleted Data?](https://www.baeldung.com/spring-jpa-soft-delete#how-to-get-the-deleted-data))
추후 필요해진다면 필터를 생성하고 현재는 `@SQLRestriction`을 사용했어요 

그런데 약속 로그 목록 조회에서 삭제된 회원의 로그를 포함해야 해서 구현을 해봤는데 [eab5366](https://github.com/woowacourse-teams/2024-ody/pull/512/commits/eab5366819c53c5d2da56cd8bafcc52907a85eea)
불편하고 실수할 여지도 많을 것 같아요! 🤔🤔
일단 오늘 QA가 예정되어 있어 현재 코드로 머지를 하게 될 것 같은데 SQLRestriction을 사용하는 것에 대해 논의가 필요할 것 같아요

2024-09-12 06:52 UTC, mzeong commented on backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
> +        );
현재는 FixtureGeneratorConfig를 두어 생성자 코드를 작성하지 않도록 코드를 개선했습니다!

2024-09-12 07:13 UTC, eun-byeol approved these changes
고생했어요 제리🐹🐹🐹
QA 화이팅~!~!!~!

2024-09-12 07:13 UTC, merged