feat: 회원 탈퇴 기능 구현
woowacourse-teams/2024-ody pull request #518
Opened 2024-09-11 08:57 UTC by kimhm0728

# 🚩 연관 이슈 
close #486 

<br>

# 📝 작업 내용
- [x] DataStore의 access/refresh 토큰 삭제
- [x] 서버 탈퇴 api 호출
- [x] 카카오 탈퇴 api 호출
- [x] 탈퇴 로그 타입 추가
- [x] 탈퇴 다이얼로그 구현
- [x] 탈퇴한 사람의 경우 회색 이미지가 뜨도록 수정 

<br>

# 🏞️ 스크린샷 (선택)

https://github.com/user-attachments/assets/4544c129-c89c-49f8-8b19-890598b550f2

<br>

# 🗣️ 리뷰 요구사항 (선택)
제리와 QA하고 제이슨께 원자성 관련 여쭤보면 코드가 살짝 변경될 수도 있을 것 같아요.
그리고 탈퇴의 경우 로그에만 뜨고 푸시 알람은 뜨지 않는데요, `NotificationType`을 통해서 "푸시 알림 타입" / "로그 타입 두개"를 다 구분하고 있더라구요.
탈퇴 **로그**를 추가하기 위해 탈퇴 **푸시 알림** 분기 처리까지 구현해야 하는 불편함이 있어서, `LogType`과 `NotificationType`을 분리했습니다~!!!

2024-09-11 12:11 UTC, haeum808 reviewed
고생하셨습니다!

2024-09-11 12:11 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +        private val TAG = SettingViewModel::class.simpleName
위 리뷰와 같습니다

2024-09-11 12:11 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
> +    private val binding get() = _binding!!
ViewBinding 사용하는거 어떤가요?

2024-09-11 12:57 UTC, aprilgom requested changes
수고 많으셨습니다 올리브~~

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    Timber.e("$code $errorMessage")
Timber는 삭제해도 될 것 같아요~~

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    analyticsHelper.logNetworkErrorEvent(TAG, "$code $errorMessage")
실패시 로그 남기는것 좋아요 👍

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +        return withdrawAccountByKakao()
제이슨께 로그아웃 원자성에 대해서 추석 전에 여쭤볼 수 있으면 좋겠습니다.. 😢

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
> +            startLoading()
로딩 처리를 더해주셨군요! 땡큐!

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +    private suspend fun withdrawAccountByKakao(): ApiResult<Unit> {
이거 KakaoOAuthService쪽으로 옮겨주실 수 있나요~

2024-09-11 12:57 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +                            continuation.resumeWithException(error)
resumeWithException으로 예외처리를 해주셨군요
Result<*>로 리턴한 것보다 이쪽이 훨씬 더 나은 것 같아요 👍

2024-09-12 07:52 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    Timber.e("$code $errorMessage")
삭제하는 이유가 뭔가요? 다른 뷰모델에서도 다 남기고 있는 것 같아서요~! 어차피 Okhttp Log남으니까 괜찮을까요?

2024-09-12 07:52 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +        return withdrawAccountByKakao()
여쭤보기 성공!

2024-09-12 07:54 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +    private suspend fun withdrawAccountByKakao(): ApiResult<Unit> {
제이슨께 여쭤봤는데 서버에서 카카오 api를 호출하는게 좋겠다는 인사이트를 얻을 수 있었어요~! 일단 merge하고 다음 이슈에서 카카오 탈퇴 코드 삭제할 예정이라 옮기지 않아도 될 것 같습니다

2024-09-12 07:57 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
> +        private val TAG = LoginViewModel::class.simpleName
동의합니다! 다른 뷰모델에도 다 const String 방식이었네요! 수정했습니다 [9f74d11](https://github.com/woowacourse-teams/2024-ody/pull/518/commits/9f74d113cb6767179130d7a9fb677b09022164a0)

2024-09-12 08:00 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
> +    private val binding get() = _binding!!
좋습니다! 수정했어요 👍 [0dbd62e](https://github.com/woowacourse-teams/2024-ody/pull/518/commits/0dbd62ea52b84873f689a02094cc1e2376c89467)

2024-09-12 08:47 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    Timber.e("$code $errorMessage")
그런 생각이긴 했는데.. 다른 뷰모델에서도 다 남기고 있다면 OK입니다!!

2024-09-12 08:47 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +        return withdrawAccountByKakao()
굳굳

2024-09-12 08:48 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +    private suspend fun withdrawAccountByKakao(): ApiResult<Unit> {
그렇군요! AN - BE - 카카오 로 처리하는것 완전 동의입니다.

2024-09-12 08:49 UTC, aprilgom approved these changes
좋습니다!

2024-09-12 14:19 UTC, haeum808 approved these changes

2024-09-19 07:47 UTC, merged