fix: 도커에 전달된 환경변수를 애플케이션이 못 읽는 문제 해결
woowacourse-teams/2024-ody pull request #530
Opened 2024-09-12 09:15 UTC by hyeon0208

# 🚩 연관 이슈 
close #529 

<br>

# 📝 작업 내용
기존에는 ARG로 환경 변수를 설정했는데 키워드를 잘못이해했어요
ARG는 환경변수 중에서도 image build 시에만 사용되서 이미지 빌드 이후 필요 없는 환경 변수에 ARG를 사용한다하더라구요
ex:) 이미지 태그 동적으로 설정

그래서 런타임 시점에 적용되는 ENV 키워드를 사용해 환경변수 적용 시켜줬습니다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-09-13 12:05 UTC, coli-geonwoo approved these changes
카키 PR message 잘 적어주셔서 approve 합니다

즉, 환경 변수의 Retention 범위가

ARG는 컴파일 시까지 / ENV는 런타임까지로 이해하면 될까요?

그럼 jasypt의 경우 런타임 시까지 password가 필요하다는 것인데, 빌드할 때 해독해서 들어가는 것이 아니라, 매 순간 private.yml에 있는 값들을 읽을 때마다 런타임에 해독을 하게 되는 것인지 궁금합니다 🤔

2024-09-13 14:01 UTC, hyeon0208 commented
@coli-geonwoo 

> ARG는 컴파일 시까지 / ENV는 런타임까지로 이해하면 될까요?

정확하게는 생명주기가 ARG는이미지 빌드시에만 ENV는 컨테이너 실행동안 유지됩니다.
즉, ARG는 이미지가 빌드되고 나면 사라지는 값이고 ENV는 컨테이너 실행동안 유지되겠죠

콜리가 설명한 부분에서 제가 "빌드할 때 변수로 주입된 password로 해독해서 들어가는 것"이라 생각해서 ARG를 적용했었어요
하지만 이미지라는 것은 읽기 전용 파일이고, ARG는 Dockerfile로 빌드되는 시점에만 유효해 이미지 설정을 동적으로 적용하는데 사용되는 환경변수 였어요
애플리케이션의 내부 설정에 필요했던 password라는 설정에 직접적인 값을 쓰는 작업이 아니였던거죠

<br>

> 그럼 jasypt의 경우 런타임 시까지 password가 필요하다는 것인데, 빌드할 때 해독해서 들어가는 것이 아니라, 매 순간 private.yml에 있는 값들을 읽을 때마다 런타임에 해독을 하게 되는 것인지 궁금합니다 🤔

매 순간 yml에 있는 값들을 읽을 때마다 런타임에 해독하진 않고
애플리케이션이 실행되면서 프로필에 맞는 설정파일(application-프로필-yml)을 읽을 때 거기에 jasypt.encryptor.password라는 옵션에 해당하는 값을 환경변수로 넣어주고, 이 때 한 번 암호화된 설정을 복호화할 것 같네요  😄

2024-09-16 15:40 UTC, eun-byeol requested changes
덕분에 새로운 개념 배우고 넘어갑니다👍
도커 맛있게 사용하기 더 기대가 되는군여

간단한 질문 하나 남겼는데, 일단 RC둘게요!
즐추즐추~

2024-09-16 15:40 UTC, eun-byeol commented on .github/workflows/backend-cd-dev.yml
> +        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-dev -f Dockerfile . --push
[질문]
이미지 빌드시에는 Jasypt 값이 불필요한가요??
ENV 이므로 이미지 만들때 값을 넣어줘도 이후에 사용 가능한것으로 이해했어요. compose up 하는 시점에 값을 넣어주는 이유가 있나요?🤔

2024-09-17 06:48 UTC, hyeon0208 commented on .github/workflows/backend-cd-dev.yml
> +        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-dev -f Dockerfile . --push
위에 답변이랑 조금 겹치는 것 같은데
ARG는 빌드시에만 사용되는 환경변수로 빌드되고 난 후에는 사라지는 값이에요
또 빌드가 애플리케이션 실행하는 것이 아니니 jaspty 비밀번호를 넣어줘도 @Value 어노테이션도 동작하지 않겠죠
ENV로 환경변수로 애플리케이션 컨테이너가 실행될 때 환경변수를 주입하도록 수정했습니다 😄

2024-09-17 06:57 UTC, eun-byeol commented on .github/workflows/backend-cd-dev.yml
> +        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-dev -f Dockerfile . --push
단순 질문입니다.
그럼 컨테이너 실행될 때(docker compose up) 할때 말고, 이미지 만들때 (build) 값을 넣어줘도 무방한가요? env 변수이니까요!

2024-09-17 07:33 UTC, hyeon0208 commented on .github/workflows/backend-cd-dev.yml
> +        run: docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:${{ github.sha }}-dev -f Dockerfile . --push
ARG 대신 ENV 로 빌드 시에 환경변수를 설정할 수 있냐는 질문으로 이해했는데
ENV 자체가 빌드된 이미지로 생성된 컨테이너에서 사용할 수 있어서 빌드시에는 ENV로 환경변수를 설정해도 ARG가 아니면 못 읽을 거에요

2024-09-17 14:08 UTC, eun-byeol approved these changes
이제 진짜 approve 합니다~!👍

2024-09-19 01:53 UTC, mzeong approved these changes

2024-09-19 01:53 UTC, merged