fix: 회원 삭제 구현 후 로그 목록 조회 API 오작동
woowacourse-teams/2024-ody pull request #534
Opened 2024-09-13 04:48 UTC by mzeong

# 🚩 연관 이슈 
close #532

<br>

# 📝 작업 내용

### 문제

soft delete 구현 후 로그 목록 조회 시 빈 리스트가 조회됨 

### 원인 

`@SQLRestriction`과 Filter가 둘 다 적용되어 쿼리문이 의도와 다르게 나감 
```sql
Hibernate: 
    select
        n1_0.id,
        n1_0.created_at,
        n1_0.fcm_topic,
        n1_0.mate_id,
        n1_0.send_at,
        n1_0.status,
        n1_0.type,
        n1_0.updated_at 
    from
        notification n1_0 
    left join
        mate m1_0 
            on m1_0.deleted_at IS NOT NULL or m1_0.deleted_at IS NULL // Filter 
            and (m1_0.deleted_at is NULL) // @SQLRestrction
            and n1_0.mate_id=m1_0.id 
    left join
        meeting m3_0 
            on m1_0.meeting_id=m3_0.id 
    where
        m3_0.id=? 
        and n1_0.send_at<=now() 
    order by
        n1_0.send_at
```

### 해결

삭제 항목도 조회가 필요한 <ins>**Member, Mate에 한해 `@SQLRestriction` 제거함 (Eta는 유지)**</ins>

<br>

## 💥 개발 시 참고사항 

### 삭제된 Member, Mate를 조회에서 제외하는 필터가 AOP로 적용되고 있음 

`@SQLRestriction`을 제거하게 되면서 모든 서비스 메서드 로직 앞뒤로 필터 적용&해제 코드가 필요해져 도입함
```java
Session session = entityManager.unwrap(Session.class);
Filter filter = session.enableFilter("deletedProductFilter");
filter.setParameter("isDeleted", isDeleted);

// 서비스 로직

session.disableFilter("deletedProductFilter");
```
앞으로 삭제된 Member, Mate 조회를 원하면 메서드에 `@DisabledDeletedFilter` 달아주면 됨!!

<br>

### 필터가 findById 메서드에는 적용이 안 됨 😭 

회원 삭제 후 로그 목록 조회를 수행했는데 삭제 회원의 토큰으로 조회가 되면 문제 발생함 
찾아보니 원인은 spring data jpa가 만들어주는 쿼리가 아니라서 인 듯함 → [@Filter definition not applied to JPA find method](https://hibernate.atlassian.net/browse/HHH-11973)
앞으로도 인지한 상태로 개발해야 할 것 같아서 공유함!!

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

현재는 아래 방법으로 findById를 사용했을 때 삭제 회원이 조회되지 않도록 막고 있는데

```java
public Member findById(Long memberId) {
        return memberRepository.findById(memberId)
                .filter(member -> member.getDeletedAt() == null) // 이 부분 추가
                .orElseThrow(() -> new OdyUnauthorizedException("존재하지 않는 회원입니다."));
}
```

다른 서비스 메서드들처럼 필터를 이용하지 않고 있어 일관성이 없는 것 같아 찝찝합니다
다른 방법을 고민해봤는데 repository 단에서 findById를 재정의해주면 필터를 적용시킬 수 있어요

```java
@Query("select m from Member m where m.id = :memberId")
Optional<Member> findById(Long memberId);
```

그런데 맥락 없이 봤을 때 findById를 재정의해놓은 의도를 다른 개발자들이 파악하기 어려울 것 같아요
<ins>**둘 중에 어떤 방법이 더 나은 것 같은가요? 뭔가 더 좋은 방법이 없을까요?**</ins>

<br>

 
### ‼️‼️ 목요일(내일)에 QA가 예정되어 있어서 (두 번 미뤄진 QA 진짜 제발 이제는 QA가 하고 싶어요)<br><ins>목요일 오후 1시까지</ins> 코드리뷰 해주실 수 있나요? ‼️‼️

2024-09-13 12:27 UTC, coli-geonwoo requested changes
제리! 혹시 fix에 대해 어떤 문제였는지/ 어떤 방식으로 해결하였는지 간단히 후술해주면 이해하기 쉬운 PR이 될 것 같아요!

또, dev trigger를 바꾸어놓으셨던데 다시 원래대로 복구할 필요가 있어 보입니다!

2024-09-13 12:27 UTC, coli-geonwoo commented on .github/workflows/backend-cd-dev.yml
> +      - feature/532
[필수]

무언가 실험이 필요해서 trigger를 바꾸어 놓으신 것 같은데 다시 돌려놓아야 할 것 같아요 😢

2024-09-13 12:27 UTC, coli-geonwoo commented on .github/workflows/backend-ci-dev.yml
> +    branches:
마찬가지로 trigger가 바뀌어 있어요!

2024-09-13 12:27 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public String toString() {
notification의 toString은 왜 선언해주신 건가요? 디버깅용도 였다면 지워도 괜찮을 것 같아요

2024-09-13 12:27 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    @Disabled
이 부분 Disabled 처리한 이유가 궁금합니다!

2024-09-13 13:12 UTC, mzeong commented on .github/workflows/backend-cd-dev.yml
> +      - feature/532
오 콜리!! 이건 아직 코드리뷰 대상이 아니에요 원래 description에 작성해두었는데 그 PR을 close해버려서 설명이 사라졌네요 (리뷰어도 일부러 추가를 안해뒀어요)

회원 삭제 구현 후 로그 목록이 빈 리스트로 조회되고 있는데, 로컬에서는 정상 작동하고 데브에서만 빈 리스트로 조회가 되어서 
임의로 트리거를 조정하고 데브 서버 상에서 원인을 찾기 위해 PR을 올린 상황이에요

대충 원인은 파악했는데 코드 수정을 하진 않아서 코드 수정+버그 픽스를 위한 커밋 롤백 후 코드리뷰 요청을 할게요!
조조와 카키도 지금은 코드 리뷰를 할 필요가 없습니다!!

2024-09-18 17:03 UTC, hyeon0208 approved these changes
고생했어요 제리 ~ 👍 
몇가지 질문들남겼고 답변해주실거라 믿기에
그 토록 간절히 원하시는 QA 원할 히 하실 수 있도록 approve 드립니다 😃

---
### 질문

> 삭제된 Member, Mate를 조회에서 제외하는 필터가 AOP로 적용되고 있음
@SQLRestriction을 제거하게 되면서 모든 서비스 메서드 로직 앞뒤로 필터 적용&해제 코드가 필요해져 도입함

@SQLRestriction가 제거된 Member, Mate 클래스에는 쿼리에 직접 where 조건절을 달아주면 될 것 같은데 joinPoint 앞 뒤로 필터 적용&해제가 필요한 이유가 있나요 ??

<br>

> 둘 중에 어떤 방법이 더 나은 것 같은가요? 뭔가 더 좋은 방법이 없을까요?

아무래도 일관성을 지킬 수 있는 2번째 방법이 좋은 것 같은데
사실상 쿼리로만 봤을 때는 삭제되지 않은 회원만 조회한다는 것을 인지하기 힘들 것 같고
Filter의 존재를 안다하더라도 meeting은 기한이 지난 약속 조회에 filter를 사용하지 않고 쿼리를 사용해 조회해 사용하는 입장에서 혼란이 생길꺼 같아
이 부분 부터 일관성을 맞춘뒤에 결정할 수 있을 것 같아요

---

논리삭제를 적용하면서 @SQLRestriction 어노테이션 사용으로 여러 문제를 겪고 많은 학습후에 해결하신 것 같은데
쿼리에 논리 삭제 조건문을 추가하는 방식 vs @SQLRestriction을 사용하고 해당 조건문의 반대 조건으로 조회를 하기위한 Filter 추가 
어떤 방식이 더 합리적인 방법이라고 생각하시나요 ??
개인적으로는 지금 구현된 코드를 봤을 때는 후자를 사용함으로써 삭제된 데이터, 삭제되지 않은 데이터를 조회하기 위해 제리가 직접 만든 어노테이션을 써서 AOP 적용되게 했는데
이 단순한 조회에 복잡한 과정이 들어가 있는 것 같아 항상 인지히고 있어야 한다는 점이 우려가 되긴하네요 🤔

2024-09-19 04:14 UTC, mzeong commented on backend/src/main/java/com/ody/mate/domain/Mate.java
>  @SQLDelete(sql = "UPDATE mate SET deleted_at = NOW() WHERE id = ?")
삭제가 구현되어 있다면 개발자가 일반적으로 삭제된 행을 조회되지 않는 것을 기대할거라고 생각했어요
그런데 `@SQLRestriction`을 사용하지 않게 되면 모든 조회 쿼리에 `deletedAt IS NULL`을 추가해줘야 하는데 
이 번거로운 작업을 하지 않기 위해 필터를 적용했어요! (필터를 사용하면 별도의 쿼리 수정 없이 해당 where절이 쿼리에 추가됩니다)

2024-09-19 04:16 UTC, mzeong commented on backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
> +                .map(NotiLogFindResponse::new)
엔티티 생성자에서 필드와 일치하지 않는 매개변수를 가진 생성자들이 많아서 
해당 경우에도 정팩메를 사용해야만 하는 상황이 아니라고 판단했어요!

2024-09-19 04:26 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
> +                .map(NotiLogFindResponse::new)
엔티티 친구들은 자신이 갖고  있는 필드들을 생성자 매개변수로 받는데
NotiLogFindResponse는 자신이 갖고 있지 않는 매개변수로 자신이 필요한 필드를 초기화해서 조금 성격이 다르다고 생각해요
제안 사항이니 반영은 제리 몫 ~! 👍

2024-09-19 04:55 UTC, coli-geonwoo approved these changes
제리, 우선 코드 관련 이해가 더 필요할 것 같아서 살펴보고 코멘트 더 남기는 방향으로 할게요. approve 하겠습니다.

2024-09-19 04:55 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
> +        entityManager.flush();
[질문]

여기에서 flush를 한 이유가 무엇인가요? JPQL 생성시 flush 이후 쿼리가 날아가서 flush 작업이 필요하지 않을 것 같아요

2024-09-19 05:28 UTC, eun-byeol approved these changes
> 그런데 맥락 없이 봤을 때 findById를 재정의해놓은 의도를 다른 개발자들이 파악하기 어려울 것 같아요
둘 중에 어떤 방법이 더 나은 것 같은가요? 뭔가 더 좋은 방법이 없을까요?

soft-delete 관련해서는 코치님께 여쭤보는게 좋을 것 같아요. 더 좋은 방법이 떠오르지 않아요🥲
우선 제리가 구현한 1번 방법으로 컨벤션으로 두고, 추후 문제가 생기기 전에 다시 컨벤션 회의를 해보면 좋을 것 같아요. 버그 잡느라 고생했어요 제리👍

2024-09-19 05:47 UTC, mzeong commented on backend/src/test/java/com/ody/eta/repository/EtaRepositoryTest.java
> +        entityManager.flush();
[반영] Member, Mate에서는 flush가 필요한 게 맞는데 Eta는 `@SQLRestriction`을 쓰고 있어서 flush가 필요 없는 게 맞네요! [de54f2f](https://github.com/woowacourse-teams/2024-ody/pull/534/commits/de54f2f1c4541a74313bbabd4b3babe4fbc892fc)

2024-09-19 05:51 UTC, mzeong commented on backend/src/test/java/com/ody/mate/repository/MateRepositoryTest.java
> +        assertThat(actual.get().getDeletedAt()).isNotNull();
첫 번째 assertThat이 실패하면 두 번째는 성공할 수 없어서 assertAll로 묶지 않았어요!

2024-09-19 05:51 UTC, mzeong commented on backend/src/test/java/com/ody/member/service/MemberServiceTest.java
> +
[반영] [7c3af3a](https://github.com/woowacourse-teams/2024-ody/pull/534/commits/7c3af3ae663410cc254e7e42fbd88fe6f8a8c211)

2024-09-19 05:57 UTC, mzeong commented on backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
> +                .map(NotiLogFindResponse::new)
[반영] [af0ee8b](https://github.com/woowacourse-teams/2024-ody/pull/534/commits/af0ee8b82d977ffb7aa5ec8849df384fb55a4164)

2024-09-19 05:58 UTC, merged