feat: DI 라이브러리 적용
woowacourse-teams/2024-ody pull request #546
Opened 2024-09-20 13:31 UTC by haeum808

# 🚩 연관 이슈 
close #488 

<br>

# 📝 작업 내용
- [x] hilt 라이브러리 적용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-09-21 04:16 UTC, aprilgom approved these changes
엄청 많네요
수고하셨습니다 해음

2024-09-21 04:16 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +    ) : LoginRepository {
LoginRepo 인터페이스를 붙여버리셨네요

2024-09-21 05:15 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
> +    ) : LoginRepository {
일관성을 위해서 붙였습니다!

2024-09-21 17:18 UTC, kimhm0728 requested changes
고생하셨어요 해음!! 👍 코드 수 견제되네요 ㄷㄷ
Hilt를 자세히 알지는 못해서 `AssistedInject`, `HiltWorkerFactory`, `Configuration` 쪽은 아직 잘 모르겠네요. 코드 맥락 상 이해는 했지만 어떤 친구인지는 확실히 파악하지 못했어요. 월요일에 간단한 오디톡 부탁드려도 괜찮을까요?

2024-09-21 17:18 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingActivity.kt
> +//    val analyticsHelper by lazy { mApplication.analyticsHelper }
주석은 삭제해주세요! `mApplication`도 DI 적용하면서 사용하는 곳이 없어진 것 같은데, 같이 삭제해도 좋을 것 같습니다

2024-09-21 17:18 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
> +//    val analyticsHelper by lazy { mApplication.analyticsHelper }
여기도 동일합니다

2024-09-21 17:18 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
> +//            analyticsHelper.logEvent(javaClass.simpleName + " destroyed", bundleOf())
Fragment 진입하거나 나갈 때 로그를 찍어야 하니까 아예 삭제하면 안 될 것 같긴하네요. 이 부분도 수정 부탁해요!

2024-09-21 17:18 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/OdyApplication.kt
> -    }
이 부분 없어지면서 `Provider`도 아예 사용되지 않는 것 같은데 삭제해주실 수 있나요?

2024-09-21 17:18 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
> +    }
순환 참조 문제를 `Lazy { ... }.get()`으로 해결하신 건가요?

2024-09-21 23:36 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
> +    }
넵 맞습니다! 추후에 새로운 이슈를 파서 순환 참조를 아예 제거하겠습니다.

2024-09-22 00:30 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
> +//            analyticsHelper.logEvent(javaClass.simpleName + " destroyed", bundleOf())
BindingFragment가 타입 파라미터를 가지고 있어서 Inject가 불가능하네요. 어떻게 해결할지 추후에 수정해보겠습니다!

2024-09-22 04:11 UTC, kimhm0728 approved these changes
리뷰 반영된 것 확인했습니다!! 👍👍 굿

2024-09-22 04:11 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
> +    val mApplication by lazy { requireContext().applicationContext as OdyApplication }
`BindingFrament`와 `BindingActivity`의 `mApplication`은 사용하는 곳이 없는 것 같은데 그대로 냅두기로 했나요?? 추후 사용을 위해서 냅둔 거라면, `application`으로 네이밍하면 어떨까요? 멤버 프로퍼티명 앞에 m을 붙이는 컨벤션은 없는 것 같아서요.

2024-09-22 04:45 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt
> +    val mApplication by lazy { requireContext().applicationContext as OdyApplication }
회색이 아니라서 헷갈렸네요 바로 삭제했습니다.

2024-09-22 04:53 UTC, merged