refactor: 소요시간 계산 외부 api 의존성 낮추기
woowacourse-teams/2024-ody pull request #555
Opened 2024-09-22 09:30 UTC by hyeon0208

# 🚩 연관 이슈 
close #521 

<br>

# 📝 작업 내용
Google Distance Matrix API를 사용하는 `RouteClient` 구현체를 추가해
`OdsayRouteClient`에 장애가 발생하면 `GoogleRouteClient`로 소요시간을 계산할 수 있도록 의존성을 낮췄습니다.

`GoogleRouteClient` 구현은 
아래 API 가이드 문서를 참고했습니다.
[Google Distance Matrix API 가이드](https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko&_gl=1*a1mmg3*_up*MQ..*_ga*MTI5NTk3NTgwNi4xNzI2OTk3MjI4*_ga_NRWSTWS78N*MTcyNjk5NzIyNy4xLjAuMTcyNjk5NzIyNy4wLjAuMA..)

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-09-23 06:28 UTC, coli-geonwoo approved these changes
카키! 구글 api 찐하게 활용하셨네요! 고생 많으셨습니다

몇가지 질문만 확인해주세요 :)

2024-09-23 06:28 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> Mockito.verify(googleRouteClient, Mockito.times(0)).calculateRouteTime(origin, target)
```suggestion
                () -> Mockito.verify(googleRouteClient, Mockito.never()).calculateRouteTime(origin, target)
```

2024-09-23 06:28 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +        Mockito.when(odsayRouteClient.calculateRouteTime(origin, target))
mock 연속적인 동작에 대해 체이닝을 통해 지정이 가능해요.
```suggestion
        Mockito.when(odsayRouteClient.calculateRouteTime(origin, target))
                      .thenThrow() //1번째 호출 동작
                      .thenReturn() //2번째 호출 동작
       
```

2024-09-23 06:28 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixResponse.java
> +        String errorMessage
[질문]

error-message가 매번 반환되는 필드인지 궁금합니다!

2024-09-23 13:09 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +        this.restClient = routeRestClientBuilder.baseUrl("https://maps.googleapis.com").build();
이 부분 됐었는데
상수 추출은 `baseUrl("https://maps.googleapis.com")`이 이미 의미를 잘 전달하고 있다고 생각했어요
프로퍼티 관리는 프로필 별 설정, CI/CD 시 설정 변경의 편의,  민감한 정보 분리가 필요할 때 장점이 있다고 생각을 해서
관리 포인트를 두 곳에서 하는 곳이 아닌 해당 클래스 내에서 관리하는 것이 좋다고 판단했어요

이에 대해 콜리는 어떻게 생각하시나요 ?? 😃

2024-09-23 13:10 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                .queryParam("destinations", mapCoordinatesToUrl(target))
파라미터를 편하게 설정해줘서 좋더라구요 👍

2024-09-23 13:11 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                    "Google Distance Matrix API 서비스 에러 | {} : {} | 에러 메시지 : {}",
Odsay와 동일하게 에러가 발생해도 200을 반환하고 Body의 Status로 서비스의 상태를 알려주고 있어요 
그래서 Body를 까서 에러 핸들링이 필요 했습니다 !😃

2024-09-23 13:14 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> Mockito.verify(googleRouteClient, Mockito.times(0)).calculateRouteTime(origin, target)
so chic ... 😮 
반영완료 !

2024-09-23 13:16 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixResponse.java
> +        String errorMessage
해당 필드는 필수 값이 아니고 매번 반환 되는 필드는 아니지만
요청이 처리되는 동안 발생한 오류에 대한 정보가 담겨 있다하여 유의미한 정보를 얻을 수 있을 것 같아 추가했어요 😄

2024-09-23 13:23 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +        Mockito.when(odsayRouteClient.calculateRouteTime(origin, target))
`odsayRouteClient.calculateRouteTime()`를 호출 했을 때  예외를 던지고
`googleRouteClient.calculateRouteTime()`을 호출 했을 때는 결과를 반환하게 해
`routeService.calculateRouteTime()`을 실행했을 때 예외가 발생한 `odsayRouteClient`는 패스하고 `googleRouteClient`를 통해 소요시간을 계산하는지 확인하는 테스트에요

위 처럼 연속적으로 호출하도록 할 상황은 아닌데 콜리의 의도는 무엇이였을까요 ?? 🤔

2024-09-23 13:26 UTC, eun-byeol requested changes
코드 참 야물딱지네
기존 오디세이 클라이언트 작업 이어서 하느라 고생하셨습니다~
리뷰 남기긴 했는데 크게 중요한건 없는 것 같아요. 그냥 참고만 하심 될것 같아요!

대신 질문있습니다
**Q. 구글 api는 응답코드 잘 주나요?**
응답 케이스들을 링크로 코드에 첨부해주시면 확인하기 편할 것 같아요.

**Q. 구글 api 에러 status가 코드에 명시된 게 전부인가요?** 
`DistanceMatrixStatus.OK`가 아니면 전부 500 에러를 반환하고 `DistanceMatrixElementStatus.OK`가 아니면 400 에러를 반환하던데, 다른 케이스는 없을까요?

2024-09-23 13:26 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
>      }
[제안]
이 메서드도 맨 밑에 배치해주면 좋을 것 같아요!

2024-09-23 13:26 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> Mockito.verify(googleRouteClient, Mockito.times(1)).calculateRouteTime(origin, target)
야무지네 야무져~

2024-09-23 13:26 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/config/RouteConfig.java
> +    @Order(1)
추가로 RouteServiceTest에서는 구현체들을 모킹하기 위해 `@Qualifer`를 사용하지만
프로덕션 코드에는 `@Qualifer`가 의미가 없어 제거했습니다 !

2024-09-23 13:32 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +        this.restClient = routeRestClientBuilder.baseUrl("https://maps.googleapis.com").build();
저도 클래스 필드에 상수로 빼면 좋을 것 같아요!

2024-09-23 13:32 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/TestRouteConfig.java
> +
반영 완 !

2024-09-23 13:34 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                    "Google Distance Matrix API 서비스 에러 | {} : {} | 에러 메시지 : {}",
진짜 왜 다 200주는걸까요... 에러코드 주면 handler사용해서 코드 깔꼼하고 이쁜데,,

2024-09-23 13:34 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/config/RouteConfig.java
> +    @Qualifier("google")
조조 말이 맞아요 👍 프로덕션 코드에서 제거 했습니다 !

2024-09-23 13:51 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +    @Qualifier("odsay")
RouteServiceTest는 RouteClient를 구현한 구현체들에 모킹이 필요해 사용이 필요했습니다 !

2024-09-23 13:52 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/OdsayRouteClientTest.java
>      }
반영 완 !

2024-09-23 13:57 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixElementStatus.java
> +public enum DistanceMatrixElementStatus {
API 가이드 문서안에 항목 별로 링크가 나눠져 있찌 않고 모든 설명이 포함되어 있어 API 가이드 링크 주석에 추가했습니다 !

2024-09-23 14:12 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                .body(DistanceMatrixResponse.class);
status 필드로 넘어오는 상태 정보를 Enum으로 처리해 OK 상태가 아닌 
해당 상태 코드와 메세지를 로그로 남긴뒤 예외가 발생하도록 했는데 
restClient 요청을 보낼때 발생할 수 있는 에러가 어떤 에러들이 있을까요 ?? 🤔

2024-09-23 16:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +        this.restClient = routeRestClientBuilder.baseUrl("https://maps.googleapis.com").build();
> 이에 대해 콜리는 어떻게 생각하시나요 ?? 😃

전반적으로 개인 선호에 따른 시각차이라 저도 카키의 관점이 하나의 정답이 될 수 있다는 점에 동의합니다! 다만 저는 properties로 관리하는 것을 더욱 선호하는데요. 그 이유는 
- ConfigurationProperties 자체에 설정관련 정보들을 응집성있게 모을 수 있고
- 의존성 직접 주입보다 상위모듈에서 POJO 기반 프로그래밍을 지향할 수 있으며
- Client나 Service 계층에서 조금 더 메인 로직에 집중할 수 있도록 세부 정보를 캡슐화하기 때문이에요.

다만 현재 케이스는 카키가 말한대로 충분히 baseUrl 자체로 의미가 전달되고 분리 과정에서 또다른 리소스들이 필요하니 지금 구조로도 괜찮다고 생각합니다!

2024-09-23 16:31 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +        Mockito.when(odsayRouteClient.calculateRouteTime(origin, target))
> 위 처럼 연속적으로 호출하도록 할 상황은 아닌데 콜리의 의도는 무엇이였을까요 ?? 🤔

아 다른 mockito의 stubbing이었군요! 꼼꼼히 리뷰해보겠습니다 😭

2024-09-23 16:35 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        for (RouteClient client : routeClients) {
List<RouteClient>를 Deque으로 선언하고 오류가 발생하면 popleft 후, 뒤로 구현체를 다시 push 하는 식의 구현은 어떤가요? 

이런 식의 rotate가 deque length 만큼 쌓이면 오류를 반환해도 좋을 것 같아요.

2024-09-23 17:11 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        for (RouteClient client : routeClients) {
오호 지금 적용하기 가장 간단한 방법이겠네요 👍 
하지만 Deque는 상태가 변한다는 점에서 여러 스레드가 접근했을 때 Deque의 상태를 예측하기 힘들다는 점에서
동시성 문제가 있을 것 같아요

2024-09-24 12:11 UTC, mzeong approved these changes

2024-09-24 12:11 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        for (RouteClient client : routeClients) {
오디세이 응답을 캐싱해두는 것도 로직이 간단할 것 같아요~ API 호출 빈도를 줄이는 용도로도 사용할 수 있구요!
여러 대안들을 고민해보고 나중에 개선하면 좋을 포인트네요 👍👍

2024-09-24 15:00 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                .body(DistanceMatrixResponse.class);
구글 서버로부터 정상적으로 온 응답(error status 포함)만 핸들링이 되고 있어서 말씀드렸어요. timeout과 같이 커넥션 도중에 발생하는 에러라면 응답이 정상적으로 안 올 것 같아요. 이부분 핸들링에 대해서는 어떻게 생각하시나요?

2024-09-24 15:26 UTC, eun-byeol approved these changes
> [Google Distance Matrix API 가이드](https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko&_gl=1*a1mmg3*_up*MQ..*_ga*MTI5NTk3NTgwNi4xNzI2OTk3MjI4*_ga_NRWSTWS78N*MTcyNjk5NzIyNy4xLjAuMTcyNjk5NzIyNy4wLjAuMA..)
명시된 status를 전부 매핑해서 추가해놓았는데 다른 케이스는 생각이 안나네요 🤔
조조가 생각나는 상황이 있을까요 ?

링크 첨부해주신거에서 status 확인했습니다! 다른 상황은 없는 것 같네요! 간단하게 추가 리뷰 남겼고, 이번 역시도 반영 여부는 카키의 몫입니다! 간단한 리뷰들이라 approve하고 merge는 하지 않을게요!

2024-09-24 15:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixResponse.java
> + * @link <a href="https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixElementStatus"></a>
[제안]
인텔리제이 상에서 아래처럼 보이던데, 개행 수정하면 어떤가요?
![image](https://github.com/user-attachments/assets/c5bb6597-8437-4cad-ade2-35c10a68bc00)

```suggestion
 * DistanceMatrixResponse 가이드 문서 @link <a href="https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixResponse"></a><br>
 *
 * DistanceMatrixStatus 가이드 문서 @link <a href="https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixStatus"></a><br>
 *
 * DistanceMatrixElementStatus 가이드 문서 @link <a href="https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixElementStatus"></a>
```

2024-09-24 15:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
> +public enum DistanceMatrixStatus {
[질문]
`MAX_DIMENSIONS_EXCEEDED`에러는 발생할 일이 없어서 추가하지 않은건가요?
[에러코드 참고](https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixElementStatus)

2024-09-24 15:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
> +    INVALID_REQUEST("잘못된 요청"),
[질문]
이 경우도 500에러를 던지는게 맞나요? 설명으로만 보면 400에러처럼 보여서요!

2024-09-24 15:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixElementStatus.java
> +    }
[제안]
enum에도 롬복 사용해도 되겠네요!
```java
@Getter
@RequiredArgsConstructor
```

2024-09-24 15:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
> +    }
[제안]
이부분도 롬복 사용할 수 있을 것 같아요!

2024-09-24 15:35 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixElementStatus.java
> +    }
오호 이넘을 프리코스에 많이 다루다보니 롬복 사용을 생각 못했네요 👍

2024-09-24 15:37 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
> +public enum DistanceMatrixStatus {
놓친 부분이네요 ! 해당 에러 상수 추가했습니다 👍

2024-09-24 15:43 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixResponse.java
> + * @link <a href="https://developers.google.com/maps/documentation/distance-matrix/distance-matrix?hl=ko#DistanceMatrixElementStatus"></a>
반영 완!

2024-09-24 15:46 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/dto/DistanceMatrixStatus.java
> +    INVALID_REQUEST("잘못된 요청"),
로컬에서 실제 응답이 잘 오는지 테스트할 때
구글에서 원하는 URI 형식과 조금 다른 형태로 우리 서버 측에서 요청을 보내면 해당 에러를 뱉기도 하고
API KEY가 잘 못되면 해당 에러를 뱉기도 했어서 조금 애매했었는데

우리 서버 측에서 요청을 보낸 것에 대해 응답이 잘 온 것을 확인했으니 우리의 잘 못이 생길 수도 있겠지만
대부분 클라이언트 에러 일 것 같네요 😃
400번으로 처리했습니다 ! 👍

2024-09-24 15:53 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/GoogleRouteClient.java
> +                .body(DistanceMatrixResponse.class);
해당 부분은 오디세이 구현하면서 작성돼있던 RouteConfig안의 RestClientCustomizer를 정의해놓은 부분 때문에
이미 타임아웃이 적용되고 있어서 해당 에러가 발생하면
에러 핸들러 중 `Exception`을 받는 에러 핸들러가 예외 처리 해주고 있는 것으로 봤어요
오디세이도 같은 맥락으로 타임아웃 핸들링을 안한 것으로 봤는데 맞을까요 ??

2024-09-24 15:59 UTC, merged