feat: 약속 시간 30분전 ETA 조회 가능 알림 기능 추가
woowacourse-teams/2024-ody pull request #563
Opened 2024-09-23 15:19 UTC by hyeon0208

# 🚩 연관 이슈 
close #552 

<br>

# 📝 작업 내용
> `NotificationType`에 `ETA_NOTICE` 타입을 추가하여 약속 시간 30분 전 ETA 조회 가능 알림 기능 추가

> `FcmEventSchedulerTest` 제거

초기에 있던 이벤트리스너에 대한 테스트였는데 현재는 필요없어져 테스트 제거했습니다
(애초에 제가 무조건 성공하도록 짰던 잘못된 테스트였기도 했어요 ㅋㅋ.. 😂)

> `Message` 클래스들 record 클래스로 변경

해당 작업하면서 내부 필드가 아닌 값으로 인스턴스를 초기화하는 것이 부자연스러워 정팩메로 변경했습니다
정팩메 호불호가 너무 갈리는 거 같은데 이에 대한 의견 주세요 😄

> 약속 시간 30분전에 taskScheduler에 스케줄링이 잘 되었고 의도한데로 실행되는지에 대한 테스트

`Mockito`에서 제공하는 `ArgumentCaptor`클래스를 사용해 테스트 했는데
이 클래스는 Mock 객체의 메소드가 호출될 때 전달되는 인자를 클래스명 그대로 "캡쳐"해 검증하는데에 사용할 수 있었어요
```
meetingService.saveV1(request);

ArgumentCaptor<Runnable> runnableCaptor = ArgumentCaptor.forClass(Runnable.class);
ArgumentCaptor<Instant> timeCaptor = ArgumentCaptor.forClass(Instant.class);

Mockito.verify(taskScheduler).schedule(runnableCaptor.capture(), timeCaptor.capture());
Instant scheduledTime = timeCaptor.getValue();
runnableCaptor.getValue().run();
```

`meetingService.saveV1()`가 호출되면 내부에서 `taskScheduler.schedule()`가 실행되는데
이 내부 작업이 의도한데로 잘 동작하는지 확인하기 위해
taskScheduler의 schedule() 메서드에 사용되는 인자 타입들을 캡쳐할 객체들을 생성하고 호출됐는지 확인함과 동시에 이 호출에 전달된 인자를 캡쳐(저장)합니다.
이 후에는 캡쳐해놓은 값을 꺼내 의도한데로 동작하는지를 테스트할 수 있었어요 

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

> 다른 알림들과 성격이 다른 NoticeMessage

이전 리팩토링에서 비슷한 성격을 가진 메세지들을 묶고자 `GroupMessage`, `DirectMessage`로 메시지들을 네이밍했는데
ETA 공지 알림도 토픽을 사용하기에 `GroupMessage`의 성격과 유사하지만 필요한 데이터가 달랐어요
ETA 공지 알림은 meeting이 갖고 있는 정보들만 필요했거든요 .. (약속 이름, 약속 ID, 토픽 명)
그래서 공지에 대한 알림들을 묶을 수 있는 `NoticeMessage`를 추가하게 됐습니다.

이 기능 추가로 `FcmPushSender`내부 로직들이 가독성이 많이 떨어진 것 같은데 마땅히 좋은 방법이 아직은 생각이 안나네요
좋은 아이디어 있으면 공유주세요 ! 👍

2024-09-23 19:04 UTC, coli-geonwoo requested changes
카키! 늦은 시간까지 요구사안들을 하나씩 해결해나아가는 모습 대단합니다 😶 

몇가지 리뷰 남겼어요! ArgumentCaptor를 활용한 테스트가 인상적이었습니다.

또한 추가적으로 두 가지 의견 남깁니다.

- fcmPushSender가 taskSchedular를 들고 있고 reserveMessage(시간, 메시지)라는 public interface를 통해 어떤 메시지를 언제 보내줘! 라는 로직을 가지고 있으면 어떨까요? 테스트도 더욱 쉬워질 것 같습니다.

| 이 기능 추가로 FcmPushSender내부 로직들이 가독성이 많이 떨어진 것 같은데 마땅히 | 좋은 방법이 아직은 생각이 안나네요

- 이전 리팩토링에서 GroupMessage, DirectMessage로 메시지 클래스 명을 추상화한 이유는 비슷한 기능 간에 재사용성 때문이라고 생각됩니다. 그런데 메시지 클래스는 추상화될 수 없다는게 제 개인적인 생각입니다.  

- 이미 DirectMessage에서도 sendPrivateMessage와 createSenderToReciverMessage 처럼 2가지 message의 역할이 합쳐져 있기도 하고, 이 메시지들의 재활용성 측면에서도 만약 Mate 이외에 다른 파라미터가 필요하다면 똑같이 sendertoreciver의 역할을 하는 message더라도 createSenderToReciverMessage 정팩메를 사용하지 못하고 새로운 메서드가 필요하게 될 것 같아요. 이번에 카키가 이야기한 `ETA 공지 알림은 meeting이 갖고 있는 정보들만 필요했거든요 `에서도 같은 맥락의 문제라고 생각되어요. 역할은 DirectMessage에 속한다고 볼 수 있지만 다른 파라미터가 필요해서 새로운 생성자나 클래스가 필요한 상황을 앞으로도 마주하게 될 것 같아요.

- 그래서 제 최종 의견은 Message 명은 기존처럼 NudgeMessage, PushMessage, ETAOpenMessage 등등 명확하게 message의 타입을 유추할 수 있는 클래스명을 사용하되 이를 Message interface나 추상클래스로 타입계층화해 상위 클래스에서는 하나의 메서드로 파라미터를 받을 수 있도록 하는 건 어떨지, 카키의 의견이 궁금합니다!

2024-09-24 15:49 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/domain/Meeting.java
> +    public LocalDateTime get30MinutesBeforeMeetingTime() {
[제안] 콜리의 의견에 동의해요 `getEtaNoticeTime`은 어떤가요?

2024-09-24 15:49 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationStatus.DONE,
[질문] DEPARTURE_REMINDER는 스케줄링을 통해 전송되는 알림인데 초기 상태를 PENDING으로 둬야하지 않나요?

2024-09-24 15:49 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +        return this.type.isDepartureReminder();
저도 == 비교가 좋습니다

2024-09-24 15:49 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
> +        return new DirectMessage(message);
[제안] 두 direct message 차이가 타인에게 보내는지, 나에게 보내는지 차이인가요? createPrivateMessage 메서드 사용처가 없어 용도가 헷갈리네요

만약 누구에게 보내는 메세지인지의 차이라면 createSenderToReceiverMessage → createMessageToOther, createPrivateMessage → createMessageToSelf는 어떤가요?

2024-09-24 15:49 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/message/NoticeMessage.java
> +public record NoticeMessage(Message message) {
[질문] DirectMessage에서 여러 생성 메서드를 두고 이름으로 구분한 것처럼 GroupMessage 내에 생성 로직을 추가하지 않고 
NoticeMessage라는 새로운 객체를 만든 이유가 있나요? 
단순히 message를 생성하기 위해 필요한 정보가 다른 거라면 전자의 방식이 덜 헷갈릴 것 같아요

2024-09-24 16:03 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/domain/Meeting.java
> +    public LocalDateTime get30MinutesBeforeMeetingTime() {
제리의 제안은 콜리의 의견에 동의하는 제안은 아닌 거 같은데요 😅
저도 콜리 의견에 동의하는 바기도하고 meeting이 eta를 알고 있다는 것이 어색한 것 같아 서비스로 뺐습니다 !

2024-09-24 16:08 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +        return this.type.isDepartureReminder();
개인적으로는 enum 내에서 어떤 타입인지를 boolean으로 반환하게 되면 재사용성이 용이하다고 생각해요
지금이야 전체적으로 해당 메서드가 쓰이진 않지만 추후에 다른 레이어에서 enum 인스턴스가 특정 타입을 갖고 있다를 확인하고 싶을 때
== 로 중복적이게 비교하는 것이 아닌 메서드로 편하게 사용할 수 있다고 생각하거든요

조조 의견까지 듣고 다수결로 반영하겠습니다 👍

2024-09-24 16:10 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +    private static final ZoneOffset KST_OFFSET = ZoneOffset.ofHours(9);
여러번 중복 선언해서 불편했는데 제리는 해당 ZoneOffset 타입을 관리하는 클래스명이 뭐가 적절하다고 생각하시나요 ?

2024-09-24 16:11 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationStatus.DONE,
nice catch ~ 👍

2024-09-24 16:12 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
> +        return new DirectMessage(message);
네이밍 고민 많이 됐는데 네이밍 잘하시네요 제리 👍 
반영 완 ~!

2024-09-24 16:18 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/message/NoticeMessage.java
> +public record NoticeMessage(Message message) {
mzeong 합니다 정팩메로 뺀 상황에서 충분히 네이밍으로 공지 알림 메시지를 생성할 수 있을 것 같아요 👍

2024-09-24 16:29 UTC, hyeon0208 commented
@coli-geonwoo 

콜리 좋은 의견 감사해요 😊
의견에 답변 드립니다
추가로 해당 부분들은 테스트들도 수정되는 등 좀 큰 리팩토링이 될 꺼 같아서 새로 이슈 파서 진행하는게 좋을 것 같아요 👍 

> fcmPushSender가 taskSchedular를 들고 있고 reserveMessage(시간, 메시지)라는 public interface를 통해 어떤 메시지를 언제 보내줘! 라는 로직을 가지고 있으면 어떨까요? 테스트도 더욱 쉬워질 것 같습니다.

콜리 말 데로 fcmPushSender가 taskSchedular를 들고 있다면 각 서비스 레이어에서 중복적으로 taskSchedular를 의존할 필요도 사라지고
복잡성이 줄 수 있겠네요 👍 

> 그래서 제 최종 의견은 Message 명은 기존처럼 NudgeMessage, PushMessage, ETAOpenMessage 등등 명확하게 message의 타입을 유추할 수 있는 클래스명을 사용하되 이를 Message interface나 추상클래스로 타입계층화해 상위 클래스에서는 하나의 메서드로 파라미터를 받을 수 있도록 하는 건 어떨지, 카키의 의견이 궁금합니다!

고민해봤는데 각자 다른 성격을 가진 메세지들이 필요한 인자들디 다달라서 하나의 메서들도 묶으라면 불필요한 파라미터도 받는등 파라미터가 많아질 것 같아요
아니면 콜리가 생각한 더 좋은 방법이 있을까요 ?? 🤔

2024-09-25 06:21 UTC, coli-geonwoo commented
@hyeon0208 

> 고민해봤는데 각자 다른 성격을 가진 메세지들이 필요한 인자들디 다달라서 하나의 메서들도 묶으라면 불필요한 파라미터도 받는등 파라미터가 많아질 것 같아요 아니면 콜리가 생각한 더 좋은 방법이 있을까요 ?? 🤔

음... 제가 생각한 개선책은 불필요한 파라미터를 받는 로직보다는 message 객체를 추상화하지 말고  역할에 맞는 세부 객체들을 세분화하고 AbstractMessage나 Message interface를 상속받아서 타입 계층으로 관리하자는 거였어요.

ex)
```
NudgeMessage extends Message
DirectMessage extends Message ..
```
=> 각각 필요한 파라미터만을 가진 생성자 1개씩만 가짐

그렇게 되면 messagesender나 상위 모듈에서는 Message하고만 소통할 수 있을 것 같아요

ex)
```
MessageSender.send(Message message)
```

2024-09-25 06:23 UTC, coli-geonwoo approved these changes

2024-09-25 06:23 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +        return this.type.isDepartureReminder();
만약 객체간 메시지 전달로 리팩터링 한다면 카키 말대로 활용가능성을 열어두었으면 좋겠다는 의견입니다!

ex)
```java

NotificationType.isType(NotificationType targetType)

```

2024-09-25 06:23 UTC, eun-byeol approved these changes
고생하셨습니다 카키! ArgumentCaptor클래스를 사용해 테스트 덕분에 배웠어요👍

> 정팩메 호불호가 너무 갈리는 거 같은데 이에 대한 의견 주세요 😄

저는 정팩페 합리적이라고 생각해요.
`createSenderToReceiverMessage`처럼 메서드명으로 의도를 드러낼 수 있어서 덜 헷갈릴 것 같아요.

2024-09-25 06:23 UTC, eun-byeol commented on backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
> +                "데모데이 회식",
🤣

2024-09-25 07:00 UTC, mzeong commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +    private static final ZoneOffset KST_OFFSET = ZoneOffset.ofHours(9);
저도 좋은 아이디어가 생각이 안나서 제안까지 포함해서 코멘트를 남기지 못했는데.. 흠.. TimeUtil에 추가해주는 건 어떤가요?

2024-09-25 07:04 UTC, mzeong approved these changes
approve 남기고 갑니다~ 🚗🔑👍

2024-09-25 14:50 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +        return this.type.isDepartureReminder();
이 부분 데모데이 끝나고 회의로 개선할 사항들 회의하면서 정해보죠 !

2024-09-25 14:50 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/service/MeetingService.java
> +    private static final ZoneOffset KST_OFFSET = ZoneOffset.ofHours(9);
지금으로써 제일 적합할 것 같아요 👍

2024-09-25 15:10 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    }
이런 부분이 전반적으로 꾀 많은데
전체적으로 일관성 맞지 않는 부분 날잡고 리팩토링 해보도록 하죠 ! 👍

2024-09-25 15:11 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +        return this.sendAt.equals(TimeUtil.nowWithTrim());
Ditto 🚩

2024-09-25 15:43 UTC, merged