feat: 출발 시간 알림 구현
woowacourse-teams/2024-ody pull request #60
Opened 2024-07-22 08:16 UTC by mzeong

# 🚩 연관 이슈 
close #20

<br>

# 📝 작업 내용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-23 02:47 UTC, coli-geonwoo requested changes
file changes 42개.... 정말 정말 고생 많았어!

헤더 관련 설명 같이 첨부할게.

[변경 제안 - 선택] : 변경을 제안할 뿐 반영여부는 자유에 맡깁니다.
[변경 제안 - 필수] : 꼭 변경이 필요한 부분이라 생각합니다.
[변경 제안] : 변경을 권유합니다.
[질문] : 답변을 기다리는 comment입니다.

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/controller/MeetingController.java
> +                                        1L,
**[변경 제안]**

줄바꿈이 위와 아래 객체가 일치되었으면 좋을 것 같아요 😄 근데 생각해보니 제가 작성한 예시인것 같네요? 죄송합니다 🙇

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
> +    public Meeting toMeeting(String inviteCode) {
**[질문]**

사실상 정적 팩터리 메서드와 같은 메서드인 것 같아요.
정적 팩터리 메서드 사용을 지양하자고 컨벤션을 정했지만 필요하다면 사용해도 된다고 생각해요.

toMeeting 메서드의 정팩메 전환에 대한 제리의 의견이 궁금합니다 🤔

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
> +@Repository
[변경 제안]

JPARepository에는 @Repository가 없어도 구현체에 빈 등록이 됩니다.

[왜 그런지 궁금해서 찾아본 링크](https://velog.io/@kshired/Spring-%EC%99%9C-JPARepository%EB%8A%94-Repository%EA%B0%80-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-deep-dive-%ED%95%B4%EB%B3%B4%EA%B8%B0)

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/config/FcmConfig.java
> +                    .setCredentials(
**[변경 제안 - 선택]**

사실 지금도 잘 읽히지만 한가지 제안해봅니다 ✋ 

option 설정은 재사용가능한 부분이 있으리라 생각해서 private method 분리를 해도 좋을 것 같아요!

```java
FirebaseOptions setUpOptions(){
    var credential =  GoogleCredentials.fromStream(new ClassPathResource(accessKeyFilename).getInputStream());

    return  FirebaseOptions.builder()
                    .setCredentials(credential)
                    .build();

}
```

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
> +        String topic,
**[변경 제안]**

@Valid를 통해 꼭 필요한 값들에 대해서는 null 검증을 해주어도 좋을 것 같습니다!

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/NotificationStatus.java
> +    PENDING,
**[질문]**

PENDING : 아직 발송되지 않은 상태
DONE : 발송 완료된 상태

이렇게 해석했는데 혹시 아니라면 추가 comment 남겨주세요 👀

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/dto/response/NotificationSaveResponse.java
> +package com.ody.notification.dto.response;
👍

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
> +@Component
**[변경 제안 - 선택]**

FcmConfig가 있어서 문득 든 생각인데 수동 빈 등록을 통해 관련 객체를 Config 파일에서 찾아갈 수 있게 만드는 것도 좋을 것 같아요!

반영은 자유롭게!

2024-07-23 02:47 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/FcmPushSender.java
> +                .setNotification(Notification.builder()
**[변경 제안]**

개인적으로 Notification 관련 세팅 부분은 private 메서드로 분리하면 좋을 것 같아요!

혹은 Notification을 상속받은 CustomNotification을 만들어 관련 도메인 로직을 넣어도 사용하기 쉬워질 것 같다는 생각입니다!

2024-07-23 04:45 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
> +    public Meeting toMeeting(String inviteCode) {
정팩메와 비슷하지만 요청을 받을 때 `MeetingSaveRequest` 객체가 초기화되서 오기 때문에 
추가적인 초기화작업이 필요 없어 인스턴스 메서드로 작성했어요 !

제 생각을 말하자면
`MeetingSaveResponse`처럼 직접 초기화가 필요하다면 정팩메로 간단하게 초기화하기엔 용이다하다고 생각합니다😄

2024-07-23 04:51 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
> +@Repository
오 새로 알게된 사실이네요 👍🏻
저 같은 경우에는 습관적으로 레포지토리 계층에 `@Repository` 어노테이션을 붙이곤 하는데
콜리는 안 붙이는 편이신가요 ?

이 부분에 대해 다 같이 논의해서 컨벤션을 맞추는 편이 좋겠네요😄

2024-07-23 04:53 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/NotificationStatus.java
> +    PENDING,
콜리의 해석이 맞습니다 전송 전이 PENDING, 전송 완료가 DONE 입니다!

2024-07-23 05:43 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/argumentresolver/AuthMemberArgumentResolver.java
> +        String value = webRequest.getHeader(HttpHeaders.AUTHORIZATION);
좋은 의견이라 생각합니다 !
토큰 형식 검증에 대한 역할은 DeviceToken이 담당하도록 코드를 변경했습니다👍🏻

2024-07-23 07:07 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +        Meeting meeting = meetingService.findById(1L);
현재는 
`MeetingService`에서 `MateService`와 `notificationService`을 들고 있게 되면 거의 중복과 비슷한 메서드만 추가될 것 같아
`MeetingController`에 코드가 추가되면 그 때 다시 생각해보면 좋을꺼 같아요 😄

2024-07-23 07:14 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/config/FcmConfig.java
> +                    .setCredentials(
FCM 설정에 대해서는 재사용하기는 힘들 것 같지만
분리하면 코드가 훨 씬 깔끔할 것 같네요 👍🏻
콜리의 제안대로 분리해보았습니다 👍🏻👍🏻

2024-07-23 07:19 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
> +        String topic,
지금 PR에는 검증 부에 대한 코드가 없어서 선언하지 않았습니다 
검증 로직 추가 PR에 해당 부분 반영되도록 하겠습니다 👍🏻

2024-07-23 07:20 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
> +@Component
좋은 의견 감사합니다 👍🏻
해당 클래스는 설정이기 보다는 FCM에 메세지를 전달하는 로직이 있어 지금이 적당할 것 같아요 !

2024-07-23 07:30 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/FcmPushSender.java
> +                .setNotification(Notification.builder()
가독성 측면이 우려되긴 하네요
말씀대로 Notification, AndroidCofig 설정 코드를 private 메서드로 분리해보았습니다 ~ 👍🏻

2024-07-24 04:48 UTC, hyeon0208 approved these changes

2024-07-24 05:20 UTC, coli-geonwoo approved these changes

2024-07-24 05:20 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
> +@Repository
**[답변]**

> @Repository 어노테이션을 붙이곤 하는데 콜리는 안 붙이는 편이신가요 ?

JPARepo에는 붙이지 않는 편입니다. 붙여도 상관없지만 일관성 유지하는 것이 좋을 것 같아서 컨벤션 맞춰보는 게 좋을 것 같아요.

2024-07-24 05:27 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/config/JpaAuditingConfig.java
> +@EnableJpaAuditing
👍
[@EnableJpaAuditing을 분리해야 하는 이유](https://hellorennon.tistory.com/9)

2024-07-24 06:24 UTC, eun-byeol requested changes
많은 file 변경이 있었군요..! 비동기 테스트까지 야무지게 코드를 짜놓으셔서 칭찬 박고👏, 코멘트 몇개 남깁니다! 확인 부탁드려요~👍

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
> +@Repository
저도 붙이지 않는 편입니다!
관련해서 레벨2에서 리뷰 받았던 부분이라, 저는 지우는 게 더 좋지 않을까~?🤔 싶네용

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/config/FcmConfig.java
> +                        .getInputStream()))
[제안]
가독성 측면에서, setXX에 들어갈 값을 변수로 빼면 어떨까요?
fcm path 경로도 상수로 빼는건 어떤지요~?🤔

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
> +                () -> fcmPushSender.sendPushNotification(fcmSendRequest), fcmSendRequest.sendAt().toInstant(KST_OFFSET)
[제안]
가독성 측면에서, 2개의 매개변수를 개행으로 구분해주면 어떨까요~?

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/service/FcmPushSender.java
> +                                .build()
[제안]
개인적인 선호이지만, 값은 변수로 빼서 정의하고 setXX에 넣어주는 건 어떤가요~?

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +        notificationRepository.save(notification);
[제안]
추후 고려 사항이 되겠지만, 파사드 패턴으로 Service를 계층화하는 것을 고려해보면 좋을 것 같아요!
[블로그 글의 3번 제목 참고](https://jangjjolkit.tistory.com/62)

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/Fixture.java
> +    );
[제안]
private 생성자 만들어서 닫아주는 게 좋을 것 같습니다!

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/IntegrationTest.java
> +public abstract class IntegrationTest {
[제안]
네이밍을 ControllerTest로 하면 어떨까요?
컨트롤러에만 사용되는 클래스인 것 같은데, 통합 테스트라는 네이밍이 적절한지 의문이 쪼꼼 드네요!(저도 레벨2 리뷰받은 부분이었습니다!)

2024-07-24 06:24 UTC, eun-byeol commented on backend/src/test/resources/application.yml
[질문]
지금 시점에서 test 전용 application.yml을 작성한 이유가 있을까요?

2024-07-24 06:54 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/config/FcmConfig.java
> +                        .getInputStream()))
좋은 의견  감사합니다 !
현재 해당 설정은 Jar 실행시에 한번만 초기화되기 때문에 static final 상수로 빼는 것보다는 변수로 빼는게 좋을 것 같다고 생각하는데
변수로 빼더라도 변수의 이름을 적절하게 부여하기 힘들어 가독성이 증가하기 힘들다고 생각하고, String으로 들어가있는
파일명 또한 어떠한 파일인지 명확하다고 생각이 듭니다! 😄

2024-07-24 07:02 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/FcmEventScheduler.java
> +                () -> fcmPushSender.sendPushNotification(fcmSendRequest), fcmSendRequest.sendAt().toInstant(KST_OFFSET)
개행을 적용했을 때는 각 파라미터의 들여쓰기가 서로 달라 보기 어렵다고 느껴졌어요 😥
가독성 측면을 고려해 2번째 인자를 변수로 빼서 schedule() 코드를 한 라인으로 만들어 봤는데 이 부분에 대해선 어떻게 생각하실까요 ??

2024-07-24 07:08 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/FcmPushSender.java
> +                                .build()
동의 합니다 👍🏻
해당 부분 반여했습니다 !

2024-07-24 07:13 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +        notificationRepository.save(notification);
좋은 의견 감사합니다 !
해당 패턴을 적용하기에는 아직은 크게 필요성을 못느끼는 것 같아 
코드가 추가되고 나서 나중에 고려해봐도 좋을 것 같아요 ! 👍🏻

2024-07-24 07:20 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/Fixture.java
> +    );
유틸이라 기본 생성자를 만들 일이 없겠네요 ! 
꼼꼼한 리뷰 감사합니다 ! 😊

2024-07-24 07:22 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/IntegrationTest.java
> +public abstract class IntegrationTest {
Service 테스트 설정도 공통화한 추상 테스트 클래스가 생길 수 있으니
해당 부분도 계층에 맞게 네이밍 해주는게 좋은 것 같네요 !
`BaseEntity` 처럼 네이밍을 `BaseControllerTest`로 정해보았습니다 ! 👍🏻

2024-07-24 07:24 UTC, hyeon0208 commented on backend/src/test/resources/application.yml
원래는 test에서는 FCM 연결을 할 것인지 말것인지를 main에서는 true, test에서는 false로 옵션을 다르게 하고 있었는데
지금은 컨트롤러 테스트해서 FcmConfig를 @MockBean으로 주입해주고 있어 
해당 파일이 필요없어졌네요 😅
해당 파일 제거했습니다 !

2024-07-24 07:31 UTC, eun-byeol approved these changes

2024-07-24 07:32 UTC, merged