feat: 모임 초대 코드 생성 기능 추가
woowacourse-teams/2024-ody pull request #61
Opened 2024-07-22 08:23 UTC by hyeon0208

# 🚩 연관 이슈 
close #56

<br>

# 📝 작업 내용
모임 초대 코드를 meetingId를 이용해 인코딩해 생성하고
decoding해 meetingId를 찾는다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-07-22 08:46 UTC, hyeon0208 commented
테스트

2024-07-22 08:48 UTC, hyeon0208 commented
zz

2024-07-22 08:50 UTC, hyeon0208 commented
zzzz

2024-07-23 14:18 UTC, coli-geonwoo approved these changes

2024-07-24 06:32 UTC, eun-byeol requested changes
야무지게~ 코드 작성하셨군요!
초대코드의 길이까지 신경써서 구현해주신 부분 멋져요~
간단한 코멘트 남겼습니다 확인부탁드려요!

2024-07-24 06:32 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/service/InviteCodeGenerator.java
> +        String base64Encoded = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
[제안]
메서드 체이닝 개행도 챙겨주시면 좋을 것 같아요~!

2024-07-24 06:32 UTC, eun-byeol commented on backend/src/main/java/com/ody/meeting/service/InviteCodeGenerator.java
> +        return Long.parseLong(decodedString.trim());
[제안]
parseLong 시에 발생 가능한 에러도 체크해주는 건 어떨까요?

2024-07-24 08:40 UTC, eun-byeol approved these changes

2024-07-24 08:46 UTC, hyeon0208 commented on backend/src/main/java/com/ody/meeting/service/InviteCodeGenerator.java
> +        return Long.parseLong(decodedString.trim());
검증이 필요할 것 같네요 !
바로 추가했습니다 👍🏻

2024-07-24 08:48 UTC, merged