refactor: 현재 위치 가져오는 객체 생성 및 분리
woowacourse-teams/2024-ody pull request #629
Opened 2024-09-30 07:44 UTC by haeum808

# 🚩 연관 이슈 
close #590 

<br>

# 📝 작업 내용
- [x] 현재 위치 가져오는 객체 생성 및 분리

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
GpsHelper에서 위치 권한이 허용되어 있는지, gps를 켰는지 확인안하는 이유가 Location 찾다가 exception이 발생하면 null을 반환하기 때문입니다.

2024-09-30 08:01 UTC, aprilgom approved these changes
수고하셨습니다 해음

2024-09-30 08:01 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
> +                val location = gpsHelper.getCurrentCoordinate()
액티비티에 있던 코드가 여기로 이사왔네요 
여기 있는게 더 나은 것 같습니다

2024-09-30 08:17 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GpsHelper.kt
> +            null
runCatching을 활용해보는건 어떨까요

2024-09-30 08:40 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GpsHelper.kt
> +            null
반영했습니다! [429a0e7](https://github.com/woowacourse-teams/2024-ody/pull/629/commits/429a0e701f35d26727df115bbcafa25c51e8579e)

2024-10-01 14:42 UTC, kimhm0728 requested changes
고생하셨어요 해음! 겹치는 로직들을 하나의 객체로 분리하니 훨씬 보기 좋네요 👍 👍

2024-10-01 14:42 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
> +        LocationServices.getFusedLocationProviderClient(context)
사소한 부분이지만 by lazy로 선언하는 건 어떨까요?? 꼭 반영하지 않으셔도 됩니다!

2024-10-01 14:42 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
> +    }
상수 분리 좋네요 👍👍

2024-10-01 14:42 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
> +    suspend fun getCurrentCoordinate(): Result<Location>
저희가 만든 `ApiResult` 객체를 반환하도록 수정하면 어떨까요? 추후 다른 구현체로 대체될 수 있으니 반환타입에 통일성을 가져가면 좋을 것 같아요!

2024-10-01 14:42 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
> +        }
저는 뷰모델이 생성될 때 스스로 어떤 일을 한다는 것이 객체지향적으로 조금 어색하게 느껴져서, 액티비티에서 뷰모델 함수를 호출하도록 구현하는 편이에요! (ex: 데이터 로드 함수 등등..) 
혹시 해음의 생각은 어떠신가요?? 개인적인 취향이니 꼭 반영하지 않으셔도 됩니다! 해음의 생각이 궁금해요

2024-10-02 09:01 UTC, aprilgom approved these changes
수고하셨습니다 해음

2024-10-02 09:01 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
> +                if (it.documents.isNotEmpty()) {
api에서 좌표가 한국이 아닐 때 에러코드가 아닌 null을 던지는건 생각하지 못했네요

2024-10-02 09:02 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
> +        LocationServices.getFusedLocationProviderClient(context)
변경했습니다!

2024-10-02 09:04 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
> +        }
변경하겠습니다!

2024-10-02 09:08 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
> +    }
[eba3d31](https://github.com/woowacourse-teams/2024-ody/pull/629/commits/eba3d31a6f1309998665722c130dba2b00e73660)

2024-10-02 09:10 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
> +    suspend fun getCurrentCoordinate(): Result<Location>
Result로 해야할거 같아요 서버에서 오는 값이 아니라서

2024-10-02 09:20 UTC, merged