feat: ODsay, GoogleMaps 호출 횟수 조회 API 구현
woowacourse-teams/2024-ody pull request #668
Opened 2024-10-04 09:01 UTC by eun-byeol

# 🚩 연관 이슈 
close #653 

<br>

# 📝 작업 내용
###  관리자 전용 API 2개 생성
- 노션 API 문서에 정리
- 오디세이, 구글 api 호출 시 DB에 저장하는 PR은 따로 올리겠습니다 #667 

### 외부 API 호출 횟수 저장하는 스키마 생성
- `client_type`, `date`과 복합 유니크 키 걸었습니다.
- 날짜별로 count 누적하도록 생성 로직 만들 계획입니다.

```sql
create table if not exists api_call (
    id bigint not null auto_increment,
    client_type varchar(255) check (client_type in ('ODSAY', 'GOOGLE_MAPS')) not null,
    `count` int not null,
    `date` date not null,
    primary key (id),
    unique (client_type, `date`)
);
```

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
### 관리자 검증
관리자인지 검증하는 로직은, 추후 제리와 협의 하에 추가할 예정입니다.

2024-10-05 09:33 UTC, coli-geonwoo requested changes
조조! 빠르게 구현해주셨네요!

역시 코드는 깔끔하고 테스트도 잘 작성해주셔서 크게 리뷰 남길 부분은 많지 않았어요.

다만 궁금했던 부분이 오늘 첫 호출을 언제 save 하는지에 대한 부분이었는데 관련해서 질문 남겨놓았으니 답변만 확인하고 approve 하겠습니다! (approve 해놓으면 PR에 잘 들어오지 않게 되더라구요;;)

고생많으셨습니다!!

2024-10-05 09:33 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/controller/ApiCallControllerTest.java
> +                .log()
합의 했던 컨벤션에 따라 한줄에 써도 좋을 것 같습니다!
```suggestion
                .then().log().all()
```

2024-10-05 09:33 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    public ApiCallCountResponse countOdsayApiCall() {
[질문] 처음 api call에 대한 저장은 어디에서 이루어지나요?

find를 통해 api call을 가져오려면 0회로 초기화된 오늘 날짜의 call이 table 내에 저장되어 있어야 할 것 같은데 어디서 저장이 이루어지는지 찾지 못해서요!

2024-10-05 09:33 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +                .get().extracting(ApiCall::getCount).isEqualTo(2);
체이닝과 extracting을 통해 연속적인 검증을 할 수도 있네요 😶 배워갑니다!

2024-10-05 09:33 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
조회 월의 시작일을 지정하려고 햇던 것 같은데 맞을까요?

저도 날짜 관련 라이브러리 다루는데는 미숙하지만 검색해보았더니 다음과 같은 방식도 있어서 공유합니다. 반영은 자유롭게 해주세요!

LocalDate startDate = LocalDate.now().withDayOfMonth(1); //오늘 월의 시작일로 초기화

아마 LocalDate.now()를 변수로 빼면 더 메서드 길이를 줄일수도 있을 것 같아요.

2024-10-05 09:53 UTC, coli-geonwoo approved these changes

2024-10-05 10:45 UTC, hyeon0208 approved these changes
#669 PR과 내용이 많이 겹치는 것 같아서
이 PR은 approve하고 #669 PR에 리뷰 남겼어요 🐥

2024-10-06 06:59 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/controller/ApiCallController.java
> +    @GetMapping("/admin/api-call/count/odsay")
두 api가 비슷해보이지만, 로직이 크게 달라요.
odsay는 `일별`로 호출 횟수를 집계하고, google은 `월별`로 해요.
물론 콜리 말처럼 endpoint는 하나로 하고 vendor별로 분기시켜도 되지만, 조회 기간이 다르기 때문에 다른 api로 보았습니다.

2024-10-06 07:00 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +                columnNames = {"client_type", "date"}
귀여운 🐹제리🐹 아이디어였습니다~👍

2024-10-06 07:07 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
(반영 완)
굿잡~~ 덕분에 배웠어요 감사합니다하~

2024-10-07 03:37 UTC, mzeong approved these changes
approve 남깁니다 ㅎㅎ 🐥🐥

2024-10-07 08:53 UTC, closed without merging