feat: Odsay, Google Maps 호출 시 DB 저장
woowacourse-teams/2024-ody pull request #669
Opened 2024-10-05 08:40 UTC by eun-byeol

# 🚩 연관 이슈 
close #667 

### ‼️ #668 에서 파생된 브랜치입니다. 코드가 꼬일 수 있어서, 두 PR 머지는 제가 하겠습니다!

<br>

# 📝 작업 내용

### Odsay, Google 호출 성공시 DB에 카운트 저장
- `RouteService`의 `calculateRouteTime()` 메서드 내 `client.calculateRouteTime()`가 성공하면, 해당 client의 count를 저장합니다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-05 09:51 UTC, coli-geonwoo approved these changes
조조! 이전 PR에서 남겼던 질문들을 이번 PR에서 해소했네요! 

이전 PR의 질문들도 수정해놓겠습니다!

정말 고생 많으셨어요 🙇

2024-10-05 09:51 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +        String className = routeClient.getClass().getSimpleName().toUpperCase();
리플렉션을 사용하셨네요! 미션에서 배운 개념들을 프로젝트에 적용해가며 체화하려는 모습 멋집니다 조조 👍 

저는 그런데 개인적으로 리플렉션을 선호하지는 않아요. OOP스럽지 않고 routeClient가 vendor 명을 담아야 한다는 컨벤션을 암묵적으로 전제하고 있는 느낌도 들어서요. 😓 

RoteClientImpl이 각각 ClientType을 들고 있는 건 어떤가요?

조금 더 메시지 중심으로 type 판별이 가능할 수 있을 것 같다는 개인적인 생각입니다.
조조의 생각은 어떠신가요?

2024-10-05 09:51 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall saveInitialCount(ClientType clientType) {
찾았던 초기 값 저장이 여기 있었네요! 다만 멀티 스레드에서 값이 덮어씌워지는 현상을 고민해보아도 좋을 것 같아요.

오늘 첫번째 호출상황에서 요청1과 요청2가 함께 들어왔을 때 한번에 increaseCountByRouteClient를  호출하면 두 call이 count되어야 하는데 saveInitialCount가 두번 호출될 수도 있을 것 같아서요!

2024-10-05 09:51 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +                () -> assertThat(actual).extracting(ApiCall::getCount).contains(1, 3),
사소한 부분이긴 하지만 containsExactly를 통해 엄밀성을 더해보는 검증도 좋을 것 같아요!

2024-10-05 09:51 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> Mockito.verify(googleRouteClient, Mockito.never()).calculateRouteTime(origin, target),
googleRouteClient와 어떠한 call도 없었음을 검증하는 검증문으로는 

verifyNoInteractions(Object... mocks)

을 활용해보아도 괜찮을 것 같아요!

Mockito.verifyNoInteractions(googleRouteClient)

2024-10-05 11:06 UTC, hyeon0208 requested changes
새로운 부분 추가되면서 전체적으로 수정되야할 부분도
꼼꼼하게 반영해주셨네요 역시 꼼꼼한 조조 👍 
여러 상황들을 고려해주신 것 같아요
간단한 제안 사항들 남기고 갑니다 😄

2024-10-05 11:06 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
[제안]
결국 이번달의 apicall 합계를 구하는 것이 핵심인 것 같은데

그렇다면 아래 처럼 의도가 분명해지도록 해보는건 어떨까요 ??
```
    LocalDate startOfMonth = LocalDate.now().withDayOfMonth(1);
    
    int totalCount = apiCallRepository.sumCountByClientTypeAndDateFrom(
        ClientType.GOOGLE, 
        startDate
    );
```

2024-10-06 07:23 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +        String className = routeClient.getClass().getSimpleName().toUpperCase();
(반영 완)
너무 좋은데요? `routeClient가 vendor 명을 담아야 한다는 전제`가 있는게 좋지 않다고 생각했어요.
구현체마다 필드로 갖고있는 것 보단, 새로운 구현체가 추가되었을때에도 강제하기 위해 `RouteClient` 인터페이스에 `getClientType()` 추가했습니다~

2024-10-06 07:27 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall saveInitialCount(ClientType clientType) {
동시성 문제 발생 가능성은 공감해요.
간단하게는 `synchronized` 키워드를 붙여놓을 순 있겠지만, 지금 다른 save 로직들도 동시성 처리가 안 되어 있더라구요.
반영하려면 전체적으로 동시성 처리를 하는 게 맞을 것 같은데, 콜리는 어떻게 생각하시나요?

2024-10-06 07:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +                () -> assertThat(actual).extracting(ApiCall::getCount).contains(1, 3),
(반영 완)
전혀 사소하지 않지만, 꼼꼼한 리뷰 감사합니다🙇‍♀️

2024-10-06 07:38 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> Mockito.verify(googleRouteClient, Mockito.never()).calculateRouteTime(origin, target),
(반영 완)
덕분에 배웠어요 감사해요👍

2024-10-06 07:40 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/service/ApiCallServiceTest.java
> +    @DisplayName("오늘 최초 API 호출이면 count=1 저장한다.")
(반영 완)
ㅋㅋㅋㅋ엠지엠지하시네~

2024-10-06 07:44 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
이 방법도 고려했었는데, count 초기화를 위한 insert 쿼리가 불필요하게 날라가서 하지 않았었어요.
로직상으로는 더 깔끔하고 의도가 드러나서 좋아요.

이에 대해 카키와 콜제는 어떻게 생각하시나요?

2024-10-06 08:17 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
이 방법은 어떤가요?
insert 시점을 뒤로 미룰 순 있을 것 같아요. 대신 update 시에도 save()를 호출하는게 어색할 순 있어요.

```java
    @Transactional
    public ApiCall increaseCountByRouteClient(RouteClient routeClient) {
        ClientType clientType = routeClient.getClientType();
        ApiCall apiCall = apiCallRepository.findFirstByDateAndClientType(LocalDate.now(), clientType)
                .orElseGet(() -> new ApiCall(clientType));
        apiCall.increaseCount();
        return apiCallRepository.save(apiCall);
    }
```
최초 호출 시)
```
Hibernate: select ac1_0.id,ac1_0.client_type,ac1_0.count,ac1_0.date from api_call ac1_0 where ac1_0.date=? and ac1_0.client_type=? fetch first ? rows only
Hibernate: insert into api_call (client_type,count,date,id) values (?,?,?,default)
```
재호출 시)
```
Hibernate: select ac1_0.id,ac1_0.client_type,ac1_0.count,ac1_0.date from api_call ac1_0 where ac1_0.date=? and ac1_0.client_type=? fetch first ? rows only
Hibernate: update api_call set client_type=?,count=?,date=? where id=?
```

2024-10-06 08:20 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    }
바로 아래에 답변 남겼습니다!

2024-10-06 08:24 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
저도 고민했던 부분인데, 확장성을 위해서 (시작, 종료)를 모두 받게 했어요. 추후 특정 기간을 조회할 수 있을 것 같아서요🤔
물론 지금 당장 필요한 로직은 아니지만, 이에 대해 카키는 어떻게 생각하시나요?

2024-10-06 08:31 UTC, eun-byeol commented on backend/src/test/java/com/ody/route/domain/ClientTypeTest.java
> +    public static Stream<Arguments> getRouteClientAndClientType() {
나이스 캐치~~ 지금은 삭제된 테스트지만 담에 유의할게요!

2024-10-06 08:39 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
제안한 코드에서 조회된 결과가 없을 때만 insert 쿼리가 호출되지 않나요 ??

조회된 결과 없으면 -> save() -> update count++
조회된 결과 있으면 ->  ApiCall 반환 -> update count++

2024-10-06 08:42 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
어드민 페이지에 호출 수, 최근 호출 시간 데이터 조회 + 특정 기간 조회까지 고려했다면
지금 구조데로 가는게 맞겠네요 👍

2024-10-06 08:43 UTC, hyeon0208 approved these changes
고생했어요 조조 ~ 이만 approve하겠습니다 😄

2024-10-06 12:03 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall saveInitialCount(ClientType clientType) {
데이터 일관성이 중요해보이는데
저는 메서드 단에 `synchronized`로 동기화를 적용하는 것 보다
DB단에서 `Lock`을 적용해주는 게 좋을 것 같아요

2024-10-06 13:57 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
맞아요. 조회된 결과 없을때만 insert 쿼리 호출되는데,
count=0 으로 insert 된 후에, 트랜잭션 닫힐 때 count=1로 update 쿼리도 호출돼요.

count=0 저장해서 DB 한번 찌르고, +1 해주기 위해서 update로 또 DB 찌르는게 불필요하다고 생각했어요.
처음부터 count=1로 저장하게 할 수 있으니까요!

2024-10-06 15:53 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +        String className = routeClient.getClass().getSimpleName().toUpperCase();
좋게 받아들여주시니 고맙네요 😄

2024-10-06 15:54 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall saveInitialCount(ClientType clientType) {
| 전체적으로 동시성 처리를 하는 게 맞을 것 같은데

동의합니다! 한번 동시성 이슈가 발생 가능한 메서드들 살펴보고 전체적으로 코드 리팩터링 함께 해보시죠!

2024-10-06 16:02 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
와우... 우선 조조! 직접 쿼리까지 스크랩해서 comment 남겨주셔서 감사해요. 덕분에 이해하기 쉬웠습니다.

저는 조조랑 카키 의견도 모두 합리적이라 생각하지만 다른 관점에서 0으로의 초기화 작업을 그날 최초 호출 시에 하는 것이 조금 어색하다고 느껴졌던 것 같아요.

현재 로직이라면 하루동안 호출이 한번도 없다면 그날의 call 기록은 남지 않아요. 그런데 요청 유무와 무관하게 그날의 기록은 저장되어 있어야 한다고 생각하거든요.

카키가 매일 오전 4시에 지난 약속을 soft delete하는 벌크성 쿼리를 예약해두었던 것 같은데, 이와 비슷하게 **매일 오후 11시 55분에 다음날 call 횟수를 0으로 초기화하여 저장해두는 건 어떨까요?**

이전과 다른 점은
- 최초 호출 유무와 무관하게 초기화 작업이 진행되며 DB에 call 횟수가 남는다
- 비즈니스 로직 안에서는 DB 상황과 무관하게 increaseCount 작업에만 집중할 수 있다.

이런 이점이 있을 것 같아요.

물론 추가적인 작업이 요구되는 만큼 조조가 요청한 현재 구조로도 좋다고 생각해요

2024-10-06 16:03 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        List<ApiCall> apiCalls = apiCallRepository.findAllByClientTypeAndDateBetween(
개인적으로는 시작, 종료 날짜 모두 파라미터로 받는 로직 좋다고 생각합니다 👍

2024-10-06 16:41 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
> @eun-byeol 코멘트 답변

최초 호출 시 새 데이터 저장 후 추가적인 update가 너무 빈번하게 호출된다면 문제가 있을 것 같은데
위 상황에서는 하루에 한번 최초 호출에 대한 데이터를 생성하기 때문에 부담이 없다고 생각해
코드 이해가 직관적인 방향으로 제안 드렸어요
제안 사항이니 판단은 조조 몫 ~ 😄

> @coli-geonwoo  코멘트 답변

호출이 없는 날을 조회했을 때 아무 값도 없는 것 보다는 호출되지 않았다는 것을 확인할 수 있으면 좋겠네요 👍

2024-10-07 03:57 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
제시한 방향들이 다 합리적인 것 같아요 

저는 개인적으로 기존 조조의 로직이 직관적이라 좋은 것 같아요 (조회해서 → 있으면 1 증가, 없으면 새로 생성)
정말 조조의 마음대로 반영하시면 될 것 같아요

```java
return apiCallRepository.findFirstByDateAndClientType(LocalDate.now(), clientType) // 조회해서
        .map(this::updateCount) // 있으면 1 증가
        .orElseGet(() -> saveInitialCount(clientType)); // 없으면 새로 생성
```

<br>

매일 일정 시간에 0으로 초기화해서 저장해두는 건 불필요하다고 느껴져요 초기화 작업과 업데이트 작업을 분리해야 할 필요성이 크지 않고 오히려 한 곳에 있어야 할 로직이 흩어진 느낌이 들어요! 스케줄링을 하는 것보다 insert 쿼리를 날리는 게 리소스가 적다고 생각합니다

2024-10-07 03:59 UTC, mzeong approved these changes
조조의 선택만 남아 approve를 남깁니다
이전 PR을 먼저 확인해서 이전 PR에 남긴 코멘트가 있습니다..!

2024-10-07 08:33 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    }
적극적으로 의견 남겨주셔서 감사합니다!
종합해보았을때, 기존 코드 그대로 남겨두겠습니다~ㅎㅎ

> 이와 비슷하게 매일 오후 11시 55분에 다음날 call 횟수를 0으로 초기화하여 저장해두는 건 어떨까요?

제리 의견에 동의해요. 또한, 호출이 없는 날을 저장해서 얻는 이점보다(주로 분석으로 쓰이겠죠?) 스케줄링을 거는 리소스가 더 크다고 생각해요. count를 증가시키는 로직을 위해, 스케줄링으로 초기화되는 작업이 선행되어야 하는 전제도 생기구요.

2024-10-07 08:54 UTC, merged