fix: 재촉알림을 보낸 사람 기준으로 nudgeNotification이 저장되도록 수정
woowacourse-teams/2024-ody pull request #671
Opened 2024-10-06 09:01 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #670

<br>

# 📝 작업 내용
- [ ] #670 

<br>

# 🏞️ 스크린샷 (선택)
ex)
재촉한 사람 : 방어진
재촉당한 사람: 김건우

**방어진이 재촉해요! 라는 메시지가 떠야 하는데 재촉당한 사람을 기준으로 로그 메시지가 구성됨**

![image](https://github.com/user-attachments/assets/456dab56-fa0d-4fcf-9689-443f4d306d78)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-06 10:58 UTC, hyeon0208 requested changes
역시 안드로이드 대표 주자 콜리
실사용을 바탕으로 버그를 찾아내셨네요 👍 
간단한 질문만 남겨봐요 😄

2024-10-06 10:58 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +                DirectMessage.createMessageToOther(requestMate, nudgedMate, nudgeNotification)
[질문]
nudgeNotification안에 nudgedMate가 포함되어 있는데 추가로 인자에 담은 이유가 있을까요 ??

2024-10-06 10:58 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    void sendSendNudgeMessage() {
[제안]
원래 메서드 이름이 `sendSendNudgeMessageMessage`이여서
`sendSendNudgeMessage`로 바꾸셨군요 👍 
한 번더 바꿔서 `sendNudgeMessage`로 바꿔야할 꺼 같아요 😂

2024-10-06 10:58 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +        ArgumentCaptor<Notification> captor = ArgumentCaptor.forClass(Notification.class);
오 ArgumentCaptor의 적절한 활용 👍

2024-10-06 14:26 UTC, eun-byeol approved these changes
실사용으로 QA 하는 콜리 멋진데?
간단한 리뷰 남겨서 approve 할게요

부대복귀라.. [부대복귀](https://school.programmers.co.kr/learn/courses/30/lessons/132266) 문제 추천드릴게요

2024-10-06 14:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
> +    public static DirectMessage createMessageToOther(Mate sender, Mate receiver, Notification recipientNotification) {
[제안]
인자로 받은 Notification을 사용하는 쪽이 type밖에 없는데, noti 대신 type을 인자로 받으면 어떤가요?

2024-10-06 14:26 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public static Notification createNudge(Mate nudgeRequestMate) {
[제안]
`requestMate`로 통일하면 어떤가요?

2024-10-06 18:04 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +                DirectMessage.createMessageToOther(requestMate, nudgedMate, nudgeNotification)
nudgeNotification 안에 nudgedMate가 담겨 있어서 찌른 사람이 아니라 찔린 사람이 notification 정보에 담겨 나온 것이 버그의 원인 이었어요.

즉, 리팩터링 이후에는 nudgeNotification에는 nudgedMate가 아닌 requestMate가 담기게 됩니다.

2024-10-06 18:04 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    void sendSendNudgeMessage() {
좋은 캐치네요! 꼼꼼하지 못했는데 잘 검토해주어서 감사해요 카키!

2024-10-06 18:06 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/message/DirectMessage.java
> +    public static DirectMessage createMessageToOther(Mate sender, Mate receiver, Notification recipientNotification) {
우선 현재 DirectMessage는 그렇지만 이후 로직이 수정될 때, Notification의 다른 정보가 필요할 수도 있다고 생각했어요! 저는 개인적으로 type만 받게 된다면 nudge message 로직에 DirectMessage 생성 로직이 너무 종속되는 것 같은데, 다른 분들 생각은 어떠신가요?

2024-10-06 18:06 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    public static Notification createNudge(Mate nudgeRequestMate) {
✅  반영해주었습니다

2024-10-07 05:27 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +                DirectMessage.createMessageToOther(requestMate, nudgedMate, nudgeNotification)
제가 인자를 착각했네요 😅
이미 담겨있는 정보인 requestMate를 넘기지 않고 `Notification`에서 꺼내서 사용하면 어떨까요 ??
```
public static DirectMessage createMessageToOther(Mate receiver, Notification senderNotification) {
```

2024-10-08 00:25 UTC, mzeong commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    void sendSendNudgeMessage() {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이 메서드 왜 이러나요?

2024-10-08 00:38 UTC, mzeong requested changes

2024-10-08 00:38 UTC, mzeong commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
>      }
[질문] requestMate = 재촉한 사람, nudgeMate = 재촉당한 사람인가요?
Notification에 저장하는 mate 정보는 알림을 받을 mate여야 하는데 그러면 nudgedMate를 넘겨줘야 하지 않나요?

2024-10-08 00:45 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
>      }
현재 nudge notification의 로그는 안드로이드에서 00이가 재촉해요로 구성됩니다

여기서 00이는 requestmate여야 합니다.

2024-10-08 08:25 UTC, mzeong approved these changes

2024-10-12 15:59 UTC, hyeon0208 approved these changes

2024-10-15 15:52 UTC, closed without merging