fix: 약속방 로그 목록 조회 시 입장 로그가 출발 알림 로그보다 먼저 출력되도록 수정
woowacourse-teams/2024-ody pull request #680
Opened 2024-10-07 13:38 UTC by hyeon0208

# 🚩 연관 이슈 
close #647 

<br>

# 📝 작업 내용

로직적으로는 입장 알림이 먼저 저장되고 출발 알림이 그 다음 저장되어
알림 목록을 조회했을 때 입장 알림 조회를 기대했으나
sentAt은 나노초를 갖고 있지 않아 정밀한 비교가 불가능해 의도하지 않은 순서대로 조회 결과가 나왔어요

따라서 알림 생성 시간으로 정렬하고자 했으나
MySQL의 DATETIME이나 TIMESTAMP로 생성된 시간은 기본적으로 나노초를 포함하고 있지 않아
MYSQL에서 최대로 지원해주는 나노초가 6자리를 포함하도록 수정 후  createdAt으로 정렬하여 조회하도록 수정했습니다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

테스트에서 사용중인 `FixtureGenerator`에 대해 이야기 나누고 싶은데
기존의 `FixtureGenerator`를 사용해서 Notification을 생성하려 했으나 원하는 날짜시간, 알림타입, 알림상태의 알림을 생성하는 
메서드가 없었어요
하지만 테스트 별로 필요한 다른 상태를 필요한 엔티티를 생성하기 위해 메서드가 점차 늘어나는 건
`FixtureGenerator`의 장점이 명확해지지 않는다고 생각했어요
현재 테스트 별로 객체들이 다른 상태를 가질 수 있는 부분들을 인자로 넘겨 생성되도록 
`findAllMeetingLogsBeforeThanEqual()` 테스트 메서드에만 적용을 해봤어요

개인적으로는 `FixtureGenerator`를 사용함으로써 수동으로 테스트 데이터를 생성하는 시간과 노력을 절약할 수 있지만
저희 테스트 코드에서 테스트 대상 객체가 여러 테스트에서 각기 다른 상태를 가져야 하는 경우가 많아보이는데
그 때마다 새로운 메서드를 추가하는 것은 오히려 시간과 노력이 더 들어간다고 생각해요
`FixtureGenerator` 메서드들이 파라미터를 넘기는 것으로 유연하게 객체가 생성되도록 하는 건 어떤가요 ?

2024-10-08 01:01 UTC, mzeong requested changes

2024-10-08 02:04 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/domain/BaseEntity.java
> +    @CreatedDate()
하하 실수 입니다 !

2024-10-08 02:18 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
> +            order by noti.createdAt asc
처음에 정렬 기준을 정해주는 것을 고려했었지만  createdAt으로 비교한 이유는 다음과 같아요
```
현재 시간 : 15:40 
-- 저장 순서 --
입장 알림 sentAt : 15:30
출발 알림 sentAt : 15:50

재촉 알림 sentAt : 15:40
```
위 상황이 주어졌다면 현재 시간 15:40분 이전이면 다음과 같이 로그가 나오겠죠
```
***가 입장했어요.
***가 재촉해요.
```
여기까지는 문제는 없지만 15:50분이 되면 조회되는 순서가 갑자기 바뀌게 되요
```
***가 입장했어요.
***가 출발할 시간이에요.
***가 재촉해요.
```

우외 같은 문제가 있어서 createdAt으로 정렬되도록 했는데
문제가 발생할 수 있는 부분에 좀 더 자세히 설명해주실 수 있을까요 ?? 😃

2024-10-08 09:55 UTC, hyeon0208 commented
이전에 말한 두 로직다 문제가 있을 것 같아서 sentAt에 나노초가 포함되도록 수정해봤씁니다 ~
추가적으로 로직으로 사용되는 Eta의 시간들은 나노초가 없이 비교되야하기 때문에 적용하지 않았고 네이밍을 새로해
타 시간 필드명들과 헷갈리지 않도록 변경해봤어요 😄

2024-10-08 10:24 UTC, mzeong commented on backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
> +            order by noti.createdAt asc
콜리가 13:00에 입장, 콜리의 DEPARTURE_REMINDER(sendAt=14:30, createdAt=13:00) 생성
조조가 13:10에 입장, 조조의 DEPARTURE_REMINDER(sendAt=14:00, createdAt=13:10) 생성

[14:00에 본 로그 화면]
```
콜리 입장 알림 13:00
조조 입장 알림 13:10
조조 출발 리마인드 알림 14:00
```

[14:30에 본 로그 화면]
```
콜리 입장 알림 13:00
조조 입장 알림 13:10
콜리 출발 리마인드 알림 14:30 (new) 
조조 출발 리마인드 14:00
```

즉시 발송하는 ENTRY, NUDGE와 같은 알림만 있으면 괜찮은데, 스케줄링 후 발송되는 DEPARTURE_REMINDER와 같은 알림도 있어서 위와 같은 문제가 발생할 수 있어요!

2024-10-09 11:30 UTC, eun-byeol approved these changes
고생하셨어요 카키~
덕분에 더 정확한 시점이 DB에 기록되겠네요👍

> FixtureGenerator 메서드들이 파라미터를 넘기는 것으로 유연하게 객체가 생성되도록 하는 건 어떤가요 ?

저도 이 방식을 선호하긴 해요. 다만, 콜제와 함께 얘기했던대로 기존 방식을 유지하되, 앞으로 추가되는 메서드에는 내부 구현이 드러나도록 메서드 이름을 구체화하도록 합시다~

2024-10-09 11:30 UTC, eun-byeol commented on backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
> +/*!ALTER TABLE notification MODIFY COLUMN updated_at timestamp(6);*/
주석 처리한 이유가 있나요?
+) 아래 불필요한 개행 제거해주세요~

2024-10-09 11:30 UTC, eun-byeol commented on backend/src/main/java/com/ody/eta/domain/Eta.java
> +    private LocalDateTime lastApiCallAt;
필드명 좋네요 이제 안 헷갈리겠네요👍

2024-10-09 11:30 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
>          Mate mate1 = fixtureGenerator.generateMate(odyMeeting, member1);
[제안] 변수명에 숫자는 빼도 좋을 것 같아요!

2024-10-09 11:30 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
> +    @DisplayName("특정 모임의 알림 발송 시간이 지나지 않은 알림을 생성 시간을 기준하여 오름차순으로 반환한다.")
[제안] `입장 로그가 출발 알림 로그보다 먼저 출력`에 대한 테스트 케이스로 보이지 않는데,
입장과 출발 알림이 거의 동시에 생성되는 케이스로 테스트하면 어떤가요?

2024-10-09 12:12 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
>          Mate mate1 = fixtureGenerator.generateMate(odyMeeting, member1);
변수가 하나라서 숫자가 필요없겠네요 !

2024-10-09 12:41 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
> +    @DisplayName("특정 모임의 알림 발송 시간이 지나지 않은 알림을 생성 시간을 기준하여 오름차순으로 반환한다.")
+ 이전에 사용했던 쿼리에 대한 테스트로 되어 있어서 테스트 명 수정 후
sentAt으로 정렬이되고 있어서 각 알림별로 sentAt을 LocalDateTime.now()로 초기화하도록 수정했어요

밀리초로 구분되고 각 알림이 저장될 때 항상 입장 알림, 출발 알림 순으로 저장되어 현재대로 테스트가 될 것 같은데
어떻게 생각하시나요 ?

2024-10-09 13:21 UTC, hyeon0208 commented
📌 추가 반영 사항

하나 놓친 부분이 있었어요
약속 참여 시 `calculateSendAt()` 에서 나노초를 제거하고 있어서
출발 알림이 나노초로 붙은 입장 알림 보다 항상 먼저 로그목록으로 조회될 수 있었는데
해당 부분 나노초를 포함하도록 수정해 
약속 참여 시 입장 알림이 먼저 저장되고, 출발 알림이 저장되는데 
출발 알림이 현재 시간 보다 전이라면 현재 시간으로 출발 알림을 전송 시간을 초기화하고
나노초로 전송되는 시점을 구분해 입장 알림이 먼저 로그 목록에 조회되도록 했습니다
[커밋 8115b4e](https://github.com/woowacourse-teams/2024-ody/pull/680/commits/8115b4eaf0e4bf1e68ed269bcb4c5b1daccce321)

<br>

추가로 `sendImmediatelyIfDepartureTimeIsPast()`에서 출발 알림을 찾지 못하는 문제가 발생했었는데
sentAt들은 나노초가 붙어 있는데 notification의 now() 메서드로 나노초가 제거된 시간을 equals 비교하고 있어서 찾질 못했어요
그리고 isNow() 메서드는 해당 테스트에만 사용되기도 해서 제거하고
나노초까지 비교할 것은 아니기에 초로만 비교하도록 isEqualToIgnoringNanos() 메서드를 사용해 테스트 수정했습니다

[커밋 ebad9dc](https://github.com/woowacourse-teams/2024-ody/pull/680/commits/ebad9dce387460998ca69212cab35429a957d3bc)

2024-10-10 01:45 UTC, mzeong commented on backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
> +/*!ALTER TABLE notification MODIFY COLUMN updated_at timestamp(6);*/
테스트 컨테이너 도입 좋은 것 같아요 😄

2024-10-10 01:45 UTC, mzeong commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
> +    @DisplayName("특정 모임의 알림 발송 시간이 지나지 않은 알림을 생성 시간을 기준하여 오름차순으로 반환한다.")
[제안] 매번 LocalDateTime.now() 해서 객체를 생성하는 대신 지역변수로 선언해두고 이를 이용하는 것은 어떤가요?

2024-10-10 02:11 UTC, mzeong commented
추가 반영 사항을 아래와 같이 이해했는데 맞나요?

### 문제 원인
departure reminder notification의 sendAt은 나노초가 제거됨 (calculateSendAt 때문)
따라서 entry가 먼저 저장되더라도 departure reminder <= entry으로 정렬됨

### 해결 방법
departure reminder의 sendAt도 나노초를 제거하지 않는 방향으로 수정함
이제 sendAt을 기준으로 의도한 대로 정렬 가능해짐!

2024-10-10 02:12 UTC, mzeong approved these changes

2024-10-10 02:40 UTC, coli-geonwoo approved these changes
카키, createAt 나노초를 붙이는 방법을 통해 일관성을 챙기셨네요!

리뷰드릴 부분들은 팀원들이 어느 정도 해주셔서 approve 합니다! 고생많으셨어요

2024-10-10 02:40 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +    @Column(nullable = false, columnDefinition = "TIMESTAMP(6)")
```suggestion
    @NotNull
    @Column(columnDefinition = "TIMESTAMP(6)")
```

2024-10-10 02:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +    void findAllMeetingLogsOrderOfEntryAndDepartureNotificationWhen() {
```suggestion
    void findAllMeetingLogsOrderOfEntryAndDepartureNotification() {
```

2024-10-10 02:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +        Member member = memberRepository.save(Fixture.MEMBER1);
```suggestion
        Member member = fixtureGenerator.generateMember();
        Meeting meeting = fixtureGenerator.generateMeeting(LocalDateTime.now()) //시간 기반으로 Meeting 만드는 generate method 하나 만들어줘도 좋을 것 같아요. (테스트 리팩터링 PR에는 있습니다.)
        
```

2024-10-11 01:50 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
> +    @DisplayName("특정 모임의 알림 발송 시간이 지나지 않은 알림을 생성 시간을 기준하여 오름차순으로 반환한다.")
지역변수로 선언해두면 각각 알림들이 동일한 밀리초를 가진 시간에 저장되서
위와 같이 매번 LocalDateTime.now()로 객체가 생성되도록 했습니다 !

2024-10-11 01:56 UTC, hyeon0208 commented on backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> +        Member member = memberRepository.save(Fixture.MEMBER1);
콜리 PR이랑 충돌날 부분이 많을 꺼 같은데 이부분은 충돌 해결하면서 반영할께요 !

2024-10-11 01:59 UTC, hyeon0208 commented
> 문제 원인
departure reminder notification의 sendAt은 나노초가 제거됨 (calculateSendAt 때문)
따라서 entry가 먼저 저장되더라도 departure reminder <= entry으로 정렬됨

> 해결 방법
departure reminder의 sendAt도 나노초를 제거하지 않는 방향으로 수정함
이제 sendAt을 기준으로 의도한 대로 정렬 가능해짐!

넵 로직적으로 사용하는 Eta의 시간 필드를 제외하고는 전부 정밀도를 부여해주기 위해 나노초를 제거 했는데
해당 로직에서는 TimeUtil을 사용하고 있어 기존과 동일하게 문제가 발생하겠더라구요
따라서 제리가 이해한데로 수정했습니다 ~ 👍

2024-10-11 08:16 UTC, hyeon0208 commented on backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
> +/*!ALTER TABLE notification MODIFY COLUMN updated_at timestamp(6);*/
v2에서 발생했떤 문제로 해당 주석 여부가 문제가 아니여서 주석제거했어요 😂

2024-10-11 08:28 UTC, merged