refactor: ViewModel의 LiveData를 Flow로 변경
woowacourse-teams/2024-ody pull request #695
Opened 2024-10-10 14:41 UTC by haeum808

# 🚩 연관 이슈 
close #640 

<br>

# 📝 작업 내용
- [x] AddressSearchViewModel
- [x] MeetingCreationViewModel 
- [x] LoginViewModel
- [x] SettingViewModel

MutableLiveData -> MutableStateFlow
LiveData -> StateFlow
MediatorLivedata -> collect
MutableSingleLiveData -> MutableSharedFlow
SingleLiveData -> SharedFlow

Flow로 다 마이그레이션 하면 MutableSingleLiveData 지워야 합니다!

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-11 05:44 UTC, aprilgom approved these changes
retrofit, repository도 flow로 바꾸자는 말을 했었는데,
대부분 한 번에 하나의 값을 불러오는 요청들이네요.
연속적으로 값을 불러오는 게 아닌 이상 flow를 쓰는 건 의미가 없었네요.
그냥 suspend인 채로 둬도 괜찮을 것 같습니다.

2024-10-11 05:44 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
> -import com.mulberry.ody.presentation.common.SingleLiveData
SingleLiveData야 고생 많았다

2024-10-11 05:44 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    .suspendOnSuccess {
아 여기 필요해서 빨리 머지해달라고 한 거였나요 😮

2024-10-11 05:44 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
> +                started = SharingStarted.WhileSubscribed(5000),
configuration change 대응 코드 맞나요

2024-10-11 05:46 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
> +                    .suspendOnSuccess {
맞습둥

2024-10-11 05:47 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
> +                started = SharingStarted.WhileSubscribed(5000),
맞습니다!

2024-10-11 09:00 UTC, kimhm0728 requested changes
고생하셨어요 해음 Flow 고수다 이제~!

2024-10-11 09:00 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
> +                started = SharingStarted.WhileSubscribed(5000),
5000 상수로 빼면 어떨까요?? 다른 ViewModel도 마찬가지입니다!!

2024-10-12 02:54 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
> +        val navigatedReason: SharedFlow<LoginNavigatedReason> get() = _navigatedReason.asSharedFlow()
<img width="1187" alt="스크린샷 2024-10-12 오전 11 54 05" src="https://github.com/user-attachments/assets/27521017-0c0b-4f7d-94e4-0313c85eee93">

ReOnly가 되어서 더 안전합니다! 즉 다른 인스턴스를 참조합니다!

2024-10-12 02:59 UTC, haeum808 commented on android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
> +        assertThat(actual).isTrue()
수정했습니다!

2024-10-12 02:59 UTC, haeum808 commented on android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
> +        viewModel.meetingHour.value = 17
테스트명에 맞게 변경했습니다!

2024-10-12 02:59 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
> +            val name = meetingName.value.takeIf { it.isNotEmpty() } ?: return null
훨씬 낫네용

2024-10-12 03:06 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
> +                started = SharingStarted.WhileSubscribed(5000),
수정했습니다! [2453241](https://github.com/woowacourse-teams/2024-ody/pull/695/commits/24532411069d64ab2d528b8cd0f39284f387f5b1)

2024-10-12 03:19 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
> +        val meetingMinute = MutableStateFlow<Int?>(null)
변경했습니다!

2024-10-12 08:49 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
> +        val navigatedReason: SharedFlow<LoginNavigatedReason> get() = _navigatedReason.asSharedFlow()
헉 대박이네요 ㄷㄷㄷㄷ 참고 자료까지 보내주셔서 감사합니다!! 유익하다

2024-10-12 08:50 UTC, kimhm0728 approved these changes
리뷰 반영된 것 확인했습니다!!!! 👍 👍 굿

2024-10-12 08:50 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
> +        val meetingMinute = MutableStateFlow(-1)
여기 매직넘버도 XXX_DEFAULT_VALUE 와 같이 상수로 빼도 좋을 것 같아요!

2024-10-12 11:32 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
> +        val meetingMinute = MutableStateFlow(-1)
수정했습니다! [25c5360](https://github.com/woowacourse-teams/2024-ody/pull/695/commits/25c53605e58c31ed9752631d4f64437f78e987ba)

2024-10-12 11:38 UTC, merged