design: 로그인 화면 새로운 디자인으로 수정
woowacourse-teams/2024-ody pull request #715
Opened 2024-10-14 08:12 UTC by aprilgom

# 🚩 연관 이슈

close #706

<br>

# 📝 작업 내용

- [x]  로그인 화면 새로운 디자인으로 수정
- [x]  9인치 로그인 화면 추가
- [x]  12인치 로그인 화면 추가

<br>

# 🏞️ 스크린샷 (선택)

차례대로 일반 폰, 9인치 태블릿, 12인치 태블릿입니다.
<img src="https://github.com/user-attachments/assets/ac0765ef-5872-42ae-bb8e-6b19429a5e29"  width="30%" height="30%"/> <br>
<img src="https://github.com/user-attachments/assets/d2a06937-3cf7-4ac6-900c-f99bec2c6b8d"  width="60%" height="60%"/> <br>
<img src="https://github.com/user-attachments/assets/55706e59-3068-4324-a524-1d6d1b5b864a"  width="90%" height="90%"/> <br>

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-14 14:33 UTC, haeum808 approved these changes
고생하셨습니다!

2024-10-15 06:31 UTC, kimhm0728 approved these changes
고생하셨습니다 차람!

2024-10-15 06:31 UTC, kimhm0728 commented on android/app/src/main/res/values/strings.xml
> +    <string name="login_welcome_prefix">간단하게</string>
피그마 상으로는 간편하게 입니다!

2024-10-15 06:34 UTC, kimhm0728 requested changes
<img width="389" alt="스크린샷 2024-10-15 오후 3 34 03" src="https://github.com/user-attachments/assets/b5ab168e-bf5f-4ebb-b573-3271d4d0d3bf">

그리고 이렇게 봤을 때는 화면 크기에 비해 문구의 startMargin이 너무 좁은 느낌이 드는데, 조금만 키우면 어떨까요? 9인치 12인치 모두 다요!
화면 크기에 따라서 아이콘 크기도 키워도 될 것 같아요!

2024-10-15 06:57 UTC, aprilgom commented on android/app/src/main/res/values/strings.xml
> +    <string name="login_welcome_prefix">간단하게</string>
앗 이런!

2024-10-15 06:57 UTC, aprilgom commented
좋습니다!

2024-10-15 07:37 UTC, aprilgom commented
<img src="https://github.com/user-attachments/assets/fa0662e9-1d38-4cfb-b474-bec12eb1bf00"  width="60%" height="60%"/> <br>
<img src="https://github.com/user-attachments/assets/9282ae27-3ac0-4597-9e7e-3029f2586a33"  width="90%" height="90%"/> <br>
로그인 글씨 크기와 마진 resize 했습니다!

2024-10-17 02:05 UTC, kimhm0728 approved these changes
고생하셨어요 차람~

2024-10-17 02:31 UTC, merged