fix/feat: flyway V5 DML이 적용되지 않는 문제 해결 + 테스트 컨테이너 적용
woowacourse-teams/2024-ody pull request #729
Opened 2024-10-15 08:08 UTC by hyeon0208

# 🚩 연관 이슈 
close #712 

<br>

# 📝 작업 내용

> flyway V5 DML이 적용되지 않는 문제 해결

flyway가 v3의 주석은 읽지만 v5의 주석을 읽지 못하는 문제가 있었어요
때때로 이런 문제가 있다고 하는것 같은데 근복적으로 주석이 문제여서 전체적으로 주석을 제거했어요

v3, v5 파일의 주석을 제거하면서 flyway 히스토리 내역을 지우고 다시 마이그레이션을 진행해야할 것 같아
같이 적용할 김에 v2 파일에 체크제약 조건 drop 구문을 추가해 로컬에서 실행할 때 체크제약 조건이 없어 제거가안되는 문제 또한 같이 해결하고자 했습니다.

<br>

> 로컬 환경과 dev, prod 환경의 DB 동일하게 세팅

flyway를 도입하게 되면서 dml 들이 mysql 종속적이여서 h2에선 실행이 안되는 등 많은 문제가 있었죠 😭
이 문제 발생을 줄이고자 동일한 mysql db를 사용하도록 수정했습니다.
각자 로컬에서 mysql 세팅을 하는 것은 귀찮을 테니 docker compose를 사용한 방식을 적용했는데요
이 또한 애플리케이션 실행 전마다 compose up하는게 귀찮잖아요 ..?
gradle-docker 플러그인을 적용해서 애플리케이션 실행 할 때 자동으로 compose up을 하고 실행할 수 있도록 적용해봤어요.
단 아래와 같은 간단한 설정이 필요합니다.

1. 인텔리제이 상단 바 -> 실행 -> 구성 편집 클릭
<img width="509" alt="image" src="https://github.com/user-attachments/assets/7ba4bbd9-17d1-45bc-9866-87934fa0fcd1">

2. 옵션 수정 클릭 -> 실행 작업 전에 추가 클릭
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/e00972e8-3667-47f2-a63c-4413202e2dc7">

3. +버튼 클릭 후 Gradle 작업 실행 클릭
<img width="375" alt="image" src="https://github.com/user-attachments/assets/128270fd-95d1-46b9-be31-896776b9eabd">

4. 다음과 같이 입력
<img width="323" alt="image" src="https://github.com/user-attachments/assets/32de294d-207a-48e2-bb0a-a3ef9d985a70">

5. gradle 작업이 추가된 것을 확인하면 적용 클릭
<img width="805" alt="image" src="https://github.com/user-attachments/assets/94d5a0c1-65f2-4606-ba9a-79463c4a7f39">

6. 이제 애플리케이션 실행할 때마다 알아서 docker compose up이 실행되고 애플리케이션이 실행됨.
<img width="706" alt="image" src="https://github.com/user-attachments/assets/12ff86b6-de67-4f86-9337-68851afe4a28">

<br>

> 테스트 컨테이너 도입

위와 같은 문제로 현재는 DB 종속적인 테스트는 없어서 문제가 없지만
똑같은 지옥을 겪는 것을 방지하고자 환경을 통일하면서 테스트도 통일할 수 있도록 테스트 컨테이너 추가했어요

<br>

> DatabaseCleaner 리팩토링

테스트 컨테이너와 `@DataJpaTest`를 같이 사용할 때 롤백이 정상적으로 이뤄지지 않는 경우들이 있어
테스트의 멱등성이 보장되지 않아 `BaseRepositoryTest`에도 DataBaseCleaner를  사용한 클린업작업을 추가했어요
추가로 DataBaseCleaner의 코드를 테이블 리스트를 찾아 반복문을 돌면서 TUNCATE하도록 리팩토링 했습니다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-16 05:37 UTC, eun-byeol requested changes
고생하셨어요 카키!! 블로그 보니 이해가 잘 됐어요.
덕분에 디비 환경 달라서 발생하는 문제는 없겠네요~
질문을 몇개 남겼는데, 간단하게만 주셔도 괜찮아요! 체크 못할 것 같아 RC 남깁니다!!

+) 참고사항
1. 테스트 돌리는데 약 30초가 걸린다는 점..
2. 테스트 성공했는데, 끝나지 않고 계속 돈다는 점
- 카키에게 듣기로, 커버리지 체크 & 리포팅용으로 사용하고 있는 jacoco 라이브러리 때문이라고 하던데, 없애는 건 좀 그렇겠죠...?

2024-10-16 05:37 UTC, eun-byeol commented on backend/src/main/resources/db/migration/V2__alter_notification_type_check.sql
> +ALTER TABLE notification ADD CONSTRAINT notification_chk_1 CHECK (`type` IN ('DEPARTURE_REMINDER', 'ENTRY', 'NUDGE', 'MEMBER_DELETION', 'ETA_NOTICE'));
[질문] drop 후에 add 다시 해주는 이유가 있을까요?

2024-10-16 05:37 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/DatabaseCleaner.java
> +        entityManager.createNativeQuery(FOREIGN_KEY_CHECK_OFF).executeUpdate();
오.. 훨씬 간단해졌네요!👍

2024-10-16 05:37 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/DatabaseCleaner.java
> +    @Transactional
[질문] 트랜잭션 어노테이션의 역할이 무엇인가요?
없애면 `TransactionRequiredException` 에러가 나는데 정확한 이유를 잘 모르겠어요ㅎㅎ

2024-10-16 05:37 UTC, eun-byeol commented on .github/workflows/backend-ci-dev.yml
> +#      TZ: 'Asia/Seoul'
[제안] 사용 안 하면 지워주세요~

2024-10-16 05:37 UTC, eun-byeol commented on backend/src/test/resources/mysql-container-init.sql
> +ALTER TABLE eta CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
[질문] flyway가 아닌 따로 sql 파일 관리하는 이유가 궁금해요!

2024-10-16 07:01 UTC, hyeon0208 commented on backend/src/main/resources/db/migration/V2__alter_notification_type_check.sql
> +ALTER TABLE notification ADD CONSTRAINT notification_chk_1 CHECK (`type` IN ('DEPARTURE_REMINDER', 'ENTRY', 'NUDGE', 'MEMBER_DELETION', 'ETA_NOTICE'));
v1 스키마가  실행될 때 type에 대한 제약조건 `notification_chk_1`이 생성되는데
이 제약조건을 지우고 새로운 타입 체크가 추가된 `notification_chk_1`를 추가해주기 위해서 drop을 추가했습니다 ~!

기존에 문제가 되지 않았던 이유는 dev, prod db에 접근해서 제약조건을 임의로 제거했기 때문이였어요

2024-10-16 07:03 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/DatabaseCleaner.java
> +    @Transactional
영속성 컨텍스트가 트랜잭션 범위 내에서 동작해야하기 떄문입니다 ~!

2024-10-16 07:04 UTC, hyeon0208 commented on .github/workflows/backend-ci-dev.yml
> +#      TZ: 'Asia/Seoul'
오프라인으로 설명해서 생략

2024-10-16 07:04 UTC, hyeon0208 commented on backend/src/test/resources/mysql-container-init.sql
> +ALTER TABLE eta CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
오프라인으로 설명해서 생략

2024-10-16 08:23 UTC, eun-byeol commented on backend/src/main/resources/application-local.yml
> +      ddl-auto: create-drop
app db도 테스트 컨테이너 도입해서 validate으로 바꾸는게 좋아요.
validate이어야 빠르게 오류 상황 잡고, 배포 후 오류 가능성을 줄일 수 있을 것 같습니다!

2024-10-16 12:35 UTC, hyeon0208 commented
### release V 2.0.0 

이야기 한데로 로컬 애플리케이션의 DB는 애플리케이션을 재시작해도 데이터 유지되도록 validate 옵션으로 변경했고
flyway로 dev, prod 마이그레이션 시 V2 파일부터 적용하도록 baseline-version 옵션을 2로 지정했어요

그리고 콜리 컴퓨터에서 테스트 컨테이너로 테스트 실행 시 너무 긴 시간이 소요된다는 점으로 h2를 사용한 테스트로 롤백해
테스트에선 flyway의 스크립트가 실행되지 않도록 수정했어요

2024-10-17 08:11 UTC, eun-byeol approved these changes
고생하셨습니다!! 덕분에 로컬 app에서도 운영과 동일한 환경에서 실행할 수 있겠네요~👍

2024-10-17 08:15 UTC, coli-geonwoo approved these changes
dev 서버 회생을 위해 우선 approve가 필요하다 하여 approve 후 코드 검토해보겠습니다!!

2024-10-17 08:31 UTC, merged

2024-10-17 08:32 UTC, hyeon0208 commented on .github/workflows/backend-ci-prod.yml
> +      TZ: 'Asia/Seoul'
모든 job들에 타임존 설정이 적용되고 있어서
시간 계산 로직으로 인한 사이드 이펙트 방지로 들어가면 좋을꺼같아요 !