feat: 서드파티 제어 및 조회 API 구현
woowacourse-teams/2024-ody pull request #732
Opened 2024-10-15 13:10 UTC by mzeong

# 🚩 연관 이슈 
close #718

<br>

# 📝 작업 내용

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-17 05:37 UTC, hyeon0208 requested changes
고생했어요 제리 ~
간단한 제안과 질문 남겨봐요 👍🏻

2024-10-17 05:37 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
>      private ApiCallService apiCallService;
ApiCallService의 호출 여부만 검증할 거라면 Mock 보단 Spy가 적합하겠네요 👍

2024-10-17 05:37 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall findOrSaveFirstByClientTypeAndDateBetween(ClientType clientType) {
[질문]
메서드명만 봐서는 날짜 파라미터를 넘겨서 원하는 날짜로 조회할 것이 예상되는데
추후에 조건 검색을 염둔 걸까요 ??

2024-10-17 05:37 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +    }
[제안]
리셋 전략이라기 보다는 리셋 날짜를 반환하는 것으로 봐서
변수명을 resetDate로 네이밍하는 건 어떤가요?

2024-10-17 08:19 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +    private final Function<LocalDate, LocalDate> resetStrategy;
[제안] 입출력이 같은 경우, `UnaryOperator` 사용할 수 있다고 하네요!
```suggestion
    private final UnaryOperator<LocalDate> resetStrategy;
```

2024-10-17 08:41 UTC, eun-byeol approved these changes
고생했어요! 제리🐹 state 필드명 의견 반영해주어 감사합니다!
간단한 질문 몇개 남겼습니다~!

2024-10-17 08:41 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/repository/ApiCallRepository.java
> +    Optional<ApiCall> findFirstByClientTypeAndDate(ClientType clientType, LocalDate date);
[질문] 파라미터 순서 바꾼 이유 궁금해요! 저는 date가 카디널리티가 더 높다고 보았어요

2024-10-17 08:41 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/controller/ApiCallController.java
> +    @GetMapping("/admin/api-call/count/{clientName}")
하나로 통합하셧네요👍👍

2024-10-19 13:34 UTC, mzeong commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +    }
[부분 반영] resetDate라고 이름 지으면 LocalDate 타입이길 기대할 것 같아서 함수형 인터페이스 타입이라는 것을 드러내고 싶어요
`resetDateOperation`이라는 이름으로 바꿔봤는데 이건 어떤가요? [e829021](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/e8290217377d92ee08b9dbb7021c4ad38bfd65f9)

2024-10-19 13:34 UTC, mzeong commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +    private final Function<LocalDate, LocalDate> resetStrategy;
[반영] 새롭게 배웠습니다!! [e829021](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/e8290217377d92ee08b9dbb7021c4ad38bfd65f9)

2024-10-19 13:42 UTC, mzeong commented on backend/src/main/java/com/ody/route/repository/ApiCallRepository.java
> +    Optional<ApiCall> findFirstByClientTypeAndDate(ClientType clientType, LocalDate date);
[반영] 저도 date의 카티널리티가 더 높다고 생각합니다!! `ApiCallRepository`에 `ClientType`가 먼저인 메서드가 두 개 있고, `Date`가 먼저인 한 개 있어서 저도 모르게 일관성을 맞추고 싶어져서 네이밍을 바꿔버렸어요.. [4c99d04](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/4c99d04912db953552682e2db45e81ef1c30e603)

2024-10-19 14:04 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall findOrSaveFirstByClientTypeAndDateBetween(ClientType clientType) {
다른 clientType이더라도 하나의 메서드로 일반화해서 토글용 api-call을 조회하기 위해서입니다!!

- odsay는 하루마다, google은 한 달마다 초기화됨
- 기존 api-call 정책은 ①odsay와 google 모두 하루마다 행을 추가해 count를 기록 + ②호출 0인 날은 행 생성을 안 하는 것임
- 외부 api 호출 설정 값은 초기화와 주기를 같이 해야 함 = 기존 api-call 정책과 깨지는 지점이 있음
- 그런데 새롭게 테이블을 만드는 것도, 기존 정책을 바꾸는 것도 하고 싶지 않았음 🤷‍♀️
- 따라서, 이번 달 중 가장 빠른 날의 state만 업데이트하고(② 때문) 나머지는 null로 유지하는 형태로 enabled 필드를 추가함
- 또 enabled를 조회할 때 하나의 일반화된 메서드로 조회하고 싶었음 (if 문, mapper 두기, 타입별로 메서드 만들기 다 싫었음)
- clientType별로 시작일만 다르게 해서 조회하면 일반화 가능해져 해당 메서드를 만들게 됨

메서드 이름의 의미를 담지 못하는 것 같아 `findOrSaveApiCallForToggleByClientType`으로 변경해주었습니다 [2535a22](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/2535a22d1840ff1365be09796191d1918eae1327)

2024-10-19 14:08 UTC, mzeong commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +    @DisplayName("특정 ClientType과 날짜 기간 내에서 가장 빠른 데이터를 조회한다.")
여기서 의미하는 `가장 빠른`은 최신이 아니라 오래된에 가까워요 (2일, 5일, 7일이라면 2일을 조회하는 게 목적입니다)
작성하면서도 가장 빠른이라는 게 의미 전달이 애매할 것 같았는데 좀 더 적합한 표현이 뭐가 있을까요 🤔

2024-10-19 14:14 UTC, mzeong commented on backend/src/main/java/com/ody/route/mapper/RouteClientMapper.java
> +                .filter(name -> name.name.equals(otherName.toLowerCase()))
[반영] 지금 보니까 name이 아닌데 `name.name`이라고 적어놨네요 [38ead55](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/38ead5568d8d176034903c430a0ac92dd15a8cca)

2024-10-19 16:54 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +    }
좋습니다 👍

2024-10-19 16:55 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +    private ApiCall findOrSaveFirstByClientTypeAndDateBetween(ClientType clientType) {
자세한 설명 감사해요 👍 현재 네이밍 괜찮은 것 같네용

2024-10-19 17:02 UTC, hyeon0208 approved these changes
반영사항 잘 확인했습니다 이만 approve 할께요
고생했어요 제리 ~ 👍

2024-10-19 17:02 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +    @DisplayName("특정 ClientType과 날짜 기간 내에서 가장 빠른 데이터를 조회한다.")
음 가장 빠른이 기간 내에서의 첫 번째를 의미하니 지금 네이밍도 좋은 것 같아요 👍

2024-10-20 07:40 UTC, coli-geonwoo approved these changes
제리! 조회 API에 많은 변화가 있었네요!

QA를 앞두고 있고, 제리 일정도 바쁜 만큼 의견 몇가지 남겨두고 approve 합니다!

고생많으셨어요!! 😄

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        Optional<ApiCall> apiCall = apiCallRepository.findFirstByDateAndClientType(LocalDate.now(), clientType);
이 부분 Optional 체이닝 활용해도 좋을 것 같아요!

```suggestion
        return  apiCallRepository.findFirstByDateAndClientType(LocalDate.now(), clientType)
        .orElseGet(~~)
```

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    private Boolean enabled;
[질문]

여기서 enabled를 Boolean으로 설정한 이유는 3가지 상태가 필요하다고 생각했는데 맞을까요?
null > 아직 한번도 호출 안됨
false > 오류가 나서 호출이 불가한 상태
true > 호출이 가능한 상태

여기서 null이 의미하는 상태가 필요한지 의문이 들어서 default 값을 true로 하고 boolean으로 설정하는 건 어떻게 생각하는지 궁금합니다!

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +
오! 좋은데요? 😮

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +    @DisplayName("특정 ClientType과 날짜 기간 내에서 가장 빠른 데이터를 조회한다.")
`기간내의 첫번째 호출 데이터` 제안해봅니다! ✋

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +        ApiCall secondApiCall = new ApiCall(clientType, 1, firstDay.plusDays(5));
여기서 first, second, third는 기간 순 정렬이네요!

변수를 count가 아닌 기간으로 정렬되었음을 파악하는 게 시간이 걸렸던 것 같아요. 기간 순으로 변수를 정렬해주어도 좋을 것 같습니다!

2024-10-20 07:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> verify(odsayRouteClient, times(0)).calculateRouteTime(any(), any()),
test 내에서 호출되지 않았음을 검증하는 컨벤션이

times(0)
never()
verifyNoInteraction

이렇게 3가지로 나뉘고 있는 것 같아서 추후 통일해보아도 좋을 것 같아요!

2024-10-20 11:10 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/ApiCallService.java
> +        Optional<ApiCall> apiCall = apiCallRepository.findFirstByDateAndClientType(LocalDate.now(), clientType);
[반영] [df1bdcc](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/df1bdcc4f99adb80d900acaf619cac63da2d7966)

2024-10-20 11:17 UTC, mzeong commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +    @DisplayName("특정 ClientType과 날짜 기간 내에서 가장 빠른 데이터를 조회한다.")
~오 채택합니다~ 취소합니다 기간 내 가장 먼저 삽입된 데이터라는 의미로 느껴질 수도 있을 것 같아요 
`가장 이른`이라는 표현으로 변경했습니다 [df1bdcc](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/df1bdcc4f99adb80d900acaf619cac63da2d7966)

2024-10-20 11:18 UTC, mzeong commented on backend/src/test/java/com/ody/route/repository/ApiCallRepositoryTest.java
> +        ApiCall secondApiCall = new ApiCall(clientType, 1, firstDay.plusDays(5));
[반영] [b88fba5](https://github.com/woowacourse-teams/2024-ody/pull/732/commits/b88fba51078fc60f1bdf469042ebe4fa49685d46)

2024-10-20 11:26 UTC, mzeong commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    private Boolean enabled;
google 같은 경우는 초기화는 한 달 주기인데 행은 매일 생깁니다. 그런데 enabled 설정은 한 달 내내 유지되어야 의미가 있을 것 같아요
따라서 그 달의 가장 이른 날짜를 가진 행의 enabled만을 이용해 한 달 동안의 호출 설정값을 관리하고자 할 때 
나머지 행들의 enabled 값이 true/false 값을 가지고 있지 않도록 null을 두었어요

아래와 같은 데이터들을 의도했습니다

| 날짜 | enabled | type |
| --- | --- | --- |
| 1일 | true/false | GOOGLE |
| 1일 | true/false | ODSAY |
| 2일 | null | GOOGLE |
| 2일 | true/false | ODSAY |
| 3일 | null | GOOGLE |
| 3일 | true/false | ODSAY |
| 4일 | null | GOOGLE |
| 4일 | true/false | ODSAY |

2024-10-20 12:01 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    private Boolean enabled;
제리, 많이 바쁘겠지만 답변에서 한가지 이해되지 않는 부분이 있어서 남겨둘게요.

enabled의 의미는 현재 네트워크 + 호출 제한량 을 고려했을 때 호출할 수 있음! 을 의미한다고 생각했는데요. 그런 차원에서 `enabled 설정은 한 달 내내 유지되어야 의미가 있을 것 같아요` 라는 문장을 잘 이해하지 못했습니다.

Google Api가 1일에는 잘될 수 있는데 2일 3일에는 server error를 반환한다면 현재 api 상태를 계속 update 해주어야 하는게 아닌가 하는 생각이 들어서요.

또한, 1일에 Google Api가 true/false로 초기화된다는 보장이 있는지 궁금합니다. 현재는 무조건 초기값 저장이 아니라 호출이 될 때 없으면 초기값 저장을 하는 것으로 로직을 짜둔 것으로 기억하는데요. 만약 매달 1일에 Google Api 호출이 없다면 어떤 방식으로 매달 1일의 enabled가 초기화가 되는지 궁금해요 🤔

2024-10-20 12:40 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +
개행을 좋아하는 콜리 ?

2024-10-20 12:50 UTC, mzeong commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    private Boolean enabled;
일단 enabled는 어드민 페이지 버튼을 통해 제어됩니다. 아직은 일정 호출 수를 초과하면 false가 되는 로직은 없어요

enabled 설정이 한 달 내내 유지되어야 한다는 의미는 일정 호출 수가 넘어서 enabled false 처리를 했다면 호출 수가 초기화되기 전까지(다음 달이 될 때까지) 다시 true로 변경될 이유가 없을 것이란 의미입니다 
(만약 odsay라면 일 1000건이 제한인데 이를 초과했다면 다음 날이 될 때까지는 호출을 해선 안 되는 상황을 생각하시면 될 것 같아요)

또한 1일에 초기화된다는 보장이 없습니다. 따라서 그 달의 가장 이른 날짜를 찾아 enabled 설정을 변경합니다
해당 달의 1일에 조회도 설정 변경도 이루어지지 않고, 2일에 설정을 변경한다면 2일의 enabled 설정이 변경됩니다

```
9월 데이터 → 1일, 2일, 5일, 10일, .. 존재 → enabled 설정은 1일 행을 가지고 이루어짐
10월 데이터 → 3일, 4일, ... 존재 → enabled 설정은 3일 행을 가지고 이루어짐
```

이해가 안 되는 부분 있으면 추가 질문 주세요

2024-10-20 12:51 UTC, mzeong commented on backend/src/main/java/com/ody/route/domain/ClientType.java
> +
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-10-20 13:20 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/ApiCall.java
> +    private Boolean enabled;
이해했습니다! 바쁜 일정에도 친절한 설명 감사해요 제리!

2024-10-21 06:25 UTC, merged