feat: 다크모드 적용
woowacourse-teams/2024-ody pull request #737
Opened 2024-10-16 04:50 UTC by haeum808

# 🚩 연관 이슈 
close #641 

<br>

# 📝 작업 내용
- [x] 다크 모드

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)
앱 실행시켜서 다크모드로 바꾸고 체크해주세요!

이 pr 머지된뒤 부터 디자인이 추가되면 피그마에 두 가지 디자인해주시고 다크테마 항상 생각해주세요!

2024-10-16 05:02 UTC, aprilgom commented
로그인화면 다크모드는 제가 해야겠군요

2024-10-16 05:03 UTC, aprilgom approved these changes
약속 리스트, 약속 만들기, 알림, eta까지 확인했습니다. 잘 만들어졌네요

2024-10-17 04:19 UTC, kimhm0728 requested changes
우왕 변경사항 많네요 정말 고생하셨습니다!!
라이트모드에서 기존 디자인과 달라진 부분, 다크모드에서 어색한 부분이 있어서 아래에 남겨두겠습니다.

<img src="https://github.com/user-attachments/assets/04fcb2dd-cac0-4582-a414-8a44436f23f4" width="200">

원래는 아이템 backgrouond 컬러가 흰색이에요!

<img src="https://github.com/user-attachments/assets/aef19c86-3dca-4c42-bbdc-fb015986732d" width="200">

TimePicker 시간 위에 보라색 부분 purple_800이 아닌 purple_300입니다!

<img src="https://github.com/user-attachments/assets/fc2b793c-96e7-4a57-a800-bb318b859f9c" width="200">

"를 입력해주세요" 텍스트 컬러가 너무 흐려서 잘 안보이는 것 같아요. 그리고 다른 입력폼의 텍스트 컬러는 white인데 여기만 gray라서 통일해주면 좋을 것 같습니다!

2024-10-17 07:28 UTC, kimhm0728 approved these changes
디자인 수정한 것도 확인했습니다! 고생했습니다~~!!

2024-10-17 08:25 UTC, merged