design: 로그 화면 초대 코드 복사하기 라이팅 변경
woowacourse-teams/2024-ody pull request #777
Opened 2024-10-20 12:56 UTC by haeum808

# 🚩 연관 이슈 
close #769 

<br>

# 📝 작업 내용
- [x] 복사하기 -> 클립보드 복사

<br>

# 🏞️ 스크린샷 (선택)
![Uploading Screenshot_20241020_215459.png…]()

<br>

# 🗣️ 리뷰 요구사항 (선택)
불필요한 파일도 삭제 했습니다!

2024-10-20 18:28 UTC, aprilgom approved these changes
복사!

2024-10-21 12:16 UTC, kimhm0728 requested changes
기존에는 해당 버튼을 누르면 클립보드로 복사되지 않고 카카오톡으로 바로 공유되었기 때문에 "복사하기"라는 문구가 조금 어색하게 느껴졌던 것 같아요. 그런데 이제는 클립보드로 복사하는 기능으로 대체될 것이니, "복사하기" 문구를 그대로 사용해도 괜찮을 것 같은데 어떠신가요??

2024-10-21 12:19 UTC, haeum808 commented
그렇네요 롤백 하겠습니다.

2024-10-21 12:26 UTC, kimhm0728 approved these changes
엄청 빠르시ㄴㅔ용 감사합니다
롤백해서 PR 제목도 바꾸신 건가요?? 👍👍👍👍

2024-10-21 12:31 UTC, merged