design: 오디 버튼 비활성화 토스트 메시지 변경
woowacourse-teams/2024-ody pull request #779
Opened 2024-10-20 13:38 UTC by haeum808

# 🚩 연관 이슈 
close #773 

<br>

# 📝 작업 내용
- [x] 오디 버튼 비활성화 토스트 메시지 변경

<br>

# 🏞️ 스크린샷 (선택)
[Screen_recording_20241020_223435.webm](https://github.com/user-attachments/assets/b9aea0a0-eaf6-4016-b75e-12931845395e)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-20 18:30 UTC, aprilgom approved these changes
수고하셨습니다 해음

2024-10-20 18:30 UTC, aprilgom commented on android/app/src/main/res/values/strings.xml
> +    <string name="meetings_entrance_unavailable_guide">아직 다른 사람의 위치를 확인할 수 없어요</string>
친구 -> 다른 사람
절교했나봐요

2024-10-21 12:13 UTC, kimhm0728 requested changes
> 오디? 버튼이 왜 활성화 안되는지 모르겠음 -> 30분 기준에 대한 설명 필요 🔥

위 UT 피드백도 같이 반영하기로 했는데, 문구를 조금 더 구체화하면 어떨까요? 30분 기준에 대한 설명을 넣으면 좋을 것 같은데.. 짧은 문장에 다 담기가 어렵긴 하네요.. 아니면 공모 받아도 좋을 것 같아요~!

2024-10-22 04:34 UTC, kimhm0728 approved these changes
바뀐 문구 좋네요!! 👍

2024-10-22 07:01 UTC, merged