feat: 약속방 나가기 기능 추가
woowacourse-teams/2024-ody pull request #792
Opened 2024-10-21 11:00 UTC by hyeon0208

# 🚩 연관 이슈 
close #791 

<br>

# 📝 작업 내용
약속방 나가기 기능 추가

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-22 01:44 UTC, coli-geonwoo requested changes
카키, 약속방 나가는 로직에서 mate 삭제까지는 완벽하게 구현한 것 같아요.

다만 약속방을 나가는 행위가 단순히 mate 삭제에서 끝나지 않고 조금 고려할 점이 있는 것 같아요.

1. mate에게 보내질 예정이었던 출발 알림 삭제가 필요합니다
2. mate의 ETA 삭제가 필요합니다
3. (선택) 합의가 필요하겠지만 입장알림이 있는 만큼 퇴장알림도 필요하다 생각합니다

3번은 논외로 두고 1과 2번에 대한 부분은 mate의 논리적 삭제 과정에서 함께 맞물려 있는 하나의 단위이므로 같이 삭제되어야 할 것 같아요!

2024-10-22 07:39 UTC, mzeong requested changes

2024-10-22 07:39 UTC, mzeong commented on backend/src/main/java/com/ody/mate/controller/MateController.java
> +    @DeleteMapping("/mates/{meetingId}/leave")
[필수] leave를 쓰지 않아도 나가기 라는 행위는 DELETE 메서드를 씀으로써 이미 나타내고 있다고 생각합니다! 

`DELETE /mates/{mateId}`가 적절할 것 같은데 안드에게 설명을 들어보니 현재는 (eta api를 통해서만 mateId를 얻을 수 있어서) mateId로 요청을 보내기 어렵겠네요 ☹️

`/mates/10/leave`는 10번 mate를 지운다로 해석될 것 같아 차라리 `DELETE /meetings/{meetingId}/mate` 제안합니다

2024-10-22 07:39 UTC, mzeong commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        mateRepository.deleteById(mate.getId());
콜리 리뷰의 연장선으로 mateRepository의 메서드가 아니라 mateService의 delete 메서드 로직 중 일부를 사용해야 할 것 같아요! 방 나가기도 로그로 남길지 아닐지에 따라 첫 번째 줄까지도 재활용될 수 있겠네요!

```java
@Transactional
public void delete(Mate mate) {
    notificationService.saveMemberDeletionNotification(mate); // TODO: noti 상위 서비스로 묶기
    notificationService.updateAllStatusPendingToDismissedByMateId(mate.getId());
    notificationService.unSubscribeTopic(mate.getMeeting(), mate.getMember().getDeviceToken());
    etaService.deleteByMateId(mate.getId());
    mateRepository.deleteById(mate.getId());
}
```

2024-10-22 07:43 UTC, eun-byeol requested changes
카키! 빠르게 구현해주셨네요👍 꼭 반영해야 하는 부분이 있어 RC 남깁니다!

다만, 나가기 기능에서 더 고려되어야 할 부분들이 있어요. (탈퇴하기와 비슷한 플로우 입니다.)
1. 나간 mate의 출발 알림이 다른 사람들에게 푸시 알림으로 가면 안 됩니다. -> notification에서 dismissed 처리가 되어야 함
2. 나간 mate에게 푸시 알림이 가면 안 됩니다. -> topic unsubscribe 해야 함

2024-10-22 07:43 UTC, eun-byeol commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        mateRepository.deleteById(mate.getId());
[필수] 지금 상황으로는 예약된 푸시 알림 `출발알림` 방 나가기 이후에 보내질 수 있습니다.
방 나갈때, 보내지지 않아야 하는 알림에 dismissed 처리가 되어야 해요.
```suggestion
        notificationService.updateAllStatusPendingToDismissedByMateId(mate.getId());
        notificationService.unSubscribeTopic(mate.getMeeting(), mate.getMember().getDeviceToken());
        etaService.deleteByMateId(mate.getId());
        mateRepository.deleteById(mate.getId());
```
나가기 전 notification:
<img width="394" alt="image" src="https://github.com/user-attachments/assets/af46e658-c6fe-4733-a3af-c6170d0e5174">

나간 후 notification:
<img width="398" alt="image" src="https://github.com/user-attachments/assets/ea787a74-c1b0-4c67-9c8e-22f2e0a5860b">

단, MateService의 `delete(Mate mate)`와 중복 코드가 있어서, 함께 개선하면 더 좋을 것 같아요
```java
    @Transactional
    public void delete(Mate mate) {
        notificationService.saveMemberDeletionNotification(mate); // 회원 삭제 noti 알림 추가만 상위에서 따로 처리하면 좋을 것 같아요.
        notificationService.updateAllStatusPendingToDismissedByMateId(mate.getId());
        notificationService.unSubscribeTopic(mate.getMeeting(), mate.getMember().getDeviceToken());
        etaService.deleteByMateId(mate.getId());
        mateRepository.deleteById(mate.getId());
    }
```

2024-10-22 07:45 UTC, eun-byeol commented
> (선택) 합의가 필요하겠지만 입장알림이 있는 만큼 퇴장알림도 필요하다 생각합니다

콜리가 언급한 퇴장 알림도 필요해 보여요. 다만, 이건 새로운 이슈로 파서 처리해도 될 것 같습니다!

2024-10-22 11:03 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        mateRepository.deleteById(mate.getId());
허허 단순히 나가기로만 생각했는데 
재참여한다해도 새로 정보를 입력하니 회원 탈퇴와 비슷한 처리를 해줘야겠네요
반영 완료 ~ !

2024-10-22 11:09 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        mateRepository.deleteById(mate.getId());
허허 단순히 나가기로만 생각했는데 
재참여한다해도 새로 정보를 입력하니 회원 탈퇴와 비슷한 처리를 해줘야겠네요
반영 완료 ~ !

[#952d7d80](https://github.com/woowacourse-teams/2024-ody/pull/792/commits/952d7d80b4068ce64ec0b5be213d03686bc2c86f)

2024-10-22 11:11 UTC, hyeon0208 commented
단순히 방에서 내보내기만 해버렸어요 😂
추가로 처리해줘야할 부분들 반영했습니다 ~ 

[추가반영내역](https://github.com/woowacourse-teams/2024-ody/pull/792/files/b1e89ff97cd8fbe8f2eaae6674664c167768183c..952d7d80b4068ce64ec0b5be213d03686bc2c86f)

2024-10-23 01:04 UTC, eun-byeol requested changes
리뷰 반영 잘 해주셨는데, 테이블 제약조건으로 테스트 실패해요.
실제 테스트도 꼭 챙겨주셔야 할 것 같습니다!
RC 남길게요!

2024-10-23 01:04 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationType.LEAVE,
[필수] 새로운 타입도 제약조건 추가해줘야겠네요!
테스트만으로 검증이 안 됐는데, 이 부분 테스트 추가해주거나, app 실행해서 실제 테스트 해봐야 할 것 같습니다~
```
2024-10-23 09:57:01.252 [ERROR] [http-nio-8080-exec-1] [017803c1-2da5-425e-85af-4d60de41ebfc] [o.h.e.jdbc.spi.SqlExceptionHelper] - Check constraint 'notification_chk_1' is violated.
Caused by: java.sql.SQLException: Check constraint 'notification_chk_1' is violated.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:194)
	... 160 common frames omitted
```

2024-10-23 03:37 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +    public void delete(Mate mate) {
반영완료 ~!

2024-10-23 03:48 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationType.LEAVE,
저는 이상하게 해당 애플리케이션 돌려도 터지질 않네요
mysql notification 테이블 상에서도 해당 제약조건이 없는걸 확인했는데도 왜 안터지느는 모르겠..
새로운 flyway 스키마 파일 추가했습니다 ~! 👍

2024-10-23 04:29 UTC, eun-byeol approved these changes
고생하셨습니다~👏

2024-10-23 04:29 UTC, eun-byeol commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationType.LEAVE,
확인 완료!
<img width="399" alt="image" src="https://github.com/user-attachments/assets/e83e6ed5-c92b-41bc-8d6c-530559d997e6">

2024-10-23 04:56 UTC, coli-geonwoo approved these changes
카키, 새로 이슈파기 이전에 빠르게 LEAVE 타입의 notification까지 구현해주셨네요!

몇가지 의견 남겼으니 선택적으로 반영해주세요~ 고생하셨습니다!!

2024-10-23 04:56 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        notificationService.saveMateLeaveNotification(mate);
[의견]

특정 타입의 notification을 저장하는 로직이 notificationService에 있어야 하는지 조금 의아한 것 같아요.

leave notification을 여기서에서 만들어주고 notificationService는 save만 해주면 다른 타입의 notification을 저장할 때에도 확장성 있게 활용될 수 있다고 생각하는데, 카키는 어떠한 생각이신가요? 🤔

2024-10-23 04:56 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +
방에서 나가기를 했을 때 LEAVE 메시지가 저장되는지 검증하는 테스트도 있으면 좋다고 생각합니다!

2024-10-23 05:21 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +
콜리 의견도 이해가 갑니다 !
이부분을 테스트하기 위해선 이 검증을 위해 해당 테스트가 NotificationService를 의존성 받아야하는데
알림 저장에 대한 부분은 NotificationServiceTest에서 검증하는게 단위 테스트 목적에 맞는 것 같아요
그렇다고 하기엔 모든 알림 타입들이 의도한 데로 잘 저장했는지를 테스트해야 테스트하는 의미가 생기는데
인자로 넘긴 값들에 대해 저장이 잘 됐는지도 테스트를 해야할까요 ?? 🤔

2024-10-23 05:25 UTC, hyeon0208 commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        notificationService.saveMateLeaveNotification(mate);
의문을 품을 수 있는 부분인 것 같아요
저도 동의합니다 ~ 👍 
다만 이 부분 개선하려면 다른 부분도 추가 수정이 필요해질 것 같아 따로 이슈 파는게 나을 것 같아요

2024-10-23 05:27 UTC, mzeong commented on backend/src/main/java/com/ody/notification/domain/Notification.java
> +                NotificationType.LEAVE,
저도 이상하게 안 터지더라구요

2024-10-23 05:28 UTC, mzeong approved these changes

2024-10-23 05:29 UTC, merged

2024-10-23 05:31 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +
mate service가 나간 이벤트를 E2E 관점에서 통합테스트 할 때 한번 같이 검증되었으면 좋겠다고 생각했던 것 같아요. 다만 단위 테스트 관점에서 NotificiationServiceTest만으로 충분하다 생각합니다. 또한, 단위 테스트를 통해 테스트의 검증 범위를 명확히 규정할 수 있으니 카키의 의견이 더 좋을 것 같네요!