fix: 출발 도착지가 가까운 경우 0으로 반환되는 문제 해결
woowacourse-teams/2024-ody pull request #794
Opened 2024-10-21 11:47 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #692 

<br>

# 📝 작업 내용
- [x] 출발 도착지가 가까운 경우 RouteTime을 0으로 반환하던 기존 로직을 10분으로 반환하도록 수정
    - [x]  OdsayResponseMapper에서 -98(700m 이내)임이 판단되면 정확한 상태 분기를 위해 소요시간 -1을 반환
    - [x] RouteService에서 시간을 계산하고 만약 시간이 -1(가까운 거리)일 경우 10L을 반환

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-21 14:40 UTC, hyeon0208 requested changes
콜리 빠르게 구현해주셨네요 ~
간단한 제안들 남기고 가봅니다 👍

2024-10-21 14:40 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
[제안]
RouteService는 추상화된 RouteClient들을 호출하고 있는데
해당 로직이 들어감으로써 구현체의 세부상황까지 알게 되어버렸다고 생각해요
RouteService는 그저 구현체만 호출하면 되도록
OdsayClient에서 responseToRouteTime() 내부에서 처리해 반환해주도록 하면 어떨까요 ?

2024-10-21 14:40 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> assertThat(result).isEqualTo(expectRouteTime),
[제안]
이 부분 테스트를 위해서 equals 오버라이딩이 필요할까 싶은데
assertThat(result.getMinutes()).isEqualTo(10) 가 아닌 이유가 있었을까요??

2024-10-21 16:26 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
저도 비슷한 생각이라 10L을 그냥 반환해줄까 생각해주었는데요.

그런데 그때 의논하다가 의견이 나왔던 부분은 routeClient가 계산한 값이 실제 대중교통 이용시간 10분인지, 거리가 가까워서 10분으로 바꾸어준 것인지 바깥에서는 구분할 수 없다는 점이었어요. 따라서 routeService 단에서 이를 처리하고자 하였구요. 

다만 로깅을 통해 responseToRouteTime에서 이 과정을 기록하면 -1 매직값이 아니더라도 로깅 트래킹이 되어 알 수 있을 것 같기는 해요. 다른 두분은 어떠신가요? 🤔

2024-10-21 16:27 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteServiceTest.java
> +                () -> assertThat(result).isEqualTo(expectRouteTime),
테스트를 위해 열어주었다기보다 VO의 논리적 동등성을 비교할 때 minutes로 비교하는 로직이 자연스럽다는 생각도 있었어요. 반대로 여기서 getter를 사용해야 하는 이유를 찾지 못해서 제가 생각했을 때 더 자연스러운 방향으로 오버라이딩을 해주었습니다.

2024-10-22 07:17 UTC, mzeong approved these changes

2024-10-22 07:17 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
10분을 OdsayClient 내부에서 반환하는 것으로 처리하게 되면 앞으로 새로운 Client가 생길 경우 그 Client에서 또 10분을 반환하는 코드를 작성하게 될 거라고 생각해요. 10이라는 상수를 각 Client로 분산하기보다 RouteClient를 호출하는 RouteService에서 관리하는 것이 로직이 집중되는 것 같아요

추가로, 로깅이나 디버깅을 하면 실제 대중교통 10분인지, 거리가 가까워 10분인지 확인할 수 있겠지만 
거리가 계산할 수 없을 정도로 가깝다면 10분을 반환하자는 것은 우리 서비스 정책이므로 
각 Client가 가져야 할 책임이 아니라는 관점에서 문제가 해결된다고 보여지지 않아요
단순히 10분이 반환된 원인을 확인할 수 있다 차원이 아니라 10분 반환 관련 문제가 생겼을 때 어느 클래스에 들어가서 문제를 해결할 것인가가 명확해질 수 있는 곳에 로직이 위치해야 한다고 생각합니다!

아래 3가지 정도 방안이 괜찮다고 생각합니다. (2번이 현재 코드)
1. RouteClient에서는 거리가 가까워 계산할 수 없는 경우 커스텀 예외 발생 
RouteService에서 해당 커스텀 예외를 캐치하면 10분  반환
2. 커스텀 예외 대신 매직값(-1) 사용 
3. RouteClient 추상 클래스 두기 (10분 반환 로직을 RouteClient가 담당하지만 분산되지는 않게)

2024-10-22 08:13 UTC, eun-byeol approved these changes
구현 전에 여러 의견 들어보고 설계해주셔서 감사합니다👍
간단한 리뷰 남겨서 approve 하겠습니다!

2024-10-22 08:13 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
제리 의견에 동의해요. 
예외를 던지는 방식보단 2, 3번이 좋을 것 같아요.

2024-10-22 08:13 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        if (calculatedRouteTime.isSame(-1L)) {
[제안]
`-1`도 상수로 관리하면 어떤가요?

2024-10-22 09:35 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
다수의 의견에 따르는데 의문이 있어서 코멘트 남겨봅니다 ~

> 0분을 OdsayClient 내부에서 반환하는 것으로 처리하게 되면 앞으로 새로운 Client가 생길 경우 그 Client에서 또 10분을 반환하는 코드를 작성하게 될 거라고 생각해요.
10이라는 상수를 각 Client로 분산하기보다 RouteClient를 호출하는 RouteService에서 관리하는 것이 로직이 집중되는 것 같아요

지금 구조가 구현체의 추가로 RouteService에서 분기 처리 메서드가 늘어나지 않나요 ??
Odsay에서만 700m 이내일 때 -98이라는 응답을 줘서 10으로 처리를 하고 있는 걸로 이해하고 있는데
오히려 Odsay 구현체에서 이를 처리하는 게 로직이 집중되어 있는 것 같아았어요

> 추가로, 로깅이나 디버깅을 하면 실제 대중교통 10분인지, 거리가 가까워 10분인지 확인할 수 있겠지만
거리가 계산할 수 없을 정도로 가깝다면 10분을 반환하자는 것은 우리 서비스 정책이므로
각 Client가 가져야 할 책임이 아니라는 관점에서 문제가 해결된다고 보여지지 않아요
단순히 10분이 반환된 원인을 확인할 수 있다 차원이 아니라 10분 반환 관련 문제가 생겼을 때 어느 클래스에 들어가서 문제를 해결할 것인가가 명확해질 수 있는 곳에 로직이 위치해야 한다고 생각합니다!

Odsay가 거리가 계산할 수 없을 정도로 가까워 특정 응답을 반환하는데
이를 10분으로 반환하는 것은 우리 서비스 정책이지만 특정 Client에 대한 정책인 상황이고
10분 반환 관련 문제가 생겼을 땐 해당 문제가 있는 클라이언트가 Odsay임을 인지하고 있기에
해당 클래스에 들어가서 문제를 해결하지 않을까? 생각했습니다

2024-10-22 09:35 UTC, hyeon0208 approved these changes
코멘트 확인해서 apporve 합니다 고생했어요 콜리 ~

2024-10-23 04:24 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
두 의견 모두 다 이해가 가고, 각자 바라보는 `가까울 경우 오류를 반환하는 client가 얼마나 되는가` 에 대한 입장 차이가 있는 것 같아요.

다른 client에서도 가까울 경우 오류를 반환하는 것이 보편적이라면 -> service 단에서 일관적으로 -1 매직값에 대한 처리를 해주는 것이 합리적
Odsayclient에서만 특수적으로 가까울 경우 오류를 반환하는 것이라면 -> service 단 처리가 OdsayClient에 대한 특수한 로직이 드러난 결과라고 생각할 수 있음

그러나, 제가 Tmap api를 찾아보았을 때에도 가까울 경우 에러를 반환하도록 되어있었어요. 이전에 폭포가 추상적으로 설명해준 대중교통 최단경로 탐색 알고리즘에 있어서도 가까운 두 점간의 거리에서 오류가 반환될 수 밖에 없다고 하였고요! 따라서 일정 거리 이내일 때 에러를 반환하는 것은 대중교통 api에 있어서는 보편적인 현상이라 생각하고 오히려 google api가 특수하다고 생각합니다.

둘째로, 10으로 반환하도록 하는 것이 서비스 로직인지는 저도 조금 의문이 있기는 해요.

단순 mapping 로직으로 바라본다면 카키의 생각이 맞는 것 같고,
mapping 이상의 view에 반환되는 것을 의식한 서비스 정책이라 생각하면 제리나 조조의 생각도 맞는 것 같네요.

다만 서비스 상 유의미한 값이라기보다 view를 의식한 정책인 것 같아서 저는 mapping 로직이 맞는 것 같습니다. 오히려 안드쪽에서 처리해도 좋은 mapping이라 생각하기도 해요.

2024-10-23 04:31 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        RouteTime routeTime = routeService.calculateRouteTime(originCoordinates, targetCoordinates);
✅ 반영 완료!

2024-10-23 04:32 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        if (calculatedRouteTime.isSame(-1L)) {
RouteTime이 public 상수로 들고 있도록 하겠습니다.

2024-10-23 04:34 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
@hyeon0208 

routeClient가 거리가 가까워 계산할 수 없는 경우에 대한 대응까지 책임지지 않도록 책임을 분리시킨 것이므로
별도의 mapper가 필요한 것은 맞습니다. 그러나 `700m라는 거리를 기준으로 10분이라는 추정치를 응답하자`라는 서비스 정책이 바뀐다고 했을 때 odsayRouteClient 내부로 들어가서 변경하는 것은 너무 내부 구현까지 들어가는 것 같아요

- 새로운 Client도 700m 이내는 계산할 수 없다면? odsay, 새로운 Client에 동일한 10분 반환 로직 분산
- 새로운 Client와 odsay의 계산 불가 거리가 다르다면? 처음에는 두 Client가 각각 10분, x분 반환 로직 가지고 있어도 ㄱㅊ
추정치 산정 서비스 정책(70m 당 1분)이 바뀌게 되었을 때 각 Client에서 변경 필요, 변경 지점 분산
제 생각에는 추정치에 대한 서비스 정책이 바뀔 때 odsay만 바뀔 것 같지 않아요 
 
내부 구현을 다 아는 입장에서는 routeClient의 책임을 어디까지로 보는지 관점에 따라 다를 것 같아요

2024-10-23 04:37 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
@hyeon0208 

routeClient가 거리가 가까워 계산할 수 없는 경우에 대한 대응까지 책임지지 않도록 책임을 분리시킨 것이므로
별도의 mapper가 필요한 것은 맞습니다. 그러나 `700m라는 거리를 기준으로 10분이라는 추정치를 응답하자`라는 서비스 정책이 바뀐다고 했을 때 odsayRouteClient 내부로 들어가서 변경하는 것은 너무 내부 구현까지 들어가는 것 같아요
(담당 개발자가 아니라면 odsay client 내부 구현까지 파악하고 있지 않을 것 같아요~)

- 새로운 Client도 700m 이내는 계산할 수 없다면? odsay, 새로운 Client에 동일한 10분 반환 로직 분산
- 새로운 Client와 odsay의 계산 불가 거리가 다르다면? 처음에는 두 Client가 각각 10분, x분 반환 로직 가지고 있어도 ㄱㅊ
그러나 추정치 산정 서비스 정책(70m 당 1분)이 바뀌게 되었을 때 각 Client에서 변경 필요, 변경 지점 분산

odsay, google만 사용하는 현재 상황만 고려하기보다 확장용이성을 기준으로 봤을 때의 의견입니다

2024-10-23 04:37 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/domain/RouteTime.java
> +    }
-1L이라는 long 형태의 minute과 비교하면 좋을 것 같아서 만들어주었습니다. equals는 같은 RouteTime과 비교해야 하므로 항상 minute를 RouteTime으로 래핑해주어야 했거든요.

다만 -1이라는 값을 RouteTime 상수로 관리하도록 하면서 자연스럽게 없어졌습니다.

2024-10-23 05:02 UTC, mzeong commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +    }
@coli-geonwoo 저는 10분이 700m를 걸어가는데 대략 10분 정도가 걸려서 10분으로 응답하자는 정책이 생겼다고 이해했어요. 안드에서 `10분 이내`라는 표현을 쓰는 것은 정확도 등 다른 이유인 줄 알았는데, 이 부분을 의식해서 안드-백이 10분이라 협의한 거였나요??

2024-10-23 05:44 UTC, merged