refactor: 약속 시간 이후 30분까지 nudge가 가능하도록 수정
woowacourse-teams/2024-ody pull request #798
Opened 2024-10-21 13:05 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #795 

<br>

# 📝 작업 내용
- [x] #795 

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

- nudge에 대한 검증조건을 추가하면서 느낀 건데 nudge에 대한 조건이 조금 커지면서 이제 분리할 시기가 온 것 같아요. 현재는 모든 nudge 관련 도메인이 mateService 내에 녹아있는데 어떻게 분리하면 좋을지 의견 받습니다. 저는 개인적으로 etaService 안으로 넣어주거나, nudgeService를 새로 만드는 것도 방법이라 생각합니다. 다만 이 경우 mateSevice가 nudgeService를 가지게 되므로 의존성이 과해진다는 문제가 생길 수도 있을 것 같아요.

2024-10-21 15:05 UTC, hyeon0208 requested changes
> nudge에 대한 검증조건을 추가하면서 느낀 건데 nudge에 대한 조건이 조금 커지면서 이제 분리할 시기가 온 것 같아요. 현재는 모든 nudge 관련 도메인이 mateService 내에 녹아있는데 어떻게 분리하면 좋을지 의견 받습니다. 저는 개인적으로 etaService 안으로 넣어주거나, nudgeService를 새로 만드는 것도 방법이라 생각합니다. 다만 이 경우 mateSevice가 nudgeService를 가지게 되므로 의존성이 과해진다는 문제가 생길 수도 있을 것 같아요.

MateService에 있는게 어색한 것 동의합니다 👍 
etaService도 도착예정시간 관련 도메인의 비즈니스 로직을 처리하기에 어색하다 생각하고
NudgeService를 만들기엔 알림 관련 기능인데 알림과 분리되어 처리되는 게 어색하다 느껴졌어요
개인적으로는 알림 도메인에 대한 기능이라 NotificationService 내에 있어야 자연스럽다고 생각하는데
이미 NotificationService 내부 로직이 복잡하기도 해서 추후에 프로젝트 코드 전체적으로 유지보수 용이하게  리팩토링하면 좋을 것 같아요

이에 대한 콜리의 생각도 듣고 싶어 RC 남깁니다 ~

2024-10-21 16:30 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +                    () -> Mockito.verifyNoInteractions(fcmPushSender)
내부 구현을 알고 있는 화이트박스 테스트 입장에서는 에러가 발생하면 pushSender 호출이 되지 않는 것이 당연하게 느껴지겠지만, 내부 구현을 모른다는 블랙박스 테스트를 전제로한다면 로직 순서에 따라 fcmPushSender가 호출된 이후에 에러가 발생하면 호출이 되는 시나리오가 있습니다.

여기서는 상태와 행위 검증을 둘다 하고 싶었는데요.
- nudge를 호출시 에러가 발생하는 `상태`에 대한 검증과
- 그 과정에서 fcmPushSender가 호출되지 않는 다는 '행위'에 대한 검증이 필요하다 생각했습니다.

2024-10-22 08:41 UTC, eun-byeol approved these changes
고생하셨습니다 콜리🥦 간단한 리뷰 남겨서 approve 할게요. 계속 리팩터링을 추후로 미루게 되지만,, 데모데이 이후에 가능하다면 다같이 집중적으로 설계하고 작업하면 좋을 것 같아요.

> nudge에 대한 검증조건을 추가하면서 느낀 건데 nudge에 대한 조건이 조금 커지면서 이제 분리할 시기가 온 것 같아요. 현재는 모든 nudge 관련 도메인이 mateService 내에 녹아있는데 어떻게 분리하면 좋을지 의견 받습니다. 저는 개인적으로 etaService 안으로 넣어주거나, nudgeService를 새로 만드는 것도 방법이라 생각합니다. 다만 이 경우 mateSevice가 nudgeService를 가지게 되므로 의존성이 과해진다는 문제가 생길 수도 있을 것 같아요.

`nudgeService`로 분리하자는 의견입니다.
nudge 관련 로직을 다른 서비스들에 넣기에는 이미 다른 서비스도 커진 상태라 책임 분리가 잘 안되지 않을까요?
> 이 경우 mateSevice가 nudgeService를 가지게 되므로 의존성이 과해진다는 문제

이렇게되면, mateService를 더 쪼개거나, mateService보다 더 상위 서비스로 만들어야 할 것 같아요.

2024-10-23 01:40 UTC, mzeong approved these changes
저도 분리의 필요성을 느낍니다~ 푸시 알림을 담당하는 서비스를 만들고, 필요하다면 nudge 서비스에 책임을 분담하는 형태는 어떤가요?

2024-10-23 02:10 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +        return !TimeUtil.nowWithTrim().isAfter(nudgeEndTime);
네, 그리고 약속 시간과 다른 시간의 선 후 관계를 판단할 때 나노초 단위가 영향을 주지 않았으면 했어요.

예를 들어 오늘 오후 11시와 오후 11시 1나노초가 다른 시간으로 판단되어 선후관계가 나뉘어지는 경우를 제하고 싶었습니다

2024-10-23 02:10 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +        @DisplayName("약속 30분 이후에는 mate를 재촉할 수 없다")
**✅ 반영 완료**

반영해주었습니다!

2024-10-23 02:10 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> +            Meeting availableNudgeMeeting = fixtureGenerator.generateMeeting(LocalDateTime.now().minusMinutes(30L));
✅ 반영 완료

2024-10-23 02:27 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/mate/service/MateService.java
> +    }
✅ 반영 완료

카키도 비슷한 의견을 주었는데요.

api를 직접 쏠 수 있는 것이고 서비스 정책 상 필요한 로직이라 생각하여 추가해주었습니다

2024-10-23 02:35 UTC, coli-geonwoo commented
일정 상 오늘 안에 Merge가 되어야 해서 우선 구조적인 리팩터링은 각 의견 수렴 후 새로운 이슈파서 마무리하겠습니다.

현재 의견들이 조금 다른 부분이 있고 서로가 이야기하는 구조가 같은지 모르겠어서 합의가 필요할 것 같아요

카키 : 알림 도메인에 대한 기능이라 NotificationService 내에 있어야 자연스럽다고 생각
제리 : 푸시 알림을 담당하는 서비스를 만들고, 필요하다면 nudge 서비스에 책임을 분담하는 형태
조조 : nudgeService로 분리하고 mateService가 nudgeService를 가지고 있는 형태

저는 Nudge라는 도메인이 더 커질 가능성이 있는 주요 기능의 위치까지 올랐다고 생각해서, nudgeService를 만들자는 입장인데요. 유저 의견 중에 다양한 공격(?) 방법을 만들자는 의견들을 바탕으로 확장성을 생각해보았을 때, Nudge라는 하나의 서브 도메인으로 바라보아도 될 정도의 큰 기능이 되었다고 생각했습니다.

2024-10-23 03:09 UTC, hyeon0208 approved these changes
답변까지 들어서 approve할께요 ~ 👍

2024-10-23 03:20 UTC, merged