refactor: 알림 누르고 뒤로가면 약속 목록으로 가게 변경
woowacourse-teams/2024-ody pull request #800
Opened 2024-10-21 14:09 UTC by haeum808

# 🚩 연관 이슈 
close #750 

<br>

# 📝 작업 내용
- [x] 앱이 꺼져있을 때 알림 누르고 입장하고 뒤로가면 약속 목록으로 가게 변경

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-10-22 01:32 UTC, aprilgom approved these changes
굳굳

2024-10-22 05:08 UTC, kimhm0728 requested changes

2024-10-22 05:08 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
> +            startActivity(MeetingsActivity.getIntent(this))
알림을 클릭해서 앱을 진입하는게 아닌, Meetings -> MeetingRoom으로 들어가는 경우에도 Meetings를 재활용하지 않고 계속해서 재생성하고 있어요. 그래서 아래 영상처럼 MeetingRoom에서 뒤로 가기를 눌러 Meetings에 진입하면 깜빡이는 현상이 있고 자연스럽지 못합니다.

https://github.com/user-attachments/assets/047d8ba6-6bc3-4917-95fd-f81e862fb0f9


반면에 기존에는 깜빡이는 현상이 없고, 사용자가 스크롤한 곳을 기억하고 있어서 자연스러워요.

https://github.com/user-attachments/assets/df659768-c1d8-4767-9158-4e441b5244d1

Meetings를 finish, startActivity하는 방식이 아니라, 알림을 클릭한 경우 처음부터 백스택에 Meetings-> MeetingRoom 순서로 쌓아두면 어떨까요? 
구현 방식은 해음이 자유롭게 판단해주셔도 괜찮지만, MeetingsActivity를 계속해서 재생성하는 방식은 좋지 않은 것 같습니다.
수정 제안 -> FCMNotification의 getPendingIntent() 함수

2024-10-22 09:54 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
> +            startActivity(MeetingsActivity.getIntent(this))
수정했습니다! [af626ba](https://github.com/woowacourse-teams/2024-ody/pull/800/commits/af626ba1b3f27bf8f2083047d2f6d07c4745c2b4)

2024-10-23 02:11 UTC, kimhm0728 approved these changes
우왕 `TaskStackBuilder`이라는게 있군요 리뷰 반영해주셔서 감사해요!! 새로운 기술 학습하느라 고생했겠네요 ㄷㄷ

2024-10-23 02:16 UTC, merged