feat: 초대 코드 복사 bottom dialog
woowacourse-teams/2024-ody pull request #84
Opened 2024-07-23 14:50 UTC by haeum808

# 🚩 연관 이슈 
close #32 

<br>

# 📝 작업 내용
- [x]  복사 (공유 버튼)
- [x]  복사 시 snackbar message
- [x] bottom dialog 띄우기

<br>

# 🏞️ 스크린샷 (선택)
[Screen_recording_20240723_234302.webm](https://github.com/user-attachments/assets/8cf820b8-df9d-4de3-bec3-71c69901a026)

<br>

# 🗣️ 리뷰 요구사항 (선택)
- 색 구별이 잘 안가서 바텀시트에 stroke 넣었는데 어떤지 궁금합니다.
- 일단 임시로 "ABCD1234" 텍스트로 클립보드 복사 테스트를 하고 있습니다. 추후에 실제 초대 코드를 사용합니다.
- 클립보드 화면이 스낵바를 가려서 추후에 스낵바를 위 쪽에 뜨게 하려고 합니다.

2024-07-23 16:32 UTC, aprilgom approved these changes
수고하셨습니다. 제가 가져다 쓰면 되는 부분이겠네요!

2024-07-24 01:06 UTC, kimhm0728 requested changes
고생하셨습니다 👍👍

2024-07-24 01:06 UTC, kimhm0728 commented on android/app/src/main/res/values/strings.xml
> +    <string name="logs_copy_code_guide">초대 코드가 복사 됐습니다.</string>
Ux Writing적인 부분이지만 `복사 됐습니다` -> `복사되었습니다` 어떤가요?! 더 자연스러운 너낌..

2024-07-24 01:27 UTC, haeum808 commented on android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
> +        Snackbar.make(binding.root, message, Snackbar.LENGTH_SHORT)
변경하는게 더 리소스가 안들것 같네요

2024-07-24 01:27 UTC, haeum808 commented on android/app/src/main/res/values/strings.xml
> +    <string name="logs_copy_code_guide">초대 코드가 복사 됐습니다.</string>
좋습니다!

2024-07-24 01:27 UTC, haeum808 commented on android/app/src/main/res/values/strings.xml
> +    <string name="logs_copy_code_guide">초대 코드가 복사 됐습니다.</string>
변경하겠습니다!

2024-07-24 01:31 UTC, kimhm0728 approved these changes

2024-07-24 01:33 UTC, merged