feat: 알림 타입별 on/off 기능 구현
woowacourse-teams/2024-ody pull request #844
Opened 2024-10-25 14:13 UTC by kimhm0728

# 🚩 연관 이슈 
close #753

<br>

# 📝 작업 내용
- [x] 설정 화면 디자인 수정
- [x] 권한 비허용 시 스위치 off
- [x] 권한 비허용일 때 스위치 클릭 시 권한 설정 화면으로 이동
- [x] 알림 설정 data store에 저장
- [x] 알림 설정 on인 경우에만 알림을 보내기
- [x] 알림 설정 on/off 저장된 값 가져와서 ui에 보여주기
<br>

# 🏞️ 스크린샷 (선택)

https://github.com/user-attachments/assets/040e0360-f9ce-43e0-982f-cde1bb0aab6b

<br>

# 🗣️ 리뷰 요구사항 (선택)
데모데이 끝나고 pr 올리는 제 광기 어떤가요 ㅋ
뷰타입 때문에 코드가 좀 많네요 리뷰에 도움 될만한 코멘트 달아두겠습니다
설정에서 알림 off 하면 실제로 알림 오지 않는 것도 확인했습니다.

2024-10-25 14:22 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
> +    }
출발 알림 on/off, 약속 참여 알림 on/off 값에 대한 datastore getter setter입니다

2024-10-25 14:22 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
> +                }
fcm으로 알림을 받고, 그 알림에 대한 알림 설정이 off되어있는 경우 실제 notification을 보여주지 않고 바로 return합니다

2024-10-25 14:22 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> +        }
설정 화면 진입하면 한번만 호출되는 코드입니다. 이미 저장된 알림 on/off 값을 통해 초기 스위치 ui를 보여주고 있습니다 (ex: 사용자가 출발 알림을 on했으면 switch ui도 on으로)
그리고 알림 권한이 꺼져있는 경우, 저장된 알림 on/off 설정값과 상관없이 switch가 off된 ui를 보여줍니다

2024-10-25 14:22 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> +            }
사용자가 switch를 클릭해 on/off할 때마다 호출되는 함수입니다.
알림 권한이 꺼져있으면 switch를 다시 off하고, 스낵바를 띄웁니다. (메시지-권한이 꺼져있음 / 액션-알림 권한 설정 화면으로 이동)
알림 권한이 켜져있으면 datastore에 알림 설정값을 저장합니다

2024-10-25 14:22 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +        const val SETTING_DIVIDER_VIEW_TYPE = 2
뷰 타입은 <헤더, 아이템, 구분선> 이렇게 세가지 타입이 존재합니다

2024-10-26 10:23 UTC, haeum808 requested changes
고생하셨습니다!

2024-10-26 10:23 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +sealed interface SettingUiModel {
프로퍼티를 가지고 있으니 sealed class는 어떤가요?

2024-10-26 10:23 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +    override val viewType: Int = SETTING_DIVIDER_VIEW_TYPE
개인적으로 궁금한 점입니다. 위 세가지 코드들 SettingUiModel 안에 넣을 수도 있는데 넣지 않은 이유가 궁금합니다.

2024-10-26 10:23 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingViewHolder.kt
> +    fun bind() {}
```fun bind() = Unit```
어떤가요

2024-10-27 12:40 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
> +            return type == NotificationType.DEPARTURE_REMINDER && !odyDatastore.getIsNotificationDepartureOn().first()
사용자가 직접 스위치를 눌러서 껐다 켜는 건 on/off, 내부적으로 알림이 무시되는 건 block이라는 표현을 사용했어요! 사용자가 직접 알림을 block/unblock 시키는 것, 내부 로직 상에서 알림을 on/off하는 것 둘다 약간 어색하다고 느껴져서요

2024-10-27 12:42 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
> +            return type == NotificationType.DEPARTURE_REMINDER && !odyDatastore.getIsNotificationDepartureOn().first()
> isNotificationBlock(type: NotificationType)으로 합치는게 어떤가요~

요건 넘 좋네요 수정했습니다 [194decd](https://github.com/woowacourse-teams/2024-ody/pull/844/commits/194decd7b67a15f9483703dcbe85200169b62c21)

2024-10-27 12:49 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +sealed interface SettingUiModel {
저는 인터페이스도 충분히 프로퍼티를 가지고 있을 수 있다고 생각하는데 해음은 어떠신가요?? sealed class를 제안하신 이유가 궁금합니다

2024-10-27 12:51 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +    override val viewType: Int = SETTING_DIVIDER_VIEW_TYPE
sealed interface나 sealed class에 프로퍼티가 존재하지 않고 간단하다면, sealed interface 내부에 구현체들을 넣어도 읽기 깔끔합니다. (ex: 일반적인 UiState 형태) 그런데 sealed interface에 프로퍼티가 존재하고 구현체들이 그 프로퍼티를 override해야 한다면, 밖으로 빼는 편입니다. sealed interface 내부에 구현체들을 작성하게 되면 depth도 깊어지고 가독성이 떨어지는 것 같아서요!

2024-10-27 12:55 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
> +    fun getIsNotificationDepartureOn(): Flow<Boolean> {
좋은데요?! 나중에 알림 설정 on/off 하는 `NotificationType`이 추가되었을 때의 확장성도 더 좋은 것 같아요. 수정했습니다~! `SettingItemType`에서 해당하는 `NotificationType`도 저장하고 있으면 좋을텐데, 그러면 `SettingItem` 뷰 타입과 `SettingNotificationItem` 뷰 타입을 또 분리해야 할 것 같아 이대로 두겠습니다 [b565ca4](https://github.com/woowacourse-teams/2024-ody/pull/844/commits/b565ca4d42cf36de9c642af42d1516b767445239)

2024-10-27 12:57 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/adapter/SettingViewHolder.kt
> +    fun bind() {}
훨씬 보기 좋네용 [eb26344](https://github.com/woowacourse-teams/2024-ody/pull/844/commits/eb26344649035d88058d23d46ecd0d20739039e5)

2024-10-27 13:00 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +sealed interface SettingUiModel {
interface를 보면 보통 행동만 있을꺼로 예상할 거 같은데 sealed라서 잘모르겠네요. 이대로 가도 괜찮을거 같아요!

2024-10-27 13:04 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/setting/model/SettingUiModel.kt
> +    override val viewType: Int = SETTING_DIVIDER_VIEW_TYPE
그렇군요! 좋은 생각 공유 감사합니다.

2024-10-27 13:05 UTC, haeum808 approved these changes

2024-10-27 13:20 UTC, aprilgom approved these changes
수고하셨습니다 올리브!!

2024-10-27 13:21 UTC, aprilgom commented on android/app/src/main/java/com/mulberry/ody/presentation/notification/FCMNotification.kt
> +            return type == NotificationType.DEPARTURE_REMINDER && !odyDatastore.getIsNotificationDepartureOn().first()
on과 block의 분리에는 그런 의미가 있었군요

2024-10-27 14:22 UTC, merged