refactor: repeatOnLifecycle 확장 함수 수정
woowacourse-teams/2024-ody pull request #875
Opened 2024-11-01 10:32 UTC by haeum808

… 코드 두번 안 불리게 변경

# 🚩 연관 이슈 
close #874 

<br>

# 📝 작업 내용
- [x] repeatOnLifecycle 확장 함수 수정

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-11-01 10:37 UTC, aprilgom approved these changes
이쪽이 더 깔끔한듯
고생하셨습니다 해음

2024-11-03 06:49 UTC, kimhm0728 requested changes
귀찮았을텐데 먼저 수정하겠다고 해주셔서 감사해요 해음~~ 
코드 리뷰가 늦었네요.. 함수명 관련 코멘트 달았으니 확인 부탁드립니다!

2024-11-03 06:49 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
> +fun <T> AppCompatActivity.collectLifecycleFlow(
`Lifecycle.State.STARTED`인 경우에만 collect되는 함수이니, 함수명에 이걸 내포하면 어떨까요? `collectWhenStarted`라던지...

2024-11-03 06:49 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
> +fun <T> AppCompatActivity.collectLifecycleFlow(
그리고 `collect`라는 단어가 들어가면 `Flow`를 `collect`한다는 것이 충분히 잘 드러나는 것 같아서, 함수명에 `Flow`를 굳이 적지 않아도 될 것 같아요!

2024-11-04 14:39 UTC, kimhm0728 commented on README.md
> +친구가 잘 오고 있는지 알지 못해 답답합니다. 결국 "너 어디야?"라는 메시지를 보냈어요.
오잉?!

2024-11-05 01:18 UTC, kimhm0728 approved these changes
👍 고생하셨어요

2024-11-05 02:06 UTC, merged