refactor : 비동기 + 이벤트 리스닝 방식으로 알림 로직 개선
woowacourse-teams/2024-ody pull request #906
Opened 2024-11-14 19:58 UTC by coli-geonwoo

# 🚩 연관 이슈 
close #905 

<br>

# 📝 작업 내용
- [x] #905  

<br>

# 🏞️ 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/051cafb7-96fb-42e4-b217-d931fcc4e6a3)

<br>

# 🗣️ 리뷰 요구사항 (선택)

### 관련 설명은 [노션 페이지](https://sly-face-106.notion.site/fcm-4c4232320b074404b2bcae32740da47f?pvs=4)에서 볼 수 있습니다. 리팩터링 양이 꽤 되어서 꼭 참고해주세요!

### Approve&Merge되지 않아도 괜찮아요. 합리적이라 생각하는지에 대한 의견도 이야기해주시면 좋을 것 같아요.

2024-11-15 14:46 UTC, hyeon0208 requested changes
전반적으로 깔끔하게 코드를 개선한 것 같아요 👍 
알림 전송에 대해서 비동기 처리가 필요했었는데 개선해주셨네요 😄
코드 리뷰하면서 이벤트 리스너를 꼭 사용해야하는지가 궁금했던 것 같아요
관련해서 질문들 남겼습니다 !

2024-11-15 14:46 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Thread.sleep(1000L); //비동기 메서드 유휴 시간
[제안]
비동기 처리가 실행 환경에 따라 1초보다 더 걸릴 수 있으니
sleep으로 테스트하면 비결정적인 테스트가 될 것 같아요...

CountDownLatch를 사용해 결정적인 테스트로 수정해보면 어떨까요?

2024-11-15 14:46 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/event/NoticeEvent.java
> +public class NoticeEvent extends ApplicationEvent {
Spring 프레임워크 4.2 버전 이후 부터는 `ApplicationEvent`를 상속받지 않아도
이벤트 객체를 생성 가능하다고 하네요!
https://www.baeldung.com/spring-events

2024-11-19 04:29 UTC, eun-byeol requested changes
콜리 고생하셨어요! 비동기 개선이 합리적이라고 생각해요. 덕분에 비동기 부분 공부해볼 수 있었어요👍

다만, 기존 동기 방식을 앱으로 사용하면서 딜레이가 있다고 느끼진 않았었는데, 메시지 전송 시간 3초 측정은 어떻게 하셨나요?

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
> +        log.error("비동기 메서드 에러 : method: {} exception: {}", method.getName(), exception.getMessage());
단순 고민입니다!
지금의 비동기 에러 핸들링은 서버 에러 상황만 커버될 수 있겠네요.
현재는 문제될 부분이 없지만, 클라이언트 에러인 케이스가 있으면 클라이언트에게 전달하지 못하니 유의해야 할 것 같아요.

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/exception/AsyncExceptionHandlerTest.java
> +class AsyncExceptionHandlerTest extends BaseControllerTest {
> 트랜잭션 관련 로직을 통합 테스트에서 검증하는 것이 어색하다고 생각하겠지만, 우선 MateControllerTest에 작성했습니다.  위치가 어울리지 않는다고 생각하면 피드백 남겨주세요!

계층 관점에서 전 합리적이라고 생각해요!

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +    ;
오잉??
```suggestion
    }
```

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Meeting  nowMeeting = fixtureGenerator.generateMeeting();
✅
```suggestion
        Meeting nowMeeting = fixtureGenerator.generateMeeting();
```

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Thread.sleep(1000L); //비동기 메서드 유휴 시간
콜리의 경우 전체 테스트가 20초가 걸렸던데,
`CountDownLatch` 사용하면 더 짧아질 수도 있어서 적용하면 좋을 것 같아요

2024-11-19 04:29 UTC, eun-byeol commented on backend/src/test/java/com/ody/notification/service/FcmEventListenerTest.java
> +    @DisplayName("트랜잭션이 열리지 않으면, 푸시 알림 발송 로직이 실행되지 않는다")
꼼꼼한 테스트👍

2024-11-21 13:42 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/event/NoticeEvent.java
> +public class NoticeEvent extends ApplicationEvent {
좋은 자료 감사합니다! 카키 👍  조조의 말처럼 FcmEventPublisher에서 ApplicationEvent를 상위 클래스로 로직을 처리해주는 부분이 있어서 우선은 타입 계층 구조로 유지하려고 해요 😄

2024-11-21 14:02 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/FcmEventListener.java
> +    }
|Async도 프록시 객체가 생성되고 Transactional도 프록시 객체가 생성되서
두 어노테이션을 같이 사용하면 롤백이 안되는 등의 이슈가 있는 것으로 알고 있어요

아마 ThreadLocal로 관리되는 트랜잭션으로 인해서 Transaction이 열린 메서드 A내에서 다른 비동기 메서드인 B를 호출하는 상황을 이야기하는 것으로 이해했어요.
```java
   @Transactional
   public void A() {
         B() //비동기일 경우 트랜잭션 동기화가 안됨
   }
```
이 경우에는 카키가 이야기한 대로 B와 A는 다른 스레드가 생성되므로 트랜잭션 동기화가 안될 것 같아요. 그러나 이 경우는 비동기 메서드인 sendPushMessage의 트랜잭션 설정을 다루는 것이기 때문에 해당 사이드 이펙트가 발생하지는 않을 것 같아요. 혹시 제가 잘못 이해한 부분이 있다면 이해해주세요!

---

|@Transactional(propagation = Propagation.REQUIRES_NEW)가 불필요해 보여요!

인정합니다. 트랜잭션을 새로 열어주는 것에 신경쓰다보니 REQUIRES_NEW를 해주었는데 fcmPushSender에서 열어주고 있었네요. 코드 상에서 제거해주었습니다.

---

|@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)가 필요�했던 이유가
궁금합니다 !

이전에 상위 서비스에서 commit이 되었는가? 아닌가? 를 의식한 코드가 있었어요. findById로 db 상에서 notification을 가져올 수 있는데 생성과 즉시 발송되어야 하는 notification의 경우 아직 db에 저장되지 않아 id를 할당받지 못한 상태이기 때문에 NoSuchElementException이 발생하는 경우가 있었어요. 

```java
@Transactional
    public void sendPushNotification(Notification notification) {
        Notification savedNotification = notificationRepository.findById(notification.getId())
                .orElse(notification); // noti 생성과 동시에 실행되는 경우, 다른 트랜잭션이므로 즉시 findById 할 수 없어 기존 noti 사용

        if (savedNotification.isStatusDismissed()) {
            log.info("DISMISSED 상태 푸시 알림 전송 스킵 : {}", savedNotification);
            return;
        }
        GroupMessage groupMessage = GroupMessage.from(savedNotification);
        sendGeneralMessage(groupMessage.message(), savedNotification);
    }

```

이 부분을 개선하기 위해 일관적으로 notification을 상위 서비스에서 commit한 이후에 id값으로 notificiation을 찾아서 발송하도록 로직을 수정한 것입니다.

2024-11-21 14:06 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
>      public void scheduleNotification(Notification notification) {
**✅ [반영 완료]**

꼼꼼히 리뷰해주셨네요 조조. 맞아요. 아마 해당 책임을 eventPublisher에게 넘기려고 했다가 생각대로 잘 진행되지 않아서 다시 책임을 이전했는데 그 과정에서 Transaction과 접근제어자를 신경쓰지 못한 것 같아요. private + 트랜잭션 제거 반영해주었습니다.

2024-11-21 14:11 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/NotificationService.java
> +
**✅ 반영 완료**

변수 한번 분리해주려 했던 시도가 남아있네요... 분리해도 라인이 넘어가서 중도에 시도하지 않았던 것 같아요. 삭제해주었습니다!

2024-11-21 14:25 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +    ;
😭 반영 완료!

2024-11-21 14:25 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Meeting  nowMeeting = fixtureGenerator.generateMeeting();
**🙇  반영 완료**

2024-11-21 14:26 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
> +        log.error("비동기 메서드 에러 : method: {} exception: {}", method.getName(), exception.getMessage());
맞아요 조조. 저도 이부분 고민이 되었는데요. 두 가지 생각이 들었어요.

**첫번째로 FCM 발송 로직에 클라이언트 에러 검증을 현재 하고 있는가? 에 대한 부분인데요.**

```java
   @Transactional
    public void sendGeneralMessage(Message message, Notification notification) {
        try {
            Notification savedNotification = findNotification(notification);
            if (savedNotification.isStatusDismissed()) {
                log.info("DISMISSED 상태 푸시 알림 전송 스킵 : {}", notification);
                return;
            }

            firebaseMessaging.send(message);
            updateDepartureReminderToDone(savedNotification);
        } catch (FirebaseMessagingException exception) {
            log.error("FCM 알림(ID : {}) 전송 실패 : {}", notification.getId(), exception.getMessage());
            throw new OdyServerErrorException(exception.getMessage());
        }
    }
```

FCM 측에 잘못된 인수를 전달하는 것은 현재로선 잘못된 토큰 값, 잘못된 토픽 정도가 될 것 같아요. 다만 현재 로직에서도 토큰 값이 형식에 맞는지를 검증하고 있지는 않아서 FCM 측에서 나온 에러를 그대로 클라이언트 측에 전달하고 그 결과를 바탕으로 서버에러인지, 클라이언트 에러인지 판단하는 식의 디버깅을 해왔던 것 같아요. 즉, 현재 동기 로직 상에서도 클라이언트 에러만을 따로 검출하여 안드 측에 보내고 있지 않고 FCM 에러를 그대로 전달하는 방식으로 에러 핸들링을 하고 있어요. 

결국 에러 로그를 보고 클라 에러인지 서버 에러인지를 확인할 수 있는 구조라면, 푸시 알림에 대한 의존성을 비즈니스로직으로부터 분리하고 에러 로그를 통해 디버깅할 수 있는 정도의 핸들링도 바람직하지는 않지만 현재 에러 핸들링과 큰 차이는 없다는 생각이 들었어요.

둘째로 트레이드 오프인데요.
푸시 알림에 대한 로직이 비즈니스 로직에 얽혀있어 FCM 서버에서 에러가 발생하면 서버 곳곳에 에러가 전파되는 상황이에요. 따라서 비동기 + 이벤트 리스닝 방식으로 도메인을 분리함으로써 얻는 이득이 정확한 에러 포인트를 전해주지 못한다는 단점과 비교했을 때 상대적으로 크다고 생각했던 점도 있습니다.

다만 저도 이 구조가 바람직하다고 생각하지는 않기 때문에 **deviceToken을 최초로 받는 시점(로그인 하는 시점)** 등에서 디바이스 토큰을 검증하거나 최초로 참여할 때 deviceToken이 옳지 않으면 참여하지 못하도록 부분적으로 알림 발송을 동기화하는 식의 방안도 있을 것 같아요. 더 좋은 생각이 있으면 적극적으로 반영해보도록 할게요!

2024-11-21 16:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/AsyncConfig.java
> +        executor.setThreadNamePrefix("ody-fcm");
우선 TaskExecutor를 Bean으로 등록하는 것이 확장성 있는 구현이라는 점은 인정해요. 또 카키가 이야기한 대로 비동기 풀 설정이 2개 이상으로 분기될 때 각 비동기 설정을 따로 지정할 수 있다는 점도 좋은 점이죠.

다만 현재 AsyncConfigurer를 사용한 것은 전역적인 비동기 풀 설정 뿐만 아니라 에러 핸들러 등록을 위함도 있어요. 에러 핸들러 등록을 위해 AsyncConfigurer의 getAsyncUncaughtExceptionHandler 함수를 오버라이드 하는 것 외의 방법을 찾을 수 없었어요. 실제로 Bean으로 등록을 했을 때 컨텍스트에서 자동으로 에러 핸들러 등록이 되지 않은 것을 테스트를 통해 확인하기도 했고요.

> 오버라이드 하지 않고 빈으로 등록하는 것만으로는 핸들러가 등록되지 않음 == AsyncConfigurer 구현이 필수적임
![image](https://github.com/user-attachments/assets/a9b4cb29-8109-416a-a04a-cc953c50f13a)


그래서 우선 AsyncConfigurer를 통한 어플리케이션 단의 등록을 먼저 수행하고 추후 비동기 풀 설정이 두 개 이상으로 나누어 진다면 그 때 Bean naming을 통해 명확히 규정해주어도 괜찮겠다고 생각했습니다!

현재는 Bean을 등록하는 클래스와 AsyncConfigurer 두 개를 각각 나누는 것이 확장성을 고려한 너무 많은 인풋이라 생각해서 우선 간단히만 설정파일을 작성했어요!

2024-11-21 16:56 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
> +        log.error("비동기 메서드 에러 : method: {} exception: {}", method.getName(), exception.getMessage());
> 결국 에러 로그를 보고 클라 에러인지 서버 에러인지를 확인할 수 있는 구조라면 ... 현재 에러 핸들링과 큰 차이는 없다는 생각이 들었어요.

지금 에러 전략 상 `FCM 에러를 클라이언트에게 보내지 않아도 괜찮다`로 이해했어요. 물론, 원인 파악을 위해 디버깅이 필요한 상황이라는 것에는 동의해요. 그 관점에서 콜리의 의견도 이해합니다.
다만, 우리가 에러 감지에 민감하게 반응해야 할 것 같아요. 지금 슬랙 경보 알림이 잘 안오기도 하고, 문제 파악 시점이 늦어지는 건 맞을 것 같아요.(이 부분의 개선이 대안이 될수도 있겠네요)
오늘 해음이 슬랙에 남긴 에러 케이스의 경우(재촉하기 도중 발생한 FCM 오류) 저희가 먼저 파악하기보다는, 해음이 테스트 도중에 바로 에러를 확인해서 알려주었죠. 만약 콜리의 전략대로 실행되었을 때, 해음이 재촉하기 요청이 성공하는데 왜 알림이 안가지? 이런 혼란스러운 상황이 생길수도 있구요.

> deviceToken 검증에 대해

FCM 에러가 발생할 수 있는 로직을 비동기 로직과 분리하는 것도 좋네요. FCM 알림을 발송하는 비동기 로직이 실행되기 전에, 검증하면 클라이언트에게 적절한 에러도 갈 수 있으니까요.
콜리가 언급한 케이스 뿐만 아니라, FCM 알림을 사용하는 모든 로직(재촉하기 포함)에 추가해야 할 것 같아요. 재촉하기의 경우, 요청값에 들어오는 게 아니라 deviceToken을 db에서 조회하고 있습니다.

혹시 제가 콜리의 의도를 다르게 이해했다면 말씀해주세요!
다른 팀원들의 생각도 궁금하네요!

2024-11-21 17:57 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/FcmPushSender.java
> +    public void sendGeneralMessage(Message message, Notification notification) {
> topic, divice token 메세지를 모두 일반 메세지로 표현하신 것 같은데

어.. 우선 저도 비슷한 생각을 했던게 private method에 sendGeneralMessage 라는 private method가 선언되어 있어 이게 어떤 메시지를 이야기하는지 이해하기 힘들었던 것 같아요.

각각 GroupMessage, DirectMessage, NoticeMessage 별로 메서드를 만들어주었습니다. 다만 바깥에서 구분은 되나 비슷한 전달메서드가 조금씩 생기게 되는 것 같아요.
```java
    @Transactional
    public void sendGroupMessage(GroupMessage groupMessage, Notification notification) {
        Notification savedNotification = findNotification(notification);
        if (savedNotification.isStatusDismissed()) {
            log.info("DISMISSED 상태 푸시 알림 전송 스킵 : {}", notification);
            return;
        }
        sendMessage(groupMessage.message());
        updateDepartureReminderToDone(savedNotification);
    }

    public void sendDirectMessage(DirectMessage directMessage) {
        sendMessage(directMessage.message());
    }

    public void sendNoticeMessage(GroupMessage groupMessage) {
        sendMessage(groupMessage.message());
    }

    private void sendMessage(Message message) {
        try {
            firebaseMessaging.send(message);
        } catch (FirebaseMessagingException exception) {
            log.error("FCM 전송 실패 : {}", exception.getMessage());
            throw new OdyServerErrorException(exception.getMessage());
        }
    }
```

2024-11-21 18:08 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
> +        log.error("비동기 메서드 에러 : method: {} exception: {}", method.getName(), exception.getMessage());
> 우리가 에러 감지에 민감하게 반응해야 할 것 같아요.

동의해요. 다만 빠른 에러 감지를 위해 FCM 에러를 클라이언트에게 반환함으로써 감지한다는 해결책은 지금으로써는 가장 힘이 들지 않는 방향이지만 근본적인 해결책은 아닌 것 같아요. 조조가 말한대로 서버쪽에서 조금 더 민감한 모니터링을 할 수 있도록 개선하는 방향을 고민해보는 게 좋지 않을까 하는게 제 의견인 것 같아요.

**> 부분 동기화는 어떤지?**

제가 리팩터링을 한 의도는 알림이 부수적인 요소인 비즈니스 로직일 때, 알림에서 오류가 남으로써 다른 부분들도 연쇄적으로 장애가 전파되는 상황을 막기 위함이었어요. 다만 재촉하기 같은 경우에는 알림 자체가 기능이다보니까 이걸 비동기화 하는게 정말 올바른 선택인가? 라는 의문도 들어요. 해음이 재촉하기 요청을 보내고 비동기로 성공할테니 성공 응답을 보내줄게~ 라는 것도 서버측에서 무책임한 HTTP 응답이라는 생각도 들고요.

그래서 **알림이 주요 기능인 재촉하기의 경우 기존처럼 동기로 로직을 처리하는 것도 방법이 될 수 있을 것 같네요.**

2024-11-21 18:16 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/AsyncConfig.java
> +        executor.setThreadNamePrefix("ody-fcm");
+) 추가적으로 찾아보니까 AsyncConfigurer에서 override 한 taskExecutor bean의 경우도 이름 지정이 가능해서 지정해주었어요!

```java
    @Override
    @Bean(name = "fcmAsyncExecutor")
    public Executor getAsyncExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setRejectedExecutionHandler(new ThreadPoolExecutor.CallerRunsPolicy()); //스레드풀이 가득찼을 경우 톰캣 스레드에서 처리
        int coreCount = Runtime.getRuntime().availableProcessors();
        executor.setCorePoolSize(coreCount);
        executor.setThreadNamePrefix("ody-fcm");
        executor.initialize();
        return executor;
    }

```

2024-11-22 02:41 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/AsyncConfig.java
> +        executor.setThreadNamePrefix("ody-fcm");
> 다만 현재 AsyncConfigurer를 사용한 것은 전역적인 비동기 풀 설정 뿐만 아니라 에러 핸들러 등록을 위함도 있어요. 에러 핸들러 등록을 위해 AsyncConfigurer의 getAsyncUncaughtExceptionHandler 함수를 오버라이드 하는 것 외의 방법을 찾을 수 없었어요. 실제로 Bean으로 등록을 했을 때 컨텍스트에서 자동으로 에러 핸들러 등록이 되지 않은 것을 테스트를 통해 확인하기도 했고요.

`AsyncUncaughtExceptionHandler`가 빈이 등록이 안되군요..
내부적으로 어떻게 동작하는진 모르지만 좋은 정보 얻어갑니다!

>  추가적으로 찾아보니까 AsyncConfigurer에서 override 한 taskExecutor bean의 경우도 이름 지정이 가능해서 지정해주었어요!

사실  `AsyncConfigurer`를 상속받지 않으면 지금처럼 오버라이딩 없이 다형성 Bean 등록이 좀더 유연하고 가독성이 생길거라 생각했는데 `AsyncUncaughtExceptionHandler`가 상속받지 않는 이상 빈 등록을 못했네요 👍 
빈 이름 지정 반영 감사합니다 👍

2024-11-22 02:41 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/AsyncConfig.java
> +public class AsyncConfig implements AsyncConfigurer {
이건 위에서 이미 설명되서 답장안해도될듯 👍

2024-11-22 02:49 UTC, hyeon0208 commented on backend/src/main/java/com/ody/notification/service/FcmEventListener.java
> +    }
> 이 경우에는 카키가 이야기한 대로 B와 A는 다른 스레드가 생성되므로 트랜잭션 동기화가 안될 것 같아요. 그러나 이 경우는 비동기 메서드인 sendPushMessage의 트랜잭션 설정을 다루는 것이기 때문에 해당 사이드 이펙트가 발생하지는 않을 것 같아요. 혹시 제가 잘못 이해한 부분이 있다면 이해해주세요!

다시 확인해보니 트랜잭션 내부에서 Async를 호출할 경우가 문제네요 감사합니다 ! 👍 

> 이전에 상위 서비스에서 commit이 되었는가? 아닌가? 를 의식한 코드가 있었어요. findById로 db 상에서 notification을 가져올 수 있는데 생성과 즉시 발송되어야 하는 notification의 경우 아직 db에 저장되지 않아 id를 할당받지 못한 상태이기 때문에 NoSuchElementException이 발생하는 경우가 있었어요.

 그러네요 `sendPushNotification()`에서 `notification`엔티티의 Id로 조회하니 커밋 여부에 따라 다르겠네요 👍

2024-11-22 03:07 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/exception/AsyncExceptionHandler.java
> +        log.error("비동기 메서드 에러 : method: {} exception: {}", method.getName(), exception.getMessage());
해음이 슬랙에 남긴 에러 케이스가 FCM의 오류인지 아니면 요청의 요류인지 아직 파악이 안된 것 같아 정확히는 모르겠지만
모니터링으로 분석후 개선방안을 검토하는 것도 좋을것 같네요 !

재촉하기와 같이 알림 자체가 기능인 것은 동기 방식이 적절하겠네요 👍

2024-11-22 18:09 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Thread.sleep(1000L); //비동기 메서드 유휴 시간
@hyeon0208 @eun-byeol 

이거 CountDonwLatch 적용하려고 한 2시간 정도 시도해보았는데 생각한 테스트 방식이 있는지 조금 더 힌트주실 수 있나요? 도와주세요..

CountDonwLatch의 경우 비동기 스레드가 끝남과 동시에 명시적으로 countDown 메서드를 호출해주고, test main thread에서는 await로 기다리는 건데 현재는 E2E 테스트로 검증하고 있고 eventListener 방식이라 countDonwLatch을 어떻게 적용해야 할지 잘 생각이 나지 않았어요..

2024-11-24 11:10 UTC, hyeon0208 commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Thread.sleep(1000L); //비동기 메서드 유휴 시간
RestAssured.given() 절 위 아래로 아래 구문 추가하니 테스트 성공하네용
```
        Mockito.doAnswer(invocation -> {
            latch.countDown();
            return null;
        }).when(firebaseMessaging).send(any(Message.class));

// RestAssured.given()...

        latch.await(3, TimeUnit.SECONDS);
```

2024-11-24 13:33 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/mate/controller/MateControllerTest.java
> +        Thread.sleep(1000L); //비동기 메서드 유휴 시간
와..... countDownLatch를 mock 안에다가 넣어서 stubbing 해줄 수도 있네요!!!!! 배워갑니다 카키 😮 
시간 꽤 썼는데 해결책을 못찾았었는데 doAnswer 안에 invocation을 지정해줄 수 있는지 몰랐어요. 감사합니다 🙇

2024-11-24 17:03 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/notification/service/FcmEventListener.java
> +    }
😭  [롤백]

| **개선하기 위해 일관적으로 notification을 상위 서비스에서 commit한 이후에 id값으로 notificiation을 찾아서 발송하도록 로직을 수정한 것입니다.**

![image](https://github.com/user-attachments/assets/de82955b-2bb1-4f67-ae23-71e261cf959e)

결론적으로 local 환경에서 QA를 하다가 에러가 발생하여 다시 orElse로 롤백해주었습니다.
더 구체적인 원인과 해결책을 떠올렸으나 PR이 두꺼워질 것 같아서 새로운 이슈파서 작업해줄게요.

```java
private Notification findNotification(Notification notification) {
        return notificationRepository.findById(notification.getId())
                .orElse(notification);
    }
```

일전에는 에러의 원인이 `바로 발송되어야 하는 Notification의 경우 id를 할당받기 이전에 find를 호출해서`라고 생각했는데요. 따라서 TransactionalEventListener의 phase를 AFTER_COMMIT으로 설정하면 flush 이후에 findById로 조회를 하니 당연히 알림을 찾아오리라 생각했습니다.

그러나 실패했어요. 그 이유는 **flush 되는 transaction이 main 트랜잭션이 아니라  taskScheduler의 트랜잭션이기 때문입니다.**

![image](https://github.com/user-attachments/assets/c0a934ec-b3c4-47ca-8cdd-c80daa2ddcda)

taskScheduler는 안의 Runnable을 새로운 스레드를 잡아 작업하게 되는데, 이 때 새로운 Transaction을 열어주었어요. 실제로도 notificationService 안의 스레드명과 taskScheduler의 스레드명이 다른 것을 알 수 있어요.

그럼 바로 알림을 발송해야 하는 경우에 다음 시나리오를 생각해볼게요.
1. main 스레드 트랜잭션 열림
2. 알림 저장 -> 엔티티 매니저에 영속화/ 아직 flush 안됨
3. taskScheduler의 트랜잭션 열림
4. taskScheduler에서 이벤트 발행 후 트랜잭션 닫힘
5. 이벤트 리스너가 수신 후 비동기 스레드의 sendPushMessage에서 새로운 트랜잭션 열기
6. notification 조회 -> 아직 flush 되지 않은 알림을 조회 x

이렇게 commit이 보장되는 트랜잭션이 main이 아닌 taskScheduler이고 + 아직 flush가 되지 않은 상태로 트랜잭션이 열려 MYSQL 기본 격리수준인 REPEATABLE_READ에 따라 신규 notification을 못 읽어오고 있었습니다.

실제로 main 스레드가 commit되기 까지 충분한 휴식시간을  Thread.sleep으로 taskScheduler 스레드 안에 주었을 때는 알림이 정상 발송되는 걸 알 수 있었어요.(이벤트 리스너 트랜잭션이 열릴 때 main 스레드가 이미 커밋된 이후이므로)


따라서 우선 orElse로 원복한 상태이며, 원인을 특정하였으니 새로운 이슈를 파서 위의 로직도 CompletableFuture를 활용해 notificationService로 넣어보려고 합니다! 우선은 orElse로 복구하고 PR을 날릴게요!

2024-11-24 17:08 UTC, coli-geonwoo commented
### [비동기 성능 테스트 결과]

동기 코드 : prod 환경에서 Postman으로 개별 10회 호출 latency 평균값
비동기 코드 : local환경에서 Postman으로 개별 10회 호출 latency 평균값

`재촉하기` : 303.7ms → **76.7ms**
`방 나가기 (unSubscribe)` : 871.4 → **110.2ms**
`약속 참여 → 바로 출발 알림 보내는 시나리오` : 1007.6ms → **596.5ms**

약속 참여의 경우 prod환경에서는 odsay를 바로 호출하나 local에서는 odsay 에러 > google 호출 식으로 api를 두번 호출하였음에도 다음과 같은 성능 향상을 바라볼 수 있었습니다.

2024-11-25 09:08 UTC, hyeon0208 commented
@coli-geonwoo 

동기 코드는 prod로
비동기는 local로 비교한 이유가 있을까요 ??
좀더 정확하게 확인하려면 비동기도 prod로 latency 평균을 내야할 것 같아서요 !

2024-11-25 09:50 UTC, coli-geonwoo commented
> @coli-geonwoo
> 
> 동기 코드는 prod로 비동기는 local로 비교한 이유가 있을까요 ?? 좀더 정확하게 확인하려면 비동기도 prod로 latency 평균을 내야할 것 같아서요 !

맞아요! develop 띄워서 같은 local 환경에서 비교해보려 했는데 에러가 나서 우선 prod 기준으로 쏘아보았던 것 같아요. develop 에서 띄워서 동일조건에서 비교해볼게요 😄

2024-11-27 07:26 UTC, eun-byeol approved these changes
콜리 고생하셨어요👍 덕분에 많은 부분 배워가요!

다만, 재촉하기 기능의 경우 동기로 적용하는 것도 제안해주셨는데, 합리적이라고 생각해요.
코멘트 남겼는데 확인 부탁드릴게요~

2024-11-27 15:30 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/config/AsyncConfig.java
> +        executor.setThreadNamePrefix("ody-fcm");
비동기가 사용되는 서비스의 성격에 따라 어떤 thread pool을 사용할 것인지 지정할 수 있습니다. 로직의 성격에 따라 지정해주어야 하는 스레드 설정이 다를 수 있는데요. 이때 bean에 이름을 지정하고 @Async("executor bean 이름")을 통해 해당 비동기 메서드의 스레드 설정을 지정해줄 수 있습니다.

2024-11-27 15:44 UTC, merged