refactor: 초대코드 유효하지 않은 메시지 서버로부터 받게 변경
woowacourse-teams/2024-ody pull request #907
Opened 2024-11-15 02:01 UTC by haeum808

# 🚩 연관 이슈 
close #893 

<br>

# 📝 작업 내용
- [x] 초대코드 유효하지 않은 메시지 서버로부터 받게 변경

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-11-15 13:06 UTC, aprilgom approved these changes
수고하셨습니다 해음!

2024-11-18 07:29 UTC, kimhm0728 requested changes
고생하셨습니다 해음 코드 리뷰 늦어서 미안해요 ㅠ
궁금한 점 코멘트 남겨두었는데 답변 부탁드려요!!

2024-11-18 07:29 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/retrofit/ApiResultCall.kt
> -                            Response.success(ApiResult.Failure(response.code(), response.message())),
기존 코드의 `response.message()`를 그대로 사용하면 서버 에러 메시지를 가져올 수 없나요?
불필요한 필드를(type, title, status, detail, instance) 다 받기 보다는 기존 방식대로 저희에게 필요한 code, message만 받는 것도 좋은 것 같아서요!

2024-11-18 07:29 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
> +        val invitationCodeEvent: SharedFlow<String> get() = _invitationCodeEvent.asSharedFlow()
`invitationCodeEvent`라고 네이밍한 이유가 궁금해요! 다른 곳에서는 `inviteCode`라는 이름을 쓰고 있어서 통일하면 어떨까요?
그리고 "초대코드이벤트" 보다는, 조금 더 구체적으로 어떤 이벤트인지 명시하면 어떨까요? (ex: 초대 코드가 유효하지 않을 때의 이벤트)

2024-11-18 07:35 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/data/retrofit/ApiResultCall.kt
> -                            Response.success(ApiResult.Failure(response.code(), response.message())),
Retrofit에서 제공해주는 code()와 message()는 HTTP 응답에 대한 정보만 제공해서 응답 본문에 대한 정보는 errorBody()를 사용해야 했습니다.

2024-11-18 07:36 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
> +        val invitationCodeEvent: SharedFlow<String> get() = _invitationCodeEvent.asSharedFlow()
확실히 invitationCodeEvent 네이밍은 전달하고자 하는 의미를 담고 있지 않네요!
inAppropriateInviteCodeEvent 어떤가요?

2024-11-18 09:26 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/data/retrofit/ApiResultCall.kt
> -                            Response.success(ApiResult.Failure(response.code(), response.message())),
그렇군요!! 알려줘서 고마워요 해음

2024-11-18 09:27 UTC, kimhm0728 commented on android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
> +        val invitationCodeEvent: SharedFlow<String> get() = _invitationCodeEvent.asSharedFlow()
inappropriate는 변수 네이밍에 일반적으로 쓰이지 않는다는 느낌이 조금 드는데, 혹시 invalid는 어떨까요????

2024-11-18 09:28 UTC, kimhm0728 approved these changes
프로퍼티명만 수정하면 될 것 같아서 approve하겠습니다 👍

2024-11-18 12:14 UTC, haeum808 commented on android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
> +        val invitationCodeEvent: SharedFlow<String> get() = _invitationCodeEvent.asSharedFlow()
invalid 좋네요

2024-11-18 13:03 UTC, merged