refacator: API 의존성 관리 로직 개선
woowacourse-teams/2024-ody pull request #910
Opened 2024-11-15 11:09 UTC by hyeon0208

# 🚩 연관 이슈 
close #900 

<br>

# 📝 작업 내용

> 문제 상황

List로 RouteClient를 관리하고 있기 때문에
첫 번째 RouteClient가 항상 실패하는 상황에서도 매번 호출 후 다음 RouteClient로 부터 요청 응답을 받는다.
이로 인해 다음과 같은 문제가 발생한다.
- 반복적인 쌓이는 너무 긴 에러 로그
- 타임아웃 대기 시간만큼 불필요한 지연 발생
- 불필요한 연결 및 타임아웃 처리를 위한 시스템 리소스 낭비

> 얻고자한 점

Redis를 도입해 에러가 발생한 요소에 TTL을 설정해 쿨다운을 적용하는 서킷 브레이커 패턴을 적용하여 아래와 같이 개선하고자 함.
- 쿨다운 동안만 다른 RouteClient에게 요청 응답을 받도록 개선.
- 분산 된 서버들도 일관되게 동작

> 적용 방식 흐름

- 쿨다운 관리
    - 에러 발생 시 장애 횟수를 1씩 카운팅
    - 30분 내에 총 3번의 RouteClient 에러 발생 시 즉시 3시간의 쿨다운 시작
    - 쿨다운 중이 아닌 클라이언트만 필터링하여 사용

> 로컬과 Dev, Prod

로컬에서는 기존에 사용하던 MySQL과 같이 Docker Compose 파일에 redis 설정을 추가해 사용가능하도록 했습니다.
dev와 prod 환경은 AWS의 Elasticache로 Redis를 추가하여 연결해주었어요.

`cache.t4g.micro`로 생성했고 저의 프로젝트 남은 기간동인 14일 동안 사용한다면 약 `11,250원`이 나올걸 봐서
저희 지원 제한 요금인 70달러는 초과하지 않을 것 같아요
<img width="894" alt="image" src="https://github.com/user-attachments/assets/6f293165-68e0-48a8-a4ee-8e3064041fd4">

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

> block(쿨다운)에 대한 TTL

현재 3회 실패시 3시간의 TTL을 걸어 해당 시간동안 다른 RouteClient를 사용하도록 적용했어요
첫 번째 RouteClient인 Odsay의 경우 주로 에러를 뱉는 상황이 API 제한량(일/1,000)을 초과할 경우일텐데
일시적인 장애 문제도 고려, Google에는 하루라는 단위가 성립안됨을 고려했고
보통 위와 같은 이유로 장애가 발생하면 긴 시간동안 사용을 할 수 없어 3시간 단위로 확인할 하도록 설정했는데요
다른 분들은 어느 정도 TTL이 적절하다고 생각하시나요 ?

2024-11-19 06:06 UTC, eun-byeol requested changes
카키 고생하셨어요! 깔끔하게 구현해주셨네요👍 덕분에 레디스와 서킷 브레이커 패턴 학습할 수 있었어요.

> 다른 분들은 어느 정도 TTL이 적절하다고 생각하시나요 ?

3시간 쿨타임도 합리적이라고 생각해요. 근데 딱 3시간이라는 기준의 근거가 궁금하네요🤔
전 가능하다면, 동적으로 쿨타임을 정하면 좋을 것 같아요.
가장 짧은 갱신 주기인 오디세이에 맞춰, 당일 23:59:59까지 쿨타임이 적용되도록요.

2024-11-19 06:23 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
> +        redisTemplate.expire(failClientKey, FAIL_MINUTES_TTL);
30분 내에 3번의 에러가 발생했을 때에만 격리 시키는 것을 의도했습니다!

2024-11-19 06:39 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/CustomRedisTemplate.java
> +public class CustomRedisTemplate extends RedisTemplate<String, String> {
Redis에 모든 값들이 String으로 저장되어 형변환 없이 String으로 가져온 뒤 원하는 타입으로 변경하도록 의도했습니다!

카운팅, 카운트 조회 기능이 다른 도메인에서도 사용될 여지가 있다고 생각했었는데
각 도메인마다 가져오고 싶은 타입이 다를 수 있으니 구체화해도 좋을것 같네요!

2024-11-19 06:39 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
> +        redisTemplate.opsForValue().set(blockKey, "1");
`BLOCK`으로 상수화했습니다!

2024-11-19 06:43 UTC, hyeon0208 commented on backend/src/main/resources/common.yml
> +      window: 300000    # 5분 내 실패 카운트
프로퍼티로 관리하려했었는데 지금은 사용하고 있지 않아 제거했습니다!

2024-11-19 06:44 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteClientCircuitBreakerTest.java
> +                () -> assertThat(failCount).isEqualTo(0),
오호 isZero()라는 메서드도 있었네요 반영완료!

2024-11-19 06:48 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
키가 없을 때 카운팅은 +1, 있을 때도 카운팅은 +1 이라서 같다고 생각했는데 
다른 점에 대해 좀 더 설명해주실수 있을까요 ?? 😃

2024-11-19 07:08 UTC, hyeon0208 commented on backend/src/main/resources/application-dev.yml
> +      host: ody-redis-001.ody-redis.vd1e5e.apn2.cache.amazonaws.com
비밀번호 설정이 필요할 것 같네요!
로컬 Redis 비밀번호는 도커 컴포즈 파일로 확인가능하고
dev, prod Redis 비밀번호는 노션 계정 페이지에 첨부했습니다! 

redis-cli 접속 시 `AUTH 비밀번호` 명령어로 인증할 수 있습니다

2024-11-20 08:02 UTC, eun-byeol commented on backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
> +        redisTemplate.expire(failClientKey, FAIL_MINUTES_TTL);
지금 구조에서는 마지막 에러 발생 기준으로 30분이던데, 의도하신게 맞나요?
카키가 말한건 최초 에러 발생 기준 30분으로 이해돼요!

2024-11-20 08:13 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
로직 다시보니 헷갈리네요,

여기서 키가 없는 경우 `orElse(0)`를 반환한다고 이해했어요.
```java
// CustomRedisTemplate
    public int increment(String key) {
        return Optional.ofNullable(opsForValue().increment(key))
                .map(Long::intValue)
                .orElse(0);
    }
```
위 메서드를 호출하고 있는 코드인데, 0->1로 증가하는 부분은 어디있죠??
```java
    public void recordFailCountInMinutes(RouteClient routeClient) {
        String failClientKey = RouteClientKey.getFailKey(routeClient);
        int failCount = redisTemplate.increment(failClientKey); // 호출
        redisTemplate.expire(failClientKey, FAIL_MINUTES_TTL);
        log.warn("{} 요청 실패 횟수 : {}", failClientKey, failCount);
    }
```

2024-11-20 08:18 UTC, eun-byeol approved these changes
간단한 질문만 남겼는데, 확인부탁드립니다!
쿨다운 시간 전략도 공유해주셔서 감사해요. 설득됨!
고생하셨어요 카키~

2024-11-20 10:44 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
없는 키 값을 조회할 때 키값이 없을 때는 NULL을 반환해서 안전하게 0을 반환하도록 의도했어요
없으면 0을 반환하는 테스트도 검증해주면 좋겠네요 !

2024-11-20 10:54 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
> +        redisTemplate.expire(failClientKey, FAIL_MINUTES_TTL);
TTL을 30분으로 설정해서 30분 내에 3번의 에러라고 표현을 했는데

에러 발생1 -> count : 1 expire : 30
에러 발생2 -> count : 2 expire : 30

마지막 에러 발생이후 30분동안 총 3번의 에러 발생 시 격리 시킨다고 하는 것이 정확하겠네요 !

2024-11-20 18:03 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteClientCircuitBreaker.java
> +        return Boolean.TRUE.equals(redisTemplate.hasKey(RouteClientKey.getBlockKey(routeClient)));
왜 이렇게 했나 했는데 키가 없는 경우 Boolean에 null이 들어올 수 있군요 👍

2024-11-20 18:20 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        List<RouteClient> availableClients = routeClientManager.getAvailableClients();
[제안]

여기서 조금 헷갈렸던 부분이 현재 Client는 두 가지 상황에 따라 호출이 불가능한 것 같아요.

1) 30분 간 3번의 실패 카운트를 초과한 경우
2) apiCallService 상 enable이 false라고 반환되는 경우

RouteClientManager에서 이 두 가지를 모두 검증해주면 어떨까요? avaliable이라는 것은 `호출 가능한` 이라고 해석되는데 여기서 또 Disabled를 검증하는 것이 어색해보여서 호출 가능횟수와 blocked 상태 모두를 RouteClient의 책임으로 넘기는 건 어떨까 싶었어요. 

혹은 getAvaliableClients()를 getNonBlockedClients() 로 명명해도 미묘한 차이를 담을 수 있다고 생각했습니다!

2024-11-20 18:21 UTC, coli-geonwoo commented on backend/src/main/resources/application-dev.yml
> +      host: ody-redis-001.ody-redis.vd1e5e.apn2.cache.amazonaws.com
@eun-byeol  레디스 해킹당하면 어떻게 되나요? 궁금해서 물어봅니다

2024-11-20 18:23 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/common/RedisTestContainersConfig.java
> +    private static final int REDIS_PORT = 6379;
```suggestion

    private static final int REDIS_PORT = 6379;
```

저도 개행을 잘 못챙기는 편이지만.. ㅎㅎ 그래도 보여서 남겨놓아요 😅

2024-11-20 18:30 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/common/RedisTestContainersConfig.java
> +            .waitingFor(Wait.forListeningPort())
오... redis가 6379 포트에 연결할 때까지 기다리는 설정이군요. 배워갑니다 👍

2024-11-20 18:37 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteClientCircuitBreakerTest.java
> +                () -> assertThat(ttlMinutes).isGreaterThanOrEqualTo(30).isLessThanOrEqualTo(31)
뭔가 있을 것 같아서 찾아보았는데 isBetween도 있더라고요!

```suggestion
                () ->  assertThat(ttlMinutes).isBetween(30L, 31L)

```

2024-11-20 18:40 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteClientManagerTest.java
> +        Mockito.when(routeClientCircuitBreaker.isBlocked(odsayRouteClient))
순차적인 요청에 대한 stubbing 값 지정도 가능할 것 같아요! 다만 이경우에는 googleRouteClient라는 명시적인 지정이 불가해서 오히려 지금 구조가 나을 것 같기도 하네요!

```java
Mockito.when(routeClientCircuitBreaker.isBlocked(any(RouteClient.class)))
                        .thenReturn(true, false);
```

2024-11-20 18:41 UTC, coli-geonwoo commented on backend/src/test/java/com/ody/route/service/RouteClientManagerTest.java
> +    void FailWhenGetAvailableClientsBy() {
✅ 테스트 명
```suggestion
    void failWhenGetAvailableClientsBy() {
```

2024-11-21 06:54 UTC, mzeong approved these changes
오 레디스 생각보다 비싸네요 💸💸

odsay 에러 복구 시간을 고려해서 TTL을 정하면 좋을 것 같은데 odsay 에러를 세분화하고 있지 않아 명확하게 정하기에 어려움이 있네요 현재 카키가 정한 3시간이 무난한 시간이라 생각해요! 

카키와 먼저 리뷰 남겨준 조조, 콜리 덕분에 레디스 잘 공부해갑니다 😋

2024-11-21 06:54 UTC, mzeong commented on backend/src/main/java/com/ody/common/config/RedisConfig.java
> +@Profile({"local", "dev", "prod"})
[질문] `!test`와 같은 의미로 작성하신 걸까요? 전과 표현이 달라서요. 환경 간에 redis 설정이 달라질 가능성을 염두에 둔 코드일까요?

2024-11-21 06:54 UTC, mzeong commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
음 리뷰 달고 있었는데 제 추측은 틀렸네요 ㅋㅋㅋㅋ 0으로 반환하도록 한 거 좋은 것 같아요

<img width="615" alt="image" src="https://github.com/user-attachments/assets/74d50fc6-4865-4c79-a308-bd8697709deb">

2024-11-21 09:04 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/RedisConfig.java
> +                .cacheDefaults(redisCacheConfiguration())
데이터 일관성이 아주 중요하다면 필요하다고 생각하는데
보통은 Look Aside + Write Around 조합을 사용하니 강력한 일관성이 요구되는 상황은 아니라 생각이 들어요
오히려 트랜잭션 동기화로 인한 오버헤드나 캐시 작업이 트랜잭션 완료까지 지연된다는 단점이 있다고 생각합니다

Write Through 쓰기 전략이 필요한 상황이라면 일관성이 중요하니 해당 옵션을 설정해주는 것도 좋을 것 같긴하네요

2024-11-21 09:12 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/domain/RouteClientKey.java
> +        return String.format(FAIL_KEY.value, routeClient.getClass().getSimpleName());
getClientType()가 있었쬬
콜리말데로 getClientType()를 활용하는 방법이 적합해보입니다 !

2024-11-21 09:16 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/repository/RouteClientRedisTemplate.java
> +package com.ody.route.repository;
> repository 패키지에 둔 이유가 궁금합니다!

Redis에 접근하는 클래스라 해당 패키지에 두었습니다
어떤 패키지가 적합하다고 생각하시나요 ??

> 현재 Value의 경우 String > Long으로 변환하는 과정이 필수적인데 RedisTemplate<String, Long>을 사용하지 않은 이유가 궁금해요!

RedisTemplate를 상속받아 기본적으로 제공하는 기능 + 커스텀한 메서드 기능을 사용하도록 만들었어요
사용하는 명령어에 따라서 반환 타입이 달라 
기본적으로 저장되는 String  타입으로 형변환 없이 Value를 들고와 필요에 따라 적절한 타입으로 수정할 수 있도록 의도했습니다

2024-11-21 09:23 UTC, hyeon0208 commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        List<RouteClient> availableClients = routeClientManager.getAvailableClients();
살짝 다르다고 생각했는데 동일한 책임이라 볼수도 있겠네요 👍 
RouteClientManager의 getAvaliableClients() 필터링 구문에 해당 조건을 확인하도록 했습니다 !

2024-11-21 09:25 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteClientCircuitBreakerTest.java
> +                () -> assertThat(ttlMinutes).isGreaterThanOrEqualTo(30).isLessThanOrEqualTo(31)
오호 isBetween() 확인!

2024-11-21 09:26 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/config/RedisConfig.java
> +@Profile({"local", "dev", "prod"})
넵 테스트에서는 따로 테스트 컨테이너 연결 설정을 하고 있어서
테스트에서는 사용하지 않도록 했습니다!

2024-11-21 09:29 UTC, hyeon0208 commented on backend/src/test/java/com/ody/route/service/RouteClientManagerTest.java
> +        Mockito.when(routeClientCircuitBreaker.isBlocked(odsayRouteClient))
저 또한 명시적인게 가독성 측면에서 좋을 것 같아 지금 구조로 두었습니다!

2024-11-21 16:03 UTC, eun-byeol commented on backend/src/main/resources/application-dev.yml
> +      host: ody-redis-001.ody-redis.vd1e5e.apn2.cache.amazonaws.com
DB 데이터 털리는거죠ㅎㅎ 데이터가 조작되거나 하는 등 문제가 있는 경우도 있을 것 같고, 로그 확인해서 비정상적인 기록이 있으면 해킹했다고 판단할 수 있을 것 같아요. 찾아보니 이런 [해킹 사례 포스팅](https://thxwelchs.github.io/%EB%82%B4redis%EA%B0%80%ED%95%B4%ED%82%B9%EB%8B%B9%ED%96%88%EB%8B%A4%EA%B3%A0%EC%8B%AC%EC%A7%80%EC%96%B4local%EC%9D%B8%EB%8D%B0/)도 있네요.

제가 모니터링했던 이슈는 아니라서, 해킹당해서 비밀번호 설정했다 정도만 알고 있습니다~

2024-11-21 16:08 UTC, eun-byeol commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
> increase하면서 key에 대한 카운팅을 해서 0이 반환되진 않는데
꺼내 올때랑 저장할 때 반환 타입이 다르기도하고
해당 메서드 반환 타입 자체가 �래퍼타입이라서 NULL 안전하게 0을 반환하도록 의도했�습니다!

`orElse(0)`을 타는 경우는 없다는 말씀이신거죠? 전 0 숫자가 의미있는 값으로 보여져서 헷갈렸던 것 같아요.

[제안 - 반영필수 아님!!]
초기값이 0이 아닌, 1로 설정하는 것이 전략이라면 1을 반환하거나 예외를 던지는 방식은 어떤가요?
만에하나 천에하나 해당 로직이 실행돼서, 0이라는 값이 저장되는 상황도 생기게 되면 더욱 헷갈릴 것 같은데, 초기값으로 맞추는게 더 낫지 않을까 싶어서요.

2024-11-21 16:11 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/config/RedisConfig.java
> +                .cacheDefaults(redisCacheConfiguration())
카키 의견에 동의해요. 일관성이 중요한 케이스는 아니라고 생각해요. 고민 지점 언급해준 콜리 감사합니다!

2024-11-21 16:36 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/repository/RouteClientRedisTemplate.java
> +package com.ody.route.repository;
> 어떤 패키지가 적합하다고 생각하시나요 ??

cache 관련된 패키지는 별도로 분리되어도 좋다고 생각했어요. 저는 repository는 DB에 직접 접근하는 Repo로만 생각하고 있어서 cache 관련된 객체들도 repository에 속하는지가 조금 애매했던것 같아요. 물론 넓은 범위에서 redis 관련 객체도 repository 패키지가 적합해 보이고 팀원들이 모두 인지한 컨벤션이라 괜찮다고 합니다! 

> 기본적으로 저장되는 String 타입으로 형변환 없이 Value를 들고와 필요에 따라 적절한 타입으로 수정할 수 있도록 의도했습니다

좋네요. 카키의 의도를 이해했습니다.

2024-11-21 16:36 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/repository/RouteClientRedisTemplate.java
> +                .orElse(0);
아 최초 호출 시에 0을 반환하는 것이 아니라 null인 경우 0을 반환토록 한 것이었군요! 이해했습니다.

2024-11-21 16:37 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteService.java
> +        List<RouteClient> availableClients = routeClientManager.getAvailableClients();
꽤 공수가 드는 일이었는데 빠르게 반영해주어서 감사합니다 카키!

2024-11-21 16:41 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/route/service/RouteClientManager.java
> +                .filter(client -> isAvailable(client) && isEnabled(client))
👍

2024-11-21 16:42 UTC, coli-geonwoo approved these changes
카키! 리뷰 반영사항 확인하여 approve 합니다 😄  고생많으셨어요! 그리고 대단해요 👍

2024-11-22 10:47 UTC, hyeon0208 commented on backend/src/test/java/com/ody/common/redis/CustomRedisTemplateTest.java
> +    @DisplayName("key의 counter를 증가시킨다.")
`increase()` 메서드를 사용하면 redis 상에서 incr 명령어로 key에 대한 카운팅을 증가시키는데
없으면 1을 반환해서 0이라는 값이 저장될 순 없을것 같아요!
하지만 연결 문제와 같은 이유로 연산자체가 실패할 수 있는 상황을 고려해 
원인을 추적할 수 있도록 예외를 던지면 좋을 것 같아 반영했습니다 👍

2024-11-22 10:48 UTC, merged