feat: API 호출 카운팅 동시성 제어
woowacourse-teams/2024-ody pull request #914
Opened 2024-11-18 11:33 UTC by hyeon0208

# 🚩 연관 이슈 
close #913 

<br>

# 📝 작업 내용

> AS - IS

- 외부 API는 호출 횟수에 따라 정지, 과금 될 수 있어 정확한 카운팅 필요
- 동시 요청 시에도 외부 API 호출 횟수의 정합성 필요
- 현재 날짜에 조회 결과가 없으면 새로운 `ApiCall`을 생성하고 저장 -> 비관적락 적용 시 존재하지 않은 엔티티에 대한 Lock 흭득 불가

> TO - BE

- Redisson 클라이언트를 사용해 분산락 적용
- API 호출 정보 전 구간(생성~업데이트)의 데이터 정합성 보장
- 분산 서버 환경에서의 데이터 정합성 확보

Redis 클라이언트를 사용해 분산락을 적용하기에는 스핀락 방식으로 사용해 부하가 많아
Pub/Sub 방식의 Lock을 사용하는 Redisson 클라이언트로 교체하여 분산락을 적용했습니다.

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-11-20 08:01 UTC, eun-byeol requested changes
카키 동시성 적용 맛있게 적용하셨네요~

분산락 적용하는건 처음 공부해봤는데, 레디스 내부에서 분산락을 사용하는 동작은 정확히 이해하진 못했어요. key가 레디스 내부에 저장되진 않는것 같더라구요? 이부분, 이해에 참고할만한 자료가 있다면 공유 부탁드리겠습니다~🙇‍♀️

> [필수] 테스트 코드 실패

도커를 띄우지 않았을 때, 테스트코드 일부가 실패하더라구요. cicd 과정에 문제가 생길 것 같은데, 이 부분 해결이 필요할것 같습니다!!
![image](https://github.com/user-attachments/assets/86324318-8c1b-4363-875d-5f373faecd67)

2024-11-20 14:04 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLock.java
> +    long leaseTime() default 5L; // Lock 보유 시간 (부하 분산 서버 다운 문제 해결을 위한 시간)
넵 초 단위 입니다
저희 서비스에서 제일 긴 응답 시간이 1.6초라
대부분의 락 획득이 3초 내에 가능한 수준으로 파악되서 3초로 설정했어요

보유 시간의 경우엔 비즈니스 로직 처리 시간과 네트워크 지연을 고려해 좀더 길게 설정했습니다

2024-11-20 14:07 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +@Order(Ordered.HIGHEST_PRECEDENCE + 1)
제일 높은 우선순위를 줌으로써 redissonLockManager.lock() 메서드 내부에서 트랜잭션으로 실행되는 supplier.get()보다
선행된 트랜잭션이 없도록 하여 트랜잭션 커밋 후 락 해제됨을 보장시켰습니다

2024-11-20 14:07 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    private static final String REDISSON_LOCK_PREFIX = "LOCK:";
✅

2024-11-20 14:09 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedisConfig.java
> +                .setRetryAttempts(3);
3000은 상수로 의미 부여했지만
재시도횟수는 직관적이여서 그대로 두었습니다!

2024-11-20 14:11 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
전략이라기보단 lock 이름을 메서드 파라미터로 넘긴 `clientType`에 따라 동적으로 네이밍해주기 위해
Spring EL 문법을 사용한 것 입니다!
아래에서 그냥 고정적인 이름을 넘기면 오디세이와 구글 키가 구별되지 않아서요
```
@DistributedLock(key = "#clientType.name()")
```

2024-11-20 14:15 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +            throw new OdyServerErrorException("다른 요청을 처리 중 입니다. 잠시 후 다시 시도해주세요.");
분산락 흭득을 실패한 것은 다른 요청이 먼저 락을 흭득 했을 때 발생할 수 있는
비즈니스 로직 상 예상 가능한 실패 상황이라 생각했어요
시스템 장애가 아닌 재시도로 해결 가능한 일시적 문제라고 생각하는데 어떻게 생각하시나요??

2024-11-20 15:32 UTC, hyeon0208 commented
> 분산락 적용하는건 처음 공부해봤는데, 레디스 내부에서 분산락을 사용하는 동작은 정확히 이해하진 못했어요. key가 레디스 내부에 저장되진 않는것 같더라구요? 이부분, 이해에 참고할만한 자료가 있다면 공유 부탁드리겠습니다~🙇‍♀️

Redis로 분산락을 구현하면 구체적인 코드들을 구현해야하고 스핀락 방식을 사용해 문제가 있어요
계속 요청을 하니 Redis에 많은 부하를 주거든요
그래서 분산락 외 다양한 기능을 제공하는 Redisson을 사용했고 Redisson은 분산락을 Pub/Sub 방식으로 제공합니다.
1. Lock 희득 시 Lock 저장과 TTL 설정 "LOCK:땡땡"
2. 락을 획득하지 못한 클라이언트들은 구독을 신청하고 기다린다.
3. Lock이 반환되면 구독자들에게 알린다.
4. 다시 Lock 시도를 한다.
5. 이 과정 반복
여기까지가 Redisson의 Pub/Sub을 활용한 분산락 처리 방식이고 스핀락에 비해 Redis에 부하가 훨씬 덜합니다

> [필수] 테스트 코드 실패
도커를 띄우지 않았을 때, 테스트코드 일부가 실패하더라구요. cicd 과정에 문제가 생길 것 같은데, 이 부분 해결이 필요할것 같습니다!!

Docker를 띄우지 않으면 Redis 연결해 테스트하는 코드들은 다 실패합니다 !
900번 PR도 이런 문제가 있었는데 로컬에선 정상작동하는 것을 보니
로컬에서 테스트했을 때와 CI에서 테스트했을 때 동작방식이 조금 다른것 같아요
테스트컨테이너의 Redis 연결 설정, Redis 관련 Bean이 필요한 클래스 문제들이 있어서 수정해 해결했습니다

2024-11-21 16:30 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +            throw new OdyServerErrorException("다른 요청을 처리 중 입니다. 잠시 후 다시 시도해주세요.");
카키 생각에 동의해요! 제가 조금 헷갈렸네요ㅎㅎ
해당 케이스의 경우 로그가 두 개 남는 데, 다른 로그레벨로 기록된다고 생각했어요.(첫번째 로그 warn, 두번째 로그 error로 오해함)
GlobalExceptionHandler에서 OdyServerErrorException error가 아닌 warn으로 로깅하고 있었네요.

2024-11-21 16:32 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +    private <T> T executeWithTransaction(Supplier<T> supplier) {
단순 궁금증인데,
> ApiCallService.increaseCountByClientType() 메서드가 종료되면 트랜잭션 커밋이 되서 정상적인 것으로 보여요

이건 어떻게 판단하셨나요? 로그 상으로는 알 수가 없다고 생각했어요.

2024-11-22 03:14 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedisConfig.java
> +                .setRetryAttempts(3);
저도 일관성을 중요하게 생각하지만 매직넘버를 상수화하는 건 가독성 측면으로 생각해
연결타임아웃 3000 은 의미 전달히 모호하지만 재시도 횟수 3이란 값은 이미 의미가 잘 전달된다고 생각했습니다!

2024-11-22 05:00 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +    private <T> T executeWithTransaction(Supplier<T> supplier) {
해당 메서드를 단독으로 쓰는것으로 착각했었는데 
increaseCountByClientType() 메서드 보다 상위 트랜잭션이 있어서 로깅이 제대로 찎힌게 맞겠네요 !

트랜잭션이 시작되는 ETA 조회, 약속 참여에 해당 분산락 어노테이션을 붙이는 것으로 수정했습니다!

2024-11-22 15:27 UTC, mzeong requested changes
카키 덕분에 요즘 PR 재밌네요 많이 배우고 있습니다

2024-11-22 15:27 UTC, mzeong commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
카키가 분산락을 고려하게 된 근본적인 이유는 **날짜별로 하나의 행을 유지하며 count를 증가하는 방식으로 호출 횟수를 저장**하고 있어서 라고 생각해요. 그런데 키를 보니 락의 범위가 커서 모든 동일 벤더 API 호출이 동일한 락을 사용해 서로 다른 요청이 병렬적으로 처리되지 못하겠다는 생각이 드네요..!

호출 횟수를 정확하게 카운트하는 게 중요하다는 것에 공감해서
차라리 **저장 방식을 호출 시마다 새로운 행을 삽입하는 것으로 변경하면 어떨까요?**
각 호출이 독립적인 행으로 저장되므로 데이터베이스 수준에서 동시성 문제가 줄어들 것 같아요

행이 많아지게 되면서 조회 시 성능 저하가 있겠지만 현재 조회 빈도가 낮고 인덱스를 사용한다면 큰 문제는 아닐 것 같아요
행의 개수가 많아지는 게 부담스러워지면 파티셔닝 등을 고려해 해결할 수도 있을 것 같아요

[질문] 분산락에 대한 제 의견은 이러한데요, 분산락 도입에 대한 카키의 의견이 더 궁금해요〰️

2024-11-23 02:01 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +@Order(Ordered.HIGHEST_PRECEDENCE + 1)
Ordered.HIGHEST_PRECEDENCE에 가까울 수록 우선순위가 높아집니다
트랜잭션 AOP보다 DistributedLockAop이 먼저 실행되는 것을 의도했고 
분산락 흭득 -> 트랜잭션 로직 실행 -> 커밋 -> 분산락 반환 순서로 이어지고 있어요

왜 반대라고 생각하셨는지 궁금합니다

2024-11-23 02:04 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
>  카키가 분산락을 고려하게 된 근본적인 이유는 날짜별로 하나의 행을 유지하며 count를 증가하는 방식으로 호출 횟수를 저장하고 있어서 라고 생각해요. 
그런데 키를 보니 락의 범위가 커서 모든 동일 벤더 API 호출이 동일한 락을 사용해 서로 다른 요청이 병렬적으로 처리되지 못하겠다는 생각이 드네요..!

비관적 락을 사용하지 않고 분산락을 적용한 이유는 여러 장점도 있겠지만
가장 큰 이유는 작업 내용에도 적었듯이 현재 날짜에 조회 결과가 없으면 새로운 ApiCall을 생성하고 저장하고 있어 비관적락을 적용하면 존재하지 않은 엔티티에 대한 Lock 흭득 불가하기 때문이였어요

수정한 락키가 범위가 너무 크네요 좋은 부분 짚어주셔서 감사합니다
특정 모임에 대한 동시요청에 대해서만 락을 흭득하도록 락 범위를 줄였습니다 !

<br>

> 호출 횟수를 정확하게 카운트하는 게 중요하다는 것에 공감해서 차라리 저장 방식을 호출 시마다 새로운 행을 삽입하는 것으로 변경하면 어떨까요? 각 호출이 독립적인 행으로 저장되므로 데이터베이스 수준에서 동시성 문제가 줄어들것 같아요
행이 많아지게 되면서 조회 시 성능 저하가 있겠지만 현재 조회 빈도가 낮고 인덱스를 사용한다면 큰 문제는 아닐 것 같아요 행의 개수가 많아지는 게 부담스러워지면 파티셔닝 등을 고려해 해결할 수도 있을 것 같아요

호출마다 매번 행을 추가하면 ApiCall 데이터의 의미가 모호한 것 같네요
현재로썬 일단위로 얼마나 호출했고 활성화 여부를 판단하는데
매번 갱신하면 카운팅도 빠질 것이고 호출 여부도 추가마다 초기화되니 의미가 없어질 것 같아요
오히려 무의미한 데이터들이 추가되어 스토리지 용량만 차지시킨다고 생각해요
이 정도 규모에서 파티셔닝도 고려하게 만들정도로 복잡도를 높일 필요가 있을까 싶기도하구요
현재는 동시성 처리를 락으로 해결할 수 있음에도 매번 행을 추가하는 방식은 인덱스 같은 성능 떠나서도 오히려 데이터 관리를 무겁고 복잡하게 만든다고도 생각합니다.
락으로 동시성을 제어하는게 아닌 행을 추가하는 방식으로 동시성 문제를 낮추는 것을 제안한 이유가 궁금합니다

2024-11-23 20:19 UTC, coli-geonwoo requested changes
카키! 분산락 리뷰를 지금에야 남기네요! 락 관련해서 여기저기 공부해보고 궁금한 점도 생겨서 몇가지 질문 남겨놓아요~

정확한 ApiCall counting을 위한 필요한 리팩터링이었다고 보여지고, 특히 테스트 부분은 인상적이었어요. 

고생많으셨습니다!

P.S

https://github.com/woowacourse-teams/2024-ody/pull/906#discussion_r1843924180
이벤트 리스너로 리팩터링한 PR에서 countDownLatch 활용 관련된 리뷰를 주셨는데 당시 PR 테스트는 E2E고 내부 코드에서 비동기를 활용하고 있어 카키가 현재 PR에서 활용한  방식대로 CountDownLatch를 사용할 수 없는데 혹시 생각한 다른 방식이 있는지 조언을 구하고 싶어요 😭 )

2024-11-23 20:19 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
> 특정 모임에 대한 동시요청에 대해서만 락을 흭득하도록 락 범위를 줄였습니다

카키, 코드 상으로 이부분에 대한 이해가 부족한데 혹시 어떤 방식으로 특정 모임에 대한 동시 요청에 대해서만 락을 획득하도록 하였는지 설명해줄 수 있을까요? 😶 

> 분산 락 vs 호출 시마다 행 추가

**분산락 적용시** 
- [장점] 현재 행 하나인 db구조 유지 가능
- [단점] apiCall을 하는 모든 로직들이 count값 증가 시마다 락 획득을 기다려야하므로 병목이 발생 가능

**호출 시마다 행 추가**
- [장점] apiCall을 하는 로직간의 병렬 처리 가능
- [단점] 무의미한 db 데이터 적재, 스토리지 공간 낭비, 조회속도 저하

저는 개인적으로 장단점의 트레이드 오프를 바라본다면 락 적용시 병목이 생기는 게 조금 더 크리티컬하다고 바라보는 편이긴 합니다. 약속 참여, ETA 같이 api 호출이 필요한 로직들이 하나의 락 범위를 공유하고 있으면 더욱 응답속도가 느려질 수 있다고 생각했어요. 다만 카키가 락 범위를 줄였다고 해서 이 부분에 대해 설명을 듣고  조금 더 논의해보고 싶습니다!

2024-11-24 08:43 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
다시보니 제가 이상하게 생각을 했어요 
락의 이름 범위라 생각을 해서 Lock 이름으로 Lock 키 이름에 대한 범위를 좁혔는데 사실 이렇게 좁힐경우 API 카운팅의 정합성이 제대로 이뤄지진 않겠네요

근본적인 문제는 락 적용 범위였는데
외부 API를 사용하다는 점 락 적용시 병목이 생긴다는 것에 공감합니다.
하지만 이 병목으로 락을 사용한 동시성 제어가 아닌 저장 방식의 변경으로 처리가 적합할지가 현재로써는 잘 안그려지네요
외부 API 호출 응답이 네트워크를 한번 더 타긴하지만 응답속도가 느리다는 것은 현재 저희 API 속도로봤을 때는 아직 안느껴졌던 것 같아요
실제 외부 API를 동시 요청 상황에서는 다르겠지만 현재 테스트 코드 상으로 테스트를 해 10개의 동시요청의 경우 400ms , 100개의 요청의 경우 1300ms
요청 수가 10배가 뛴 상황에서 응답속도도 배수로 늘어난다면 문제라고 생각하지만 크리티컬한 병목 현상같지 않다고 생각했어요
실제 외부 API를 동시 요청 시에는 이보다 확실히 병목으로 인한 응답 지연이 발생할 수 있겠지만 실제 운영환경에서 모니터링으로 판단할 수 있을 것 같아요

만약 병목현상이 발생해 응답속도가 기존보다 크게 늘어났고 이 문제가 자주 발생한다고 하면
REQUIRE_NEW로 트랜잭션을 분리해 분산락 적용 범위를 API 카운팅에만 적용하도록 개선할 수 있을 것 같다고 생각이 듭니다

그렇다면 콜리의 Lock 사용 기준이 궁금합니다!

2024-11-24 08:44 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +            Thread.currentThread().interrupt();
바로 예외를 던지고 있어 필요없겠네요 ! 제거했습니다 👍

2024-11-24 08:44 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +            log.warn("[분산락 획득 실패] {} {}초 대기 후 락 획득 실패", lockName, waitTime);
실제 대기 시간이 아닌 distributedLock의 waitTime으로 지정한 대기시간을 확인할 수 있도록 했습니다
distributedLock 어노테이션에 waitTime을 지정하면 지정한 시간대로 달리 보이겠지만 현재는 지정하지 않아 default 값이 보이고 있습니다
몇초동안 락을 대기해야하는지 확인하는 것을 의도했습니다 !

2024-11-24 08:44 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/redis/RedisConfig.java
> +    public RedissonClient redissonClient() {
넵 맞습니다!
useSingleServer()가 단일 인스턴스 설정이고 이 외에도 센티널, 레플리케이션, 클러스터 설정도 메서드로 제공되더라구요

2024-11-24 14:09 UTC, coli-geonwoo approved these changes
카키! 질문한 부분들에 대한 답은 모두 얻어서 approve 합니다. 나머지 이야기는 다른 팀원들 comment 따라가면서 팔로우업할게요!

그리고, countDownLatch 테스트 신경써주셔서 감사합니다.. 많은 시간을 쏟았는데 해결하지 못했던 부분이어서, 카키 덕분에 명쾌하게 해결할 수 있었어요 👍

고생많으셨습니다.

2024-11-24 14:09 UTC, coli-geonwoo commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
> 사실 이렇게 좁힐경우 API 카운팅의 정합성이 제대로 이뤄지진 않겠네요
락 키 이름은 이전으로 롤백했습니다

검토해주셔서 감사합니다 🙇 

> Lock 사용 기준

음... 우선 현재 카키가 PR 올린 부분, 그리고 문제로 정의했던 api counting 정합성과 관한 문제에 매우 공감해요. 그리고 이 문제를 먼저 분산락이라는 해결책을 떠올리고 PR까지 올려준 것에 대해 감사한 마음입니다. 

다만 카키도 공감하듯 병목현상에 대해서는 실제 prod 환경 기준으로 테스트를 해보았을 때는 생각보다 의식할 필요가 많은 것 같아요.

비동기 성능 테스트를 간단히 해보고자 어제 prod 기준 latency 측정을 간단히 해보았는데요. 각 10회 개별 요청으로 측정했고 평균 응답속도입니다.

- 약속에 참여하고 바로 출발 메시지 보내는 시나리오: 1007.6ms
- 약속방 나가기 (unSubscribe) : 871ms

외부 api를 실제로 연결했을 때, 테스트 환경보다 latency가 느리고, 특히 동시요청이 아니라 개별요청이라는 점도 주목해볼만하다고 생각해요.

다만 이러한 생각은 카키가 생각한 해결책에 대한 비판보다 `REQUIRES_NEW 같은 병목 현상에 대한 개선의 필요성`을 이야기하고자 하는 의도가 더 큽니다!

---

그래서 제가 생각한 방식도 카키의 제안처럼 lock 획득의 트랜잭션 범위를 최소화하는 것 or 락이 아닌 다른 해결책(호출 시마다 행 추가 방식)을 도입하는 것이었는데요.

후자에 대한 구체적인 방법은 다음과 같아요.
호출 테이블 : 당일 호출에 대한 데이터를 임시 저장할 테이블
호출 집계 테이블 : 현재 apiCallService 구조

- 호출 테이블에 호출 1회당 1개의 행으로 저장
- 매일 자정+1분에 호출 집계 테이블에 당일 호출량을 count하여 저장
- 호출 테이블에서 집계된 당일 호출 데이터 hard delete

이렇게 되면 다른 스레드가 대기하는 상황이 적어지니 현재 병렬 처리를 그대로 유지하고, 스토리지도 지속적으로 용량관리를 할 수 있지 않을까- 하는 시나리오였습니다.

다만 이 경우에도 현재 고려하지 못한 단점들이 있으리라 생각해요. 분산락에 더불어 병목을 해결할만한 개선책을 떠올리는 것이 합리적일 수도 있다고 생각합니다. 이 부분은 다른 팀원들 의견도 궁금하네요!

2024-11-25 08:12 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
의견 감사합니다 콜리 ~ 👍
병목현상도 중요한데 모든 장점을 다 가질순 없으니 상황에 맞게 적용하는 것이 중요하다고 생각해요
또한 모든 상황을 예측해서 성능을 다 고려하긴 힘들다고 생각합니다

Lock을 적용한 건 이전 코드에선 API 호출 카운팅에 대해 동시성 문제가 발생했는지 확인을 못하니 API 카운팅 정합성 문제를 예방하기 위해서입니다
콜리도 ETA를 같이 개발해서 알겠지만 ETA 조회 시 각각의 약속방에 있는 사람들마다 3번의 ETA를 호출하고 이를 분 단위로 비교해 호출해
동시성 발생 확률이 더욱 높다고 생각했습니다

현재 저희 서비스는 아직 지연시간으로 어느 정도의 불폄함이 있는지 실제로 확인할 수 없어
데이터 저장 방식의 변경이나 파티셔닝 고려는 오버엔지니어링이라고 생각해요
Lock로 제어를 하되 현재는 동시성 이슈가 발생하면 로깅이남아
모니터링으로 다른 큰 문제가 포착되면 다른 해결책을 찾아봐야하지 않을까 싶기도 하구요

REQRIED_NEW로 분산락 적용 범위를 좁히는 것도 좋지만
이것도 커넥션 풀을 하나 더 쓰기 때문에 적용 여부를 판단하기 위해선
동시성 문제가 발생했을 때 지연 시간을 확인을 해야할 것 같아요
이것도 커넥션 풀을 한개 더 사용하는 거라 커넥션 풀 개수도 조정할 필요가 있더라구요

2024-11-26 02:38 UTC, mzeong commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
카키와 콜리가 나눈 내용 잘 확인했습니다~👍

해당 API가 부하 테스트를 진행했을 때 이미 개선이 필요한 수준의 지연을 보여서 분산락을 추가하는 것에 대해 고민하게 되는 것 같아요
그렇지만 카키의 말처럼 적용 후 모니터링으로 확인하는 방향도 좋다고 생각합니다.

제 선에서 할 수 있는 논의는 충분히 진행된 것 같아 저는 approve를 남기겠습니다.

---

ps. 곧 인프라가 철거될 예정이라 더 이상 분산 서버 환경이 아닌 점을 고려해서 (^^)

```java
@Transactional public void increaseCountByClientType(ClientType clientType) {  	
	ApiCall apiCall = findOrSaveFirstByClientTypeAndDate(clientType); 	
	apiCall.increaseCount(); 
}
```

위 기존 방식 대신 **UPDATE 쿼리를 직접 실행해 데이터베이스가 동시성 제어를 처리**하도록 하는 방안도 대안이 될 수 있을 것 같아요
외부 시스템 없이 간단하게 갱신 손실 문제 해결 + 현재 서비스가 소규모 트래픽인 점을 고려하면 괜찮은 선택지인 것 같아요

2024-11-26 02:38 UTC, mzeong approved these changes

2024-11-26 04:56 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
답변 감사합니다 제리 ~
마지막으로 궁금한점이 있어 질문 남겨요 😀

분산 서버 환경이 아니라도 비관점 락의 단점을 보완한다 + DB 부하 감소 부분에서 분산락은 유의미할 것 같아요
회의 때 인프라 철거 이후 운영에서도 Redis를 도커로 띄워 사용한다는 의향이 있다해서 
현재 서비스 개선 목적으로 Redis로 외부 API 장애 관리 PR을 보냈고 Redis 도입된 시점에서 분산락을 적용한거구요

아래가 궁금한점입니다 !
제리가 말한 방식은 동시성 문제가 발생했을 때 수기로 처리한다는 것 같은데 수기로 일일히 다 처리할 수 있을까요 ?
동시성 문제로 update가 발생했을 때 따로 처리를 해주지 않으면 어떻게 문제가 발생했다는 것을 인지할 수 있을까요 ?
오히려 현재 서비스가 소규모 트래픽이라는 점을 고려하면 API 부하 테스트를 진행했을 때의 지연의 걱정은 안해도 되지 않을까요 ?

2024-11-27 11:00 UTC, eun-byeol approved these changes
카키 고생하셨어요!
덕분에 동시성 처리에 대해 많이 배웠어요. 스스로 적용해보면서 저만의 기준을 세워야겠다는 생각이 들었어요.
approve 할게요! 머지는 카키가 해주세요~

2024-11-27 11:00 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
> 해당 API가 부하 테스트를 진행했을 때 이미 개선이 필요한 수준의 지연을 보여서 분산락을 추가하는 것에 대해 고민하게 되는 것 같아요. 그렇지만 카키의 말처럼 적용 후 모니터링으로 확인하는 방향도 좋다고 생각합니다.

저도 이 맥락에서 공감이 되긴 하지만, 모니터링으로 확인해봐야 할 것 같아요👍

2024-11-27 11:00 UTC, eun-byeol commented on backend/build.gradle
> +
✅
```suggestion
```

2024-11-27 11:00 UTC, eun-byeol commented on backend/src/main/java/com/ody/common/redis/RedissonLockManager.java
> +    private <T> T executeWithTransaction(Supplier<T> supplier) {
👍 확인했습니다!
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/63b1ed30-5e54-44d6-b06a-7fb49fc369db">

2024-11-27 13:16 UTC, merged

2024-11-27 13:52 UTC, mzeong commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
@hyeon0208 업데이트 쿼리를 수기로 처리한다는 의미가 아니에요! 아래 메서드를 통해 UPDATE 쿼리를 직접 실행해 **데이터베이스에서 동시성 제어를 담당**하도록 해도 갱신 손실 문제를 방지할 수 있을 것 같아 남긴 코멘트였어요~

```java
@Repository
public interface ApiCallRepository extends JpaRepository<ApiCall, Long> {
    
    @Modifying
    @Query("UPDATE ApiCall a SET a.count = a.count + 1 WHERE a.clientType = :clientType AND a.date = CURRENT_DATE")
    int updateCountByClientTypeAndDate(@Param("clientType") ClientType clientType);
}
```

> 오히려 현재 서비스가 소규모 트래픽이라는 점을 고려하면 API 부하 테스트를 진행했을 때의 지연의 걱정은 안해도 되지 않을까요 ?

단순히 사용자가 지연을 경험하게 된다는 측면을 떠나더라도 API가 효율적이지 않은 방향으로 설계되어 있다면 개선 대상이라고 생각합니다. 다만 상황을 고려해서, 좀 더 간단한 방법으로 문제를 해결할 순 없을까? 다른 방법은 또 어떤 게 있을까? 하는 맥락으로 리뷰 남겼어요!

2024-11-27 15:06 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
> int updateCountByClientTypeAndDate(@Param("clientType") ClientType clientType);

MySQL의 기본 격리 레벨 수준의 경우 동시성 문제가 주로 동시에 업데이트를 한다면
선행 트랜잭션이 데이터를 변경하고 커밋하기 전에 후행 트랜잭션이 데이터를 읽을 때 언두 로그를 읽어 동시성 문제가 발생할 텐데
해당 쿼리 메서드를 실행하면 어떻게 DB가 동시성 제어를 담당하게 되는지 궁금하네요 🤔

> 단순히 사용자가 지연을 경험하게 된다는 측면을 떠나더라도 API가 효율적이지 않은 방향으로 설계되어 있다면 개선 대상이라고 생각합니다. 다만 상황을 고려해서, 좀 더 간단한 방법으로 문제를 해결할 순 없을까? 다른 방법은 또 어떤 게 있을까? 하는 맥락으로 리뷰 남겼어요!

동시성 제어가 필요하다면 제일 간단하게 처리가능한 방법이 락이라고 생각해요 !
락이 동시성 제어의 기본이라고 생각하거든요

2024-12-04 11:23 UTC, hyeon0208 commented on backend/src/main/java/com/ody/common/aop/DistributedLockAop.java
> +    }
특정 조건에 넥스트 키 락을 거는 것은 알고 있었지만 항상 건다는 것은 찾아보지 못해서
"MySQL이 INSERT UPDATE할 때 자동으로 넥스트 키 락을 건다"로 MySQL이 동시성을 제어한다는 부분이 어디있었는지 궁금해요 🤔

기존에 없던 새로운 데이터가 생기거나, 기존의 데이터가 사라지는 문제인 팬텀 리드를
조건이 맞을 때는 넥스트 키 락으로 어느 정도 동시성은 제어해주긴 하겠지만
사실 제리와 조조가 말한데로 MySQL이 자동으로 동시성을 처리해준다면 다른 서비스들도 동시성을 고려할 필요가 없지 않을까 싶어요

동시성 문제가 발생하는 상황을 짚어보자면 
```
SELECT count FROM api_call WHERE id = 1;  -- 트랜잭션 1

SELECT count FROM api_call WHERE id = 1; -- 트랜잭션 2
UPDATE api_call SET count = count + 1 WHERE id = 1; -- 트랜잭션 2
COMMIT -- 트랜잭션 2

UPDATE api_call SET count = count + 1 WHERE id = 1;  -- 트랜잭션 1
COMMIT -- 트랜잭션 1
```
update를 하기 전 선행작업으로 항상 조회를 해오는데 넥스트 키 락을 UPDATE에 자동으로 건다하더라도
트랜잭션 1의 SELECT와 UPDATE 사이에 다른 트랜잭션이 끼어 들어 UPDATE를 해버리면 결국 동시성 문제가 발생하기 때문에
SELECT 시점 부터 Lock을 걸어줘야 완벽한 동시성 제어가 될 수 있을 것 같습니다!

텍스트 보다는 동시성 원인에 대해서 시각적인 자료들로 정리된 글들이 많으니 이를 참고하시면 더욱 도움이 될 것 같습니다 !