chore: 개발 서버 마이그레이션
woowacourse-teams/2024-ody pull request #933
Opened 2024-12-23 09:51 UTC by mzeong

# 🚩 연관 이슈 
close #927

<br>

# 📝 작업 내용

개발 서버 마이그레이션 과정 중에 레디스 호스트 변경으로 yml 파일 수정이 있었습니다

<br>

# 🏞️ 스크린샷 (선택)

<br>

# 🗣️ 리뷰 요구사항 (선택)

2024-12-27 11:33 UTC, coli-geonwoo requested changes
제리, 몇가지 질문이 있어 우선 RC로 남겨두어요.
특히 redis의 host명을 바꾸어준 부분에 대해 ody-dev-redis와 ody-prod-redis를 각각 어떻게 설정했는지 알고 싶습니다!

2024-12-27 11:33 UTC, coli-geonwoo commented on .github/workflows/backend-cd-dev.yml
> +          ref: feature/927
trigger를 다시 복구해주어야 할 것 같아요!

2024-12-27 11:33 UTC, coli-geonwoo commented on backend/src/main/resources/application-dev.yml
> +      host: ody-dev-redis
[질문]

- 여기서 ody-dev-redis와 ody-prod-redis는 어떻게 설정해주었나요? 원래는 카키 계정의 elastic cache를 통해 소통하는 것으로 알았는데, 제리가 어디에 어떻게 redis를 설정해놓았는지 이야기해주면 고마울 것 같아요!
-

2024-12-28 17:42 UTC, eun-byeol approved these changes
prod까지 미리 redis 설정해준 센스! 고생했어요 제리~🐹🐹🐹

방금 전 #932 머지했는데, 배포가 실패해서 현재 dev app이 띄워지지 않았어요.
서버는 이전해서 aws redis 사용하지 않아 이전 호스트를 찾지 못한 문제로 보여요.
이 pr이 머지되면 해결이 될 것 같네요!! 빠르게 approve 하겠습니다ㅎㅎ
```
Caused by: java.net.UnknownHostException: Failed to resolve 'ody-redis-001.ody-redis.vd1e5e.apn2.cache.amazonaws.com' [A(1)]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1151)
	... 35 common frames omitted
Caused by: io.netty.resolver.dns.DnsErrorCauseException: Query failed with NXDOMAIN
	at io.netty.resolver.dns.DnsResolveContext.onResponse(..)(Unknown Source)
```

2024-12-28 17:42 UTC, eun-byeol commented on backend/src/main/resources/application-dev.yml
> +      host: ody-dev-redis
컴포즈로 redis 컨테이너를 같이 띄우고 있는데, 해당 컨테이너 이름을 `ody-dev-redis`로 지어줬네요. 같은 네트워크를 공유하고 있어서 dns처럼 호스트 네임으로 접근 가능한 것으로 알고있습니다.

[노션 > BE 애플리케이션 설정 관리](https://www.notion.so/BE-aea91802a3d84e37b2792f51f0e555e0)에서 docker-compose.yml 확인해보심 됩니다!

2024-12-28 17:42 UTC, eun-byeol commented on backend/src/main/resources/application-prod.yml
> +      host: ody-prod-redis
`노션 > BE 애플리케이션 설정 관리 > prod 컴포즈 파일`에 redis 부분이 없어서 업데이트 해두었습니다!

2024-12-28 18:22 UTC, coli-geonwoo commented on backend/src/main/resources/application-dev.yml
> +      host: ody-dev-redis
확인했습니다~ 감사해요 조조

2024-12-29 10:43 UTC, mzeong commented on .github/workflows/backend-cd-dev.yml
> +          ref: feature/927
[29d6e29](https://github.com/woowacourse-teams/2024-ody/pull/933/commits/29d6e29d079165e2b766fac17d93e72d5a1928ee) 커밋을 통해 트리거를 복구해주었고 브랜치에 들어가서 확인해도 반영이 되었는데 이상하게 PR files changed에서는 반영이 안 되네요

2024-12-29 10:55 UTC, coli-geonwoo commented on .github/workflows/backend-cd-dev.yml
> +          ref: feature/927
확인했습니다! approve할게요!

2024-12-29 10:55 UTC, coli-geonwoo approved these changes

2024-12-29 11:36 UTC, merged